force-app/main/default/objects/Location/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>HR Recruiting Partners</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organization_Department__c/Organization_Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <displayFormat>Dpt-{00000}</displayFormat>
        <label>Department ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_Department__c/fields/Dept_ID__c.field-meta.xml
<CustomField>
    <fullName>Dept_ID__c</fullName>
    <label>Master Department ID</label>
    <referenceTo>Organization_Department_Mgr__c</referenceTo>
    <relationshipLabel>Departments</relationshipLabel>
    <relationshipName>Departments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Organization_Department__c/fields/MGR_LVL_1_DESCR__c.field-meta.xml
<CustomField>
    <fullName>MGR_LVL_1_DESCR__c</fullName>
    <formula>TEXT(Dept_ID__r.MGR_LVL_1_DESCR__c)</formula>
    <label>MGR LVL 1 DESCR</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Department__c/fields/MGR_LVL_2_DESCR__c.field-meta.xml
<CustomField>
    <fullName>MGR_LVL_2_DESCR__c</fullName>
    <formula>Text( Dept_ID__r.MGR_LVL_2_DESCR__c )</formula>
    <label>MGR LVL 2 DESCR</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Department__c/fields/MGR_LVL_3_DESCR__c.field-meta.xml
<CustomField>
    <fullName>MGR_LVL_3_DESCR__c</fullName>
    <formula>TEXT(Dept_ID__r.MGR_LVL_3_DESCR__c )</formula>
    <label>MGR LVL 3 DESCR</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Department__c/fields/MGR_LVL_4_DESCR__c.field-meta.xml
<CustomField>
    <fullName>MGR_LVL_4_DESCR__c</fullName>
    <formula>TEXT(Dept_ID__r.MGR_LVL_4_DESCR__c )</formula>
    <label>MGR LVL 4 DESCR</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Department__c/fields/MGR_LVL_5_DESCR__c.field-meta.xml
<CustomField>
    <fullName>MGR_LVL_5_DESCR__c</fullName>
    <formula>TEXT( Dept_ID__r.MGR_LVL_5_DESCR__c )</formula>
    <label>MGR LVL 5 DESCR</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Department__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>HR_Talent_Pools</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Departments</relationshipLabel>
    <relationshipName>Departments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organization_Department_Mgr__c/Organization_Department_Mgr__c.object-meta.xml
<CustomObject>
    <label>Master Department</label>
    <nameField>
        <displayFormat>DMGR-{00000}</displayFormat>
        <label>Master Department ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_Department_Mgr__c/fields/Dept_ID__c.field-meta.xml
<CustomField>
    <fullName>Dept_ID__c</fullName>
    <externalId>true</externalId>
    <label>Dept ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Organization_Department_Mgr__c/fields/MGR_LVL_1_DESCR__c.field-meta.xml
<CustomField>
    <fullName>MGR_LVL_1_DESCR__c</fullName>
    <label>MGR LVL 1 DESCR</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrative</fullName>
            </value>
            <value>
                <fullName>Dene Nation Industrial Service</fullName>
            </value>
            <value>
                <fullName>Environmental Services</fullName>
            </value>
            <value>
                <fullName>SK Sustainability Solutions</fullName>
            </value>
            <value>
                <fullName>#N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Organization_Department_Mgr__c/fields/MGR_LVL_2_DESCR__c.field-meta.xml
<CustomField>
    <fullName>MGR_LVL_2_DESCR__c</fullName>
    <label>MGR LVL 2 DESCR</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>#N/A</fullName>
            </value>
            <value>
                <fullName>Asset Mgmt &amp; Supply Chain</fullName>
            </value>
            <value>
                <fullName>Corp Dev &amp; Real Estate</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corp Sales &amp; Corp Marketing</fullName>
            </value>
            <value>
                <fullName>Dene Nation Industrial Service</fullName>
            </value>
            <value>
                <fullName>Discontinued Facilities</fullName>
            </value>
            <value>
                <fullName>Distribution Centers</fullName>
            </value>
            <value>
                <fullName>Environ Svcs Sales and Service</fullName>
            </value>
            <value>
                <fullName>Facilities and Facility Sales</fullName>
            </value>
            <value>
                <fullName>Indust Svcs Sales and Service</fullName>
            </value>
            <value>
                <fullName>National Trans</fullName>
            </value>
            <value>
                <fullName>Pricing &amp; Proposals</fullName>
            </value>
            <value>
                <fullName>Safety-Kleen Oil</fullName>
            </value>
            <value>
                <fullName>Safety-Kleen Supply</fullName>
            </value>
            <value>
                <fullName>SK Bulk Products &amp; Services</fullName>
            </value>
            <value>
                <fullName>Trans Compliance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Organization_Department_Mgr__c/fields/MGR_LVL_3_DESCR__c.field-meta.xml
<CustomField>
    <fullName>MGR_LVL_3_DESCR__c</fullName>
    <label>MGR LVL 3 DESCR</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asset Mgmt &amp; Supply Chain</fullName>
            </value>
            <value>
                <fullName>Broker Business</fullName>
            </value>
            <value>
                <fullName>Canada Industrial Svcs</fullName>
            </value>
            <value>
                <fullName>CHES Sales and Service</fullName>
            </value>
            <value>
                <fullName>Corp Dev &amp; Real Estate</fullName>
            </value>
            <value>
                <fullName>Corp Pricing &amp; Proposals</fullName>
            </value>
            <value>
                <fullName>Corp Sales &amp; Corp Marketing</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Daylighting Services Canada</fullName>
            </value>
            <value>
                <fullName>Dene Nation Industrial Service</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Distribution Centers</fullName>
            </value>
            <value>
                <fullName>Environmental Svcs Sls and Adm</fullName>
            </value>
            <value>
                <fullName>Facilities Group</fullName>
            </value>
            <value>
                <fullName>IS Sales &amp; Svc Sales &amp; Admin</fullName>
            </value>
            <value>
                <fullName>Lodging Services</fullName>
            </value>
            <value>
                <fullName>National Transportation</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas Field Services</fullName>
            </value>
            <value>
                <fullName>Oil Sands</fullName>
            </value>
            <value>
                <fullName>Project Services</fullName>
            </value>
            <value>
                <fullName>Refined &amp; Blended Product Sale</fullName>
            </value>
            <value>
                <fullName>Safety-Kleen Supply</fullName>
            </value>
            <value>
                <fullName>SK Bulk Products &amp; Services1</fullName>
            </value>
            <value>
                <fullName>SK Facility Operations</fullName>
            </value>
            <value>
                <fullName>SK Pricing &amp; Proposals</fullName>
            </value>
            <value>
                <fullName>SK Sales and Service</fullName>
            </value>
            <value>
                <fullName>SKO Customer Service</fullName>
            </value>
            <value>
                <fullName>SKO Packaging &amp; Blending</fullName>
            </value>
            <value>
                <fullName>SKO Supply Chain</fullName>
            </value>
            <value>
                <fullName>Specialty Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Organization_Department_Mgr__c/fields/MGR_LVL_4_DESCR__c.field-meta.xml
<CustomField>
    <fullName>MGR_LVL_4_DESCR__c</fullName>
    <label>MGR LVL 4 DESCR</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asset Mgmt &amp; Supply Chain</fullName>
            </value>
            <value>
                <fullName>Automotive Services</fullName>
            </value>
            <value>
                <fullName>Base Oil Sales</fullName>
            </value>
            <value>
                <fullName>Blended Sales</fullName>
            </value>
            <value>
                <fullName>BPS Admin</fullName>
            </value>
            <value>
                <fullName>BPS Canada Region</fullName>
            </value>
            <value>
                <fullName>BPS Central Region</fullName>
            </value>
            <value>
                <fullName>BPS East Region</fullName>
            </value>
            <value>
                <fullName>BPS Lab</fullName>
            </value>
            <value>
                <fullName>BPS Oil Filter Recylers</fullName>
            </value>
            <value>
                <fullName>BPS West Region</fullName>
            </value>
            <value>
                <fullName>Broker Business</fullName>
            </value>
            <value>
                <fullName>Canada Industrial Svcs</fullName>
            </value>
            <value>
                <fullName>Canada Region</fullName>
            </value>
            <value>
                <fullName>Central Region IS</fullName>
            </value>
            <value>
                <fullName>Chemical Region IS</fullName>
            </value>
            <value>
                <fullName>CHESI Sales</fullName>
            </value>
            <value>
                <fullName>Corp Dev &amp; Real Estate</fullName>
            </value>
            <value>
                <fullName>Corp Pricing &amp; Proposals</fullName>
            </value>
            <value>
                <fullName>Corp Sales &amp; Mktg Admin</fullName>
            </value>
            <value>
                <fullName>Corporate Billing</fullName>
            </value>
            <value>
                <fullName>Corporate Executive</fullName>
            </value>
            <value>
                <fullName>Corporate Finance</fullName>
            </value>
            <value>
                <fullName>Corporate Government Strategy</fullName>
            </value>
            <value>
                <fullName>Corporate Marketing</fullName>
            </value>
            <value>
                <fullName>Corporate MIS &amp; TI</fullName>
            </value>
            <value>
                <fullName>Customer Care_Central Routing</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Daylighting Services Canada</fullName>
            </value>
            <value>
                <fullName>Dene Nation Industrial Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DepartmentsDAO.cls
/**
 * @description       : 
 * @author            : Suresh Beniwal
 * @group             : 
 * @last modified on  : 10-13-2022
 * @last modified by  : Suresh Beniwal
 * Modifications Log
 * Ver   Date         Author           Modification
 * 1.0   06-09-2022   Suresh Beniwal   Initial Version
**/
public without sharing class DepartmentsDAO {
    
    /**
    * @description 
    * @author Suresh Beniwal | 06-09-2022 
    * @param Set<Id> setOfId 
    * @return List<Organization_Department__c> 
    **/
    public static List<Organization_Department__c> getListOfDepartmentByOrganizationIds(Set<Id> setOfId) {
        return [
            SELECT Id, Name, Dept_ID__r.Dept_ID__c, Organization__r.Name, Dept_ID__r.MGR_LVL_1_DESCR__c,
                Dept_ID__r.MGR_LVL_2_DESCR__c, Dept_ID__r.MGR_LVL_3_DESCR__c, Dept_ID__r.MGR_LVL_4_DESCR__c,
                Dept_ID__r.MGR_LVL_5_DESCR__c, Dept_ID__r.MGR_LVL_6_DESCR__c, Dept_ID__r.MGR_LVL_7_DESCR__c,
                Location__c, Location__r.Name, Location__r.Location_Id__c, Organization__r.Organization_Id__c 
            FROM Organization_Department__c 
            WHERE Organization__c IN: setOfId AND Dept_ID__c != null AND Organization__c != null
                ORDER BY Location__r.Name ASC NULLS FIRST
        ];
    }

    /**
    * @description 
    * @author Suresh Beniwal | 06-09-2022 
    * @param String optionValue 
    * @return List<Organization_Department__c> 
    **/
    public static List<Organization_Department__c> dynamicQueryGetListOfDepartmentByOrganizationIds(List<String> optionValue) {
        return Database.query('SELECT Id, Organization__c, Location__r.Location_Id__c, Organization__r.Organization_Id__c FROM Organization_Department__c WHERE Dept_ID__c != null AND Dept_ID__r.MGR_LVL_3_DESCR__c IN: optionValue');
    }


    /**
    * @description 
    * @author Suresh Beniwal | 07-21-2022 
    * @param Set<Id> setOfId 
    * @param List<String> optionValue 
    * @return List<Organization_Department__c> 
    **/
    public static List<Organization_Department__c> getDynamicListOfDepartmentByOrganizationIds(Set<Id> setOfId, List<String> optionValue) {
        String dynamicQuery = 'SELECT Id, Name, Dept_ID__r.Dept_ID__c, Organization__r.Name, Dept_ID__r.MGR_LVL_1_DESCR__c, ' +
        '    Dept_ID__r.MGR_LVL_2_DESCR__c, Dept_ID__r.MGR_LVL_3_DESCR__c, Dept_ID__r.MGR_LVL_4_DESCR__c, ' +
        '    Dept_ID__r.MGR_LVL_5_DESCR__c, Dept_ID__r.MGR_LVL_6_DESCR__c, Dept_ID__r.MGR_LVL_7_DESCR__c, ' +
        '    Location__c, Location__r.Name, Location__r.Location_Id__c, Organization__r.Organization_Id__c ' +
        ' FROM Organization_Department__c ' +
        ' WHERE Organization__c IN: setOfId AND Dept_ID__c != null AND Organization__c != null ' +
        '    ORDER BY LastModifiedDate DESC NULLS FIRST ';

        if (!optionValue.isEmpty()) {
            dynamicQuery = 'SELECT Id, Name, Dept_ID__r.Dept_ID__c, Organization__r.Name, Dept_ID__r.MGR_LVL_1_DESCR__c, ' +
            '    Dept_ID__r.MGR_LVL_2_DESCR__c, Dept_ID__r.MGR_LVL_3_DESCR__c, Dept_ID__r.MGR_LVL_4_DESCR__c, ' +
            '    Dept_ID__r.MGR_LVL_5_DESCR__c, Dept_ID__r.MGR_LVL_6_DESCR__c, Dept_ID__r.MGR_LVL_7_DESCR__c, ' +
            '    Location__c, Location__r.Name, Location__r.Location_Id__c, Organization__r.Organization_Id__c ' +
            ' FROM Organization_Department__c ' +
            ' WHERE Organization__c IN: setOfId AND Dept_ID__c != null AND Organization__c != null AND Dept_ID__c != null AND Dept_ID__r.MGR_LVL_3_DESCR__c IN: optionValue' +
            '    ORDER BY LastModifiedDate DESC NULLS FIRST ';
        }

        System.debug('setOfId : ' + setOfId);
        System.debug('optionValue : ' + optionValue);
        System.debug('dynamicQuery : ' + dynamicQuery);
        return Database.query(dynamicQuery);
    }
}