force-app/main/default/objects/Location/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>HR Recruiting Partners</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organization_Department__c/Organization_Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <displayFormat>Dpt-{00000}</displayFormat>
        <label>Department ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_Department__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Departments</relationshipLabel>
    <relationshipName>Departments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organization_Department__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>HR_Talent_Pools</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Departments</relationshipLabel>
    <relationshipName>Departments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DepartmentServiceHandler.cls
/**
 * @description       : 
 * @author            : Suresh Beniwal
 * @group             : 
 * @last modified on  : 08-12-2022
 * @last modified by  : Suresh Beniwal
 * Modifications Log
 * Ver   Date         Author           Modification
 * 1.0   06-28-2022   Suresh Beniwal   Initial Version
**/
public with sharing class DepartmentServiceHandler {
    /**
    * @description 
    * @author Suresh Beniwal | 06-28-2022 
    * @param List<Organization_Department__c> listOfSobject 
    **/
    public static void updateOrganization(List<Organization_Department__c> listOfSobject) {
        Map<Id, Schema.Location> mapOfLocation = new Map<Id, Schema.Location>();
        for (Organization_Department__c sobjectRecord: listOfSobject) {
            if (sobjectRecord.Location__c != null) {
                mapOfLocation.put(sobjectRecord.Location__c, null);
            }
        }

        mapOfLocation = new Map<Id, Schema.Location>(LocationDAO.getLocationsBySetOfId(mapOfLocation.keySet()));

        for (Organization_Department__c sobjectRecord: listOfSobject) {
            String organizationLocation = sobjectRecord.Location__c != null && mapOfLocation.get(sobjectRecord.Location__c) != null ? mapOfLocation.get(sobjectRecord.Location__c).Organization__c : null;
            if (sobjectRecord.Organization__c == null && mapOfLocation.containsKey(sobjectRecord.Location__c) && mapOfLocation.get(sobjectRecord.Location__c) != null) {
                sobjectRecord.Organization__c = mapOfLocation.get(sobjectRecord.Location__c).Organization__c;
            }

            if (organizationLocation != null && organizationLocation != sobjectRecord.Organization__c) {
                sobjectRecord.addError('Location is not associated with the selected Organization');
            }
        }
    }
}