force-app/main/default/objects/Organization_Department_Mgr__c/Organization_Department_Mgr__c.object-meta.xml
<CustomObject>
    <label>Master Department</label>
    <nameField>
        <displayFormat>DMGR-{00000}</displayFormat>
        <label>Master Department ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_Department_Mgr__c/fields/Dept_ID__c.field-meta.xml
<CustomField>
    <fullName>Dept_ID__c</fullName>
    <externalId>true</externalId>
    <label>Dept ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Organization_Department_Mgr__c/fields/MGR_LVL_1_DESCR__c.field-meta.xml
<CustomField>
    <fullName>MGR_LVL_1_DESCR__c</fullName>
    <label>MGR LVL 1 DESCR</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrative</fullName>
            </value>
            <value>
                <fullName>Dene Nation Industrial Service</fullName>
            </value>
            <value>
                <fullName>Environmental Services</fullName>
            </value>
            <value>
                <fullName>SK Sustainability Solutions</fullName>
            </value>
            <value>
                <fullName>#N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Organization_Department_Mgr__c/fields/MGR_LVL_2_DESCR__c.field-meta.xml
<CustomField>
    <fullName>MGR_LVL_2_DESCR__c</fullName>
    <label>MGR LVL 2 DESCR</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>#N/A</fullName>
            </value>
            <value>
                <fullName>Asset Mgmt &amp; Supply Chain</fullName>
            </value>
            <value>
                <fullName>Corp Dev &amp; Real Estate</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corp Sales &amp; Corp Marketing</fullName>
            </value>
            <value>
                <fullName>Dene Nation Industrial Service</fullName>
            </value>
            <value>
                <fullName>Discontinued Facilities</fullName>
            </value>
            <value>
                <fullName>Distribution Centers</fullName>
            </value>
            <value>
                <fullName>Environ Svcs Sales and Service</fullName>
            </value>
            <value>
                <fullName>Facilities and Facility Sales</fullName>
            </value>
            <value>
                <fullName>Indust Svcs Sales and Service</fullName>
            </value>
            <value>
                <fullName>National Trans</fullName>
            </value>
            <value>
                <fullName>Pricing &amp; Proposals</fullName>
            </value>
            <value>
                <fullName>Safety-Kleen Oil</fullName>
            </value>
            <value>
                <fullName>Safety-Kleen Supply</fullName>
            </value>
            <value>
                <fullName>SK Bulk Products &amp; Services</fullName>
            </value>
            <value>
                <fullName>Trans Compliance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Organization_Department_Mgr__c/fields/MGR_LVL_3_DESCR__c.field-meta.xml
<CustomField>
    <fullName>MGR_LVL_3_DESCR__c</fullName>
    <label>MGR LVL 3 DESCR</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asset Mgmt &amp; Supply Chain</fullName>
            </value>
            <value>
                <fullName>Broker Business</fullName>
            </value>
            <value>
                <fullName>Canada Industrial Svcs</fullName>
            </value>
            <value>
                <fullName>CHES Sales and Service</fullName>
            </value>
            <value>
                <fullName>Corp Dev &amp; Real Estate</fullName>
            </value>
            <value>
                <fullName>Corp Pricing &amp; Proposals</fullName>
            </value>
            <value>
                <fullName>Corp Sales &amp; Corp Marketing</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Daylighting Services Canada</fullName>
            </value>
            <value>
                <fullName>Dene Nation Industrial Service</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Distribution Centers</fullName>
            </value>
            <value>
                <fullName>Environmental Svcs Sls and Adm</fullName>
            </value>
            <value>
                <fullName>Facilities Group</fullName>
            </value>
            <value>
                <fullName>IS Sales &amp; Svc Sales &amp; Admin</fullName>
            </value>
            <value>
                <fullName>Lodging Services</fullName>
            </value>
            <value>
                <fullName>National Transportation</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas Field Services</fullName>
            </value>
            <value>
                <fullName>Oil Sands</fullName>
            </value>
            <value>
                <fullName>Project Services</fullName>
            </value>
            <value>
                <fullName>Refined &amp; Blended Product Sale</fullName>
            </value>
            <value>
                <fullName>Safety-Kleen Supply</fullName>
            </value>
            <value>
                <fullName>SK Bulk Products &amp; Services1</fullName>
            </value>
            <value>
                <fullName>SK Facility Operations</fullName>
            </value>
            <value>
                <fullName>SK Pricing &amp; Proposals</fullName>
            </value>
            <value>
                <fullName>SK Sales and Service</fullName>
            </value>
            <value>
                <fullName>SKO Customer Service</fullName>
            </value>
            <value>
                <fullName>SKO Packaging &amp; Blending</fullName>
            </value>
            <value>
                <fullName>SKO Supply Chain</fullName>
            </value>
            <value>
                <fullName>Specialty Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Organization_Department_Mgr__c/fields/MGR_LVL_4_DESCR__c.field-meta.xml
<CustomField>
    <fullName>MGR_LVL_4_DESCR__c</fullName>
    <label>MGR LVL 4 DESCR</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asset Mgmt &amp; Supply Chain</fullName>
            </value>
            <value>
                <fullName>Automotive Services</fullName>
            </value>
            <value>
                <fullName>Base Oil Sales</fullName>
            </value>
            <value>
                <fullName>Blended Sales</fullName>
            </value>
            <value>
                <fullName>BPS Admin</fullName>
            </value>
            <value>
                <fullName>BPS Canada Region</fullName>
            </value>
            <value>
                <fullName>BPS Central Region</fullName>
            </value>
            <value>
                <fullName>BPS East Region</fullName>
            </value>
            <value>
                <fullName>BPS Lab</fullName>
            </value>
            <value>
                <fullName>BPS Oil Filter Recylers</fullName>
            </value>
            <value>
                <fullName>BPS West Region</fullName>
            </value>
            <value>
                <fullName>Broker Business</fullName>
            </value>
            <value>
                <fullName>Canada Industrial Svcs</fullName>
            </value>
            <value>
                <fullName>Canada Region</fullName>
            </value>
            <value>
                <fullName>Central Region IS</fullName>
            </value>
            <value>
                <fullName>Chemical Region IS</fullName>
            </value>
            <value>
                <fullName>CHESI Sales</fullName>
            </value>
            <value>
                <fullName>Corp Dev &amp; Real Estate</fullName>
            </value>
            <value>
                <fullName>Corp Pricing &amp; Proposals</fullName>
            </value>
            <value>
                <fullName>Corp Sales &amp; Mktg Admin</fullName>
            </value>
            <value>
                <fullName>Corporate Billing</fullName>
            </value>
            <value>
                <fullName>Corporate Executive</fullName>
            </value>
            <value>
                <fullName>Corporate Finance</fullName>
            </value>
            <value>
                <fullName>Corporate Government Strategy</fullName>
            </value>
            <value>
                <fullName>Corporate Marketing</fullName>
            </value>
            <value>
                <fullName>Corporate MIS &amp; TI</fullName>
            </value>
            <value>
                <fullName>Customer Care_Central Routing</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Daylighting Services Canada</fullName>
            </value>
            <value>
                <fullName>Dene Nation Industrial Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Organization_Department_Mgr__c/fields/MGR_LVL_5_DESCR__c.field-meta.xml
<CustomField>
    <fullName>MGR_LVL_5_DESCR__c</fullName>
    <label>MGR LVL 5 DESCR</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automotive Services</fullName>
            </value>
            <value>
                <fullName>Base Oil Sales</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Blended Sales</fullName>
            </value>
            <value>
                <fullName>BPS Admin1</fullName>
            </value>
            <value>
                <fullName>BPS California Area</fullName>
            </value>
            <value>
                <fullName>BPS Canada Region1</fullName>
            </value>
            <value>
                <fullName>BPS Central Region1</fullName>
            </value>
            <value>
                <fullName>BPS East Region1</fullName>
            </value>
            <value>
                <fullName>BPS Eastern Canada Area</fullName>
            </value>
            <value>
                <fullName>BPS Lab1</fullName>
            </value>
            <value>
                <fullName>BPS Midwest Area</fullName>
            </value>
            <value>
                <fullName>BPS Mountain States Area</fullName>
            </value>
            <value>
                <fullName>BPS Northeast Area</fullName>
            </value>
            <value>
                <fullName>BPS Northwest Area</fullName>
            </value>
            <value>
                <fullName>BPS Oil Filter Recylers1</fullName>
            </value>
            <value>
                <fullName>BPS Plain States Area</fullName>
            </value>
            <value>
                <fullName>BPS Southeast Area</fullName>
            </value>
            <value>
                <fullName>BPS Southwest Area</fullName>
            </value>
            <value>
                <fullName>BPS Texas Area</fullName>
            </value>
            <value>
                <fullName>BPS West Region1</fullName>
            </value>
            <value>
                <fullName>BPS Western Canada Area</fullName>
            </value>
            <value>
                <fullName>Broker Business</fullName>
            </value>
            <value>
                <fullName>Canada East Industrial Svcs</fullName>
            </value>
            <value>
                <fullName>Canada Industrial Sales &amp; Adm</fullName>
            </value>
            <value>
                <fullName>Canada SK Env Regions</fullName>
            </value>
            <value>
                <fullName>Canada Technical Svcs</fullName>
            </value>
            <value>
                <fullName>Canada West Industrial Svcs</fullName>
            </value>
            <value>
                <fullName>Central CenTex District</fullName>
            </value>
            <value>
                <fullName>Central District</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DeparmentManagerDAO.cls
/**
 * @description       : 
 * @author            : Suresh Beniwal
 * @group             : 
 * @last modified on  : 06-09-2022
 * @last modified by  : Suresh Beniwal 
 * Modifications Log
 * Ver   Date         Author           Modification
 * 1.0   06-09-2022   Suresh Beniwal   Initial Version
**/
public without sharing class DeparmentManagerDAO {
    
    /**
    * @description 
    * @author Suresh Beniwal | 06-09-2022 
    * @return List<Organization_Department_Mgr__c> 
    **/
    public static List<Organization_Department_Mgr__c> getListOfDepartmentManagers() {
        return  [
            SELECT Id, Name, Dept_ID__c, MGR_LVL_3_DESCR__c, MGR_LVL_1_DESCR__c, MGR_LVL_2_DESCR__c, 
                MGR_LVL_4_DESCR__c, MGR_LVL_5_DESCR__c, MGR_LVL_6_DESCR__c, MGR_LVL_7_DESCR__c 
            FROM Organization_Department_Mgr__c
            WHERE MGR_LVL_3_DESCR__c != NULL
        ];
    }
}