force-app/main/default/objects/Competitor_Capture__c/Competitor_Capture__c.object-meta.xml
<CustomObject>
    <label>Competitor Capture</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Competitor Capture Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitor Capture</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Capture__c/fields/CreatedBy_Username__c.field-meta.xml
<CustomField>
    <fullName>CreatedBy_Username__c</fullName>
    <label>Created by Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CompetitorCaptureCRUDHandler.cls
/*
Author: Sireesha
Date: 22nd June, 2020
Description: Handler class for the Competitor Capture Trigger
*/

public class CompetitorCaptureCRUDHandler {
	
    
    public static void updateCreatedOwnerAlias(List<Competitor_Capture__c> newList){
        
        Profile intProfile = [Select Id, Name from Profile where Name  = 'Integration' LIMIT 1];
        
        Id profileId = UserInfo.getProfileId();
        Id userId = UserInfo.getUserId();
        
        if(profileId != intProfile.Id){
            
            String aliasName = [Select Id, Name, Alias from User where Id =:userId].Alias;
            
            for(Competitor_Capture__c cc : newList){
                
                if(aliasName != NULL){
                    cc.CreatedBy_Username__c = aliasName;
                }
            }
        }
    }        
}