force-app/main/default/objects/Ownership_Change_Request__c/Ownership_Change_Request__c.object-meta.xml
<CustomObject>
    <label>Ownership Change Request</label>
    <nameField>
        <displayFormat>OCR-{000000}</displayFormat>
        <label>Ownership Change Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ownership Change Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ownership_Change_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ownership Change Requests</relationshipLabel>
    <relationshipName>Ownership_Change_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>  
</CustomField>

force-app/main/default/objects/Ownership_Change_Request__c/fields/Account_Operating_Segment__c.field-meta.xml
<CustomField>
    <fullName>Account_Operating_Segment__c</fullName>
    <formula>Text(Account__r.Primary_Service_Provider_New__c)</formula>
    <inlineHelpText>Current Operating Segment on the account.</inlineHelpText>
    <label>Account Operating Segment</label>
    <type>Text</type>
</CustomField> 

force-app/main/default/objects/Ownership_Change_Request__c/fields/Account_Operating_Segment_Text__c.field-meta.xml
<CustomField>
    <fullName>Account_Operating_Segment_Text__c</fullName>
    <label>Account Operating Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ownership_Change_Request__c/fields/Account_Owner_del__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner_del__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Ownership_Change_Requests_del</relationshipName>
    <type>Lookup</type>
</CustomField>
 

force-app/main/default/objects/Ownership_Change_Request__c/fields/Account_Primary_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Account_Primary_Service_Provider__c</fullName>
    <formula>Text(Account__r.Primary_Business__c)</formula>
    <inlineHelpText>Current Primary Service Provider on the account.</inlineHelpText>
    <label>Account Primary Service Provider</label>
    <type>Text</type>
</CustomField> 

force-app/main/default/objects/Ownership_Change_Request__c/fields/Account_Primary_Service_Provider_Text__c.field-meta.xml
<CustomField>
    <fullName>Account_Primary_Service_Provider_Text__c</fullName>
    <label>Account Primary Service Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ownership_Change_Request__c/fields/Current_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Current_Account_Owner__c</fullName>
    <description>This field is used for the Items to Approve unmanaged package and is intentionally left off of the layout</description>
    <formula>Account_Owner_del__r.FirstName &amp;&quot; &quot;&amp;  Account_Owner_del__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Account Owner</label>
    <type>Text</type>
</CustomField>
 

force-app/main/default/objects/Ownership_Change_Request__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>    
    <formula>IF(Intra_Quarter_Flip__c,
TODAY(),
IF(EligibileForIntraQuarterFlip__c &amp;&amp; ISPICKVAL(Account_Owner_del__r.Sales_Person_Type__c, &apos;Sales Placeholder&apos;),
NULL,
IF(Month(DATEVALUE(CreatedDate)) =1, DATE(YEAR(DATEVALUE(CreatedDate)) , 04 , 01), 
IF(Month(DATEVALUE(CreatedDate)) =2, DATE(YEAR(DATEVALUE(CreatedDate)) , 04 , 01),
IF(Month(DATEVALUE(CreatedDate)) =3, if((DAY(DATEVALUE(CreatedDate))&gt;= 25),DATE(YEAR(DATEVALUE(CreatedDate)) , 07 , 01),DATE(YEAR(DATEVALUE(CreatedDate)) , 04 , 01)),
IF(Month(DATEVALUE(CreatedDate)) =4, DATE(YEAR(DATEVALUE(CreatedDate)) , 07 , 01), 
IF(Month(DATEVALUE(CreatedDate)) =5, DATE(YEAR(DATEVALUE(CreatedDate)) , 07 , 01), 
IF(Month(DATEVALUE(CreatedDate)) =6, if((DAY(DATEVALUE(CreatedDate))&gt;= 24),DATE(YEAR(DATEVALUE(CreatedDate)) , 10 , 01),DATE(YEAR(DATEVALUE(CreatedDate)) , 07 , 01)),
IF(Month(DATEVALUE(CreatedDate)) =7, DATE(YEAR(DATEVALUE(CreatedDate)) , 10 , 01), 
IF(Month(DATEVALUE(CreatedDate)) =8, DATE(YEAR(DATEVALUE(CreatedDate)) , 10 , 01), 
IF(Month(DATEVALUE(CreatedDate)) =9, if((DAY(DATEVALUE(CreatedDate))&gt;= 24),DATE(YEAR(DATEVALUE(CreatedDate))+1 , 01 , 01),DATE(YEAR(DATEVALUE(CreatedDate)) , 10 , 01)),
IF(Month(DATEVALUE(CreatedDate)) =10, DATE(YEAR(DATEVALUE(CreatedDate))+1 , 01 , 01), 
IF(Month(DATEVALUE(CreatedDate)) =11, DATE(YEAR(DATEVALUE(CreatedDate))+1 , 01 , 01), 
IF(DAY(DATEVALUE(CreatedDate))&gt;= 25,DATE(YEAR(DATEVALUE(CreatedDate))+1 , 04 , 01),DATE(YEAR(DATEVALUE(CreatedDate))+1 , 01 , 01)))))))))))))))</formula>
    <inlineHelpText>This field is auto populated to the first day of the next quarter. Unless submitted in the final week of the current quarter.</inlineHelpText>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ownership_Change_Request__c/fields/Existing_Owner_s_Manager__c.field-meta.xml
<CustomField>
    <fullName>Existing_Owner_s_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Existing Owner’s Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Ownership_Change_Requests5</relationshipName>
    <type>Lookup</type>
</CustomField>
 

force-app/main/default/objects/Ownership_Change_Request__c/fields/Existing_Owner_s_VP__c.field-meta.xml
<CustomField>
    <fullName>Existing_Owner_s_VP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Existing Owner’s VP</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Ownership_Change_Requests6</relationshipName>
    <type>Lookup</type>
</CustomField>
 

force-app/main/default/objects/Ownership_Change_Request__c/fields/Justification__c.field-meta.xml
<CustomField>
    <fullName>Justification__c</fullName>
    <inlineHelpText>Provide any additional information on this particular change request.</inlineHelpText>
    <label>Justification</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>
 

force-app/main/default/objects/Ownership_Change_Request__c/fields/Need_Existing_Manager_Approval__c.field-meta.xml
<CustomField>
    <fullName>Need_Existing_Manager_Approval__c</fullName>
    <formula>AND(NOT(ISPICKVAL(Account__r.Primary_Business__c,&quot;&quot;)), New_Owner_s_Manager__c &lt;&gt;  Existing_Owner_s_Manager__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Need Existing Manager Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ownership_Change_Request__c/fields/New_Operating_Segment__c.field-meta.xml
<CustomField>
    <fullName>New_Operating_Segment__c</fullName>
    <inlineHelpText>The operating segment that will be populated on the account if approved. This is determined by the requested owner&apos;s primary business.</inlineHelpText>
    <label>Requested Operating Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SK ENV</fullName>
            </value>
            <value>
                <fullName>SK BPS</fullName>
            </value>
            <value>
                <fullName>SK KPP</fullName>
            </value>
            <value>
                <fullName>Clean Harbors ENV</fullName>
            </value>
            <value>
                <fullName>CHES Oil and Gas</fullName>
            </value>
            <value>
                <fullName>CHES Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>
   

force-app/main/default/objects/Ownership_Change_Request__c/fields/New_Owner__c.field-meta.xml
<CustomField>
    <fullName>New_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the owner that is being requested for the account ownership change</description>
    <inlineHelpText>If approved, the user that will become the owner of the account.</inlineHelpText>
    <label>Requested Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Ownership_Change_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>
  

force-app/main/default/objects/Ownership_Change_Request__c/fields/New_Owner_s_Manager__c.field-meta.xml
<CustomField>
    <fullName>New_Owner_s_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Owner’s Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Ownership_Change_Requests3</relationshipName>
    <type>Lookup</type>
</CustomField>  
 

force-app/main/default/objects/Ownership_Change_Request__c/fields/New_Owner_s_VP__c.field-meta.xml
<CustomField>
    <fullName>New_Owner_s_VP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Owner’s VP</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Ownership_Change_Requests4</relationshipName>
    <type>Lookup</type>
</CustomField>
 

force-app/main/default/objects/Ownership_Change_Request__c/fields/New_Primary_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>New_Primary_Service_Provider__c</fullName>
    <inlineHelpText>The primary service provider that will be populated on the account if approved. This is determined by the requested owner&apos;s primary business. Please confirm that this value is correct before submitting the request for approval.</inlineHelpText>
    <label>Requested Primary Service Provider</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>New_Operating_Segment__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Daylighting Services</fullName>
            </value>
            <value>
                <fullName>Emerald Services</fullName>
            </value>
            <value>
                <fullName>Field Services</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Industrial Services</fullName>
            </value>
            <value>
                <fullName>Lodging</fullName>
            </value>
            <value>
                <fullName>Murphys Oil</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Technical Services</fullName>
            </value>
            <value>
                <fullName>Thermo Fluids</fullName>
            </value>
            <value>
                <fullName>H2O</fullName>
            </value>
            <value>
                <fullName>BPS</fullName>
            </value>
            <value>
                <fullName>CYN</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>SK KPP</fullName>
            </value>
            <value>
                <fullName>Surface Rentals</fullName>
            </value>
            <value>
                <fullName>Seismic</fullName>
            </value>
            <value>
                <fullName>SK ENV</fullName>
            </value>
            <value>
                <fullName>OER</fullName>
            </value>
            <value>
                <fullName>HPC Industrial</fullName>
            </value>
            <value>
                <fullName>PSC</fullName>
            </value>
            <value>
                <fullName>Synergy</fullName>
            </value>
			<value>
                <fullName>Thompson</fullName>
            </value>
			<value>
                <fullName>Noble Oil</fullName>
            </value>
            <value>
                <fullName>HEPACO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>  

force-app/main/default/objects/Ownership_Change_Request__c/fields/Prior_year_s_revenue__c.field-meta.xml
<CustomField>
    <fullName>Prior_year_s_revenue__c</fullName>
    <label>Prior year&apos;s revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>
 

force-app/main/default/objects/Ownership_Change_Request__c/fields/Requested_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Requested_Account_Owner__c</fullName>
    <description>This field is used for the Items to Approve unmanaged package and is intentionally left off of the layout</description>
    <formula>New_Owner__r.FirstName &amp;&quot; &quot;&amp; New_Owner__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Requested Account Owner</label>
    <type>Text</type>
</CustomField> 

force-app/main/default/objects/Ownership_Change_Request__c/fields/Requested_Owner_Territory_Id__c.field-meta.xml
<CustomField>
    <fullName>Requested_Owner_Territory_Id__c</fullName>
    <label>Requested Owner Territory Id</label>
    <length>255</length>
    <type>Text</type> 
</CustomField> 

force-app/main/default/objects/Ownership_Change_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet> 
        <restricted>true</restricted>
        <valueSetDefinition>
            <value> 
                <fullName>New</fullName>
            </value>
            <value> 
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved-Pending</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value> 
            <value>
                <fullName>Executed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
			<value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OwnershipChangeRequestSchduler.cls
public class OwnershipChangeRequestSchduler implements Schedulable{  
     String query = '';
    public OwnershipChangeRequestSchduler(String query)
    {
        this.query = query;
    }
    public void execute(SchedulableContext SC) {
        if(query=='')
        {
            query = 'SELECT Id, Name, Account__c, Account_Owner_del__c,Account_Operating_Segment_Text__c,Requested_Owner_Territory_Id__c, Account_Operating_Segment__c,Account_Primary_Service_Provider_Text__c, Account_Primary_Service_Provider__c,'+
                'Current_Account_Owner__c, Requested_Account_Owner__c, New_Owner__c, Justification__c, New_Owner_s_Manager__c, New_Owner_s_VP__c, Existing_Owner_s_Manager__c, Existing_Owner_s_VP__c, Effective_Date__c, Status__c, New_Operating_Segment__c, New_Primary_Service_Provider__c, Prior_year_s_revenue__c, Need_Existing_Manager_Approval__c, Account_Owner_Managers_Same__c,'+
                'Account_Owner_Vps_Same__c,  Reason_for_Change__c FROM Ownership_Change_Request__c where Status__c = \'Approved-Pending\'  AND Intra_Quarter_Flip__c =true';
        }
        AccountOwnershipChangeBatch accountOwnerShipChangeBatchObj = new AccountOwnershipChangeBatch(query); 
        Database.executeBatch(accountOwnerShipChangeBatchObj, 150);
    }
}