force-app/main/default/objects/Account/fields/Account_Assign_Override__c.field-meta.xml
<CustomField>
    <fullName>Account_Assign_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Account Assign Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Buying_Decision__c.field-meta.xml
<CustomField>
    <fullName>Buying_Decision__c</fullName>
    <label>Buying Decision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Central Buying</fullName>
            </value>
            <value>
                <fullName>Locally Managed</fullName>
            </value>
            <value>
                <fullName>Hybrid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <formula>ShippingCity</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/dunbrdst__c.field-meta.xml
<CustomField>
    <fullName>dunbrdst__c</fullName>
    <description>dunbrdst from Beacon for Key Accounts</description>
    <externalId>true</externalId>
    <label>dunbrdst</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/KAM_Manager__c.field-meta.xml
<CustomField>
    <fullName>KAM_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Key Account owner&apos;s manager.  Generally a VP.</description>
    <label>CAM Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/KAM_Support__c.field-meta.xml
<CustomField>
    <fullName>KAM_Support__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person that supports KAM Account</description>
    <label>CAM Support</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Business__c.field-meta.xml
<CustomField>
    <fullName>Primary_Business__c</fullName>
    <description>Primary business based off account owner</description>
    <label>Primary Service Provider</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Primary_Service_Provider_New__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Daylighting Services</fullName>
            </value>
            <value>
                <fullName>Emerald Services</fullName>
            </value>
            <value>
                <fullName>Field Services</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Industrial Services</fullName>
            </value>
            <value>
                <fullName>Lodging</fullName>
            </value>
            <value>
                <fullName>Murphys Oil</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Technical Services</fullName>
            </value>
            <value>
                <fullName>Thermo Fluids</fullName>
            </value>
            <value>
                <fullName>H2O</fullName>
            </value>
            <value>
                <fullName>BPS</fullName>
            </value>
            <value>
                <fullName>CYN</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>SK KPP</fullName>
            </value>
            <value>
                <fullName>Surface Rentals</fullName>
            </value>
            <value>
                <fullName>Seismic</fullName>
            </value>
            <value>
                <fullName>Safety-Kleen</fullName>
                <label>SK ENV</label>
            </value>
            <value>
                <fullName>OER</fullName>
            </value>
            <value>
                <fullName>HPC Industrial</fullName>
            </value>
            <value>
                <fullName>PSC</fullName>
            </value>
            <value>
                <fullName>Synergy</fullName>
            </value>
            <value>
                <fullName>DFW</fullName>
            </value>
			<value>
                <fullName>Thompson</fullName>
            </value>
			<value>
                <fullName>Noble Oil</fullName>
            </value>
            <value>
                <fullName>HEPACO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/WIN_ID__c.field-meta.xml
<CustomField>
    <fullName>WIN_ID__c</fullName>
    <externalId>true</externalId>
    <label>WIN ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ZIP_Master__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZIP Master</label>
    <referenceTo>ZIP_Master__c</referenceTo>
    <relationshipLabel>Accounts (ZIP Master)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Corporate.recordType-meta.xml
<RecordType>
    <fullName>Corporate</fullName>
    <active>true</active>
    <description>All Clean Harbor Corporate Accounts</description>
    <label>Corporate</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/WIN_ID__c.field-meta.xml
<CustomField>
    <fullName>WIN_ID__c</fullName>
    <description>WIN ID of account picked for opportunity.</description>
    <formula>Account.WIN_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>WIN ID of account picked for opportunity.</inlineHelpText>
    <label>WIN ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <formula>Account.ShippingPostalCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zip</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Zip_Master__c.field-meta.xml
<CustomField>
    <fullName>Zip_Master__c</fullName>
    <description>Link to Accounts Zip Master</description>
    <formula>HYPERLINK(&quot;/&quot; &amp;  Account.ZIP_Master__c,  Account.ZIP_Master__r.ZIP__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zip Master</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Safety_Kleen_BPS_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Safety_Kleen_BPS_Opportunity</fullName>
    <active>true</active>
    <businessProcess>All Clean Harbors Sales Process</businessProcess>
    <description>Safety Kleen and BPS Opportunity</description>
    <label>Safety Kleen / BPS Opportunity</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Primary_Business__c.field-meta.xml
<CustomField>
    <fullName>Primary_Business__c</fullName>
    <description>Primary Business for the LOB</description>
    <label>Primary Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Primary_Business</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SIC_VALIDATION_SETTING__c/SIC_VALIDATION_SETTING__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS will consist of a flag which determines if SIC Validation on Account should be implemented or not.</description>
    <label>SIC VALIDATION SETTING</label>
</CustomObject>

force-app/main/default/objects/SIC_VALIDATION_SETTING__c/fields/SIC_VALIDATION_FLAG__c.field-meta.xml
<CustomField>
    <fullName>SIC_VALIDATION_FLAG__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag which determines if SIC Validation should be executed in the custom code or not. Should be Checked if SIC Validation is required.</description>
    <label>SIC_VALIDATION_FLAG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TERRITORY_MANAGEMENT__c/TERRITORY_MANAGEMENT__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS will consist of a flag which determines if Territory Management on Account should be implemented or not. If Yes, the Territory and Owner on Account are set based on the criteria.</description>
    <label>TERRITORY MANAGEMENT</label>
</CustomObject>

force-app/main/default/objects/TERRITORY_MANAGEMENT__c/fields/TM_FLAG__c.field-meta.xml
<CustomField>
    <fullName>TM_FLAG__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag which determines if TM should be executed in the custom code or not thus setting the Territory and the Account Owner field on the Account record. Should be Checked if TM is required.</description>
    <inlineHelpText>Flag which determines if TM should be executed in the custom code or not</inlineHelpText>
    <label>TM_FLAG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Process__c/Trigger_Process__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to allow or prevent the creation of revenue schedules and updating the cross lob flags.</description>
    <label>Product Revenue Schedule Trigger</label>
</CustomObject>

force-app/main/default/objects/Trigger_Process__c/fields/canProcess__c.field-meta.xml
<CustomField>
    <fullName>canProcess__c</fullName>
    <defaultValue>false</defaultValue>
    <label>canProcess</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Primary_Business__c.field-meta.xml
<CustomField>
    <fullName>Primary_Business__c</fullName>
    <description>Primary business to be added to the accounts based off the owners value</description>
    <label>Primary Business</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BPS</fullName>
            </value>
            <value>
                <fullName>CYN Environmental</fullName>
            </value>
            <value>
                <fullName>CYN Oil</fullName>
            </value>
            <value>
                <fullName>Daylighting Services</fullName>
            </value>
            <value>
                <fullName>DFW</fullName>
            </value>
            <value>
                <fullName>Emerald Services</fullName>
            </value>
            <value>
                <fullName>Field Services</fullName>
            </value>
            <value>
                <fullName>H2O</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Industrial Services</fullName>
            </value>
            <value>
                <fullName>Kleen Performance Products</fullName>
            </value>
            <value>
                <fullName>Lodging</fullName>
            </value>
            <value>
                <fullName>Murphys Oil</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Performance Plus Products</fullName>
            </value>
            <value>
                <fullName>Production Services</fullName>
            </value>
            <value>
                <fullName>RS Used Oil</fullName>
            </value>
            <value>
                <fullName>Safety-Kleen</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>Technical Services</fullName>
            </value>
            <value>
                <fullName>Thermo Fluids</fullName>
            </value>
			<value>
                <fullName>Thompson</fullName>
            </value>
			<value>
                <fullName>Noble Oil</fullName>
            </value>
            <value>
                <fullName>HEPACO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Primary_Business__c/User_Primary_Business__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>User Primary Business</label>
</CustomObject>

force-app/main/default/objects/User_Primary_Business__c/fields/Primary_Business__c.field-meta.xml
<CustomField>
    <fullName>Primary_Business__c</fullName>
    <label>Primary Business</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/ZIP_Master__c.object-meta.xml
<CustomObject>
    <label>ZIP Master</label>
    <nameField>
        <label>ZIP Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZIP Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZIP_Master__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Zip codes primary city</description>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>US States</description>
    <label>State</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/fields/ZIP__c.field-meta.xml
<CustomField>
    <fullName>ZIP__c</fullName>
    <label>ZIP</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Primary_Business.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Emerald Services</fullName>
    </customValue>
    <customValue>
        <fullName>Field Services</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare Services</fullName>
    </customValue>
    <customValue>
        <fullName>Industrial Services</fullName>
    </customValue>
    <customValue>
        <fullName>Kleen Performance Products</fullName>
    </customValue>
    <customValue>
        <fullName>Lodging</fullName>
    </customValue>
    <customValue>
        <fullName>Oil &amp; Gas</fullName>
    </customValue>
    <customValue>
        <fullName>Safety-Kleen</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Operations</fullName>
    </customValue>
    <customValue>
        <fullName>Technical Services</fullName>
    </customValue>
    <customValue>
        <fullName>Thermo Fluids</fullName>
    </customValue>
    <customValue>
        <fullName>Performance Plus Products</fullName>
    </customValue>
    <customValue>
        <fullName>Murphys Oil</fullName>
    </customValue>
    <customValue>
        <fullName>Daylighting Services</fullName>
    </customValue>
    <customValue>
        <fullName>Production Services</fullName>
    </customValue>
    <customValue>
        <fullName>CYN Environmental</fullName>
    </customValue>
    <customValue>
        <fullName>CYN Oil</fullName>
    </customValue>
    <customValue>
        <fullName>H2O</fullName>
    </customValue>
    <customValue>
        <fullName>BPS</fullName>
    </customValue>
    <customValue>
        <fullName>HPC</fullName>
    </customValue>
	<customValue>
        <fullName>Thompson</fullName>
    </customValue>
	<customValue>
        <fullName>Noble Oil</fullName>
    </customValue>
    <customValue>
        <fullName>HEPACO</fullName>
    </customValue>
    <customValue>
        <fullName>DFW</fullName>
    </customValue>
    <description>Global Picklist for Primary Business</description>
    <masterLabel>Primary Business</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/Q2COppotuniyDataAPITest.cls
@isTest
public class Q2COppotuniyDataAPITest {
	@testSetup
    private static void setupDate(){
        User_Primary_Business__c bps = new User_Primary_Business__c();
        bps.Name = 'Safety-Kleen';
        bps.Primary_Business__c = 'Safety-Kleen';
        insert bps;
        
        Trigger_Process__c tp_lobcs = new Trigger_Process__c(
            Name='LOB Cross Sell',
            canProcess__c=true
        );
        Trigger_Process__c tp_rs = new Trigger_Process__c(
            Name='Revenue Schedule',
            canProcess__c=true
        );   
        
        insert tp_lobcs;
        
        insert tp_rs;
        
        TERRITORY_MANAGEMENT__c territoryMgmt = new TERRITORY_MANAGEMENT__c();
        territoryMgmt.Name = 'TERRITORY_MGMT_SETTING';
        territoryMgmt.TM_FLAG__c = true;
        insert territoryMgmt;
        COUNTRY_CODES__c countrycodes = new COUNTRY_CODES__c();
        countrycodes.Name = 'CA';
        insert countrycodes;
        
        COUNTRY_CODES__c countrycodes1 = new COUNTRY_CODES__c();
        countrycodes1.Name = 'US';
        insert countrycodes1;
        
        List<ZIP_Master__c> zipMasterList = new List<ZIP_Master__c>();
        for(Integer i = 0; i < 10; i++){
            zipMasterList.add(new ZIP_Master__c(Zip__c = '12345',Country__c = 'US', State__c = 'NY',City__c ='Ashburn'));
			zipMasterList.add(new ZIP_Master__c(Zip__c = '20147',Country__c = 'US', State__c = 'NY',City__c ='Ashburn'));
        }
       insert zipMasterList;
        
        SIC_VALIDATION_SETTING__c sicValidation = new SIC_VALIDATION_SETTING__c();
        sicValidation.Name = 'SIC_VALIDATION_SETTING';
        sicValidation.SIC_VALIDATION_FLAG__c = true;
        insert sicValidation;
        
        Id accRecTypeId = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get(CHConstants.ACCOUNT_RECORD_TYPE_CORPORATE).getRecordTypeId();
        User activeUser = [select Id from User where isActive = True Limit 1];
        Account accRec = new Account();
        accRec.Name = 'Parent Corporate Account';
		accRec.dunbrdst__c = '12345';
        accRec.ShippingCountry = 'US';
        accRec.ShippingState = 'NY';
        accRec.ShippingStreet = 'Test Street';
        accRec.ShippingCity = 'Ashburn';
        accRec.ShippingPostalCode = '12345';
        accRec.KAM_Manager__c = activeUser.id;
        accRec.KAM_Support__c = activeUser.id;
        accRec.RecordTypeId = accRecTypeId;
        accRec.Buying_Decision__c = 'Central Buying';
        accRec.Account_Assign_Override__c = false;
        accRec.Status__c = 'Active';
        accRec.WIN_ID__c = '1234';
        INSERT accRec;
        
        Id pricebookId = Test.getStandardPricebookId();  
        
        Pricebook2 customPB = new Pricebook2(
            Name='Safety-Kleen / BPS', 
            isActive=true,
            CurrencyISOCode = 'USD'
        );
        insert customPB;
        
        Product2 prod = new Product2(
            Name = 'Bulk Services',
            isActive=true,
            CanUseRevenueSchedule=true,
            Business_Unit__c='Field Services',
            Product_Hierarchy_Number__c = '3000',
            CurrencyIsoCode = 'USD'
        );
        insert prod;
        
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, 
            Product2Id = prod.Id,
            UnitPrice = 100,
            IsActive = true
        );
        
        PricebookEntry customPBEnt = new PricebookEntry(
            Pricebook2Id = customPB.Id, 
            Product2Id = prod.Id,
            UnitPrice = 100,
            IsActive = true
        );
        
        customPBEnt.CurrencyIsoCode = 'USD';
        
        System.debug('customPBEnt ' + customPBEnt);
        
        List<PricebookEntry> prBkList = new List<PricebookEntry>();
        prBkList.add(standardPrice);
        prBkList.add(customPBEnt);
        
        insert prBkList;
        
        Test.startTest();
        Opportunity oppRec = new Opportunity();		  
        oppRec.Name = 'SK Driver';
        oppRec.CloseDate = Date.today().addMonths(1);
        oppRec.Job_Start_Date__c = Date.today().addMonths(1);
        oppRec.StageName = '1 - Prospecting';
        oppRec.Creator_Username__c = 'test';
        oppRec.Creator_ID__c = '33356';
        oppRec.Opp_Strength__c = 'Interest level high - Quote needed';
        oppRec.Description = 'Test Comments';
        oppRec.Services_Discussed__c = '3000';
        oppRec.OwnerId = UserInfo.getUserId();
        oppRec.Parts_Cleaner_Type__c = 'None';
        oppRec.AccountId = accRec.Id; 
        oppRec.Pricebook2Id = customPB.Id;
        oppRec.CurrencyIsoCode = 'USD';
        oppRec.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Safety_Kleen_BPS_Opportunity').getRecordTypeId();
        INSERT oppRec;
        
        oppRec.Pricebook2Id = customPB.Id;
        UPDATE oppRec;
        
        System.debug('sdd ' + [SELECT Id, Pricebook2Id FROM Opportunity WHERE Id = :oppRec.Id]);
        
        OpportunityLineItem oppLineItemObj = new OpportunityLineItem();
        oppLineItemObj.OpportunityId = oppRec.Id;
        oppLineItemObj.Product2Id = prod.Id;
        oppLineItemObj.PricebookEntryId = customPBEnt.Id;
        INSERT oppLineItemObj;
        Test.stopTest();
    }
    
    @isTest
    private static void unitTest(){
        Account accountRec = [
            SELECT Id, WIN_ID__c
            FROM Account
            LIMIT 1
        ];
        Q2COppotuniyDataAPI.Q2COpportunityDataRequest Q2cDataReq = new Q2COppotuniyDataAPI.Q2COpportunityDataRequest();
        Q2cDataReq.OpportunityGeneratorCoCd = accountRec.WIN_ID__c;
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/Q2COppotuniyData/*';
        req.httpMethod = 'POST';
        
        req.requestBody = Blob.ValueOf(JSON.serialize(Q2cDataReq));
        RestContext.request = req;
        RestContext.response = res;
        Q2COppotuniyDataAPI.getQ2COppData();
        
        System.assert(res != NULL);
    }
}