force-app/main/default/objects/Account/fields/Active_Inactive__c.field-meta.xml
<CustomField>
    <fullName>Active_Inactive__c</fullName>
    <formula>IF(
 
 
  OR( ISPICKVAL( Status__c , &quot;Inactive&quot;)), IMAGE(&quot;http://i346.photobucket.com/albums/p420/Alexwaddell47/red_zpsstmdfrrt.png&quot;,&quot;red&quot;,14,14),
 

IF(
 

  AND(
 

      ISPICKVAL( Status__c , &quot;Active&quot;)) , IMAGE(&quot;http://i346.photobucket.com/albums/p420/Alexwaddell47/120px-Green_sphere_zpsvi7byqdp.png&quot;, &quot;Green&quot;, 16, 16), NULL
 

))</formula>
    <label>Active / Inactive</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Diversity_Organization_Detail__c.field-meta.xml
<CustomField>
    <fullName>Diversity_Organization_Detail__c</fullName>
    <label>Diversity Organization Detail</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>People with Disabilities</fullName>
            </value>
            <value>
                <fullName>Minorities</fullName>
            </value>
            <value>
                <fullName>Women</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Generator_Status__c.field-meta.xml
<CustomField>
    <fullName>Generator_Status__c</fullName>
	<inlineHelpText>An account&apos;s generator status can only be upgraded from Salesforce. Downgrades in this area need to be coordinated by our compliance team. For status downgrades, please submit a Service Now ticket using category/subcategory: WIN-Aurora(FocalPoint), CWT-Compliance or WIN-Compliance, EPA ID Number.</inlineHelpText>
    <label>Generator Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Large Quantity Generator</fullName>
            </value>
            <value>
                <fullName>Small Quantity Generator</fullName>
            </value>
            <value>
                <fullName>Conditionally Exempt Sm Qty Generator</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
                <default>true</default>
                <label>Undetermined</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Hires__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Hires__c</fullName>
    <label>Number of Hires</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Category__c.field-meta.xml
<CustomField>
    <fullName>Organization_Category__c</fullName>
    <label>Organization Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>College</fullName>
                <isActive>false</isActive>
                <label>College</label>
            </value>
            <value>
                <fullName>College or University</fullName>
            </value>
            <value>
                <fullName>Diversity Organization</fullName>
            </value>
            <value>
                <fullName>Driver School</fullName>
            </value>
            <value>
                <fullName>Military Agency</fullName>
            </value>
            <value>
                <fullName>Military Base</fullName>
            </value>
            <value>
                <fullName>National Organization</fullName>
                <isActive>false</isActive>
                <label>National Organization</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Skilled Trades Technical/Professional</fullName>
            </value>
            <value>
                <fullName>State Workforce Agency</fullName>
            </value>
            <value>
                <fullName>Technical High School</fullName>
                <isActive>false</isActive>
                <label>Technical High School</label>
            </value>
            <value>
                <fullName>Trade High School</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
                <isActive>false</isActive>
                <label>Website</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Category_Detail__c.field-meta.xml
<CustomField>
    <fullName>Organization_Category_Detail__c</fullName>
    <label>Organization Category Detail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_ID__c.field-meta.xml
<CustomField>
    <fullName>Organization_ID__c</fullName>
    <displayFormat>Org-{00000}</displayFormat>
    <label>Organization ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Status__c.field-meta.xml
<CustomField>
    <fullName>Organization_Status__c</fullName>
    <label>Organization Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Qualifying</fullName>
            </value>
            <value>
                <fullName>Qualified Partner</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Strategic Partner</fullName>
            </value>
            <value>
                <fullName>Archive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Size_of_Candidate_Pool__c.field-meta.xml
<CustomField>
    <fullName>Size_of_Candidate_Pool__c</fullName>
    <label>Size of Candidate Pool</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/HR_Talent_Pools.recordType-meta.xml
<RecordType>
    <fullName>HR_Talent_Pools</fullName>
    <active>true</active>
    <description>HR Partnership organizations used to recruit from their talent pools</description>
    <label>HR Recruiting Partners</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <description>Prospect Account Record Type</description>
    <label>Prospect</label>
</RecordType>

force-app/main/default/classes/AccountServiceTest.cls
/**
 * @description       : 
 * @author            : Suresh Beniwal
 * @group             : 
 * @last modified on  : 09-12-2022
 * @last modified by  : Suresh Beniwal
 * Modifications Log
 * Ver   Date         Author           Modification
 * 1.0   08-05-2022   Suresh Beniwal   Initial Version
**/
@isTest(SeeAllData=false)
public class AccountServiceTest {
    @testSetup static void setupmethod() {
        Id RecordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('HR_Talent_Pools').getRecordTypeId();
        Account acc = new Account();
        acc.Name = 'Farheen';
        acc.RecordTypeId = RecordTypeIdAccount;
        acc.Organization_Status__c ='Draft';
        //acc.Organization_ID__c = acc.id;
        acc.Organization_Category__c = 'Driver School';
        acc.ShippingStreet = '123';
        acc.ShippingCity = 'Jaipur';
        acc.ShippingState = 'Rajasthan';
		acc.Generator_Status__c='Small Quantity Generator';
        acc.ShippingCountry = 'US';
        acc.ShippingPostalCode = '302012';
        insert acc;

        Account acc1 = new Account();
        acc1.Name = 'Farheen1';
        acc1.RecordTypeId = RecordTypeIdAccount;
        acc1.Organization_Status__c ='Draft';
        //acc1.Organization_ID__c = acc.id;
        acc1.Organization_Category__c = 'Driver School';
        acc1.ShippingStreet = '123';
        acc1.ShippingCity = 'Jaipur';
        acc1.ShippingState = 'Rajasthan';
		acc1.Generator_Status__c='Small Quantity Generator';  
        acc1.ShippingCountry = 'US';
        acc1.ShippingPostalCode = '302012';
        insert acc1;
        acc.Organization_Status__c = 'Prospect';

        Test.startTest();
       
            try {
                update acc;
            } catch(Exception ex) {}
           
                
        Test.stopTest();
    }

    @IsTest static void TestOrganizationOwner(){
        List<Account> accList = [SELECT Id, Name, ParentId, Parent.Name, Organization_Id__c, Organization_Status__c, Organization_Category__c, Diversity_Organization_Detail__c, Size_of_Candidate_Pool__c, Number_of_Hires__c, Active_Inactive__c, Status__c, ShippingStreet, ShippingCity, ShippingState, ShippingCountry, ShippingPostalCode, Organization_Category_Detail__c FROM Account WHERE name = 'Farheen'];
        
        Test.startTest();
        	accList.get(0).Organization_Status__c = 'Draft';
        	update accList;
            List<AccountService.AccountWrapper> listOfAccountWrapper = AccountService.getListOfAccounts(accList);
        Test.stopTest();

        System.assertEquals(false, listOfAccountWrapper.isEmpty(), 'Wrapper data should be return !!');
    } 
    
    @IsTest static void TestOrganizationOwnerUpdate(){
        List<Account> accList = [SELECT Id FROM Account WHERE name = 'Farheen1' LIMIT 1];
        accList[0].Name = 'Farheen';
        
        Test.startTest();
            try {
                update accList;
            } catch (Exception ex) {}
        Test.stopTest();
    } 
    
}