force-app/main/default/objects/Account/fields/Active_Inactive__c.field-meta.xml
<CustomField>
    <fullName>Active_Inactive__c</fullName>
    <formula>IF(
 
 
  OR( ISPICKVAL( Status__c , &quot;Inactive&quot;)), IMAGE(&quot;http://i346.photobucket.com/albums/p420/Alexwaddell47/red_zpsstmdfrrt.png&quot;,&quot;red&quot;,14,14),
 

IF(
 

  AND(
 

      ISPICKVAL( Status__c , &quot;Active&quot;)) , IMAGE(&quot;http://i346.photobucket.com/albums/p420/Alexwaddell47/120px-Green_sphere_zpsvi7byqdp.png&quot;, &quot;Green&quot;, 16, 16), NULL
 

))</formula>
    <label>Active / Inactive</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Diversity_Organization_Detail__c.field-meta.xml
<CustomField>
    <fullName>Diversity_Organization_Detail__c</fullName>
    <label>Diversity Organization Detail</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>People with Disabilities</fullName>
            </value>
            <value>
                <fullName>Minorities</fullName>
            </value>
            <value>
                <fullName>Women</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Hires__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Hires__c</fullName>
    <label>Number of Hires</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Category__c.field-meta.xml
<CustomField>
    <fullName>Organization_Category__c</fullName>
    <label>Organization Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>College</fullName>
                <isActive>false</isActive>
                <label>College</label>
            </value>
            <value>
                <fullName>College or University</fullName>
            </value>
            <value>
                <fullName>Diversity Organization</fullName>
            </value>
            <value>
                <fullName>Driver School</fullName>
            </value>
            <value>
                <fullName>Military Agency</fullName>
            </value>
            <value>
                <fullName>Military Base</fullName>
            </value>
            <value>
                <fullName>National Organization</fullName>
                <isActive>false</isActive>
                <label>National Organization</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Skilled Trades Technical/Professional</fullName>
            </value>
            <value>
                <fullName>State Workforce Agency</fullName>
            </value>
            <value>
                <fullName>Technical High School</fullName>
                <isActive>false</isActive>
                <label>Technical High School</label>
            </value>
            <value>
                <fullName>Trade High School</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
                <isActive>false</isActive>
                <label>Website</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Category_Detail__c.field-meta.xml
<CustomField>
    <fullName>Organization_Category_Detail__c</fullName>
    <label>Organization Category Detail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_ID__c.field-meta.xml
<CustomField>
    <fullName>Organization_ID__c</fullName>
    <displayFormat>Org-{00000}</displayFormat>
    <label>Organization ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Status__c.field-meta.xml
<CustomField>
    <fullName>Organization_Status__c</fullName>
    <label>Organization Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Qualifying</fullName>
            </value>
            <value>
                <fullName>Qualified Partner</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Strategic Partner</fullName>
            </value>
            <value>
                <fullName>Archive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Size_of_Candidate_Pool__c.field-meta.xml
<CustomField>
    <fullName>Size_of_Candidate_Pool__c</fullName>
    <label>Size of Candidate Pool</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountService.cls
/**
 * @description       : 
 * @author            : Suresh Beniwal
 * @group             : 
 * @last modified on  : 08-17-2022
 * @last modified by  : Suresh Beniwal
 * Modifications Log
 * Ver   Date         Author           Modification
 * 1.0   06-10-2022   Suresh Beniwal   Initial Version
**/
public without sharing class AccountService {
    
    /**
    * @description 
    * @author Suresh Beniwal | 06-10-2022 
    * @param List<Account> listOfAccount 
    * @return List<AccountWrapper> 
    **/
    public static List<AccountWrapper> getListOfAccounts(List<Account> listOfAccount) {
        List<AccountWrapper> listOfAccountWrapper = new List<AccountWrapper>();

        for (Account accountRecord: listOfAccount) {
            AccountWrapper accountWrapperRecord = new AccountWrapper();
            accountWrapperRecord.organizationName = accountRecord.Name;
            accountWrapperRecord.organizationCode = accountRecord.Organization_Id__c;
            accountWrapperRecord.parentAccount = accountRecord.Parent.Name;
            accountWrapperRecord.organizationStatus = accountRecord.Organization_Status__c;
            accountWrapperRecord.organizationCategory = accountRecord.Organization_Category__c;
            accountWrapperRecord.organizationCategoryDetail = accountRecord.Organization_Category_Detail__c;
            accountWrapperRecord.diversityOrganizationDetail = accountRecord.Diversity_Organization_Detail__c;
            accountWrapperRecord.sizeofCandidatePool = accountRecord.Size_of_Candidate_Pool__c;
            accountWrapperRecord.numberofHires = accountRecord.Number_of_Hires__c;
            accountWrapperRecord.status = accountRecord.Status__c;
            accountWrapperRecord.activeInactive = accountRecord.Active_Inactive__c;
            accountWrapperRecord.shippingAddress = accountRecord.ShippingStreet != null ? (accountRecord.ShippingStreet + ' ' + accountRecord.ShippingCity + ' , ' + accountRecord.ShippingState + ' , ' + accountRecord.ShippingCountry + ' ' + accountRecord.ShippingPostalCode) : '';
            accountWrapperRecord.street = accountRecord.ShippingStreet;
            accountWrapperRecord.city = accountRecord.ShippingCity;
            accountWrapperRecord.state = accountRecord.ShippingState;
            accountWrapperRecord.country = accountRecord.ShippingCountry;
            accountWrapperRecord.zipcode = accountRecord.ShippingPostalCode;

            listOfAccountWrapper.add(accountWrapperRecord);
        }

        return listOfAccountWrapper;
    }
    
    public class AccountWrapper {
        @AuraEnabled public String organizationName;
        @AuraEnabled public String organizationCode;
        @AuraEnabled public String parentAccount;
        @AuraEnabled public String organizationStatus;
        @AuraEnabled public String organizationCategory;
        @AuraEnabled public String organizationCategoryDetail;
        @AuraEnabled public String diversityOrganizationDetail;
        @AuraEnabled public Decimal sizeofCandidatePool;
        @AuraEnabled public Decimal numberofHires;
        @AuraEnabled public String activeInactive;
        @AuraEnabled public String status;
        @AuraEnabled public String shippingAddress;
        @AuraEnabled public String street;
        @AuraEnabled public String city;
        @AuraEnabled public String state;
        @AuraEnabled public String country;
        @AuraEnabled public String zipcode;
    }
}