force-app/main/default/objects/Account/fields/Billing_Address_2__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address_2__c</fullName>
    <label>Billing Address 2</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Chain__c.field-meta.xml
<CustomField>
    <fullName>Chain__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chain Code Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Chain</value>
        </filterItems>
        <filterItems>
            <field>Account.Expired__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Chain)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Corporate_Address_2__c.field-meta.xml
<CustomField>
    <fullName>Corporate_Address_2__c</fullName>
    <label>Corporate Address 2</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CS_EPA_ID__c.field-meta.xml
<CustomField>
    <fullName>CS_EPA_ID__c</fullName>
    <inlineHelpText>The following fields are required in order to validate the EPA Id in addition to the EPA Id field. 
-Corporate Street 
-Corporate State 
-Corporate Country 
-Generator Status 
-Primary Service Provider</inlineHelpText>
    <label>EPA ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Generator_Status__c.field-meta.xml
<CustomField>
    <fullName>Generator_Status__c</fullName>
	<inlineHelpText>An account&apos;s generator status can only be upgraded from Salesforce. Downgrades in this area need to be coordinated by our compliance team. For status downgrades, please submit a Service Now ticket using category/subcategory: WIN-Aurora(FocalPoint), CWT-Compliance or WIN-Compliance, EPA ID Number.</inlineHelpText>
    <label>Generator Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Large Quantity Generator</fullName>
            </value>
            <value>
                <fullName>Small Quantity Generator</fullName>
            </value>
            <value>
                <fullName>Conditionally Exempt Sm Qty Generator</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
                <default>true</default>
                <label>Undetermined</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/GENREG__c.field-meta.xml
<CustomField>
    <fullName>GENREG__c</fullName>
    <label>GenReg Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Manifest_Address1__c.field-meta.xml
<CustomField>
    <fullName>Manifest_Address1__c</fullName>
    <label>Manifest Address1</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Manifest_Address2__c.field-meta.xml
<CustomField>
    <fullName>Manifest_Address2__c</fullName>
    <label>Manifest Address2</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Manifest_Address_Same_As_Corp__c.field-meta.xml
<CustomField>
    <fullName>Manifest_Address_Same_As_Corp__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To Copy Corp Address into Manifest Address</description>
    <label>Manifest Address Same As Corp</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Manifest_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Manifest_Country_Code__c</fullName>
    <label>Manifest Country</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Manifest_Locality1__c.field-meta.xml
<CustomField>
    <fullName>Manifest_Locality1__c</fullName>
    <label>Manifest City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Manifest_Post_Code__c.field-meta.xml
<CustomField>
    <fullName>Manifest_Post_Code__c</fullName>
    <label>Manifest Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Manifest_Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Manifest_Region_Code__c</fullName>
    <label>Manifest State</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Business__c.field-meta.xml
<CustomField>
    <fullName>Primary_Business__c</fullName>
    <description>Primary business based off account owner</description>
    <label>Primary Service Provider</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Primary_Service_Provider_New__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Daylighting Services</fullName>
            </value>
            <value>
                <fullName>Emerald Services</fullName>
            </value>
            <value>
                <fullName>Field Services</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Industrial Services</fullName>
            </value>
            <value>
                <fullName>Lodging</fullName>
            </value>
            <value>
                <fullName>Murphys Oil</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Technical Services</fullName>
            </value>
            <value>
                <fullName>Thermo Fluids</fullName>
            </value>
            <value>
                <fullName>H2O</fullName>
            </value>
            <value>
                <fullName>BPS</fullName>
            </value>
            <value>
                <fullName>CYN</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>SK KPP</fullName>
            </value>
            <value>
                <fullName>Surface Rentals</fullName>
            </value>
            <value>
                <fullName>Seismic</fullName>
            </value>
            <value>
                <fullName>Safety-Kleen</fullName>
                <label>SK ENV</label>
            </value>
            <value>
                <fullName>OER</fullName>
            </value>
            <value>
                <fullName>HPC Industrial</fullName>
            </value>
            <value>
                <fullName>PSC</fullName>
            </value>
            <value>
                <fullName>Synergy</fullName>
            </value>
            <value>
                <fullName>DFW</fullName>
            </value>
			<value>
                <fullName>Thompson</fullName>
            </value>
			<value>
                <fullName>Noble Oil</fullName>
            </value>
            <value>
                <fullName>HEPACO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Primary_Service_Provider__c</fullName>
    <description>Displays the old Primary Service providers</description>
    <label>Primary Service Provider Old</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Clean Harbors</fullName>
                <default>true</default>
                <label>Clean Harbors</label>
            </value>
            <value>
                <fullName>CYN</fullName>
            </value>
            <value>
                <fullName>Emerald Services</fullName>
            </value>
            <value>
                <fullName>RS Used Oil</fullName>
            </value>
            <value>
                <fullName>Safety Kleen</fullName>
            </value>
            <value>
                <fullName>SK BPS</fullName>
            </value>
            <value>
                <fullName>Thermo Fluids</fullName>
            </value>
			<value>
                <fullName>Thompson</fullName>
            </value> 
            <value>
                <fullName>HPC</fullName>
            </value>
            <value>
                <fullName>Noble Oil</fullName>
            </value>
            <value>
                <fullName>HEPACO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Service_Provider_New__c.field-meta.xml
<CustomField>
    <fullName>Primary_Service_Provider_New__c</fullName>
    <label>Operating Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SK ENV</fullName>
            </value>
            <value>
                <fullName>SK BPS</fullName>
            </value>
            <value>
                <fullName>SK KPP</fullName>
            </value>
            <value>
                <fullName>Clean Harbors ENV</fullName>
            </value>
            <value>
                <fullName>CHES Oil and Gas</fullName>
            </value>
            <value>
                <fullName>CHES Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Same_as_Corp_Address__c.field-meta.xml
<CustomField>
    <fullName>Same_as_Corp_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If True, Corporate Address will be copied to Billing Address</description>
    <label>Remit-to/Billing Address same as Corp</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/State_EPA_ID__c.field-meta.xml
<CustomField>
    <fullName>State_EPA_ID__c</fullName>
    <label>State EPA ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Exemption_Type__c.field-meta.xml
<CustomField>
    <fullName>Tax_Exemption_Type__c</fullName>
    <label>Tax Exemption</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tax Exempt</fullName>
            </value>
            <value>
                <fullName>Non Exempt</fullName>
                <default>true</default> 
                <label>Non Exempt</label>
            </value>
            <value>
                <fullName>Direct Pay Permit</fullName>
                <isActive>false</isActive>
                <label>Direct Pay Permit</label>
            </value>
            <value>
                <fullName>Resale</fullName>
                <isActive>false</isActive>
                <label>Resale</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ZIP_Master__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZIP Master</label>
    <referenceTo>ZIP_Master__c</referenceTo>
    <relationshipLabel>Accounts (ZIP Master)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Corporate.recordType-meta.xml
<RecordType>
    <fullName>Corporate</fullName>
    <active>true</active>
    <description>All Clean Harbor Corporate Accounts</description>
    <label>Corporate</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>All Clean Harbors Customers</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Case/fields/Zip_Master__c.field-meta.xml
<CustomField>
    <fullName>Zip_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ZIP Master</description>
    <label>Single Postal Code</label>
    <referenceTo>ZIP_Master__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Business__c.field-meta.xml
<CustomField>
    <fullName>Primary_Business__c</fullName>
    <formula>text( Account.Primary_Business__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Business</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Old_New_Primary_Service_Provider_Mapping__mdt/Old_New_Primary_Service_Provider_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Old New Primary Service Provider Mapping</label>
    <pluralLabel>Old New Primary Service Provider Mapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/Old_New_Primary_Service_Provider_Mapping__mdt/fields/Primary_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Primary_Service_Provider__c</fullName>
    <label>Primary Service Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Zip_Master__c.field-meta.xml
<CustomField>
    <fullName>Zip_Master__c</fullName>
    <description>Link to Accounts Zip Master</description>
    <formula>HYPERLINK(&quot;/&quot; &amp;  Account.ZIP_Master__c,  Account.ZIP_Master__r.ZIP__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zip Master</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Document__c/Tax_Document__c.object-meta.xml
<CustomObject>
    <label>Tax Document</label>
    <nameField>
        <displayFormat>TXD-{00000}</displayFormat>
        <label>Tax Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Document__c/fields/Tax_Exemption_Type__c.field-meta.xml
<CustomField>
    <fullName>Tax_Exemption_Type__c</fullName>
    <label>Tax Exemption Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Resale</fullName>
            </value>
            <value>
                <fullName>Direct Pay Permit</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GuidedAccountCreateSetup.cls
public without sharing class GuidedAccountCreateSetup {
    private static Map<Id, Profile> prfMap = new Map<Id, Profile>([SELECT id FROM Profile WHERE name IN ('Salesforce API Only System Integrations', 'Integration', 'Customer Service Light-EOC')]);
    private static Map<Id, Profile> prfMapMDM = new Map<Id, Profile>([SELECT id FROM Profile WHERE name IN ('Master Data Management')]);
    private final static string OPPORTUNITY_STAGE_PROSPECTING = '1 - Prospecting'; 

    @AuraEnabled 
    public static List<Account> getAccounts(String strAccountData) {
        AccountSetupWrappers.AccountWrapper  accWrapper =(AccountSetupWrappers.AccountWrapper ) System.JSON.deserialize(strAccountData, AccountSetupWrappers.AccountWrapper.class);
        AccountDuplicateSearch accountDupicateSearchObj = new AccountDuplicateSearch();
        Account[] duplicateMatchAccounts = accountDupicateSearchObj.classifyAndGetDuplicateAccounts(accWrapper);
        return duplicateMatchAccounts;
    } 
    @AuraEnabled 
    public static List<account> getDuplicateAccountsRecords(Id caseId) {
        Id childCaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Field Change Request').getRecordTypeId();
        AccountSetupWrappers.AccountWrapper  accWrapper = new AccountSetupWrappers.AccountWrapper();
        Case caseRec = [Select id,recordTypeId,Accountid,Account.Name,Account.ShippingAddress,Account.recordTypeId,Account.parentId,ParentId from Case where id =: caseId];
        if(caseRec.recordTypeId== childCaseRecordTypeId)
        {
            caseRec = [Select id,Accountid,Account.Name,Account.ShippingAddress,Account.recordTypeId,Account.parentId from Case where id =: caseRec.ParentId];
        }
        AccountSetupWrappers.CorporateAddressWrapper corpAddress = new AccountSetupWrappers.CorporateAddressWrapper(); 
        corpAddress.ShippingStreet = caseRec.Account.ShippingAddress.getStreet();
        corpAddress.ShippingCity = caseRec.Account.ShippingAddress.getCity();
        corpAddress.ShippingState = caseRec.Account.ShippingAddress.getState();
        corpAddress.ShippingPostalCode = caseRec.Account.ShippingAddress.getPostalCode();
        corpAddress.ShippingCountry = caseRec.Account.ShippingAddress.getCountry();
        accWrapper.CorporateAddress = corpAddress;
        accWrapper.accountName = caseRec.Account.Name;
        accWrapper.recordTypeId =caseRec.Account.recordTypeId;
        accWrapper.parentId =caseRec.Account.parentId;
        AccountDuplicateSearch accountDupicateSearchObj = new AccountDuplicateSearch();
        Map<Id, Account> duplicateAccountMap = new Map<Id, Account>(accountDupicateSearchObj.classifyAndGetDuplicateAccounts(accWrapper));
        duplicateAccountMap.remove(caseRec.AccountId);
        return duplicateAccountMap.Values();
    }
     
    @AuraEnabled
    public static AccountSetupWrappers.OperationResult checkAddressinZipMaster(String corpCountry,String corpState,String corpCity, String corpPostalCode,
                                                 String billCountry,String billState,String billCity, String billPostalCode, Boolean hasCustomerOrBrokerParentAccount) {
        Set<String> corporateZips = new Set<String>();
        Set<String> billingZips = new Set<String>();
        List<Zip_Master__c> corpZipList = new List<Zip_Master__c>();     
        List<Zip_Master__c> billingZipList = new List<Zip_Master__c>();
        AccountSetupWrappers.OperationResult operationRes = new AccountSetupWrappers.OperationResult(); 		
    
        if(corpPostalCode != null){
            if(corpCountry == 'US') {
                corporateZips.add(corpPostalCode.trim().left(5));
            } else if(corpCountry == 'CA'){
                corporateZips.add(corpPostalCode.trim());
            }
        }
         // Checks if Billing zip code is populated
        if(billPostalCode != null) {
            if(billCountry == 'US') { 
                billingZips.add(billPostalCode.trim().left(5)); 
            } else if(billCountry == 'CA'){   
                billingZips.add(billPostalCode.trim());                                                                                                                                                      
            }
        }
        corpZipList = ZipMasterDAO.getZipMastersByPostalCodeCountryState(corporateZips, corpCountry, corpState);
        billingZipList = ZipMasterDAO.getZipMastersByPostalCodeCountryState(billingZips, billCountry, billState);
		if(!hasCustomerOrBrokerParentAccount)  
        if(corpZipList.isEmpty()){
            operationRes.status = 'Error';
            operationRes.message = 'The Corporate State/Province and Country codes are not in the zip code entered. (Check state and country codes again please)';
        } 
        else if(!hasCustomerOrBrokerParentAccount && billingZipList.isEmpty() ){
            operationRes.status = 'Error';
            operationRes.message = 'The Billing State/Province and Country codes are not in the zip code entered. (Check state and country codes again please)';
        }
        else{
            operationRes.status = 'Success';
            operationRes.message = 'Address found';
        }        
        return operationRes;       
    }

    @AuraEnabled
    public static AccountSetupWrappers.OperationResult checkManiAddressinZipMaster(String maniCountry,String maniState,String maniCity, String maniPostalCode) {
        Set<String> maniZips = new Set<String>();
        List<Zip_Master__c> maniZipList = new List<Zip_Master__c>(); 
        if(maniPostalCode != null){
            if(maniCountry == 'US') {
                maniZips.add(maniPostalCode.trim().left(5));
            } else if(maniCountry == 'CA'){
                maniZips.add(maniPostalCode.trim());
            }
        } 
        maniZipList = ZipMasterDAO.getZipMastersByPostalCodeCountryState(maniZips, maniCountry, maniState);
        AccountSetupWrappers.OperationResult operationRes = new AccountSetupWrappers.OperationResult();
        if(maniZipList.isEmpty()){
            operationRes.status = 'Error';
            operationRes.message = 'The Manifest State/Province and Country codes are not in the zip code entered. (Check state and country codes again please)';
        }
        else{
            operationRes.status = 'Success';
            operationRes.message = 'MANI Address found';
        }
        return operationRes;
    } 
 
    @AuraEnabled
    public static AccountSetupWrappers.AccountResponseWrapper checkEPAIdIsValid(AccountSetupWrappers.AccountDataWrapper accountDataWrapperObj) {
        AccountSetupWrappers.AccountResponseWrapper accountResWrapper = new AccountSetupWrappers.AccountResponseWrapper();
        if (accountDataWrapperObj != null && accountDataWrapperObj.country!='CA'
            && !prfMap.containsKey(userinfo.getProfileId())  
            && !prfMapMDM.containsKey(userinfo.getProfileId())) {
                Account accountRec = new Account(
                    CS_EPA_ID__c=accountDataWrapperObj.epaId,
                    GENREG__c = accountDataWrapperObj.genRegId,
                    ShippingCountry = accountDataWrapperObj.country,
                    Generator_Status__c = accountDataWrapperObj.generatorStatus,
                    State_EPA_ID__c = accountDataWrapperObj.stateEpaId,
                    ShippingStreet = accountDataWrapperObj.shippingStreet,
                    ShippingState = accountDataWrapperObj.shippingState,
                    ShippingCity = accountDataWrapperObj.shippingCity,
                    RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(CHConstants.ACCOUNT_TYPE_CUSTOMER).getRecordTypeId(),
                    RecordType = new RecordType(DeveloperName=CHConstants.ACCOUNT_TYPE_CUSTOMER)
                );
                String tempPrimaryProvider;
                List<Old_New_Primary_Service_Provider_Mapping__mdt> primaryServiceProvMtdList = Old_New_Primary_Service_Provider_Mapping__mdt.getAll().values();
                for(Old_New_Primary_Service_Provider_Mapping__mdt primaryServiceProvObj : primaryServiceProvMtdList){
                    if(primaryServiceProvObj.Primary_Business__c == accountDataWrapperObj.primaryServiceProvider){
                        tempPrimaryProvider = primaryServiceProvObj.Primary_Service_Provider__c;
                        break;
                    } 
                }
                accountRec.Primary_Service_Provider__c = tempPrimaryProvider;
                accountResWrapper.response = AccountValidatorController.validateEPAId(accountRec);
            }
        else{
            accountResWrapper.isEPAValid = true;
        }
        
        return accountResWrapper;  
    }
  
    @AuraEnabled
    public static boolean deleteCustomDocument(String documentId) {
        try{
            ContentDocument contentDoc = [SELECT Id FROM ContentDocument WHERE Id = :documentId];
            delete contentDoc;
            return true;
        }
        Catch(exception e)
        {
            return false;
        }
    }
     
    @AuraEnabled
      public static Id createAccountAndRelatedInfoRecords(AccountSetupWrappers.AccountWrapper accWrapper) {
        List<Contact> contacts = new List<Contact>();
        Id customerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(CHConstants.ACCOUNT_RECORD_TYPE_CUSTOMER).getRecordTypeId();
        AccountSetupWrappers.BillingAddressWrapper BillingAddress = accWrapper.BillingAddress;
        AccountSetupWrappers.CorporateAddressWrapper CorporateAddress = accWrapper.CorporateAddress;
        Account acc = new Account();
        acc.Name = accWrapper.accountName;
        acc.RecordTypeId = accWrapper.recordTypeId;
        acc.ShippingStreet = CorporateAddress.ShippingStreet;
        acc.ShippingCity = CorporateAddress.ShippingCity;
        acc.ShippingState = CorporateAddress.ShippingState;
        acc.ShippingPostalCode = CorporateAddress.ShippingPostalCode;
        acc.ShippingCountry = CorporateAddress.ShippingCountry;
        acc.Corporate_Address_2__c = CorporateAddress.CorporateAddress2;
        acc.BillingStreet = BillingAddress.BillingStreet; 
        acc.BillingCity = BillingAddress.BillingCity; 
        acc.BillingState = BillingAddress.BillingState;
        acc.BillingPostalCode = BillingAddress.BillingPostalCode;
        acc.BillingCountry = BillingAddress.BillingCountry;
        acc.Billing_Address_2__c = BillingAddress.BillingAddress2;
        acc.Primary_Service_Provider_New__c = accWrapper.primaryServiceProviderNew;
        acc.Same_as_Corp_Address__c = accWrapper.sameAsCorpAddress == true;
        acc.Primary_Business__c = accWrapper.primaryBusiness;
        acc.ParentId = String.isNotBlank(accWrapper.parentId) ? accWrapper.parentId : NULL;
		acc.Chain__c = String.isNotBlank(accWrapper.chainId) ? accWrapper.chainId : NULL;
        acc.CS_EPA_ID__c = accWrapper.epaId;
		acc.CurrencyIsoCode=accWrapper.currencyCode;
        acc.Generator_Status__c = accWrapper.generatorStatus;
        acc.State_EPA_ID__c = accWrapper.stateEpaId;
        acc.GENREG__c = accWrapper.genRegId;
        acc.Manifest_Address_Same_As_Corp__c = accWrapper.manifestAddressSameAsCorp != NULL ? accWrapper.manifestAddressSameAsCorp : false ;
        acc.Manifest_Address1__c = accWrapper.manifestAddress1;
        acc.Manifest_Locality1__c = accWrapper.manifestLocality1;
        acc.Manifest_Region_Code__c = accWrapper.manifestRegionCode;
        acc.Manifest_Post_Code__c = accWrapper.manifestPostalCode;
        acc.Manifest_Country_Code__c = accWrapper.manifestCountryCode;
        acc.Manifest_Address2__c = accWrapper.manifestAddress2;
        acc.SicDesc = accWrapper.sicDesc;
		acc.Sic_Code_Description__c = accWrapper.sicCodeDescription;
        acc.Tax_Exemption_Type__c = accWrapper.taxExemptionType;
        acc.AccountSource = accWrapper.accountSource;
        acc.Industry_Segment__c = accWrapper.industrySegment;
        acc.Class__c = accWrapper.accountClass;
        acc.Duplicate_Reason__c=accWrapper.duplicateReason;
        acc.Duplicate_Justification__c=accWrapper.duplicateJustification;
        acc.Phone= accWrapper.accountPhone;
        acc.Rank__c = accWrapper.rank;
        acc.SKO_Sales_Segment__c = accWrapper.skoSalesSegment;
        acc.Is_Created_Through_New_Account_Setup__c = true;
        acc.Broker_Group__c = accWrapper.brokergroup;

        try{
            Database.DMLOptions dml = new Database.DMLOptions(); 
			dml.DuplicateRuleHeader.AllowSave = true;
            Database.SaveResult sr = Database.insert(acc, dml);
            if(!sr.isSuccess())
            {
                String errorMessage = '';
                for(Database.Error err : sr.getErrors()) {
                    errorMessage += err.getMessage();                    
                }
                throw new AuraHandledException(errorMessage);
            }
            if(accWrapper.documentId != null && accWrapper.documentId !='')
            {
                List<Tax_Document__c> taxDocs =[Select Id from Tax_Document__c where Account__c =:acc.Id];
                if(taxDocs!=null && !taxDocs.IsEmpty())
                {
                    ContentDocumentLink cdl= new ContentDocumentLink();
                    cdl.ContentDocumentId = accWrapper.documentId;
                    cdl.LinkedEntityId = taxDocs[0].id;
                    insert cdl;
                }
            }
            if(accWrapper.contacts!= null){
                Contact con;
                for(AccountSetupWrappers.ContactsWrapper conRec : accWrapper.contacts){
                    if( conRec.contactType != null){
                        con = new Contact();
                        con.Salutation = conRec.salutation;
                        con.LastName = conRec.lastName;
                        con.FirstName = conRec.firstName;
                        con.Phone = conRec.phone;  
                        con.Title = conRec.title;                  
                        con.Email = conRec.email;
                        con.RLT_Contact__c = conRec.rltContact;
                        con.AccountId = acc.Id;
                        con.MobilePhone = conRec.mobile;
                        con.Phone_Extension__c = conRec.phoneExtension; 
                        List<String> contactTypeValues = conRec.contactType;
                        con.Contact_Type__c = String.join(contactTypeValues, ';');
                        contacts.add(con);
                    }
                }
                 try{
                        insert contacts;
                    }catch (Exception exe){
                        throw new AuraHandledException('Error while creating Contact:' + exe.getMessage());
                    }
                }
                if(accWrapper.autoCreateOpportunity == true){
                    Opportunity opp = new Opportunity();
                    opp.Name = accWrapper.accountName;
                    opp.AccountId = acc.Id;
                    if(!String.isBlank(accWrapper.opportunityRecordTypeId)){
                        opp.RecordTypeId = accWrapper.opportunityRecordTypeId;
                    }
                    opp.StageName = OPPORTUNITY_STAGE_PROSPECTING;
                    opp.CloseDate = Date.today().addMonths(3);
                    opp.Job_Start_Date__c = Date.today().addMonths(3);
                    try{
                        insert opp;
                    }catch (Exception exe){
                        throw new AuraHandledException('Error while creating Opportunity:' + exe.getMessage());
                    }
                }
                return acc.Id;
            } catch (Exception e){
            throw new AuraHandledException('Error while creating account:' + e.getMessage());
        }
    }
}