force-app/main/default/objects/Account/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Key_Account_Support_Person__c.field-meta.xml
<CustomField>
    <fullName>Key_Account_Support_Person__c</fullName>
    <formula>IF(AND(RecordType.Name = &apos;Customer&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Chain&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Distributor&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Broker&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Customer Chain&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Customer Location&apos;, Parent.Parent.RecordType.Name = &apos;Key Account&apos;), Parent.Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Broker Location&apos;, Parent.Parent.RecordType.Name = &apos;Key Account&apos;), Parent.Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Distributor Location&apos;, Parent.Parent.RecordType.Name = &apos;Key Account&apos;), Parent.Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName ,
IF(RecordType.Name = &apos;Customer Location&apos;,  Parent.Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName , 
IF(RecordType.Name = &apos;Distributor Location&apos;,  Parent.Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName, 
IF(RecordType.Name = &apos;Broker Location&apos;,  Parent.Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName , 
IF(RecordType.Name = &apos;Customer&apos;,  Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(RecordType.Name = &apos;Key Account&apos;,  Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(RecordType.Name = &apos;Customer Chain&apos;,  Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(RecordType.Name = &apos;Distributor&apos;,  Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(RecordType.Name = &apos;Broker&apos;,  Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(RecordType.Name = &apos;Chain&apos;,  Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,&apos;&apos;)))))))))))))))))</formula>
    <label>Corp/Key Account Support Person</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Key_Buying_Decision__c.field-meta.xml
<CustomField>
    <fullName>Key_Buying_Decision__c</fullName>
    <formula>IF(AND(RecordType.Name = &apos;Customer&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), text(Parent.Buying_Decision__c),
IF(AND(RecordType.Name = &apos;Distibutor&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), text(Parent.Buying_Decision__c),
IF(AND(RecordType.Name = &apos;Broker&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), text(Parent.Buying_Decision__c),
IF(AND(RecordType.Name = &apos;Customer Chain&apos;, Parent.RecordType.Name = &apos;Key Account&apos;),  text(Parent.Buying_Decision__c),
IF(AND(RecordType.Name = &apos;Chain&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), text(Parent.Buying_Decision__c),
IF(AND(RecordType.Name = &apos;Customer Location&apos;, Parent.Parent.RecordType.Name = &apos;Key Account&apos;), text(Parent.Parent.Buying_Decision__c),
IF(AND(RecordType.Name = &apos;Distributor Location&apos;, Parent.Parent.RecordType.Name = &apos;Key Account&apos;), text(Parent.Parent.Buying_Decision__c),
IF(AND(RecordType.Name = &apos;Broker Location&apos;, Parent.Parent.RecordType.Name = &apos;Key Account&apos;), text(Parent.Parent.Buying_Decision__c),
IF(RecordType.Name = &apos;Customer Location&apos;, IF(ISBLANK(text(Parent.Parent.Buying_Decision__c)), text(Chain__r.Buying_Decision__c), text(Parent.Parent.Buying_Decision__c)),
IF(RecordType.Name = &apos;Broker Location&apos;, text(Parent.Parent.Buying_Decision__c),
IF(RecordType.Name = &apos;Distributor Location&apos;, text(Parent.Parent.Buying_Decision__c),
IF(RecordType.Name = &apos;Pricing Chain&apos;, text(Parent.Buying_Decision__c),
IF(RecordType.Name = &apos;Distributor&apos;, text(Parent.Buying_Decision__c),
IF(RecordType.Name = &apos;Broker&apos;, text(Parent.Buying_Decision__c),
IF(RecordType.Name = &apos;Customer&apos;, IF(ISBLANK(text(Parent.Buying_Decision__c)), text(Chain__r.Buying_Decision__c), text(Parent.Buying_Decision__c)),
IF(RecordType.Name = &apos;Chain&apos;, text(Buying_Decision__c),
IF(RecordType.Name = &apos;Customer Chain&apos;, text(Parent.Buying_Decision__c), text(Buying_Decision__c) )))))))))))))))))</formula>
    <label>Corp/Key Account Buying Decision</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Primary_Service_Provider__c</fullName>
    <description>Displays the old Primary Service providers</description>
    <label>Primary Service Provider Old</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Clean Harbors</fullName>
                <default>true</default>
                <label>Clean Harbors</label>
            </value>
            <value>
                <fullName>CYN</fullName>
            </value>
            <value>
                <fullName>Emerald Services</fullName>
            </value>
            <value>
                <fullName>RS Used Oil</fullName>
            </value>
            <value>
                <fullName>Safety Kleen</fullName>
            </value>
            <value>
                <fullName>SK BPS</fullName>
            </value>
            <value>
                <fullName>Thermo Fluids</fullName>
            </value>
			<value>
                <fullName>Thompson</fullName>
            </value> 
            <value>
                <fullName>HPC</fullName>
            </value>
            <value>
                <fullName>Noble Oil</fullName>
            </value>
            <value>
                <fullName>HEPACO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Service_Provider_New__c.field-meta.xml
<CustomField>
    <fullName>Primary_Service_Provider_New__c</fullName>
    <label>Operating Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SK ENV</fullName>
            </value>
            <value>
                <fullName>SK BPS</fullName>
            </value>
            <value>
                <fullName>SK KPP</fullName>
            </value>
            <value>
                <fullName>Clean Harbors ENV</fullName>
            </value>
            <value>
                <fullName>CHES Oil and Gas</fullName>
            </value>
            <value>
                <fullName>CHES Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/WIN_ID__c.field-meta.xml
<CustomField>
    <fullName>WIN_ID__c</fullName>
    <externalId>true</externalId>
    <label>WIN ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Branch_Queue_Map__c/Branch_Queue_Map__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used for Branch Queue Mapping</description>
    <label>Branch Queue Map</label>
</CustomObject>

force-app/main/default/objects/Branch_Queue_Map__c/fields/Branch_Queue__c.field-meta.xml
<CustomField>
    <fullName>Branch_Queue__c</fullName>
    <description>Queue name of a Branch</description>
    <label>Branch Queue</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Branch_Account_NSB__c.field-meta.xml
<CustomField>
    <fullName>Branch_Account_NSB__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Branch Account of the Case</description>
    <label>Branch Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Branch</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Branch Account)</relationshipLabel>
    <relationshipName>Cases7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Conver_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Conver_DateTime__c</fullName>
    <label>Conver DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Generator_Code__c.field-meta.xml
<CustomField>
    <fullName>Generator_Code__c</fullName>
    <label>Generator Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <description>Invoice Date</description>
    <label>Invoice Date</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Numbers</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Invoice_Value__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Value__c</fullName>
    <label>Invoice Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/OPRID__c.field-meta.xml
<CustomField>
    <fullName>OPRID__c</fullName>
    <label>Added By</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <description>This fields is the second step in the case routing logic that will be evaluated after &quot;purchase order timing&quot;.</description>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aurora</fullName>
            </value>
            <value>
                <fullName>Win</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PO_Timing__c.field-meta.xml
<CustomField>
    <fullName>PO_Timing__c</fullName>
    <description>This fields is used for the case routing process.</description>
    <label>PO Timing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>After Service</fullName>
            </value>
            <value>
                <fullName>Before Service</fullName>
            </value>
            <value>
                <fullName>At Time of Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sales_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Number__c</fullName>
    <description>WIN Sales Order Number</description>
    <label>Sales Order Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Servicing_Branch__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Branch__c</fullName>
    <description>This field is used to enter the Branch which is limited to length 4.</description>
    <label>Servicing Branch</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/WIN_Id__c.field-meta.xml
<CustomField>
    <fullName>WIN_Id__c</fullName>
    <label>WIN Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/Exception_Log__c.object-meta.xml
<CustomObject>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>EL-{00000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception_Log__c/fields/Apex_Method_Event__c.field-meta.xml
<CustomField>
    <fullName>Apex_Method_Event__c</fullName>
    <label>Apex Method/Event</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RestCreateCase.cls
/**
 * @description       : 
 * @author            : Balaji Bezawada
 * @group             : 
 * @last modified on  : 03-06-2023
 * @last modified by  : Balaji Bezawada
**/
@RestResource(urlMapping = '/CreateCase/*') 
global class RestCreateCase {
    @HttpPost
global static void createnewcase(){   
 List<String> PSPCHES= new List<String>{'Clean Harbors ENV', 'CHES Oil and Gas', 'CHES Industrial'};
 List<String> PSPSKE= new List<String>{'SK ENV', 'SK BPS', 'SK KPP'};
 List<String> CASETYPES= new List<String>{'NOPO', 'WRONGPO', 'PO-UNDRFND'};
        RestRequest request = RestContext.request;
        String reqBody = request.requestbody != NULL ? request.requestbody.tostring() : '';
        RquestWrapper reqWrapper = (RquestWrapper)JSON.deserialize(request.requestbody.tostring(), RquestWrapper.class);
        
        try{
		    String servicingbranchQueue;
			String servicingbranchQueueMapname;
            String branchQueueName;
			Group poCaseQueue = new Group();    
            String accSuppPerson;
            List<Group> branchQueue = new List<Group>();
            case newcase = new case ();
            List<Account> branchAccount = new List<Account>();
            List<Account> invoiceAccount = new List<Account>();
            
            newcase.status = CHConstants.CASE_STATUS_NEW;
            newcase.WIN_Id__c = reqWrapper.CUST_ID;
            newcase.Generator_Code__c = reqWrapper.GENERATOR_CODE;
            newcase.DESCRIPTION = reqWrapper.DESCRIPTION;
            newCase.Conver_DateTime__c = System.now(); //This has been added to include the Case Creation time - Sireesha
            
            //Changes to include the Added by Name based on the OPR ID
            if(reqWrapper.USER_ID != NULL){
                for(User usrObj : [Select Id, Name from User where FederationIdentifier =: reqWrapper.USER_ID LIMIT 1]){
                    newCase.OPRID__c = usrObj.Name;
                } 
            }
            
            List<Account> accs = new List<Account>();
            accs = [Select Id, Name, OwnerId, Owner.ManagerId, Owner.Name, Owner.Manager.Name,Primary_Service_Provider__c,Primary_Service_Provider_New__c, Key_Buying_Decision__c,Key_Account_Support_Person__c,Owner.IsActive, Owner.Manager.IsActive from Account where WIN_ID__c =:reqWrapper.CUST_ID LIMIT 1];
             if(!accs.isEmpty()){
                    newCase.AccountId = accs[0].Id;
                    
                } 
            
            
            if(reqWrapper.SOURCE_APP == CHConstants.INTEGRATION_SOURCE_APP_NSB || reqWrapper.SOURCE_APP == CHConstants.INTEGRATION_SOURCE_APP_COWB){
                      
                newcase.Invoice_Number__c = reqWrapper.INVOICE_NUM;
                newcase.Invoice_Date__c = reqWrapper.INVOICE_DATE; 
                newcase.Invoice_Value__c = Decimal.ValueOf(reqWrapper.INVOICE_VAL);
                newcase.Sales_Order_Number__c = reqWrapper.SALESORDER_NUM;            
                newcase.Type= reqWrapper.CASE_TYPE;
				newcase.Order_Type__c=reqWrapper.ORDER_TYPE;
                newcase.PO_Timing__c=reqWrapper.PO_TIMING;
                newcase.Servicing_Branch__c=reqWrapper.SERVICING_BRANCH;
                newcase.Subject=reqWrapper.Subject;
                
                if(String.isNotBlank(reqWrapper.BRANCH_CODE)){
                    branchAccount = [Select Id, Name from Account where RecordType.Name =:CHConstants.ACCOUNT_RECORD_TYPE_NAME_BRANCH AND Branch_Code__c =:reqWrapper.BRANCH_CODE LIMIT 1];
                }
                
                if(!branchAccount.isEmpty()){
                    newcase.Branch_Account_NSB__c = branchAccount[0].Id;
                }
                 if(String.isNotBlank(reqWrapper.BRANCH_CODE) || String.isNotBlank(reqWrapper.SERVICING_BRANCH)){
                    if(Branch_Queue_Map__c.getValues(reqWrapper.BRANCH_CODE) != NULL || Branch_Queue_Map__c.getValues(reqWrapper.SERVICING_BRANCH) != NULL){
                        Branch_Queue_Map__c branchQueueMap = Branch_Queue_Map__c.getValues(reqWrapper.BRANCH_CODE);
                        Branch_Queue_Map__c servicingbranchQueueMap = Branch_Queue_Map__c.getValues(reqWrapper.SERVICING_BRANCH);
                        if(branchQueueMap !=null){
                            branchQueueName = branchQueueMap.Branch_Queue__c;
                        } 
                        
                        if(servicingbranchQueueMap != NULL){
                            servicingbranchQueueMapname= servicingbranchQueueMap.Branch_Queue__c;
                        }
                    }
                }
                
                 if(String.isNotBlank(branchQueueName) || String.isNotBlank(servicingbranchQueueMapname)){
                    for(Group groupRec :  [SELECT Id, Name FROM Group WHERE Type = 'Queue' AND (Name = :branchQueueName OR Name = :servicingbranchQueueMapname)]){
                        if(branchQueueName == groupRec.Name){
                            branchQueue = new List<Group>{groupRec};
                        }
                        
                        if(servicingbranchQueueMapname == groupRec.Name){
                            servicingbranchQueue = groupRec.Id;
                        }
                    }
                }
                
                for(Group grpObj : [Select Id, Name from Group where type = 'Queue' AND (Name =: CHConstants.QUEUE_NAME_PO_CASE_QUEUE)]){
                    if(grpObj.Name == CHConstants.QUEUE_NAME_PO_CASE_QUEUE){
                        poCaseQueue = grpObj;
                    }
                }
               if(reqWrapper.PO_TIMING == CHConstants.PO_TIMING)
                {
                    if(reqWrapper.SOURCE_APP == CHConstants.INTEGRATION_SOURCE_APP_NSB){
                     newcase.RecordTypeId =  Schema.SObjectType.Case.getRecordTypeInfosByName().get(CHConstants.CASE_RECORD_TYPE_NAME_NSB_WIN).getRecordTypeId();
                    }else
                    if(reqWrapper.SOURCE_APP == CHConstants.INTEGRATION_SOURCE_APP_COWB){
                     newcase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get(CHConstants.CASE_RECORD_TYPE_NAME_COWB).getRecordTypeId();
                    }
                    if(String.isNotBlank(reqWrapper.SERVICING_BRANCH) && String.isNotBlank(servicingbranchQueue)){
                        if(PSPSKE.contains(accs[0].Primary_Service_Provider_New__c)
                          && !accs[0].Primary_Service_Provider_New__c.equals('SK KPP')) { 
                            newCase.OwnerId = servicingbranchQueue;
                        }
                        else 
                            newCase.OwnerId=poCaseQueue.id;
                    } else 
                        newCase.OwnerId=poCaseQueue.id; 
                }   
                else
                if(reqWrapper.SOURCE_APP == CHConstants.INTEGRATION_SOURCE_APP_NSB){
                    newcase.RecordTypeId =  Schema.SObjectType.Case.getRecordTypeInfosByName().get(CHConstants.CASE_RECORD_TYPE_NAME_NSB_WIN).getRecordTypeId();
                    if(reqWrapper.CASE_TYPE == CHConstants.CASE_TYPE_SERVICE || CASETYPES.contains(reqWrapper.CASE_TYPE)){
                        if(accs[0].Key_Buying_Decision__c == 'Central Buying'  && accs[0].Key_Account_Support_Person__c != NULL){
                            accSuppPerson = accs[0].Key_Account_Support_Person__c;
                        }else  if(PSPCHES.contains(accs[0].Primary_Service_Provider_New__c)){
                            if(accs[0].Owner.IsActive){
                                newCase.OwnerId = accs[0].OwnerId;    
                            }else{
							    newCase.OwnerId = accs[0].Owner.ManagerId;    
                            }
                        }else if(PSPSKE.contains(accs[0].Primary_Service_Provider_New__c)){
                            List<Account> accountRecLst = [SELECT Id, OwnerId, Owner.ManagerId, Owner.IsActive FROM Account WHERE WIN_ID__c = :reqWrapper.GENERATOR_CODE];
                            if(!accountRecLst.isEmpty()){
                                if(accountRecLst[0].Owner.IsActive){
                                    newCase.OwnerId = accountRecLst[0].OwnerId;    
                                }else{ newCase.OwnerId = accountRecLst[0].Owner.ManagerId;    
                                }
                            }else{RestContext.response.responseBody = Blob.valueOf('{"case_id":"","Error":"No account record for the generator code.","Case_No":""}');
							     RestCreateCase.createExceptionLog('No account record for the generator code.'+ '|' + reqBody, '','');
                                return;
                            }
                        }
                        
                         if(accSuppPerson != null){
                            User us = [Select Id, Name, isActive, ManagerId, Manager.isActive, Manager.Name FROM USER WHERE Name =: accSuppPerson LIMIT 1]; //Update the query to pull Manager Related information - Sireesha
                        	
                            //Assign the user as owner only if the User is active - Sireesha
                            if(us.isActive && !us.Name.Contains('Inactive')){
                                newCase.OwnerId = us.Id;
                            }//Otherwise assign to the Manager if he is active - Sireesha
                            else if(us.ManagerId != NULL && us.Manager.isActive && !us.Manager.Name.Contains('Inactive')){
                                newCase.OwnerId = us.ManagerId;
                            }
                        }
                    }  
                } 
                else if(reqWrapper.SOURCE_APP == CHConstants.INTEGRATION_SOURCE_APP_COWB){
                    newcase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get(CHConstants.CASE_RECORD_TYPE_NAME_COWB).getRecordTypeId();
                     if( reqWrapper.CASE_TYPE == CHConstants.CASE_TYPE_SERVICE){
					if(!branchQueue.isEmpty()){ 
                            newCase.OwnerId = branchQueue[0].Id;
                        } else
                        if(accs[0].Owner.IsActive){
                                newCase.OwnerId = accs[0].OwnerId;    
                            }else{
							    newCase.OwnerId = accs[0].Owner.ManagerId;    
                            }
					}
                    if(CASETYPES.contains(reqWrapper.CASE_TYPE)){
                        if(accs[0].Key_Buying_Decision__c == 'Central Buying'  && accs[0].Key_Account_Support_Person__c != NULL){
                            accSuppPerson = accs[0].Key_Account_Support_Person__c; 
                        }else if(PSPCHES.contains(accs[0].Primary_Service_Provider_New__c)){ 
                            if(accs[0].Owner.IsActive){
                                newCase.OwnerId = accs[0].OwnerId;    
                            }else{
                                newCase.OwnerId = accs[0].Owner.ManagerId;    
                            }
                        }else if(PSPSKE.contains(accs[0].Primary_Service_Provider_New__c)){
                            List<Account> accountRecLst = [SELECT Id, OwnerId, Owner.ManagerId, Owner.IsActive FROM Account WHERE WIN_ID__c = :reqWrapper.GENERATOR_CODE];
                            if(!accountRecLst.isEmpty()){
                                if(accountRecLst[0].Owner.IsActive){ 
                                    newCase.OwnerId = accountRecLst[0].OwnerId;    
                                }else{
                                    newCase.OwnerId = accountRecLst[0].Owner.ManagerId;    
                                }
                            }else{
                                RestContext.response.responseBody = Blob.valueOf('{"case_id":"","Error":"No account record for the generator code.","Case_No":""}');
								RestCreateCase.createExceptionLog('No account record for the generator code.'+ '|' + reqBody, '','');
                                return;
                            }
                         } 
                    }
                    
                    if(accSuppPerson != null){
                        User us = [Select Id, Name, isActive, ManagerId, Manager.isActive, Manager.Name FROM USER WHERE Name =: accSuppPerson LIMIT 1]; //Update the query to pull Manager Related information - Sireesha
                    	//Assign the user as owner only if the User is active - Sireesha
                        if(us.isActive && !us.Name.Contains('Inactive')){
                            newCase.OwnerId = us.Id;
                        }//Otherwise assign to the Manager if he is active - Sireesha
                        else if(us.ManagerId != NULL && us.Manager.isActive && !us.Manager.Name.Contains('Inactive')){
                            newCase.OwnerId = us.ManagerId;
                        }
                    }
                }
                insert newcase;
                
            }
             /*This is to handle Invoice Delovery Record Type Cases
             */
            else if(reqWrapper.SOURCE_APP == CHConstants.INTEGRATION_SOURCE_APP_INV_DEL){
                
                newcase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get(CHConstants.CASE_RECORD_TYPE_NAME_INV_DEL).getRecordTypeId();
                
               
                
                newcase.Description= CHConstants.INVOICE_DELIVERY_CASE_DESCRIPTION;
                newcase.Type= reqWrapper.CASE_TYPE;
                if(!accs.isEmpty()){
                   
                    newCase.OwnerId = accs[0].OwnerId;
                }
                insert newCase;
            }
            
            Case caseObj = [select Id,CaseNumber from case where Id=: newcase.Id LIMIT 1];

            RestContext.response.responseBody = Blob.valueOf('{"case_id" :"' +newcase.Id+'","Error":"","Case_No":"'+caseObj.CaseNumber+'"}');
        } catch (Exception e){
            system.debug('---'+e.getLineNumber());
            RestContext.response.responseBody = Blob.valueOf('{"case_id":"","Error":"'+ e.getMessage()+'","Case_No":""}');
			RestCreateCase.createExceptionLog(e.getMessage()+ '|' +reqBody,e.getStackTraceString(), '');
        }
        
    }
    
    public class RquestWrapper{
        
        public String SOURCE_APP;
        public String CUST_ID;
        public String DESCRIPTION;
        public string USER_ID;
        
        //Parameters related to NSB and Closed Order WorkBench
        public String INVOICE_DATE;
        public String INVOICE_NUM;
        public String SALESORDER_NUM;
        public String INVOICE_VAL;
        public String BRANCH_CODE;
        public String CASE_TYPE;
        public String GENERATOR_CODE;
		Public String PO_TIMING;
        public String ORDER_TYPE;
        public String SERVICING_BRANCH;
        Public String Subject;		
        
        //Parameters related to Test
        public String BUSINESS_UNIT;
        public String FOLLOW_UP_ACTION;
        public String Keyword1;
        public String Keyword2;
        public String Keyword3;
        public String SETID;
        public String CUST_BALANCE;        
              
        
    }
    private static void createExceptionLog(string errorMessage, string stackTrace, string recordId){
        Exception_Log__c log = new Exception_Log__c(
            Error_Message__c= errorMessage, 
            Exception_Stack_Trace__c= stackTrace, 
            Record_Id__c= recordId, 
            Apex_Method_Event__c= 'createnewcase'
        );
        ExceptionLogDAO.logException(new List<Exception_Log__c>{log});
    }
}