force-app/main/default/objects/Account/fields/Branch_Call_Origin_Flag__c.field-meta.xml
<CustomField>
    <fullName>Branch_Call_Origin_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag for branches to be used in the call origin in case mgmt</description>
    <label>Branch Call Origin Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Branch_Opportunity_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Branch_Opportunity_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this field is selected then this branch can be used on an opportunity</description>
    <label>Branch Opportunity Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <formula>ShippingCity</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CS_EPA_ID__c.field-meta.xml
<CustomField>
    <fullName>CS_EPA_ID__c</fullName>
    <inlineHelpText>The following fields are required in order to validate the EPA Id in addition to the EPA Id field. 
-Corporate Street 
-Corporate State 
-Corporate Country 
-Generator Status 
-Primary Service Provider</inlineHelpText>
    <label>EPA ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/dunbrdst__c.field-meta.xml
<CustomField>
    <fullName>dunbrdst__c</fullName>
    <description>dunbrdst from Beacon for Key Accounts</description>
    <externalId>true</externalId>
    <label>dunbrdst</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Generator_Status__c.field-meta.xml
<CustomField>
    <fullName>Generator_Status__c</fullName>
	<inlineHelpText>An account&apos;s generator status can only be upgraded from Salesforce. Downgrades in this area need to be coordinated by our compliance team. For status downgrades, please submit a Service Now ticket using category/subcategory: WIN-Aurora(FocalPoint), CWT-Compliance or WIN-Compliance, EPA ID Number.</inlineHelpText>
    <label>Generator Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Large Quantity Generator</fullName>
            </value>
            <value>
                <fullName>Small Quantity Generator</fullName>
            </value>
            <value>
                <fullName>Conditionally Exempt Sm Qty Generator</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
                <default>true</default>
                <label>Undetermined</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Segment__c.field-meta.xml
<CustomField>
    <fullName>Industry_Segment__c</fullName>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Base &amp; Blended Oils</fullName>
            </value>
            <value>
                <fullName>Brokers</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Ecommerce</fullName>
            </value>
            <value>
                <fullName>Education Services</fullName>
            </value>
            <value>
                <fullName>Engineering &amp; Consulting</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Insurance &amp; Real Estate</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Mining</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Paper &amp; Wood</fullName>
            </value>
            <value>
                <fullName>Pharmaceutical &amp; Biotechnology</fullName>
            </value>
            <value>
                <fullName>Refineries &amp; Oilsands</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Terminals &amp; Pipelines</fullName>
            </value>
            <value>
                <fullName>Transportation Services</fullName>
            </value>
            <value>
                <fullName>Utilities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <type>Picklist</type>
    <valueSet>
	    <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CH A Large &gt;200K</fullName>
            </value>
            <value>
                <fullName>CH C Assigned &gt;30K</fullName>
            </value>
            <value>
                <fullName>D &lt;30,000</fullName>
            </value>
            <value>
                <fullName>CH E Small &lt;30K</fullName>
            </value>
            <value>
                <fullName>CH B Medium &gt;100K</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Sales_Business_Unit__c</fullName>
    <description>Sales business unit (temporary field - do not use)</description>
    <label>Sales Business Unit</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ZIP_Master__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZIP Master</label>
    <referenceTo>ZIP_Master__c</referenceTo>
    <relationshipLabel>Accounts (ZIP Master)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Branch.recordType-meta.xml
<RecordType>
    <fullName>Branch</fullName>
    <active>true</active>
    <description>All Clean Harbors Branches</description>
    <label>Branch</label> 
</RecordType>

force-app/main/default/objects/Account/recordTypes/Corporate.recordType-meta.xml
<RecordType>
    <fullName>Corporate</fullName>
    <active>true</active>
    <description>All Clean Harbor Corporate Accounts</description>
    <label>Corporate</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>All Clean Harbors Customers</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Location/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SIC_VALIDATION_SETTING__c/SIC_VALIDATION_SETTING__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS will consist of a flag which determines if SIC Validation on Account should be implemented or not.</description>
    <label>SIC VALIDATION SETTING</label>
</CustomObject>

force-app/main/default/objects/SIC_VALIDATION_SETTING__c/fields/SIC_VALIDATION_FLAG__c.field-meta.xml
<CustomField>
    <fullName>SIC_VALIDATION_FLAG__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag which determines if SIC Validation should be executed in the custom code or not. Should be Checked if SIC Validation is required.</description>
    <label>SIC_VALIDATION_FLAG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TERRITORY_MANAGEMENT__c/TERRITORY_MANAGEMENT__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS will consist of a flag which determines if Territory Management on Account should be implemented or not. If Yes, the Territory and Owner on Account are set based on the criteria.</description>
    <label>TERRITORY MANAGEMENT</label>
</CustomObject>

force-app/main/default/objects/TERRITORY_MANAGEMENT__c/fields/TM_FLAG__c.field-meta.xml
<CustomField>
    <fullName>TM_FLAG__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag which determines if TM should be executed in the custom code or not thus setting the Territory and the Account Owner field on the Account record. Should be Checked if TM is required.</description>
    <inlineHelpText>Flag which determines if TM should be executed in the custom code or not</inlineHelpText>
    <label>TM_FLAG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Territory_Master__c/Territory_Master__c.object-meta.xml
<CustomObject>
    <description>Contains all Territory Information viz., SBU, Territory Name, Territory Owner, etc. based on the ZIP Codes.</description>
    <label>Territory Master</label>
    <nameField>
        <label>Territory Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Master</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Master__c/fields/Sales_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Sales_Business_Unit__c</fullName>
    <label>Primary Service Provider</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BPS</fullName>
            </value>
            <value>
                <fullName>CYN</fullName>
            </value>
            <value>
                <fullName>Daylighting Services</fullName>
            </value>
            <value>
                <fullName>DFW</fullName>
            </value>
            <value>
                <fullName>Emerald Services</fullName>
            </value>
            <value>
                <fullName>Field Services</fullName>
            </value>
            <value>
                <fullName>H2O</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Industrial Services</fullName>
            </value>
            <value>
                <fullName>Lodging</fullName>
            </value>
            <value>
                <fullName>Murphys Oil</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Seismic</fullName>
            </value>
            <value>
                <fullName>Safety-Kleen</fullName>
                <label>SK ENV</label>
            </value>
            <value>
                <fullName>SK KPP</fullName>
            </value>
            <value>
                <fullName>Surface Rentals</fullName>
            </value>
            <value>
                <fullName>Synergy</fullName>
            </value>
            <value>
                <fullName>Technical Services</fullName>
            </value>
            <value>
                <fullName>Thermo Fluids</fullName>
            </value>
			<value>
                <fullName>Thompson</fullName>
            </value>
			<value>
                <fullName>Noble Oil</fullName>
            </value>
            <value>
                <fullName>HEPACO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory_Master__c/fields/ZIP_Master__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Master__c</fullName>
    <label>ZIP Master</label>
    <referenceTo>ZIP_Master__c</referenceTo>
    <relationshipLabel>Territory Master</relationshipLabel>
    <relationshipName>Territory_Master</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/ZIP_Master__c.object-meta.xml
<CustomObject>
    <label>ZIP Master</label>
    <nameField>
        <label>ZIP Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZIP Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZIP_Master__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Zip codes primary city</description>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>US States</description>
    <label>State</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/fields/ZIP__c.field-meta.xml
<CustomField>
    <fullName>ZIP__c</fullName>
    <label>ZIP</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EPAIdUpdateControllerTests.cls
@isTest
public class EPAIdUpdateControllerTests {
     private final static string TEST_SHIPPING_POSTALCODE = '45204';
     private final static string TEST_SHIPPING_COUNTRY = 'US';
     private final static string TEST_SHIPPING_STATE = 'OR'; 
     private final static string TEST_SHIPPING_CITY = 'Brookings'; 
     private final static string TEST_SHIPPING_STREET = 'Test Street';
     private final static string TEST_NAME = 'Gillette Company';
     private final static string TEST_PHONE = '799856414';
     private final static string TEST_TYPE =  'Customer'; 
     private final static string TEST_TYPE1 = 'ShipTo/Gen';
     private final static string TEST_BUSINESS_TYPE = 'Base'; 
     private final static string TEST_RANK = 'CH A Large >200K';
     private final static string TEST_INDUSTRY_SEGMENT = 'Chemical';
     private final static string TEST_INDUSTRY_SEGMENT1 = 'Machinery Manufacturing';
     private final static string TEST_CURRENCYISOCODE = 'USD';
     private final static string TEST_CS_EPA_ID = 'PENDING';
     private final static string TEST_GENERATOR_STATUS = 'Large Quantity Generator'; 
     private final static string TEST_MISSING_CONTACT_TYPE = 'MAIN';
     private final static string TEST_STATUS = 'Active';
     private final static string TEST_ZIP = '45204';
     private final static string TEST_SALES_BUSINESS_UNIT = 'lodging';  
     private final static string TEST_CASE_TYPE = 'New';
     private final static string TEST_CASE_POSTAL_CODES = '02061';
     private final static string TEST_CASE_WIN_ID = 'ECOMT2';
     private final static string TEST_CASE_FIRST_NAME = 'ABC';
     private final static string TEST_CASE_DESCRIPTION = 'Test';
     private final static string TEST_CASE_UNEXPIRE_REASON = 'Account needs to be serviced';
     private final static string TEST_CASE_CALL_CENTER_ACTIVITY_ID = 'ASDE234';
     private final static string TEST_CASE_COMEENT_BODY = 'This is closed because no need of service';
     private final static string TEST_FIRST_NAME = 'Test'; 
     private final static string TEST_LAST_NAME = 'Test';
     private final static string TEST_SALUTATION = 'Mr';    
     private final static string TEST_TITLE = 'title';
     private final static string TEST_EMAIL = 'Test1@testemail.com';
     private final static string TEST_REQUEST_TYPE1 = 'Inactivation Request';
    @testsetup
    static void setup(){
        SIC_VALIDATION_SETTING__c svsObj = new SIC_VALIDATION_SETTING__c();
        svsObj.name = 'SIC_VALIDATION_SETTING';
        svsObj.SIC_VALIDATION_FLAG__c = true;
        insert svsObj;
        
        TERRITORY_MANAGEMENT__c tmgObj = new TERRITORY_MANAGEMENT__c();
        tmgObj.name = 'TERRITORY_MGMT_SETTING';
        tmgObj.TM_FLAG__c = true;
        insert tmgObj;
        
         COUNTRY_CODES__c countrycodes = new COUNTRY_CODES__c();    
         countrycodes.Name = 'CA';  
         insert countrycodes;   
            
         COUNTRY_CODES__c countrycodes1 = new COUNTRY_CODES__c();   
         countrycodes1.Name = 'US'; 
         insert countrycodes1;  
            
         ZIP_Master__c zpObj = new ZIP_Master__c(); 
        zpObj.zip__c = TEST_ZIP;    
        zpObj.CurrencyIsoCode = TEST_CURRENCYISOCODE;   
        zpObj.Country__c = TEST_Shipping_Country;   
        zpObj.State__c = TEST_Shipping_State;   
        insert zpObj; 

        List<ZIP_Master__c> zipMasterList = new List<ZIP_Master__c>();
        for(Integer i = 0; i < 10; i++){
            zipMasterList.add(new ZIP_Master__c(Zip__c = '12345',Country__c = 'US', State__c = 'NY',City__c ='Ashburn'));
			zipMasterList.add(new ZIP_Master__c(Zip__c = '10047',Country__c = 'US', State__c = 'NY',City__c = 'New York'));
         
        }
        insert zipMasterList;
            
        Territory_Master__c tmObj = new Territory_Master__c();  
        tmObj.name = 'Test TM'; 
        tmObj.ZIP_Master__c = zpObj.id; 
        tmObj.CurrencyIsoCode = TEST_CURRENCYISOCODE;   
        tmObj.Sales_business_unit__C = 'lodging';           
        insert tmObj;
        
        Id branchRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Branch').getRecordTypeId();
        Account a = new Account(Name='Test Account',RecordTypeId=branchRecTypeId,Branch_Opportunity_Allowed__c =true ,AccountSource='Web',Rank__c='CH A Large >200K',Industry_Segment__c='Other',Phone='5555555675',CS_EPA_ID__c='100',Generator_Status__c='Small Quantity Generator',Branch_Call_Origin_Flag__c=TRUE,CurrencyIsoCode='USD');
        insert a;
        user activeUser =[select id from user where IsActive = True limit 1];
        Account accObj = new Account();
        accObj.Name =  TEST_NAME;
        accObj.dunbrdst__c = '12345';
        accObj.KAM_Manager__c = activeUser.id;
        accObj.KAM_Support__c = activeUser.id;
        accObj.OwnerId = activeUser.id;
        accObj.Phone = TEST_PHONE;
        accObj.Type = TEST_TYPE;
        accObj.Business_Type__c = TEST_BUSINESS_TYPE;
        accObj.Rank__c = TEST_RANK;
        accObj.WIN_ID__c = 'GIL210';
        accObj.Industry_Segment__c = TEST_INDUSTRY_SEGMENT;
        accObj.CurrencyIsoCode = TEST_CURRENCYISOCODE;
        accObj.CS_EPA_ID__c =  TEST_CS_EPA_ID;
        accObj.Generator_Status__c = TEST_GENERATOR_STATUS;
        accObj.ShippingPostalCode = TEST_SHIPPING_POSTALCODE;
        accObj.ShippingCountry = TEST_SHIPPING_COUNTRY;
        accObj.ShippingState = TEST_SHIPPING_STATE;
        accObj.ShippingCity = TEST_SHIPPING_CITY;
        accObj.ShippingStreet = TEST_SHIPPING_STREET;
        accObj.recordtypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Corporate').getRecordTypeId();
        insert accObj;
        
        Account accObjCust = new Account();
        accObjCust.Name = TEST_NAME;
        accObjCust.Phone = TEST_PHONE;
        accObjCust.Type = TEST_TYPE;
        accObjCust.Business_Type__c = TEST_BUSINESS_TYPE; 
        accObjCust.Rank__c = TEST_RANK;
        accObjCust.Industry_Segment__c = TEST_INDUSTRY_SEGMENT;
        accObjCust.CurrencyIsoCode = TEST_CURRENCYISOCODE;
        accObjCust.CS_EPA_ID__c = TEST_CS_EPA_ID;
         accObjCust.State_EPA_ID__c=TEST_CS_EPA_ID;
        accObjCust.Generator_Status__c = TEST_GENERATOR_STATUS;
        accObjCust.ShippingPostalCode = TEST_SHIPPING_POSTALCODE;
        accObjCust.ShippingCountry = TEST_SHIPPING_COUNTRY;
        accObjCust.ShippingState = TEST_SHIPPING_STATE;
        accObjCust.ShippingCity = TEST_SHIPPING_CITY;
        accObjCust.ShippingStreet = TEST_SHIPPING_STREET;
         
        accObjCust.recordtypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        accObjCust.ParentId = accObj.Id;
        insert accObjCust;
        
        Account gens = new Account();
        gens.ParentId = accObjCust.id;
        gens.Name = TEST_NAME;
        gens.Phone = TEST_PHONE;
        gens.Type = TEST_TYPE1; 
        gens.Business_Type__c = TEST_BUSINESS_TYPE;
        gens.Rank__c =  TEST_RANK;
        gens.WIN_ID__c = 'GI11503';
        gens.Industry_Segment__c = TEST_INDUSTRY_SEGMENT; 
        gens.CurrencyIsoCode = TEST_CURRENCYISOCODE;
        gens.CS_EPA_ID__c = TEST_CS_EPA_ID;
        gens.Generator_Status__c = TEST_GENERATOR_STATUS;
        gens.Missing_Contact_Type__c=  TEST_MISSING_CONTACT_TYPE;
        gens.Status__c = TEST_STATUS;
        gens.recordtypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer Location').getRecordTypeId();
        
        insert gens;
        EPA_SERVICE__c setting = new EPA_SERVICE__c();
        setting.Name = 'EPA_SERVICE_ENDPOINT';
        setting.ENDPOINT_URL__c = 'https:///websvcdev.cleanharbors.com//crmservices//api//epa//rules';

        insert setting;
    }
    @isTest
    private static void updateEPAIDTest(){

        Test.startTest();
            List<EPAIdUpdateController.EPAIdRequest> epaIdList = new List<EPAIdUpdateController.EPAIdRequest>();
            Account accRec = [SELECT Id FROM Account WHERE RecordType.Name = 'Customer'];
		    EPAIdMock epaMock=new EPAIdMock(false);
            Test.setMock(HttpCalloutMock.class, epaMock);
            EPAIdUpdateController.EPAIdRequest upAcc =new EPAIdUpdateController.EPAIdRequest();
            upAcc.accId = accRec.id;
            upAcc.epaIDValue = 'CS023';
            epaIdList.add(upAcc);
            EPAIdUpdateController.updateEPAID(epaIdList);
            Account updatedAccRec = [Select id,WIN_Compliance_Errors__c from Account where Id = :accRec.Id];
        Test.stopTest();

        Assert.areEqual(updatedAccRec.WIN_Compliance_Errors__c, null); 
    }
}