force-app/main/default/objects/Account/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Buying_Decision__c.field-meta.xml
<CustomField>
    <fullName>Buying_Decision__c</fullName>
    <label>Buying Decision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Central Buying</fullName>
            </value>
            <value>
                <fullName>Locally Managed</fullName>
            </value>
            <value>
                <fullName>Hybrid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Key_Account_Primary_Business__c.field-meta.xml
<CustomField>
    <fullName>Key_Account_Primary_Business__c</fullName>
    <formula>IF(RecordType.Name = &apos;Customer Location&apos;, TEXT(Parent.Parent.Owner.Primary_Business__c), 
IF(RecordType.Name = &apos;Distributor Location&apos;, TEXT(Parent.Parent.Owner.Primary_Business__c), 
IF(RecordType.Name = &apos;Broker Location&apos;, TEXT(Parent.Parent.Owner.Primary_Business__c), 
IF(RecordType.Name = &apos;Customer&apos;, TEXT(Parent.Owner.Primary_Business__c), 
IF(RecordType.Name = &apos;Customer Chain&apos;, TEXT(Parent.Owner.Primary_Business__c), 
IF(RecordType.Name = &apos;Distibutor&apos;, TEXT(Parent.Owner.Primary_Business__c), 
IF(RecordType.Name = &apos;Broker&apos;, TEXT(Parent.Owner.Primary_Business__c), &apos;&apos;)))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Corp Account Primary Business</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Key_Account_Support_Person__c.field-meta.xml
<CustomField>
    <fullName>Key_Account_Support_Person__c</fullName>
    <formula>IF(AND(RecordType.Name = &apos;Customer&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Chain&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Distributor&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Broker&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Customer Chain&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Customer Location&apos;, Parent.Parent.RecordType.Name = &apos;Key Account&apos;), Parent.Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Broker Location&apos;, Parent.Parent.RecordType.Name = &apos;Key Account&apos;), Parent.Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Distributor Location&apos;, Parent.Parent.RecordType.Name = &apos;Key Account&apos;), Parent.Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName ,
IF(RecordType.Name = &apos;Customer Location&apos;,  Parent.Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName , 
IF(RecordType.Name = &apos;Distributor Location&apos;,  Parent.Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName, 
IF(RecordType.Name = &apos;Broker Location&apos;,  Parent.Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName , 
IF(RecordType.Name = &apos;Customer&apos;,  Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(RecordType.Name = &apos;Key Account&apos;,  Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(RecordType.Name = &apos;Customer Chain&apos;,  Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(RecordType.Name = &apos;Distributor&apos;,  Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(RecordType.Name = &apos;Broker&apos;,  Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(RecordType.Name = &apos;Chain&apos;,  Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,&apos;&apos;)))))))))))))))))</formula>
    <label>Corp/Key Account Support Person</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Key_Buying_Decision__c.field-meta.xml
<CustomField>
    <fullName>Key_Buying_Decision__c</fullName>
    <formula>IF(AND(RecordType.Name = &apos;Customer&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), text(Parent.Buying_Decision__c),
IF(AND(RecordType.Name = &apos;Distibutor&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), text(Parent.Buying_Decision__c),
IF(AND(RecordType.Name = &apos;Broker&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), text(Parent.Buying_Decision__c),
IF(AND(RecordType.Name = &apos;Customer Chain&apos;, Parent.RecordType.Name = &apos;Key Account&apos;),  text(Parent.Buying_Decision__c),
IF(AND(RecordType.Name = &apos;Chain&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), text(Parent.Buying_Decision__c),
IF(AND(RecordType.Name = &apos;Customer Location&apos;, Parent.Parent.RecordType.Name = &apos;Key Account&apos;), text(Parent.Parent.Buying_Decision__c),
IF(AND(RecordType.Name = &apos;Distributor Location&apos;, Parent.Parent.RecordType.Name = &apos;Key Account&apos;), text(Parent.Parent.Buying_Decision__c),
IF(AND(RecordType.Name = &apos;Broker Location&apos;, Parent.Parent.RecordType.Name = &apos;Key Account&apos;), text(Parent.Parent.Buying_Decision__c),
IF(RecordType.Name = &apos;Customer Location&apos;, IF(ISBLANK(text(Parent.Parent.Buying_Decision__c)), text(Chain__r.Buying_Decision__c), text(Parent.Parent.Buying_Decision__c)),
IF(RecordType.Name = &apos;Broker Location&apos;, text(Parent.Parent.Buying_Decision__c),
IF(RecordType.Name = &apos;Distributor Location&apos;, text(Parent.Parent.Buying_Decision__c),
IF(RecordType.Name = &apos;Pricing Chain&apos;, text(Parent.Buying_Decision__c),
IF(RecordType.Name = &apos;Distributor&apos;, text(Parent.Buying_Decision__c),
IF(RecordType.Name = &apos;Broker&apos;, text(Parent.Buying_Decision__c),
IF(RecordType.Name = &apos;Customer&apos;, IF(ISBLANK(text(Parent.Buying_Decision__c)), text(Chain__r.Buying_Decision__c), text(Parent.Buying_Decision__c)),
IF(RecordType.Name = &apos;Chain&apos;, text(Buying_Decision__c),
IF(RecordType.Name = &apos;Customer Chain&apos;, text(Parent.Buying_Decision__c), text(Buying_Decision__c) )))))))))))))))))</formula>
    <label>Corp/Key Account Buying Decision</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Primary_Service_Provider__c</fullName>
    <description>Displays the old Primary Service providers</description>
    <label>Primary Service Provider Old</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Clean Harbors</fullName>
                <default>true</default>
                <label>Clean Harbors</label>
            </value>
            <value>
                <fullName>CYN</fullName>
            </value>
            <value>
                <fullName>Emerald Services</fullName>
            </value>
            <value>
                <fullName>RS Used Oil</fullName>
            </value>
            <value>
                <fullName>Safety Kleen</fullName>
            </value>
            <value>
                <fullName>SK BPS</fullName>
            </value>
            <value>
                <fullName>Thermo Fluids</fullName>
            </value>
			<value>
                <fullName>Thompson</fullName>
            </value> 
            <value>
                <fullName>HPC</fullName>
            </value>
            <value>
                <fullName>Noble Oil</fullName>
            </value>
            <value>
                <fullName>HEPACO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Service_Provider_New__c.field-meta.xml
<CustomField>
    <fullName>Primary_Service_Provider_New__c</fullName>
    <label>Operating Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SK ENV</fullName>
            </value>
            <value>
                <fullName>SK BPS</fullName>
            </value>
            <value>
                <fullName>SK KPP</fullName>
            </value>
            <value>
                <fullName>Clean Harbors ENV</fullName>
            </value>
            <value>
                <fullName>CHES Oil and Gas</fullName>
            </value>
            <value>
                <fullName>CHES Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/WIN_ID__c.field-meta.xml
<CustomField>
    <fullName>WIN_ID__c</fullName>
    <externalId>true</externalId>
    <label>WIN ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Branch.recordType-meta.xml
<RecordType>
    <fullName>Branch</fullName>
    <active>true</active>
    <description>All Clean Harbors Branches</description>
    <label>Branch</label> 
</RecordType>

force-app/main/default/objects/Case/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Conver_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Conver_DateTime__c</fullName>
    <label>Conver DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/CONVER_DT__c.field-meta.xml
<CustomField>
    <fullName>CONVER_DT__c</fullName>
    <label>Conversation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_Balance__c.field-meta.xml
<CustomField>
    <fullName>Customer_Balance__c</fullName>
    <label>Customer Balance</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/EBiller__c.field-meta.xml
<CustomField>
    <fullName>EBiller__c</fullName>
    <label>EBiller</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Follow_up_action__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_action__c</fullName>
    <label>Follow up action</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Follow_up_date__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_date__c</fullName>
    <label>Follow up date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Generator_Code__c.field-meta.xml
<CustomField>
    <fullName>Generator_Code__c</fullName>
    <label>Generator Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Keyword_1__c.field-meta.xml
<CustomField>
    <fullName>Keyword_1__c</fullName>
    <label>Issue</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Keyword_2__c.field-meta.xml
<CustomField>
    <fullName>Keyword_2__c</fullName>
    <label>Responsible</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Keyword_3__c.field-meta.xml
<CustomField>
    <fullName>Keyword_3__c</fullName>
    <label>Action</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/OPRID__c.field-meta.xml
<CustomField>
    <fullName>OPRID__c</fullName>
    <label>Added By</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Overdue_Balance__c.field-meta.xml
<CustomField>
    <fullName>Overdue_Balance__c</fullName>
    <label>Overdue Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/PROMISE_AMT__c.field-meta.xml
<CustomField>
    <fullName>PROMISE_AMT__c</fullName>
    <label>Promise Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Promise_DT__c.field-meta.xml
<CustomField>
    <fullName>Promise_DT__c</fullName>
    <label>Promise Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/REFERENCES__c.field-meta.xml
<CustomField>
    <fullName>REFERENCES__c</fullName>
    <label>Invoices</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/SETID__c.field-meta.xml
<CustomField>
    <fullName>SETID__c</fullName>
    <label>SETID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/WIN_Id__c.field-meta.xml
<CustomField>
    <fullName>WIN_Id__c</fullName>
    <label>WIN Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/Exception_Log__c.object-meta.xml
<CustomObject>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>EL-{00000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception_Log__c/fields/Apex_Method_Event__c.field-meta.xml
<CustomField>
    <fullName>Apex_Method_Event__c</fullName>
    <label>Apex Method/Event</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RestCollectionCase.cls
@RestResource(urlMapping = '/CollectionCase/*')
global class RestCollectionCase {
        
    @HttpGet
    global static List <Case> getCase()
    { 
          
        List<Case> c = [select id, createdDate, status, subject, WIN_Id__c, Business_Unit__c,Conver_DateTime__c, Follow_up_action__c,Follow_up_date__c,Keyword_1__c, Keyword_2__c, Keyword_3__c, OPRID__c, SETID__c,EBiller__c,Customer_Balance__c, Description  from Case
                        //where createddate > startDate and createddate < enddate
                        limit 1];  
        return c; 
    }   
         
    @HttpPost
    global static void createnewcase (string CUST_ID, string BUSINESS_UNIT, String FOLLOW_UP_ACTION, String CONVER_DT, String CASE_TYPE, String FOLLOW_UP_DT, String PROMISE_DT,
                                     String PROMISE_AMT,String KEYWORD1, string COMMENTS, String KEYWORD2,  String KEYWORD3, String OPRID, String SETID,String EBILLER ,String CUST_BALANCE,String REFERENCES, String CONVER_DTTM_INIT, String BRANCH, String OVERDUE_BALANCE, String GENERATOR_CODE){
									 
         String reqBody = '\'{\'"CUST_ID": "{0}", "BUSINESS_UNIT": "{1}", "FOLLOW_UP_ACTION": "{2}", "CONVER_DT": "{3}", "CASE_TYPE": "{4}", "FOLLOW_UP_DT": "{5}", "PROMISE_DT": "{6}", "PROMISE_AMT": "{7}", "KEYWORD1": "{8}", "COMMENTS": "{9}", "KEYWORD2": "{10}", "KEYWORD3": "{11}", "OPRID": "{12}", "SETID": "{13}", "EBILLER": "{14}", "CUST_BALANCE": "{15}", "REFERENCES": "{16}", "CONVER_DTTM_INIT": "{17}", "BRANCH": "{18}", "OVERDUE_BALANCE": "{19}", "GENERATOR_CODE": "{20}"\'}\'';
         list<String> lstst=new     List<String>{CUST_ID,BUSINESS_UNIT,FOLLOW_UP_ACTION,CONVER_DT,CASE_TYPE,FOLLOW_UP_DT,PROMISE_DT,PROMISE_AMT,KEYWORD1,COMMENTS,KEYWORD2,KEYWORD3,OPRID,SETID,EBILLER,CUST_BALANCE,REFERENCES,CONVER_DTTM_INIT,BRANCH,OVERDUE_BALANCE,GENERATOR_CODE};
         String message = String.format(reqBody, lstst);
		 List<String> PSPCHES= new List<String>{'Clean Harbors ENV', 'CHES Oil and Gas', 'CHES Industrial'};
         List<String> PSPSKE= new List<String>{'SK ENV', 'SK BPS', 'SK KPP'};
         List<Account> accList = new List<Account>();
		 String accSuppPerson;	
         String ownerid;
                                         
         if(CUST_ID != NULL)
         {
           	accList = [
                SELECT Id, Key_Account_Primary_Business__c, Primary_Service_Provider__c,Buying_Decision__c, Primary_Service_Provider_New__c,Key_Buying_Decision__c,Key_Account_Support_Person__c, OwnerId, Owner.IsActive, Owner.ManagerId, Owner.Manager.IsActive 
                FROM Account 
                WHERE WIN_ID__c =:CUST_ID 
                LIMIT 1
            ]; 
             
             if(!accList.isEmpty()){
                     if(accList[0].Key_Buying_Decision__c == 'Central Buying' && accList[0].Key_Account_Support_Person__c != NULL){
                         accSuppPerson = accList[0].Key_Account_Support_Person__c;
                     }else 
                     if(PSPCHES.contains(accList[0].Primary_Service_Provider_New__c)){ 
                         if(accList[0].Owner.IsActive){
                             ownerid = accList[0].OwnerId;    
                      }else
                         {
                             ownerid = accList[0].Owner.ManagerId;    
                         }
                     }else if(PSPSKE.contains(accList[0].Primary_Service_Provider_New__c)){
                           List<Account> accountRecLst = [SELECT Id, OwnerId, Owner.ManagerId, Owner.IsActive FROM Account WHERE WIN_ID__c = :GENERATOR_CODE];
                             if(!accountRecLst.isEmpty()){
                                if(accountRecLst[0].Owner.IsActive){
                                 ownerid = accountRecLst[0].OwnerId;    
                             }else{
                                 ownerid = accountRecLst[0].Owner.ManagerId;    
                             }
                         }else{
                             RestContext.response.responseBody = Blob.valueOf('{"case_id":"","Error":"No account record for the generator code.","Case_No":""}');
							 RestCollectionCase.createExceptionLog('No account record for the generator code.'+ '|' + reqBody, '','');
                             return;
                      }
                 }
             }
         }
         
         User uObj = new User();
         for(User obj : [Select Id, Name from User where FederationIdentifier =: OPRID Limit 1]){
             uObj = obj;
         }       
         List<user> us = new list<user>();     
         if(accSuppPerson != null){
             us = [Select Id, Name, isActive, ManagerId, Manager.isActive, Manager.Name FROM USER WHERE Name =: accSuppPerson LIMIT 1]; //Update the query to pull Manager Related information - Sireesha
         }
         if(!us.isEmpty()){
             //Assign the user as owner only if the User is active - Sireesha
             if(us[0].isActive && !us[0].Name.Contains('Inactive')){
                 ownerId = us[0].Id;
             }//Otherwise assign to the Manager if he is active - Sireesha
             else if(us[0].ManagerId != NULL && us[0].Manager.isActive && !us[0].Manager.Name.Contains('Inactive')){
                 ownerId = us[0].ManagerId;
             }
         }
                                          
          
          if(EBILLER!='' && EBILLER!=null ){
             us= [SELECT id,EmployeeNumber, isActive, ManagerId, Manager.isActive FROM USER WHERE EmployeeNumber =:EBILLER]; //Update the query to pull Manager Related information - Sireesha
             if(!us.isEmpty() && us.size()>0)
             {
                 //Assign the user as owner only if the User is active
                 if(us[0].isActive){
                     ownerId = us[0].Id;
                 }//Otherwise assign to the Manager if he is active
                 else if(us[0].ManagerId != NULL && us[0].Manager.isActive){
                     ownerId = us[0].ManagerId;
                 }
             }
         } 
         if(ownerId == NULL){
             ownerid=System.label.Ebill_Owner;
         }
                          
        Id devRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Collector Case').getRecordTypeId();
                                         
        try{
           case newcase = new case ();
            newcase.RecordTypeId = devRecordTypeId;
            newcase.Subject = 'Collection Case';
            newcase.status = 'New';
            newcase.WIN_Id__c = CUST_ID;           
            newcase.Business_Unit__c = BUSINESS_UNIT;
            newcase.Follow_up_action__c = FOLLOW_UP_ACTION;
            newcase.Keyword_1__c = Keyword1;
            newcase.Keyword_2__c = Keyword2;
            newcase.Keyword_3__c = Keyword3;
            newcase.SETID__c = SETID;
            newcase.EBiller__c = EBILLER;
            newcase.Customer_Balance__c = CUST_BALANCE;
            newcase.Type=CASE_TYPE;
            newcase.PROMISE_AMT__c=decimal.valueOf(Promise_Amt);
            newcase.Description = COMMENTS;
            newcase.Branch_Code__c = BRANCH;
            newcase.Overdue_Balance__c = decimal.valueOf(OVERDUE_BALANCE);
            //To include replace Federation Id with User name
            if(uObj.Name != NULL){
                newcase.OPRID__c = uObj.Name;
            }
            else{
                newcase.OPRID__c = OPRID;
            }
            
            newcase.REFERENCES__c=References;
            newcase.CONVER_DT__c = Date.valueOf(CONVER_DT);
            newcase.Follow_up_date__c = Date.valueOf(FOLLOW_UP_DT);
            newcase.Conver_DateTime__c=Datetime.valueOf(CONVER_DTTM_INIT);
            newcase.Promise_DT__c=Date.valueOf(PROMISE_DT); 
            newcase.Generator_Code__c = GENERATOR_CODE;
			CaseCRUDHandler.skipAutomatedOwnerAssignment=true;
            newcase.OwnerId=ownerid;
            
            insert newcase;
            
           string CaseNumber;
           List<case> acc= [select Id,CaseNumber from case where Id=: newcase.Id];
            for(case a: acc) {  CaseNumber = a.CaseNumber;}      
            RestContext.response.responseBody = Blob.valueOf('{"case_id" :"' +acc[0].Id+'","Error":"","Case_No":"'+CaseNumber+'"}');
        } catch (Exception e){
            RestContext.response.responseBody = Blob.valueOf('{"case_id":"","Error":"'+ e.getMessage()+'","Case_No":""}');
			RestCollectionCase.createExceptionLog(e.getMessage()+ '|' +reqBody,e.getStackTraceString(), '');
        } 
    }   
	
    private static void createExceptionLog(string errorMessage, string stackTrace, string recordId){
        Exception_Log__c log = new Exception_Log__c(
            Error_Message__c= errorMessage, 
            Exception_Stack_Trace__c= stackTrace, 
            Record_Id__c= recordId, 
            Apex_Method_Event__c= 'createnewcase');
        ExceptionLogDAO.logException(new List<Exception_Log__c>{log});
    }	
}