force-app/main/default/objects/Account/fields/Branch_Call_Origin_Flag__c.field-meta.xml
<CustomField>
    <fullName>Branch_Call_Origin_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag for branches to be used in the call origin in case mgmt</description>
    <label>Branch Call Origin Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Branch_Opportunity_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Branch_Opportunity_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this field is selected then this branch can be used on an opportunity</description>
    <label>Branch Opportunity Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/CS_EPA_ID__c.field-meta.xml
<CustomField>
    <fullName>CS_EPA_ID__c</fullName>
    <inlineHelpText>The following fields are required in order to validate the EPA Id in addition to the EPA Id field. 
-Corporate Street 
-Corporate State 
-Corporate Country 
-Generator Status 
-Primary Service Provider</inlineHelpText>
    <label>EPA ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Generator_Status__c.field-meta.xml
<CustomField>
    <fullName>Generator_Status__c</fullName>
	<inlineHelpText>An account&apos;s generator status can only be upgraded from Salesforce. Downgrades in this area need to be coordinated by our compliance team. For status downgrades, please submit a Service Now ticket using category/subcategory: WIN-Aurora(FocalPoint), CWT-Compliance or WIN-Compliance, EPA ID Number.</inlineHelpText>
    <label>Generator Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Large Quantity Generator</fullName>
            </value>
            <value>
                <fullName>Small Quantity Generator</fullName>
            </value>
            <value>
                <fullName>Conditionally Exempt Sm Qty Generator</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
                <default>true</default>
                <label>Undetermined</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Segment__c.field-meta.xml
<CustomField>
    <fullName>Industry_Segment__c</fullName>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Base &amp; Blended Oils</fullName>
            </value>
            <value>
                <fullName>Brokers</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Ecommerce</fullName>
            </value>
            <value>
                <fullName>Education Services</fullName>
            </value>
            <value>
                <fullName>Engineering &amp; Consulting</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Insurance &amp; Real Estate</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Mining</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Paper &amp; Wood</fullName>
            </value>
            <value>
                <fullName>Pharmaceutical &amp; Biotechnology</fullName>
            </value>
            <value>
                <fullName>Refineries &amp; Oilsands</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Terminals &amp; Pipelines</fullName>
            </value>
            <value>
                <fullName>Transportation Services</fullName>
            </value>
            <value>
                <fullName>Utilities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <type>Picklist</type>
    <valueSet>
	    <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CH A Large &gt;200K</fullName>
            </value>
            <value>
                <fullName>CH C Assigned &gt;30K</fullName>
            </value>
            <value>
                <fullName>D &lt;30,000</fullName>
            </value>
            <value>
                <fullName>CH E Small &lt;30K</fullName>
            </value>
            <value>
                <fullName>CH B Medium &gt;100K</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Branch.recordType-meta.xml
<RecordType>
    <fullName>Branch</fullName>
    <active>true</active>
    <description>All Clean Harbors Branches</description>
    <label>Branch</label> 
</RecordType>

force-app/main/default/objects/Branch_Queue_Map__c/Branch_Queue_Map__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used for Branch Queue Mapping</description>
    <label>Branch Queue Map</label>
</CustomObject>

force-app/main/default/objects/Branch_Queue_Map__c/fields/Branch_Queue__c.field-meta.xml
<CustomField>
    <fullName>Branch_Queue__c</fullName>
    <description>Queue name of a Branch</description>
    <label>Branch Queue</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SurfaceBranchListOnBranchAccountTests.cls
@isTest
public class SurfaceBranchListOnBranchAccountTests {
    @testSetup 
    private static void setup(){
        Group testGroup = new Group(Name='queu', Type='Regular');
        insert testGroup;
        Group testGroup1 = new Group(Name='sque', Type='Queue');
        insert testGroup1;
        System.runAs(new User(Id=UserInfo.getUserId())){
            List<QueueSobject> qs = new List<QueueSobject>();            
            qs.add(new QueueSobject (
                SobjectType='Case',
                QueueId = testGroup1.Id
            ));            
            Database.insert( qs );
            GroupMember queMem = new GroupMember();
            queMem.GroupId = testGroup1.Id;
            queMem.UserOrGroupId = UserInfo.getUserId();
            INSERT queMem;
            GroupMember queMem1 = new GroupMember();
            queMem1.GroupId = testGroup1.Id;
            queMem1.UserOrGroupId = testGroup.Id;
            INSERT queMem1;            
        }        
        Branch_Queue_Map__c branchQueueMap = new Branch_Queue_Map__c();
        branchQueueMap.Name = 'AA123';
        branchQueueMap.Branch_Queue__c = 'queu';
        INSERT branchQueueMap;        
        Branch_Queue_Map__c branchQueueMap1 = new Branch_Queue_Map__c();
        branchQueueMap1.Name = 'S123';
        branchQueueMap1.Branch_Queue__c = 'sque';
        INSERT branchQueueMap1;
        Id branchRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Branch').getRecordTypeId();
        Account a = new Account(Name='Test Account',RecordTypeId=branchRecTypeId,Branch_Opportunity_Allowed__c =true,Branch_Code__c ='S123' ,AccountSource='Web',Rank__c='CH A Large >200K',Industry_Segment__c='Other',Phone='5555555555',CS_EPA_ID__c='100',Generator_Status__c='Small Quantity Generator',Branch_Call_Origin_Flag__c=TRUE,CurrencyIsoCode='USD');
        insert a;
    }
    @isTest
    private static void getSurfaceBranchListOnBranchAccountTest(){
        List<Account> acc = [Select id from account where name='Test Account'];
        List<User> users = SurfaceBranchListOnBranchAccount.getSurfaceBranchListOnBranchAccount(acc[0].Id);
        System.assertNotEquals(null, users, 'No users found for the Branch Account.');
    }
    
}