force-app/main/default/objects/Account/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
                <default>true</default>
                <label>Base</label>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Locating</fullName>
            </value>
            <value>
                <fullName>Key</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CS_EPA_ID__c.field-meta.xml
<CustomField>
    <fullName>CS_EPA_ID__c</fullName>
    <inlineHelpText>The following fields are required in order to validate the EPA Id in addition to the EPA Id field. 
-Corporate Street 
-Corporate State 
-Corporate Country 
-Generator Status 
-Primary Service Provider</inlineHelpText>
    <label>EPA ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Generator_Status__c.field-meta.xml
<CustomField>
    <fullName>Generator_Status__c</fullName>
	<inlineHelpText>An account&apos;s generator status can only be upgraded from Salesforce. Downgrades in this area need to be coordinated by our compliance team. For status downgrades, please submit a Service Now ticket using category/subcategory: WIN-Aurora(FocalPoint), CWT-Compliance or WIN-Compliance, EPA ID Number.</inlineHelpText>
    <label>Generator Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Large Quantity Generator</fullName>
            </value>
            <value>
                <fullName>Small Quantity Generator</fullName>
            </value>
            <value>
                <fullName>Conditionally Exempt Sm Qty Generator</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
                <default>true</default>
                <label>Undetermined</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Segment__c.field-meta.xml
<CustomField>
    <fullName>Industry_Segment__c</fullName>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Base &amp; Blended Oils</fullName>
            </value>
            <value>
                <fullName>Brokers</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Ecommerce</fullName>
            </value>
            <value>
                <fullName>Education Services</fullName>
            </value>
            <value>
                <fullName>Engineering &amp; Consulting</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Insurance &amp; Real Estate</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Mining</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Paper &amp; Wood</fullName>
            </value>
            <value>
                <fullName>Pharmaceutical &amp; Biotechnology</fullName>
            </value>
            <value>
                <fullName>Refineries &amp; Oilsands</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Terminals &amp; Pipelines</fullName>
            </value>
            <value>
                <fullName>Transportation Services</fullName>
            </value>
            <value>
                <fullName>Utilities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IS_Opportunity_Rank__c.field-meta.xml
<CustomField>
    <fullName>IS_Opportunity_Rank__c</fullName>
    <label>IS Opportunity Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Business__c.field-meta.xml
<CustomField>
    <fullName>Primary_Business__c</fullName>
    <description>Primary business based off account owner</description>
    <label>Primary Service Provider</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Primary_Service_Provider_New__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Daylighting Services</fullName>
            </value>
            <value>
                <fullName>Emerald Services</fullName>
            </value>
            <value>
                <fullName>Field Services</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Industrial Services</fullName>
            </value>
            <value>
                <fullName>Lodging</fullName>
            </value>
            <value>
                <fullName>Murphys Oil</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Technical Services</fullName>
            </value>
            <value>
                <fullName>Thermo Fluids</fullName>
            </value>
            <value>
                <fullName>H2O</fullName>
            </value>
            <value>
                <fullName>BPS</fullName>
            </value>
            <value>
                <fullName>CYN</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>SK KPP</fullName>
            </value>
            <value>
                <fullName>Surface Rentals</fullName>
            </value>
            <value>
                <fullName>Seismic</fullName>
            </value>
            <value>
                <fullName>Safety-Kleen</fullName>
                <label>SK ENV</label>
            </value>
            <value>
                <fullName>OER</fullName>
            </value>
            <value>
                <fullName>HPC Industrial</fullName>
            </value>
            <value>
                <fullName>PSC</fullName>
            </value>
            <value>
                <fullName>Synergy</fullName>
            </value>
            <value>
                <fullName>DFW</fullName>
            </value>
			<value>
                <fullName>Thompson</fullName>
            </value>
			<value>
                <fullName>Noble Oil</fullName>
            </value>
            <value>
                <fullName>HEPACO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <type>Picklist</type>
    <valueSet>
	    <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CH A Large &gt;200K</fullName>
            </value>
            <value>
                <fullName>CH C Assigned &gt;30K</fullName>
            </value>
            <value>
                <fullName>D &lt;30,000</fullName>
            </value>
            <value>
                <fullName>CH E Small &lt;30K</fullName>
            </value>
            <value>
                <fullName>CH B Medium &gt;100K</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/WIN_ID__c.field-meta.xml
<CustomField>
    <fullName>WIN_ID__c</fullName>
    <externalId>true</externalId>
    <label>WIN ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>All Clean Harbors Customers</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/WIN_ID__c.field-meta.xml
<CustomField>
    <fullName>WIN_ID__c</fullName>
    <description>WIN ID of account picked for opportunity.</description>
    <formula>Account.WIN_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>WIN ID of account picked for opportunity.</inlineHelpText>
    <label>WIN ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SIC_VALIDATION_SETTING__c/SIC_VALIDATION_SETTING__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS will consist of a flag which determines if SIC Validation on Account should be implemented or not.</description>
    <label>SIC VALIDATION SETTING</label>
</CustomObject>

force-app/main/default/objects/SIC_VALIDATION_SETTING__c/fields/SIC_VALIDATION_FLAG__c.field-meta.xml
<CustomField>
    <fullName>SIC_VALIDATION_FLAG__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag which determines if SIC Validation should be executed in the custom code or not. Should be Checked if SIC Validation is required.</description>
    <label>SIC_VALIDATION_FLAG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TERRITORY_MANAGEMENT__c/TERRITORY_MANAGEMENT__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS will consist of a flag which determines if Territory Management on Account should be implemented or not. If Yes, the Territory and Owner on Account are set based on the criteria.</description>
    <label>TERRITORY MANAGEMENT</label>
</CustomObject>

force-app/main/default/objects/TERRITORY_MANAGEMENT__c/fields/TM_FLAG__c.field-meta.xml
<CustomField>
    <fullName>TM_FLAG__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag which determines if TM should be executed in the custom code or not thus setting the Territory and the Account Owner field on the Account record. Should be Checked if TM is required.</description>
    <inlineHelpText>Flag which determines if TM should be executed in the custom code or not</inlineHelpText>
    <label>TM_FLAG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Process__c/Trigger_Process__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to allow or prevent the creation of revenue schedules and updating the cross lob flags.</description>
    <label>Product Revenue Schedule Trigger</label>
</CustomObject>

force-app/main/default/objects/Trigger_Process__c/fields/canProcess__c.field-meta.xml
<CustomField>
    <fullName>canProcess__c</fullName>
    <defaultValue>false</defaultValue>
    <label>canProcess</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Primary_Business__c.field-meta.xml
<CustomField>
    <fullName>Primary_Business__c</fullName>
    <description>Primary business to be added to the accounts based off the owners value</description>
    <label>Primary Business</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BPS</fullName>
            </value>
            <value>
                <fullName>CYN Environmental</fullName>
            </value>
            <value>
                <fullName>CYN Oil</fullName>
            </value>
            <value>
                <fullName>Daylighting Services</fullName>
            </value>
            <value>
                <fullName>DFW</fullName>
            </value>
            <value>
                <fullName>Emerald Services</fullName>
            </value>
            <value>
                <fullName>Field Services</fullName>
            </value>
            <value>
                <fullName>H2O</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Industrial Services</fullName>
            </value>
            <value>
                <fullName>Kleen Performance Products</fullName>
            </value>
            <value>
                <fullName>Lodging</fullName>
            </value>
            <value>
                <fullName>Murphys Oil</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Performance Plus Products</fullName>
            </value>
            <value>
                <fullName>Production Services</fullName>
            </value>
            <value>
                <fullName>RS Used Oil</fullName>
            </value>
            <value>
                <fullName>Safety-Kleen</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>Technical Services</fullName>
            </value>
            <value>
                <fullName>Thermo Fluids</fullName>
            </value>
			<value>
                <fullName>Thompson</fullName>
            </value>
			<value>
                <fullName>Noble Oil</fullName>
            </value>
            <value>
                <fullName>HEPACO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Primary_Business__c/User_Primary_Business__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>User Primary Business</label>
</CustomObject>

force-app/main/default/objects/User_Primary_Business__c/fields/Primary_Business__c.field-meta.xml
<CustomField>
    <fullName>Primary_Business__c</fullName>
    <label>Primary Business</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestOpportunityRankBatch.cls
@isTest
private class TestOpportunityRankBatch {
    static testmethod void OpportunityRankScheduleTest(){
        Profile p1 = [Select id from Profile where name = 'Inside Sales Agent'];
        Profile p = [Select id from Profile where name = 'Integration'];
        UserRole R1 = [Select Id From UserRole where DeveloperName = 'SK_INS_BPS_AM'];
        List<User> userList = new List <User>();
        User u1 = new User(Alias = 'isduser', Email='insidesalesuser@cleanharbors.com', 
                           EmailEncodingKey='UTF-8', LastName='Inside Sales User', LanguageLocaleKey='en_US', 
                           LocaleSidKey='en_US', ProfileId = p1.Id,UserRoleId = R1.Id,
                           TimeZoneSidKey='America/Los_Angeles', UserName='insidesalesuser@cleanharbors.com',Primary_Business__c='Safety-Kleen');
        userList.add(u1);
        User u = new User(Alias = 'iuser', Email='iuser@cleanharbors.com', 
                          EmailEncodingKey='UTF-8', LastName='Integration User', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='integrationuser@cleanharbors.com',Primary_Business__c='Safety-Kleen');
        userList.add(u);
        insert userList;
        System.runAs(u){
            // Insert the custom settings with the checkbox enabled to true to ensure that the trigger allows the revenue schedule updates
            // and LOB field updates.
            Trigger_Process__c tp_lobcs = new Trigger_Process__c(Name='LOB Cross Sell',canProcess__c=true);
            Trigger_Process__c tp_rs = new Trigger_Process__c(Name='Revenue Schedule',canProcess__c=true);   
            
            insert tp_lobcs;
            
            insert tp_rs;
            
            //Insert the custom settings with validation set to false to skip validation of business rules and checks on account fields called in the account trigger.       
            SIC_VALIDATION_SETTING__c svc = new SIC_VALIDATION_SETTING__c(Name='SIC_VALIDATION_SETTING',SIC_VALIDATION_FLAG__c=false);
            insert svc;
            
            //Insert the custom settings with TM flag set to false to skip account owner assignment by territory
            TERRITORY_MANAGEMENT__c tm = new TERRITORY_MANAGEMENT__c(name='TERRITORY_MGMT_SETTING',TM_FLAG__c = false);
            insert tm;
            User_Primary_Business__c bps = new User_Primary_Business__c();
            bps.Name = 'Safety-Kleen';
            bps.Primary_Business__c = 'Safety-Kleen';
            insert bps;
            Id AccountRTId = [Select id from RecordType where DeveloperName='Customer'].Id;
            List <account> accList = new List<account>();
            Account a1 = new Account(Name='Test Account3',AccountSource='Web',Rank__c='CH A Large >200K',Industry_Segment__c='Other',Phone='5555555555',CS_EPA_ID__c='100',Generator_Status__c='Small Quantity Generator',
                                     ownerid = u1.id, Status__c ='Active', WIN_ID__c = 'TS1234', RecordTypeId = AccountRTId, IS_Opportunity_Rank__c = null);
            accList.add(a1);
            insert accList;
            
            List<Opportunity> oppList = new List<Opportunity>();
            Opportunity o1 = new Opportunity(Name='Test Opportunity',AccountId=a1.id,Business_Type__c='NEW-One Time',CloseDate=system.today(),Job_Start_Date__c=system.today(),StageName='1 - Prospecting',OwnerId = u1.id);
            
            oppList.add(o1);
            insert oppList;
            
            
            //Opportunity rank test
            String cronExpr = '0 0 23 * * ?';
            Test.startTest();
            OpportunityRankScheduler oppSched = new OpportunityRankScheduler();
            String jobId = System.schedule('myJobTestJobName', cronExpr, oppSched);
            Test.stopTest();
        }
    }
    
}