force-app/main/default/objects/Account/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
                <default>true</default>
                <label>Base</label>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Locating</fullName>
            </value>
            <value>
                <fullName>Key</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry_Segment__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agricultural Production</fullName>
            </value>
            <value>
                <fullName>Agricultural Svcs</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Airports &amp; Aviation Svcs</fullName>
            </value>
            <value>
                <fullName>Asphalt, Terminal</fullName>
            </value>
            <value>
                <fullName>Auto Maintenance</fullName>
            </value>
            <value>
                <fullName>Auto Retail</fullName>
            </value>
            <value>
                <fullName>Biotechnology</fullName>
            </value>
            <value>
                <fullName>Brokers - Waste &amp; Environmental Svcs</fullName>
            </value>
            <value>
                <fullName>Building Materials (excl Lumber Mills)</fullName>
            </value>
            <value>
                <fullName>Business and Personal Services</fullName>
            </value>
            <value>
                <fullName>Chemical - Distributor</fullName>
            </value>
            <value>
                <fullName>Chemical Manufacturing</fullName>
            </value>
            <value>
                <fullName>Colleges &amp; Universities</fullName>
            </value>
            <value>
                <fullName>Construction, Gen Contractors &amp; Builders</fullName>
            </value>
            <value>
                <fullName>Corporate Real Estate</fullName>
            </value>
            <value>
                <fullName>Cruise Lines</fullName>
            </value>
            <value>
                <fullName>Dealerships - Auto</fullName>
            </value>
            <value>
                <fullName>Dealerships - Recreational &amp; Machinery</fullName>
            </value>
            <value>
                <fullName>Drill Rig Owners</fullName>
            </value>
            <value>
                <fullName>Dry Cleaners</fullName>
            </value>
            <value>
                <fullName>Ecommerce</fullName>
            </value>
            <value>
                <fullName>Emergency Response Management</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Civil/Heavy Construction</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Drilling</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Enviro Remediation</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Oilsands</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Seismic &amp; Production</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Utilities</fullName>
            </value>
            <value>
                <fullName>Entertainment and Recreation Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CS_EPA_ID__c.field-meta.xml
<CustomField>
    <fullName>CS_EPA_ID__c</fullName>
    <inlineHelpText>The following fields are required in order to validate the EPA Id in addition to the EPA Id field. 
-Corporate Street 
-Corporate State 
-Corporate Country 
-Generator Status 
-Primary Service Provider</inlineHelpText>
    <label>EPA ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Segment__c.field-meta.xml
<CustomField>
    <fullName>Industry_Segment__c</fullName>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Base &amp; Blended Oils</fullName>
            </value>
            <value>
                <fullName>Brokers</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Ecommerce</fullName>
            </value>
            <value>
                <fullName>Education Services</fullName>
            </value>
            <value>
                <fullName>Engineering &amp; Consulting</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Insurance &amp; Real Estate</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Mining</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Paper &amp; Wood</fullName>
            </value>
            <value>
                <fullName>Pharmaceutical &amp; Biotechnology</fullName>
            </value>
            <value>
                <fullName>Refineries &amp; Oilsands</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Terminals &amp; Pipelines</fullName>
            </value>
            <value>
                <fullName>Transportation Services</fullName>
            </value>
            <value>
                <fullName>Utilities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Manifest_Post_Code__c.field-meta.xml
<CustomField>
    <fullName>Manifest_Post_Code__c</fullName>
    <label>Manifest Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <type>Picklist</type>
    <valueSet>
	    <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CH A Large &gt;200K</fullName>
            </value>
            <value>
                <fullName>CH C Assigned &gt;30K</fullName>
            </value>
            <value>
                <fullName>D &lt;30,000</fullName>
            </value>
            <value>
                <fullName>CH E Small &lt;30K</fullName>
            </value>
            <value>
                <fullName>CH B Medium &gt;100K</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Reporting_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Vertical__c</fullName>
    <label>Reporting Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Base Oil, Blender, Packager, or Marketer</fullName>
            </value>
            <value>
                <fullName>Brokers</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>Construction - Building Related Trades</fullName>
            </value>
            <value>
                <fullName>Corp RE</fullName>
            </value>
            <value>
                <fullName>Drill Rig Owner</fullName>
            </value>
            <value>
                <fullName>Education Services</fullName>
            </value>
            <value>
                <fullName>Engineering &amp; Consulting - Environmental</fullName>
            </value>
            <value>
                <fullName>Engineering &amp; Consulting - Heavy Construction</fullName>
            </value>
            <value>
                <fullName>Engineering and Consulting – Utilities</fullName>
            </value>
            <value>
                <fullName>Engineering, Consulting - Seismic</fullName>
            </value>
            <value>
                <fullName>General Manufacturing</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Mining, Primary Metals</fullName>
            </value>
            <value>
                <fullName>Oil, Gas Exploration</fullName>
            </value>
            <value>
                <fullName>Oil, Gas Production</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pharmaceutical &amp; Biotechnology</fullName>
            </value>
            <value>
                <fullName>Refineries &amp; Oilsands</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Terminals &amp; Pipelines</fullName>
            </value>
            <value>
                <fullName>Transportation Services</fullName>
            </value>
            <value>
                <fullName>Utilities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ZIP_Master__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZIP Master</label>
    <referenceTo>ZIP_Master__c</referenceTo>
    <relationshipLabel>Accounts (ZIP Master)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>All Clean Harbors Customers</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <description>All Clean Harbors Distributors</description>
    <label>Distributor</label>
</RecordType>

force-app/main/default/objects/SIC_VALIDATION_SETTING__c/SIC_VALIDATION_SETTING__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS will consist of a flag which determines if SIC Validation on Account should be implemented or not.</description>
    <label>SIC VALIDATION SETTING</label>
</CustomObject>

force-app/main/default/objects/SIC_VALIDATION_SETTING__c/fields/SIC_VALIDATION_FLAG__c.field-meta.xml
<CustomField>
    <fullName>SIC_VALIDATION_FLAG__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag which determines if SIC Validation should be executed in the custom code or not. Should be Checked if SIC Validation is required.</description>
    <label>SIC_VALIDATION_FLAG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TERRITORY_MANAGEMENT__c/TERRITORY_MANAGEMENT__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS will consist of a flag which determines if Territory Management on Account should be implemented or not. If Yes, the Territory and Owner on Account are set based on the criteria.</description>
    <label>TERRITORY MANAGEMENT</label>
</CustomObject>

force-app/main/default/objects/TERRITORY_MANAGEMENT__c/fields/TM_FLAG__c.field-meta.xml
<CustomField>
    <fullName>TM_FLAG__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag which determines if TM should be executed in the custom code or not thus setting the Territory and the Account Owner field on the Account record. Should be Checked if TM is required.</description>
    <inlineHelpText>Flag which determines if TM should be executed in the custom code or not</inlineHelpText>
    <label>TM_FLAG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/ZIP_Master__c.object-meta.xml
<CustomObject>
    <label>ZIP Master</label>
    <nameField>
        <label>ZIP Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZIP Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZIP_Master__c/fields/ZIP__c.field-meta.xml
<CustomField>
    <fullName>ZIP__c</fullName>
    <label>ZIP</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestContact1.cls
@istest
public class TestContact1 {
  public static Testmethod void method1(){
    
         Id accRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        
        List<ZIP_Master__c> zipMasterList = new List<ZIP_Master__c>();
        for(Integer i = 0; i < 10; i++){
            zipMasterList.add(new ZIP_Master__c(Zip__c = '12345'));
        }
        insert zipMasterList;
        
        TERRITORY_MANAGEMENT__c territoryMgmt = new TERRITORY_MANAGEMENT__c();
        territoryMgmt.Name = 'TERRITORY_MGMT_SETTING';
        territoryMgmt.TM_FLAG__c = true;
        insert territoryMgmt;
        
        SIC_VALIDATION_SETTING__c sicValidation = new SIC_VALIDATION_SETTING__c();
        sicValidation.Name = 'SIC_VALIDATION_SETTING';
        sicValidation.SIC_VALIDATION_FLAG__c = true;
        insert sicValidation;
        
        List<Account> accList = new List<Account>();
        for(Integer i = 0; i < 10; i++){
            accList.add(new Account(Name = 'Test ' + i, Business_Type__c = 'Base', AccountSource = 'Phone', CS_EPA_ID__c = '12345', /*Sic = '54321',*/ RecordTypeId = accRecTypeId,
            Rank__c = 'CH A Large >200K', Reporting_Vertical__c = 'Chemical', Industry_Segment__c = 'Chemical - Distributor', Class__c = 'Chemical - Distributor'
                                    /*Manifest_Post_Code__c = '12345', ShippingPostalCode = '12345', BillingPostalCode = '12345'*/));
        }
        insert accList;
        
        List<Contact> conList = new List<Contact>();
        for(Integer i = 0; i < 10; i++){
            if(i < 5 ){
                conList.add(new Contact(AccountId = accList[i].Id, LastName = 'Last ' + i, FirstName = 'First ' + i, Email = 'test'+i+'@test.com', Salutation = 'Mr.'));
            }
            else{
                conList.add(new Contact(AccountId = accList[i].Id, LastName = 'Last ' + i, FirstName = 'First ' + i, Email = 'test'+i+'@test.com', Salutation = 'Mr.'));
            }
        }
        insert conList;
        
        
        
    }

	
	
}