force-app/main/default/objects/Account/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
                <default>true</default>
                <label>Base</label>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Locating</fullName>
            </value>
            <value>
                <fullName>Key</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <formula>ShippingCity</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CS_EPA_ID__c.field-meta.xml
<CustomField>
    <fullName>CS_EPA_ID__c</fullName>
    <inlineHelpText>The following fields are required in order to validate the EPA Id in addition to the EPA Id field. 
-Corporate Street 
-Corporate State 
-Corporate Country 
-Generator Status 
-Primary Service Provider</inlineHelpText>
    <label>EPA ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Generator_Status__c.field-meta.xml
<CustomField>
    <fullName>Generator_Status__c</fullName>
	<inlineHelpText>An account&apos;s generator status can only be upgraded from Salesforce. Downgrades in this area need to be coordinated by our compliance team. For status downgrades, please submit a Service Now ticket using category/subcategory: WIN-Aurora(FocalPoint), CWT-Compliance or WIN-Compliance, EPA ID Number.</inlineHelpText>
    <label>Generator Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Large Quantity Generator</fullName>
            </value>
            <value>
                <fullName>Small Quantity Generator</fullName>
            </value>
            <value>
                <fullName>Conditionally Exempt Sm Qty Generator</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
                <default>true</default>
                <label>Undetermined</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Segment__c.field-meta.xml
<CustomField>
    <fullName>Industry_Segment__c</fullName>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Base &amp; Blended Oils</fullName>
            </value>
            <value>
                <fullName>Brokers</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Ecommerce</fullName>
            </value>
            <value>
                <fullName>Education Services</fullName>
            </value>
            <value>
                <fullName>Engineering &amp; Consulting</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Insurance &amp; Real Estate</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Mining</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Paper &amp; Wood</fullName>
            </value>
            <value>
                <fullName>Pharmaceutical &amp; Biotechnology</fullName>
            </value>
            <value>
                <fullName>Refineries &amp; Oilsands</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Terminals &amp; Pipelines</fullName>
            </value>
            <value>
                <fullName>Transportation Services</fullName>
            </value>
            <value>
                <fullName>Utilities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <type>Picklist</type>
    <valueSet>
	    <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CH A Large &gt;200K</fullName>
            </value>
            <value>
                <fullName>CH C Assigned &gt;30K</fullName>
            </value>
            <value>
                <fullName>D &lt;30,000</fullName>
            </value>
            <value>
                <fullName>CH E Small &lt;30K</fullName>
            </value>
            <value>
                <fullName>CH B Medium &gt;100K</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Same_as_Corp_Address__c.field-meta.xml
<CustomField>
    <fullName>Same_as_Corp_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If True, Corporate Address will be copied to Billing Address</description>
    <label>Remit-to/Billing Address same as Corp</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Exemption_Type__c.field-meta.xml
<CustomField>
    <fullName>Tax_Exemption_Type__c</fullName>
    <label>Tax Exemption</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tax Exempt</fullName>
            </value>
            <value>
                <fullName>Non Exempt</fullName>
                <default>true</default> 
                <label>Non Exempt</label>
            </value>
            <value>
                <fullName>Direct Pay Permit</fullName>
                <isActive>false</isActive>
                <label>Direct Pay Permit</label>
            </value>
            <value>
                <fullName>Resale</fullName>
                <isActive>false</isActive>
                <label>Resale</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/WIN_ID__c.field-meta.xml
<CustomField>
    <fullName>WIN_ID__c</fullName>
    <externalId>true</externalId>
    <label>WIN ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ZIP_Master__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZIP Master</label>
    <referenceTo>ZIP_Master__c</referenceTo>
    <relationshipLabel>Accounts (ZIP Master)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>All Clean Harbors Customers</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Case/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>This field is used to store the Billing city while converting ShipTo/Gen to Customer account</description>
    <label>City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This field is used to store the Billing Country while converting ShipTo/Gen to Customer account</description>
    <label>Country</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>This field is used to store the Billing State while converting ShipTo/Gen to Customer account</description>
    <label>State</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/WIN_Id__c.field-meta.xml
<CustomField>
    <fullName>WIN_Id__c</fullName>
    <label>WIN Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Zip_Master__c.field-meta.xml
<CustomField>
    <fullName>Zip_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ZIP Master</description>
    <label>Single Postal Code</label>
    <referenceTo>ZIP_Master__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <formula>IF( ISBLANK( Locations__c ) ,   Account.ShippingCity   , Locations__r.Address__City__s)</formula>
    <label>Contact City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>TEXT(Locations__r.Address__CountryCode__s)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>IF( ISBLANK( Locations__c ),  Account.ShippingState  ,TEXT(Locations__r.Address__StateCode__s))</formula>
    <label>Contact State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WIN_ID__c.field-meta.xml
<CustomField>
    <fullName>WIN_ID__c</fullName>
    <formula>Account.WIN_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>WIN ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SIC_VALIDATION_SETTING__c/SIC_VALIDATION_SETTING__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS will consist of a flag which determines if SIC Validation on Account should be implemented or not.</description>
    <label>SIC VALIDATION SETTING</label>
</CustomObject>

force-app/main/default/objects/SIC_VALIDATION_SETTING__c/fields/SIC_VALIDATION_FLAG__c.field-meta.xml
<CustomField>
    <fullName>SIC_VALIDATION_FLAG__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag which determines if SIC Validation should be executed in the custom code or not. Should be Checked if SIC Validation is required.</description>
    <label>SIC_VALIDATION_FLAG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/ZIP_Master__c.object-meta.xml
<CustomObject>
    <label>ZIP Master</label>
    <nameField>
        <label>ZIP Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZIP Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZIP_Master__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Zip codes primary city</description>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>US States</description>
    <label>State</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/fields/ZIP__c.field-meta.xml
<CustomField>
    <fullName>ZIP__c</fullName>
    <label>ZIP</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestCompanySync.cls
@isTest
public class TestCompanySync {
    private final static string TEST_Shipping_PostalCode = '45204'; 
    private final static string TEST_Shipping_Country = 'US';
    private final static string TEST_Shipping_State = 'OH';
    private final static string TEST_Shipping_City = 'Cincinnati';
    private final static string TEST_Shipping_Street = 'Test Street'; 
    private final static string TEST_NAME = 'TestAccount';
    private final static string TEST_PHONE = '799856414';
    private final static string TEST_TYPE =  'Customer';
    private final static string TEST_BUSINESS_TYPE = 'Base'; 
    private final static string TEST_RANK = 'CH A Large >200K';
    private final static string TEST_INDUSTRY_SEGMENT = 'Chemical';
    private final static string TEST_CURRENCYISOCODE = 'USD';
    private final static string TEST_CS_EPA_ID = 'PENDING';
    private final static string TEST_GENERATOR_STATUS = 'Large Quantity Generator'; 
    private final static string TEST_CASE_TYPE = 'New';
    private final static Id accountUpdateValidationRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Account Update Validations').getRecordTypeId();
    private final static Id fieldChangeRequestRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Field Change Request').getRecordTypeId();
    private final static Id customerRecordTypeId = Schema.Sobjecttype.Account.getRecordTypeInfosByDeveloperName().get(CHConstants.ACCOUNT_RECORD_TYPE_CUSTOMER).getRecordTypeId();
 
    @testsetup 
    static void setup(){
        List<Account> accountsToInsert = new List<Account>(); 
        List<Contact> contactsToInsert = new List<Contact>();
        
        SIC_VALIDATION_SETTING__c svsObj = new SIC_VALIDATION_SETTING__c();
        svsObj.name = 'SIC_VALIDATION_SETTING';
        svsObj.SIC_VALIDATION_FLAG__c = true;
        insert svsObj;
        
        COUNTRY_CODES__c countrycodes1 = new COUNTRY_CODES__c();
        countrycodes1.Name = 'US';
        insert countrycodes1;
        
        List<ZIP_Master__c> zipMasterList = new List<ZIP_Master__c>();
            zipMasterList.add(new ZIP_Master__c(Zip__c = '45204',Country__c = 'US', State__c = 'OH',City__c = 'Cincinnati'));
        insert zipMasterList;   
        
        for(Integer i=0; i<2; i++){
        	Account accObj = new Account();
            accObj.Name =  TEST_NAME+i;
            accObj.Phone = TEST_PHONE;
            accObj.Type = TEST_TYPE;
            accObj.Business_Type__c = TEST_BUSINESS_TYPE;
            accObj.Rank__c = TEST_RANK;
            accObj.Same_as_Corp_Address__c =true;
            accObj.Tax_Exemption_Type__c = 'Non Exempt';
            accObj.WIN_ID__c = 'GIL21'+i;
            accObj.Industry_Segment__c = TEST_INDUSTRY_SEGMENT;
            accObj.CurrencyIsoCode = TEST_CURRENCYISOCODE;
            accObj.CS_EPA_ID__c =  TEST_CS_EPA_ID;
            accObj.Generator_Status__c = TEST_GENERATOR_STATUS;
            accObj.ShippingPostalCode = TEST_Shipping_PostalCode;	
            accObj.ShippingCountry = TEST_Shipping_Country;	
            accObj.ShippingState = TEST_Shipping_State;	
            accObj.ShippingCity = TEST_Shipping_City;	
            accObj.ShippingStreet = TEST_Shipping_Street;
            accObj.Industry_Segment__c = TEST_INDUSTRY_SEGMENT;
            accObj.recordtypeId = customerRecordTypeId;
            accountsToInsert.add(accObj);
        }
        insert accountsToInsert;       
        
        for(Integer i=0; i<2; i++){
            Contact con = new Contact();
            con.AccountId = accountsToInsert[i].id;
            con.LastName = 'Contact'+i;
            con.FirstName = 'Main'+i;
            con.Salutation = 'Mr';
            con.Title = 'Default Mgr';
            con.Email = 'Main'+i+'@default.com';
            con.Phone = '781-792-500'+i;
            con.Contact_Type__c = 'MAIN';
            contactsToInsert.add(con);
        }        
        insert contactsToInsert; 
      
        case parentCase = new case();
        parentCase.Type = TEST_CASE_TYPE;
        parentCase.Effective_Date__c = system.today();
        parentCase.Proposed_Owner_Case_Approver__c = UserInfo.getUserId();
        parentCase.Current_Owner_Case_Approver__c =UserInfo.getUserId();
        parentCase.AccountId = accountsToInsert[1].Id;
        parentCase.Status = 'New';
        parentCase.recordTypeId = accountUpdateValidationRecordTypeId;
        insert parentCase;

        case childCase = new case();
        childCase.Type = TEST_CASE_TYPE;
        childCase.Effective_Date__c = system.today();
        childCase.Proposed_Owner_Case_Approver__c = UserInfo.getUserId();
        childCase.Current_Owner_Case_Approver__c =UserInfo.getUserId();
        childCase.AccountId = accountsToInsert[1].Id;
        childCase.Account_Field_Changed__c = 'Name';
        childCase.Status ='Awaiting Manager Approval';
        childCase.ParentId = parentCase.id;
        childCase.recordTypeId = fieldChangeRequestRecordTypeId;
        childCase.Old_Value__c=TEST_NAME;
        childCase.New_Value__c = TEST_NAME+'TEst';
        insert childCase; 
    }
    
    @isTest
    private static void checkCompanyCaseCreationTest(){
        Test.startTest();        
            Account acc =[Select id,Name from Account where name = 'TestAccount0' and recordTypeid=:customerRecordTypeId limit 1];
            acc.name='TestCompany';
            update acc;
        Test.StopTest();
        List<Case> cases = [select id,casenumber from Case where Accountid = :acc.id];
        Assert.areEqual(cases!=null,true,'Case Is not created for company sync');
    } 
    
    @isTest
    private static void updateParentCaseStatusTest(){
        Test.startTest();
            Account acc =[Select id,Name from Account where name = 'TestAccount1' and recordtypeid =:customerRecordTypeId limit 1];
            Case casobjchild =[select id,casenumber,Old_value__c, Is_Submitted_for_Approval__c,Proposed_Owner_Case_Approver__c from case where accountid=:acc.id and RecordTypeId = : fieldChangeRequestRecordTypeId];
            system.debug('ChildCase' +casobjchild);
            casobjchild.Status = 'Closed - Rejected';
            casobjchild.Proposed_Owner_Case_Approver__c = UserInfo.getUserId();
            casobjchild.Old_value__c = 'TestAccount1';
            casobjchild.Is_Submitted_for_Approval__c = false;
            update casobjchild;
            Account accnew =[Select id,Name from Account where id= :acc.id limit 1];
            Assert.areEqual(accnew.NAme, casobjchild.Old_value__c,'Account Names didnt match for company sync');
        Test.stopTest();        
    }    
	
	@isTest
    private static void checkUpdateCaseWithdrwan(){
         Test.startTest();        
         User u = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Integration' LIMIT 1].Id,
            LastName = 'Integration User',
            FirstName='First',
            Email = 'TEST@safety-kleen.com',
            Username = 'integrationuser@safety-kleen.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            Primary_Business__c = 'Healthcare Services'
        );
        insert u;
        System.runAs(u) 
        {
        
         	Account acc =[Select id,Name from Account where name = 'TestAccount1' and recordtypeid=:customerRecordTypeId limit 1];
            acc.name='Testcomapny';
            acc.ShippingStreet='Test';
            update acc;
            Case casobjchild =[select id,casenumber,Old_value__c, Proposed_Owner_Case_Approver__c from case where accountid=:acc.id and RecordTypeId = : fieldChangeRequestRecordTypeId];
            casobjchild.Status = 'Closed- winbacksync';
            casobjchild.Proposed_Owner_Case_Approver__c = UserInfo.getUserId();
            update casobjchild;
           	// Assertions
            casobjchild = [SELECT Id, CaseNumber, Old_value__c, Status FROM Case WHERE Id = :casobjchild.Id];
            Assert.areEqual(true, casobjchild != null); 
            Test.stopTest();
    	}
    }
    
   	@isTest
    private static void testCompanyCaseCreation(){
        Test.startTest();
        
        Account acc =[Select id,Name from Account where name = 'TestAccount0' and recordTypeid=:customerRecordTypeId limit 1];
        acc.ShippingStreet='TestCompany';
        
        update acc;
        
        for(Case caseObj : [SELECT Id, Status, Account_Field_Changed__c FROM Case WHERE Parent.AccountId = :acc.Id]){
            System.assertEquals('Awaiting Manager Approval', caseObj.Status);
        }        
        AccountCRUDHandler.isAfterAccount = true;
        try{
         	acc.ShippingCity='TestCompany12';
          	acc.Win_Validate_New__c=false;
         	update acc;
        }catch(Exception excpetionObj){
            Boolean isContainsCaseException = excpetionObj.getMessage().contains(CHConstants.CASE_MESSAGE);
           	Assert.areEqual(true, isContainsCaseException);
        }        
        Test.StopTest();
    }    
}