force-app/main/default/objects/Account/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
                <default>true</default>
                <label>Base</label>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Locating</fullName>
            </value>
            <value>
                <fullName>Key</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry_Segment__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agricultural Production</fullName>
            </value>
            <value>
                <fullName>Agricultural Svcs</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Airports &amp; Aviation Svcs</fullName>
            </value>
            <value>
                <fullName>Asphalt, Terminal</fullName>
            </value>
            <value>
                <fullName>Auto Maintenance</fullName>
            </value>
            <value>
                <fullName>Auto Retail</fullName>
            </value>
            <value>
                <fullName>Biotechnology</fullName>
            </value>
            <value>
                <fullName>Brokers - Waste &amp; Environmental Svcs</fullName>
            </value>
            <value>
                <fullName>Building Materials (excl Lumber Mills)</fullName>
            </value>
            <value>
                <fullName>Business and Personal Services</fullName>
            </value>
            <value>
                <fullName>Chemical - Distributor</fullName>
            </value>
            <value>
                <fullName>Chemical Manufacturing</fullName>
            </value>
            <value>
                <fullName>Colleges &amp; Universities</fullName>
            </value>
            <value>
                <fullName>Construction, Gen Contractors &amp; Builders</fullName>
            </value>
            <value>
                <fullName>Corporate Real Estate</fullName>
            </value>
            <value>
                <fullName>Cruise Lines</fullName>
            </value>
            <value>
                <fullName>Dealerships - Auto</fullName>
            </value>
            <value>
                <fullName>Dealerships - Recreational &amp; Machinery</fullName>
            </value>
            <value>
                <fullName>Drill Rig Owners</fullName>
            </value>
            <value>
                <fullName>Dry Cleaners</fullName>
            </value>
            <value>
                <fullName>Ecommerce</fullName>
            </value>
            <value>
                <fullName>Emergency Response Management</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Civil/Heavy Construction</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Drilling</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Enviro Remediation</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Oilsands</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Seismic &amp; Production</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Utilities</fullName>
            </value>
            <value>
                <fullName>Entertainment and Recreation Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>The account&apos;s department or division gets stored in this field</description>
    <label>Division Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Segment__c.field-meta.xml
<CustomField>
    <fullName>Industry_Segment__c</fullName>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Base &amp; Blended Oils</fullName>
            </value>
            <value>
                <fullName>Brokers</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Ecommerce</fullName>
            </value>
            <value>
                <fullName>Education Services</fullName>
            </value>
            <value>
                <fullName>Engineering &amp; Consulting</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Insurance &amp; Real Estate</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Mining</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Paper &amp; Wood</fullName>
            </value>
            <value>
                <fullName>Pharmaceutical &amp; Biotechnology</fullName>
            </value>
            <value>
                <fullName>Refineries &amp; Oilsands</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Terminals &amp; Pipelines</fullName>
            </value>
            <value>
                <fullName>Transportation Services</fullName>
            </value>
            <value>
                <fullName>Utilities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <type>Picklist</type>
    <valueSet>
	    <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CH A Large &gt;200K</fullName>
            </value>
            <value>
                <fullName>CH C Assigned &gt;30K</fullName>
            </value>
            <value>
                <fullName>D &lt;30,000</fullName>
            </value>
            <value>
                <fullName>CH E Small &lt;30K</fullName>
            </value>
            <value>
                <fullName>CH B Medium &gt;100K</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Reporting_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Vertical__c</fullName>
    <label>Reporting Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Base Oil, Blender, Packager, or Marketer</fullName>
            </value>
            <value>
                <fullName>Brokers</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>Construction - Building Related Trades</fullName>
            </value>
            <value>
                <fullName>Corp RE</fullName>
            </value>
            <value>
                <fullName>Drill Rig Owner</fullName>
            </value>
            <value>
                <fullName>Education Services</fullName>
            </value>
            <value>
                <fullName>Engineering &amp; Consulting - Environmental</fullName>
            </value>
            <value>
                <fullName>Engineering &amp; Consulting - Heavy Construction</fullName>
            </value>
            <value>
                <fullName>Engineering and Consulting – Utilities</fullName>
            </value>
            <value>
                <fullName>Engineering, Consulting - Seismic</fullName>
            </value>
            <value>
                <fullName>General Manufacturing</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Mining, Primary Metals</fullName>
            </value>
            <value>
                <fullName>Oil, Gas Exploration</fullName>
            </value>
            <value>
                <fullName>Oil, Gas Production</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pharmaceutical &amp; Biotechnology</fullName>
            </value>
            <value>
                <fullName>Refineries &amp; Oilsands</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Terminals &amp; Pipelines</fullName>
            </value>
            <value>
                <fullName>Transportation Services</fullName>
            </value>
            <value>
                <fullName>Utilities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Risk_Category__c.field-meta.xml
<CustomField>
    <fullName>Risk_Category__c</fullName>
    <label>Risk Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corp Account</fullName>
            </value>
            <value>
                <fullName>Regional Account</fullName>
            </value>
            <value>
                <fullName>Branch Account</fullName>
            </value>
            <value>
                <fullName>Sensitive Account</fullName>
            </value>
            <value>
                <fullName>Oil</fullName>
            </value>
            <value>
                <fullName>3PC Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Skip_Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Skip_Duplicate_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <description>DO NOT DELETE THIS FIELD. This field is used to skip the duplicate check on Account created from New Location Flow. For skipping duplicate check for Integration flow, the Duplicate Rule takes care by looking at the profile as Integration and skips it.</description>
    <label>Skip Duplicate Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Broker.recordType-meta.xml
<RecordType>
    <fullName>Broker</fullName>
    <active>true</active>
    <description>All Clean Harbors Brokers</description>
    <label>Broker</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>All Clean Harbors Customers</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <description>All Clean Harbors Distributors</description>
    <label>Distributor</label>
</RecordType>

force-app/main/default/classes/NewLocationController.cls
/**
 * @description       : 
 * @author            : Irfan Khan
 * @group             : 
 * @last modified on  : 01-09-2023
 * @last modified by  : Irfan Khan
**/
public class NewLocationController {
	@AuraEnabled
    public static LocationWrapper redirectToNewLocation(String recordId) {
    	Account account = [
            select Id, RecordTypeId, RecordType.DeveloperName, Type, Name,
            Division__c, Business_Type__c, AccountSource, Reporting_Vertical__c,
            Industry_Segment__c, Class__c, Sic, Rank__c, Risk_Category__c,
            CurrencyISOCode, ShippingState, ShippingStreet, ShippingCountry, ShippingCity, ShippingPostalCode, 
            BillingState, BillingStreet, BillingCountry, BillingCity, BillingPostalCode
            from Account
            where Id =:recordId
            limit 1
        ];
		String accountType;
	    Id recordType;

        // for customer, create a new customer location type only
        if(CHConstants.ACCOUNT_RECORD_TYPE_CUSTOMER.equalsIgnoreCase(account.RecordType.DeveloperName)) {
            accountType = CHConstants.ACCOUNT_TYPE_SHIPTO_GEN;
            recordType = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get(
                CHConstants.ACCOUNT_RECORD_TYPE_CUSTOMER_LOCATION).getRecordTypeId();
        }
        
         if(CHConstants.ACCOUNT_RECORD_TYPE_CUSTOMER_Chain.equalsIgnoreCase(account.RecordType.DeveloperName)) {
            accountType = CHConstants.ACCOUNT_TYPE_SHIPTO_GEN;
            recordType = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get(
                CHConstants.ACCOUNT_RECORD_TYPE_CUSTOMER_LOCATION).getRecordTypeId();
        }
        
        // for broker, create a new broker location type only
        if(CHConstants.ACCOUNT_RECORD_TYPE_BROKER.equalsIgnoreCase(account.RecordType.DeveloperName)) {
            accountType = CHConstants.ACCOUNT_TYPE_BROK_GEN;
            recordType = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get(
                CHConstants.ACCOUNT_RECORD_TYPE_BROKER_LOCATION).getRecordTypeId();
        }

        // for distributor, create a new distributor location type only
        if(CHConstants.ACCOUNT_RECORD_TYPE_DISTRIBUTOR.equalsIgnoreCase(account.RecordType.DeveloperName)) {
            accountType = CHConstants.ACCOUNT_TYPE_DIST_GEN;
            recordType = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get(
                CHConstants.ACCOUNT_RECORD_TYPE_DISTRIBUTOR_LOCATION).getRecordTypeId();
        }

        Account newLocationAccount = 
            new Account(
                Name = account.Name,
                Skip_Duplicate_Check__c = true,
                Business_Type__c = account.Business_Type__c,
                AccountSource = account.AccountSource,
                Reporting_Vertical__c = account.Reporting_Vertical__c,
                Industry_Segment__c = account.Industry_Segment__c,
                Class__c = account.Class__c,
                Sic = account.Sic,
                ParentId = account.Id,
                RecordTypeId = recordType,
                Type = accountType,
            	Rank__c = account.Rank__c,
            	Risk_Category__c = account.Risk_Category__c,
                CurrencyISOCode = account.CurrencyIsoCode);

        LocationWrapper locWrap = new LocationWrapper();
        try {
            // we don't need validations during account creation, as the rep will still need
            // to edit the record after it was redirected to the location record
            AccountCRUDHandler.SKIP_VALIDATION = true;
            insert newLocationAccount;
            locWrap.isSuccess = true;
            locWrap.newLocationId = newLocationAccount.Id;
        } catch (Exception e) {
            locWrap.isSuccess = false;
            system.debug(LoggingLevel.ERROR, 'Error creating location account - ' + e.getStackTraceString());
            locWrap.errorMsg = Label.ERROR_CREATING_LOCATION + e.getMessage();
        }
       
        return locWrap;
    }
    
    public class LocationWrapper{
        @AuraEnabled public Boolean isSuccess;
        @AuraEnabled public String newLocationId;
        @AuraEnabled public String errorMsg;
    }
}