force-app/main/default/objects/Account/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
                <default>true</default>
                <label>Base</label>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Locating</fullName>
            </value>
            <value>
                <fullName>Key</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <type>Picklist</type>
    <valueSet>
	    <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CH A Large &gt;200K</fullName>
            </value>
            <value>
                <fullName>CH C Assigned &gt;30K</fullName>
            </value>
            <value>
                <fullName>D &lt;30,000</fullName>
            </value>
            <value>
                <fullName>CH E Small &lt;30K</fullName>
            </value>
            <value>
                <fullName>CH B Medium &gt;100K</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Skip_Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Skip_Duplicate_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <description>DO NOT DELETE THIS FIELD. This field is used to skip the duplicate check on Account created from New Location Flow. For skipping duplicate check for Integration flow, the Duplicate Rule takes care by looking at the profile as Integration and skips it.</description>
    <label>Skip Duplicate Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SIC_VALIDATION_SETTING__c/SIC_VALIDATION_SETTING__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS will consist of a flag which determines if SIC Validation on Account should be implemented or not.</description>
    <label>SIC VALIDATION SETTING</label>
</CustomObject>

force-app/main/default/objects/SIC_VALIDATION_SETTING__c/fields/SIC_VALIDATION_FLAG__c.field-meta.xml
<CustomField>
    <fullName>SIC_VALIDATION_FLAG__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag which determines if SIC Validation should be executed in the custom code or not. Should be Checked if SIC Validation is required.</description>
    <label>SIC_VALIDATION_FLAG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/NewLocationControllerTest.cls
@isTest
public class NewLocationControllerTest {
	@isTest
    public static void testAccountRedirection(){
        AccountCRUDHandler.SKIP_VALIDATION = true;
        SIC_VALIDATION_SETTING__c sicValidation = new SIC_VALIDATION_SETTING__c();
        sicValidation.Name = 'SIC_VALIDATION_SETTING';
        sicValidation.SIC_VALIDATION_FLAG__c = true;
        insert sicValidation;
        Account newLocationAccount = new Account(
                Name = 'Test',
                Skip_Duplicate_Check__c = true,
                Business_Type__c = 'Base',
                AccountSource = 'Import',
                Sic = '1000',
                RecordTypeId = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get(
                CHConstants.ACCOUNT_RECORD_TYPE_CUSTOMER).getRecordTypeId(),
            	Rank__c = 'CH E Small <30K',
                CurrencyISOCode = 'USD'
            );
        INSERT newLocationAccount;
        
        NewLocationController.redirectToNewLocation(newLocationAccount.Id);
        
        
        Account newLocationAccount2 = new Account(
                Name = 'Test',
                Skip_Duplicate_Check__c = true,
                Business_Type__c = 'Base',
                AccountSource = 'Import',
                Sic = '1000',
                RecordTypeId = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get(
                CHConstants.ACCOUNT_RECORD_TYPE_BROKER).getRecordTypeId(),
            	Rank__c = 'CH E Small <30K',
                CurrencyISOCode = 'USD'
            );
        INSERT newLocationAccount2;
        
        NewLocationController.redirectToNewLocation(newLocationAccount2.Id);
    }
}