force-app/main/default/objects/Account/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
                <default>true</default>
                <label>Base</label>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Locating</fullName>
            </value>
            <value>
                <fullName>Key</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <formula>ShippingCity</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CS_EPA_ID__c.field-meta.xml
<CustomField>
    <fullName>CS_EPA_ID__c</fullName>
    <inlineHelpText>The following fields are required in order to validate the EPA Id in addition to the EPA Id field. 
-Corporate Street 
-Corporate State 
-Corporate Country 
-Generator Status 
-Primary Service Provider</inlineHelpText>
    <label>EPA ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/dunbrdst__c.field-meta.xml
<CustomField>
    <fullName>dunbrdst__c</fullName>
    <description>dunbrdst from Beacon for Key Accounts</description>
    <externalId>true</externalId>
    <label>dunbrdst</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Segment__c.field-meta.xml
<CustomField>
    <fullName>Industry_Segment__c</fullName>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Base &amp; Blended Oils</fullName>
            </value>
            <value>
                <fullName>Brokers</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Ecommerce</fullName>
            </value>
            <value>
                <fullName>Education Services</fullName>
            </value>
            <value>
                <fullName>Engineering &amp; Consulting</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Insurance &amp; Real Estate</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Mining</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Paper &amp; Wood</fullName>
            </value>
            <value>
                <fullName>Pharmaceutical &amp; Biotechnology</fullName>
            </value>
            <value>
                <fullName>Refineries &amp; Oilsands</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Terminals &amp; Pipelines</fullName>
            </value>
            <value>
                <fullName>Transportation Services</fullName>
            </value>
            <value>
                <fullName>Utilities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/KAM_Manager__c.field-meta.xml
<CustomField>
    <fullName>KAM_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Key Account owner&apos;s manager.  Generally a VP.</description>
    <label>CAM Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <type>Picklist</type>
    <valueSet>
	    <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CH A Large &gt;200K</fullName>
            </value>
            <value>
                <fullName>CH C Assigned &gt;30K</fullName>
            </value>
            <value>
                <fullName>D &lt;30,000</fullName>
            </value>
            <value>
                <fullName>CH E Small &lt;30K</fullName>
            </value>
            <value>
                <fullName>CH B Medium &gt;100K</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Reporting_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Vertical__c</fullName>
    <label>Reporting Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Base Oil, Blender, Packager, or Marketer</fullName>
            </value>
            <value>
                <fullName>Brokers</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>Construction - Building Related Trades</fullName>
            </value>
            <value>
                <fullName>Corp RE</fullName>
            </value>
            <value>
                <fullName>Drill Rig Owner</fullName>
            </value>
            <value>
                <fullName>Education Services</fullName>
            </value>
            <value>
                <fullName>Engineering &amp; Consulting - Environmental</fullName>
            </value>
            <value>
                <fullName>Engineering &amp; Consulting - Heavy Construction</fullName>
            </value>
            <value>
                <fullName>Engineering and Consulting – Utilities</fullName>
            </value>
            <value>
                <fullName>Engineering, Consulting - Seismic</fullName>
            </value>
            <value>
                <fullName>General Manufacturing</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Mining, Primary Metals</fullName>
            </value>
            <value>
                <fullName>Oil, Gas Exploration</fullName>
            </value>
            <value>
                <fullName>Oil, Gas Production</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pharmaceutical &amp; Biotechnology</fullName>
            </value>
            <value>
                <fullName>Refineries &amp; Oilsands</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Terminals &amp; Pipelines</fullName>
            </value>
            <value>
                <fullName>Transportation Services</fullName>
            </value>
            <value>
                <fullName>Utilities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ZIP_Master__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZIP Master</label>
    <referenceTo>ZIP_Master__c</referenceTo>
    <relationshipLabel>Accounts (ZIP Master)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Corporate.recordType-meta.xml
<RecordType>
    <fullName>Corporate</fullName>
    <active>true</active>
    <description>All Clean Harbor Corporate Accounts</description>
    <label>Corporate</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>All Clean Harbors Customers</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Case/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>This field is used to store the Billing city while converting ShipTo/Gen to Customer account</description>
    <label>City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This field is used to store the Billing Country while converting ShipTo/Gen to Customer account</description>
    <label>Country</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>This field is used to store the Billing State while converting ShipTo/Gen to Customer account</description>
    <label>State</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Zip_Master__c.field-meta.xml
<CustomField>
    <fullName>Zip_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ZIP Master</description>
    <label>Single Postal Code</label>
    <referenceTo>ZIP_Master__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/CPG_Request.recordType-meta.xml
<RecordType>
    <fullName>CPG_Request</fullName>
    <active>true</active>
    <businessProcess>CPG Request</businessProcess>
    <label>CPG Request</label>
</RecordType>

force-app/main/default/objects/SIC_VALIDATION_SETTING__c/SIC_VALIDATION_SETTING__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS will consist of a flag which determines if SIC Validation on Account should be implemented or not.</description>
    <label>SIC VALIDATION SETTING</label>
</CustomObject>

force-app/main/default/objects/SIC_VALIDATION_SETTING__c/fields/SIC_VALIDATION_FLAG__c.field-meta.xml
<CustomField>
    <fullName>SIC_VALIDATION_FLAG__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag which determines if SIC Validation should be executed in the custom code or not. Should be Checked if SIC Validation is required.</description>
    <label>SIC_VALIDATION_FLAG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TERRITORY_MANAGEMENT__c/TERRITORY_MANAGEMENT__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS will consist of a flag which determines if Territory Management on Account should be implemented or not. If Yes, the Territory and Owner on Account are set based on the criteria.</description>
    <label>TERRITORY MANAGEMENT</label>
</CustomObject>

force-app/main/default/objects/TERRITORY_MANAGEMENT__c/fields/TM_FLAG__c.field-meta.xml
<CustomField>
    <fullName>TM_FLAG__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag which determines if TM should be executed in the custom code or not thus setting the Territory and the Account Owner field on the Account record. Should be Checked if TM is required.</description>
    <inlineHelpText>Flag which determines if TM should be executed in the custom code or not</inlineHelpText>
    <label>TM_FLAG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/ZIP_Master__c.object-meta.xml
<CustomObject>
    <label>ZIP Master</label>
    <nameField>
        <label>ZIP Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZIP Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZIP_Master__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Zip codes primary city</description>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>US States</description>
    <label>State</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/fields/ZIP__c.field-meta.xml
<CustomField>
    <fullName>ZIP__c</fullName>
    <label>ZIP</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestCPGCaseCreation.cls
/* 
* @author    Vikram Simha
* @createddate  07-08-2023   
*/   
@isTest
public class TestCPGCaseCreation {
    @testSetup
    private static void setup(){
        User userRec = new User(Id=UserInfo.getUserId(), EmployeeNumber='333');
        UPDATE userRec;
        TERRITORY_MANAGEMENT__c territoryMgmt = new TERRITORY_MANAGEMENT__c();
        territoryMgmt.Name = 'TERRITORY_MGMT_SETTING';
        territoryMgmt.TM_FLAG__c = true;
        insert territoryMgmt;
        COUNTRY_CODES__c countrycodes = new COUNTRY_CODES__c();
        countrycodes.Name = 'CA';
        insert countrycodes;
        
        COUNTRY_CODES__c countrycodes1 = new COUNTRY_CODES__c();
        countrycodes1.Name = 'US';
        insert countrycodes1;
        
        List<ZIP_Master__c> zipMasterList = new List<ZIP_Master__c>();
        for(Integer i = 0; i < 10; i++){
            zipMasterList.add(new ZIP_Master__c(Zip__c = '12345',Country__c = 'US', State__c = 'NY',City__c ='Ashburn'));
			zipMasterList.add(new ZIP_Master__c(Zip__c = '20147',Country__c = 'US', State__c = 'NY',City__c ='Ashburn'));
        }
        insert zipMasterList;
        SIC_VALIDATION_SETTING__c sicValidation = new SIC_VALIDATION_SETTING__c();
        sicValidation.Name = 'SIC_VALIDATION_SETTING';
        sicValidation.SIC_VALIDATION_FLAG__c = false;
        insert sicValidation;
        Id accRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        Id accCorporateRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Corporate').getRecordTypeId();
        Account corAcc = new Account(
            Name = 'Test ',       
            Business_Type__c = 'Base', 
            AccountSource = 'Phone',
            CS_EPA_ID__c = '12345', 
            Sic = '0111', 
            dunbrdst__c = '12345',
            ShippingCountry = 'US',
            ShippingState = 'NY',
        	ShippingStreet = 'Test Street',
       	    ShippingCity = 'Ashburn',
            ShippingPostalCode = '12345',
        	KAM_Manager__c = UserInfo.getUserId(),
            RecordTypeId = accCorporateRecTypeId,                               
            Rank__c = 'CH A Large >200K',
            Reporting_Vertical__c = 'Automotive',
            Industry_Segment__c = 'Automotive',
            Class__c = 'Agricultural Production',
            ownerId = UserInfo.getUserId(), 
            Primary_Service_Provider_New__c='SK ENV',
            KAM_Support__c = UserInfo.getUserId(),
            WIN_ID__c = 'DEL200',
            Buying_Decision__c = 'Central Buying'
        ); 
        insert corAcc; 
        Account acc = new Account(
            Name = 'Test1',       
            Business_Type__c = 'Base', 
            AccountSource = 'Phone',
            CS_EPA_ID__c = '12345', 
            Sic = '0111', 
            RecordTypeId = accRecTypeId,                               
            Rank__c = 'CH A Large >200K',
            Reporting_Vertical__c = 'Automotive',
            Industry_Segment__c = 'Automotive',
            Class__c = 'Agricultural Production',
            ownerId = UserInfo.getUserId(), 
            Primary_Service_Provider__c='Safety Kleen',
            WIN_ID__c = 'DEL201',
            ParentId = corAcc.Id
        ); 
        insert acc;
    }
    @isTest
    public static void testCreateNewCaseUpdate(){
        
        Test.startTest();
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', EmployeeNumber='108182', UserName='standarduser@testorg.com', isActive = TRUE);
        Id accRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        List<Account> accounts = [Select Id,name from Account where Win_Id__c ='DEL201'];
        List<User> users =[select id,name from user where isActive = True and EmployeeNumber!=null];
        List<case> lstcase=new List<Case>();
        case newcase = new case ();
        Id CPGCaseRecordType = Schema.Sobjecttype.Case.getRecordTypeInfosByDeveloperName().get('CPG_Request').getRecordTypeId();
        newcase.Subject = 'CPG Case';
        newCase.AccountId = accounts[0].id;
        newCase.Profile_Number__c = '45687';
        newCase.RecordTypeId = CPGCaseRecordType;
        newCase.Waste_Description__c = 'Test Description';
        newCase.CPG_Owner__c = users[0].Id;
        newCase.Incomplete_Profile_Comments__c = 'Test Profile Instructions.';
        insert newcase;
        List<Case> cases =[ SELECT Id, casenumber,Profile_Number__c, 
                           ACCOUNT.WIN_ID__c,RecordType.Name,status FROM case 
                           where Id=:newcase.Id Limit 1];
        try{
            CPGCaseCreation.CaseRequestWrapper cWrapper = new CPGCaseCreation.CaseRequestWrapper();
            cWrapper.GeneratorCode ='DEL201';
            cWrapper.CPGOwnerID ='108182';
            cWrapper.ApprovalStatus='I';
            cWrapper.CurrentProfileDescription = 'Test Update';
            cWrapper.Profile = '45687';
            cWrapper.ProfileInstructions = 'Test Instructions';
            CPGCaseCreation.createnewcase(cWrapper);
            Case cs = [SELECT Id,Status FROM Case where Id = :newcase.Id];
        }
        catch (Exception e){}
        
        Test.stopTest();
    }
    @isTest
    public static void testCreateNewCaseInsert(){
        
        Test.startTest();
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', EmployeeNumber='108182', UserName='standarduser@testorg.com', isActive = TRUE);
        Id accRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        List<Account> accounts = [Select Id,name from Account where Win_Id__c ='DEL201'];
        List<User> users =[select id,name from user where isActive = True and EmployeeNumber!=null];
        List<case> lstcase=new List<Case>();
        case newcase = new case ();
        Id CPGCaseRecordType = Schema.Sobjecttype.Case.getRecordTypeInfosByDeveloperName().get('CPG_Request').getRecordTypeId();
        newcase.Subject = 'CPG Case';
        newCase.AccountId = accounts[0].id;
        newCase.Profile_Number__c = '45687';
        newCase.RecordTypeId = CPGCaseRecordType;
        newCase.Waste_Description__c = 'Test Description';
        newCase.CPG_Owner__c = users[0].Id;
		newCase.OwnerId = users[0].Id;
        newCase.Incomplete_Profile_Comments__c = 'Test Profile Instructions.';
        insert newcase;
        List<Case> cases =[ SELECT Id, casenumber,Profile_Number__c, 
                           ACCOUNT.WIN_ID__c,RecordType.Name,status FROM case 
                           where Id=:newcase.Id Limit 1];
        try{
            CPGCaseCreation.CaseRequestWrapper cWrapper = new CPGCaseCreation.CaseRequestWrapper();
            cWrapper.GeneratorCode ='DEL201';
            cWrapper.CPGOwnerID ='108182';
            cWrapper.ApprovalStatus='I';
            cWrapper.CurrentProfileDescription = 'Test Update';
            cWrapper.Profile = '4568';
            cWrapper.ProfileInstructions = 'Test Instructions';
            CPGCaseCreation.createnewcase(cWrapper);
            Case cs = [SELECT Id,Status FROM Case where Id = :newcase.Id];
        }
        catch (Exception e){}
        
        Test.stopTest();
    }
    @isTest
    public static void testCreateNewCaseUpdate1(){
        
        Test.startTest();
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', EmployeeNumber='108182', UserName='standarduser@testorg.com', isActive = TRUE);
        Id accRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        List<Account> accounts = [Select Id,name from Account where Win_Id__c ='DEL201'];
        List<User> users =[select id,name from user where isActive = True and EmployeeNumber!=null];
        List<case> lstcase=new List<Case>();
        case newcase = new case ();
        Id CPGCaseRecordType = Schema.Sobjecttype.Case.getRecordTypeInfosByDeveloperName().get('CPG_Request').getRecordTypeId();
        newcase.Subject = 'CPG Case';
        newCase.AccountId = accounts[0].id;
        newCase.Profile_Number__c = '45687';
        newCase.RecordTypeId = CPGCaseRecordType;
        newCase.Waste_Description__c = 'Test Description';
        newCase.CPG_Owner__c = users[0].Id;
        newCase.Incomplete_Profile_Comments__c = 'Test Profile Instructions.';
        insert newcase;
        List<Case> cases =[ SELECT Id, casenumber,Profile_Number__c, 
                           ACCOUNT.WIN_ID__c,RecordType.Name,status FROM case 
                           where Id=:newcase.Id Limit 1];
        try{
            CPGCaseCreation.CaseRequestWrapper cWrapper = new CPGCaseCreation.CaseRequestWrapper();
            cWrapper.GeneratorCode ='DEL201';
            cWrapper.CPGOwnerID ='108182';
            cWrapper.ApprovalStatus='A';
            cWrapper.CurrentProfileDescription = 'Test Update';
            cWrapper.Profile = '45687';
            cWrapper.ProfileInstructions = 'Test Instructions';
            CPGCaseCreation.createnewcase(cWrapper);
            Case cs = [SELECT Id,Status FROM Case where Id = :newcase.Id];
        }
        catch (Exception e){}
        
        Test.stopTest();
    }
    @isTest
    public static void testCreateNewCaseError(){
        
        Test.startTest();
        try{
            CPGCaseCreation.CaseRequestWrapper cWrapper = new CPGCaseCreation.CaseRequestWrapper();
            CPGCaseCreation.createnewcase(cWrapper);
        }
        catch (Exception e){}
        
        Test.stopTest();
    }
    
}