force-app/main/default/objects/Account/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
                <default>true</default>
                <label>Base</label>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Locating</fullName>
            </value>
            <value>
                <fullName>Key</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CS_EPA_ID__c.field-meta.xml
<CustomField>
    <fullName>CS_EPA_ID__c</fullName>
    <inlineHelpText>The following fields are required in order to validate the EPA Id in addition to the EPA Id field. 
-Corporate Street 
-Corporate State 
-Corporate Country 
-Generator Status 
-Primary Service Provider</inlineHelpText>
    <label>EPA ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/dunbrdst__c.field-meta.xml
<CustomField>
    <fullName>dunbrdst__c</fullName>
    <description>dunbrdst from Beacon for Key Accounts</description>
    <externalId>true</externalId>
    <label>dunbrdst</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/KAM_Manager__c.field-meta.xml
<CustomField>
    <fullName>KAM_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Key Account owner&apos;s manager.  Generally a VP.</description>
    <label>CAM Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <type>Picklist</type>
    <valueSet>
	    <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CH A Large &gt;200K</fullName>
            </value>
            <value>
                <fullName>CH C Assigned &gt;30K</fullName>
            </value>
            <value>
                <fullName>D &lt;30,000</fullName>
            </value>
            <value>
                <fullName>CH E Small &lt;30K</fullName>
            </value>
            <value>
                <fullName>CH B Medium &gt;100K</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Sales_Business_Unit__c</fullName>
    <description>Sales business unit (temporary field - do not use)</description>
    <label>Sales Business Unit</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ZIP_Master__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZIP Master</label>
    <referenceTo>ZIP_Master__c</referenceTo>
    <relationshipLabel>Accounts (ZIP Master)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Corporate.recordType-meta.xml
<RecordType>
    <fullName>Corporate</fullName>
    <active>true</active>
    <description>All Clean Harbor Corporate Accounts</description>
    <label>Corporate</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>All Clean Harbors Customers</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Branch_Queue_Map__c/Branch_Queue_Map__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used for Branch Queue Mapping</description>
    <label>Branch Queue Map</label>
</CustomObject>

force-app/main/default/objects/Branch_Queue_Map__c/fields/Branch_Queue__c.field-meta.xml
<CustomField>
    <fullName>Branch_Queue__c</fullName>
    <description>Queue name of a Branch</description>
    <label>Branch Queue</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Bypass_Account_Validation__c/Bypass_Account_Validation__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bypass Account Validation</label>
</CustomObject>

force-app/main/default/objects/Bypass_Account_Validation__c/fields/Bypass_Manifest_Address_Requirement__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Manifest_Address_Requirement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Manifest Address Requirement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This field is used to store the Billing Country while converting ShipTo/Gen to Customer account</description>
    <label>Country</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>This field is used to store the Billing State while converting ShipTo/Gen to Customer account</description>
    <label>State</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Zip_Master__c.field-meta.xml
<CustomField>
    <fullName>Zip_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ZIP Master</description>
    <label>Single Postal Code</label>
    <referenceTo>ZIP_Master__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>TEXT(Locations__r.Address__CountryCode__s)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>IF( ISBLANK( Locations__c ),  Account.ShippingState  ,TEXT(Locations__r.Address__StateCode__s))</formula>
    <label>Contact State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SIC_VALIDATION_SETTING__c/SIC_VALIDATION_SETTING__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS will consist of a flag which determines if SIC Validation on Account should be implemented or not.</description>
    <label>SIC VALIDATION SETTING</label>
</CustomObject>

force-app/main/default/objects/SIC_VALIDATION_SETTING__c/fields/SIC_VALIDATION_FLAG__c.field-meta.xml
<CustomField>
    <fullName>SIC_VALIDATION_FLAG__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag which determines if SIC Validation should be executed in the custom code or not. Should be Checked if SIC Validation is required.</description>
    <label>SIC_VALIDATION_FLAG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TERRITORY_MANAGEMENT__c/TERRITORY_MANAGEMENT__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS will consist of a flag which determines if Territory Management on Account should be implemented or not. If Yes, the Territory and Owner on Account are set based on the criteria.</description>
    <label>TERRITORY MANAGEMENT</label>
</CustomObject>

force-app/main/default/objects/TERRITORY_MANAGEMENT__c/fields/TM_FLAG__c.field-meta.xml
<CustomField>
    <fullName>TM_FLAG__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag which determines if TM should be executed in the custom code or not thus setting the Territory and the Account Owner field on the Account record. Should be Checked if TM is required.</description>
    <inlineHelpText>Flag which determines if TM should be executed in the custom code or not</inlineHelpText>
    <label>TM_FLAG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Territory_Master__c/Territory_Master__c.object-meta.xml
<CustomObject>
    <description>Contains all Territory Information viz., SBU, Territory Name, Territory Owner, etc. based on the ZIP Codes.</description>
    <label>Territory Master</label>
    <nameField>
        <label>Territory Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Master</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Master__c/fields/Sales_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Sales_Business_Unit__c</fullName>
    <label>Primary Service Provider</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BPS</fullName>
            </value>
            <value>
                <fullName>CYN</fullName>
            </value>
            <value>
                <fullName>Daylighting Services</fullName>
            </value>
            <value>
                <fullName>DFW</fullName>
            </value>
            <value>
                <fullName>Emerald Services</fullName>
            </value>
            <value>
                <fullName>Field Services</fullName>
            </value>
            <value>
                <fullName>H2O</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Industrial Services</fullName>
            </value>
            <value>
                <fullName>Lodging</fullName>
            </value>
            <value>
                <fullName>Murphys Oil</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Seismic</fullName>
            </value>
            <value>
                <fullName>Safety-Kleen</fullName>
                <label>SK ENV</label>
            </value>
            <value>
                <fullName>SK KPP</fullName>
            </value>
            <value>
                <fullName>Surface Rentals</fullName>
            </value>
            <value>
                <fullName>Synergy</fullName>
            </value>
            <value>
                <fullName>Technical Services</fullName>
            </value>
            <value>
                <fullName>Thermo Fluids</fullName>
            </value>
			<value>
                <fullName>Thompson</fullName>
            </value>
			<value>
                <fullName>Noble Oil</fullName>
            </value>
            <value>
                <fullName>HEPACO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory_Master__c/fields/ZIP_Master__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Master__c</fullName>
    <label>ZIP Master</label>
    <referenceTo>ZIP_Master__c</referenceTo>
    <relationshipLabel>Territory Master</relationshipLabel>
    <relationshipName>Territory_Master</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/ZIP_Master__c.object-meta.xml
<CustomObject>
    <label>ZIP Master</label>
    <nameField>
        <label>ZIP Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZIP Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZIP_Master__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>US States</description>
    <label>State</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/fields/ZIP__c.field-meta.xml
<CustomField>
    <fullName>ZIP__c</fullName>
    <label>ZIP</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RestCreateCase_Test.cls
@isTest
public class RestCreateCase_Test {
    private final static string TEST_CURRENCYISOCODE = 'USD';
    private final static string TEST_ZIP = '45204';
    private final static string TEST_Shipping_PostalCode = '45204'; 
    private final static string TEST_Shipping_Country = 'US';
    private final static string TEST_Shipping_State = 'OR';     
    @testSetup 
    private static void setup(){
        Bypass_Account_Validation__c accountValidation = new Bypass_Account_Validation__c();
        accountValidation.Bypass_Manifest_Address_Requirement__c = false;
        INSERT accountValidation;
		
		Group testGroup = new Group(Name='queue', Type='Queue');
        insert testGroup;
        
        Group testGroup1 = new Group(Name='squeue', Type='Queue');
        insert testGroup1;
		
		System.runAs(new User(Id=UserInfo.getUserId())){
            List<QueueSobject> qs = new List<QueueSobject>();
            
            qs.add(new QueueSobject (
                SobjectType='Case',
                QueueId = testGroup1.Id
            ));
            
            Database.insert( qs );
			GroupMember queMem = new GroupMember();
            queMem.GroupId = testGroup1.Id;
            queMem.UserOrGroupId = UserInfo.getUserId();
            INSERT queMem;
        }
        
        Branch_Queue_Map__c branchQueueMap = new Branch_Queue_Map__c();
        branchQueueMap.Name = 'AA123';
		branchQueueMap.Branch_Queue__c = 'queue';
        INSERT branchQueueMap;
		
		Branch_Queue_Map__c branchQueueMap1 = new Branch_Queue_Map__c();
        branchQueueMap1.Name = 'S123';
        branchQueueMap1.Branch_Queue__c = 'squeue';
        INSERT branchQueueMap1;
        
        COUNTRY_CODES__c countrycodes = new COUNTRY_CODES__c();	
        countrycodes.Name = 'CA';	
        insert countrycodes;	
        
        COUNTRY_CODES__c countrycodes1 = new COUNTRY_CODES__c();	
        countrycodes1.Name = 'US';	
        insert countrycodes1;	
        
        ZIP_Master__c zpObj = new ZIP_Master__c();	
        zpObj.zip__c = TEST_ZIP;	
        zpObj.CurrencyIsoCode = TEST_CURRENCYISOCODE;	
        zpObj.Country__c = TEST_Shipping_Country;	
        zpObj.State__c = TEST_Shipping_State;	
        insert zpObj;	
        
        Territory_Master__c tmObj = new Territory_Master__c();	
        tmObj.name = 'Test TM';	
        tmObj.ZIP_Master__c = zpObj.id;	
        tmObj.CurrencyIsoCode = TEST_CURRENCYISOCODE;	
        tmObj.Sales_business_unit__C = 'lodging';       	
        insert tmObj;
        
        
        TERRITORY_MANAGEMENT__c territoryMgmt = new TERRITORY_MANAGEMENT__c();
        territoryMgmt.Name = 'TERRITORY_MGMT_SETTING';
        territoryMgmt.TM_FLAG__c = true;
        insert territoryMgmt;
        
        SIC_VALIDATION_SETTING__c sicValidation = new SIC_VALIDATION_SETTING__c();
        sicValidation.Name = 'SIC_VALIDATION_SETTING';
        sicValidation.SIC_VALIDATION_FLAG__c = false;
        insert sicValidation;
        Id accRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        Id accCorporateRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Corporate').getRecordTypeId();
        Test.startTest();
        Account corAcc = new Account(
            Name = 'Test ',       
            Business_Type__c = 'Base', 
            AccountSource = 'Phone',
            CS_EPA_ID__c = '12345', 
            ShippingCountry = TEST_Shipping_Country,
            ShippingState = TEST_Shipping_State,
        	ShippingStreet = 'Test Street',
       	    ShippingCity = 'Ashburn',
            ShippingPostalCode = TEST_ZIP,
            Sic = '0111', 
            dunbrdst__c = '12345',
        	KAM_Manager__c = UserInfo.getUserId(),
            RecordTypeId = accCorporateRecTypeId,                               
            Rank__c = 'CH A Large >200K',
            Reporting_Vertical__c = 'Automotive',
            Industry_Segment__c = 'Automotive',
            Class__c = 'Agricultural Production',
            ownerId = UserInfo.getUserId(), 
            Tax_Exemption_Type__c = 'Non Exempt',
            Primary_Service_Provider_New__c='SK ENV',
            KAM_Support__c = UserInfo.getUserId(),
            Buying_Decision__c = 'Central Buying'
        ); 
        
        INSERT corAcc; 
        
        
        Account acc = new Account(
            Name = 'Test ',       
            Business_Type__c = 'Base', 
            AccountSource = 'Phone',
            CS_EPA_ID__c = '12345', 
            Sic = '0111', 
            ShippingPostalCode = '45204',
            ShippingCountry = 'US',
            ShippingState = 'OR',
            ShippingStreet= 'Test Street',
            ShippingCity= 'Brookings',
            BillingPostalCode = '45204',
            BillingCountry = 'US',
            BillingState = 'OR',
            BillingStreet= 'Test Street',
            BillingCity = 'Brookings',
            RecordTypeId = accRecTypeId, 
            Tax_Exemption_Type__c = 'Non Exempt',
            Rank__c = 'CH A Large >200K',
            Reporting_Vertical__c = 'Automotive',
            Industry_Segment__c = 'Automotive',
            Class__c = 'Agricultural Production',
            ownerId = UserInfo.getUserId(), 
            Primary_Service_Provider_New__c='SK ENV',
            WIN_ID__c = '1234',
            ParentId = corAcc.Id
        ); 
        
        insert acc;
        
        Account acc1 = new Account(
            Name = 'Test ',       
            Business_Type__c = 'Base', 
            AccountSource = 'Phone',
            CS_EPA_ID__c = '12345', 
            Sic = '0111', 
            ShippingPostalCode = '45204',
            ShippingCountry = 'US',
            ShippingState = 'OR',
            ShippingStreet= 'Test Street',
            ShippingCity= 'Brookings',
            BillingPostalCode = '45204',
            BillingCountry = 'US',
            BillingState = 'OR',
            BillingStreet= 'Test Street',
            BillingCity = 'Brookings',
            Tax_Exemption_Type__c = 'Non Exempt',
            RecordTypeId = accRecTypeId,                               
            Rank__c = 'CH A Large >200K',
            Reporting_Vertical__c = 'Automotive',
            Industry_Segment__c = 'Automotive',
            Class__c = 'Agricultural Production',
            ownerId = UserInfo.getUserId(), 
            Primary_Service_Provider_New__c='SK ENV',
            Primary_Service_Provider__c='Safety Kleen',
            WIN_ID__c = '333'
        ); 
        
        insert acc1;
        
        Contact con = new Contact(AccountId = acc1.id);
        con.LastName = 'Contact';
        con.FirstName = 'Main';
        con.Salutation = 'Mr';
        con.Title = 'Default Mgr';
        con.Email = 'Main@default.com';
        con.Phone = '781-792-5000';
        con.Contact_Type__c = 'MAIN';
        insert con;
        Test.stopTest();
    }
    
    @isTest
    private static void createNewCaseTestNSB(){
        
        RestCreateCase.RquestWrapper reqObj = new RestCreateCase.RquestWrapper();
        reqObj.SOURCE_APP = CHConstants.INTEGRATION_SOURCE_APP_NSB;
        reqObj.CUST_ID = '1234';
        reqObj.DESCRIPTION = 'This is a description';
        reqObj.INVOICE_NUM = '1234';
        reqObj.INVOICE_VAL = '33';
        reqObj.SALESORDER_NUM = '1234';
        reqObj.BRANCH_CODE = 'AA123';
        reqObj.CASE_TYPE = CHConstants.CASE_TYPE_SERVICE;
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CreateCase/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.ValueOf(JSON.serialize(reqObj));
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        RestCreateCase.createnewcase();
        Test.stopTest();
        
        List<Case> caseLst = [SELECT Id from Case];
        System.assertEquals(caseLst.size(), 1);
    }
    
    @isTest
    private static void createNewCaseTestNSBCHES(){
        RestCreateCase.RquestWrapper reqObj = new RestCreateCase.RquestWrapper();
        reqObj.SOURCE_APP = CHConstants.INTEGRATION_SOURCE_APP_NSB;
        reqObj.CUST_ID = '1234';
        reqObj.DESCRIPTION = 'This is a description';
        reqObj.INVOICE_NUM = '1234';
        reqObj.INVOICE_VAL = '33';
        reqObj.SALESORDER_NUM = '1234';
        reqObj.BRANCH_CODE = 'AA123';
        reqObj.CASE_TYPE = CHConstants.CASE_TYPE_SERVICE;
        reqObj.USER_ID = [SELECT Id, Alias FROM User WHERE Id = :UserInfo.getUserId()][0].Alias;
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CreateCase/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.ValueOf(JSON.serialize(reqObj));
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        RestCreateCase.createnewcase();
        Test.stopTest();
        
        List<Case> caseLst = [SELECT Id from Case];
        System.assertEquals(caseLst.size(), 1);
    }
    
    private static testmethod void createNewCaseTestCOWB(){
        
        RestCreateCase.RquestWrapper reqObj = new RestCreateCase.RquestWrapper();
        reqObj.SOURCE_APP = CHConstants.INTEGRATION_SOURCE_APP_COWB;
        reqObj.CUST_ID = '1234';
        reqObj.DESCRIPTION = 'This is a description';
        reqObj.INVOICE_NUM = '1234';
        reqObj.INVOICE_VAL = '33';
        reqObj.SALESORDER_NUM = '1234';
        reqObj.BRANCH_CODE = 'AA123';
        reqObj.CASE_TYPE = 'NOPO';
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CreateCase/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.ValueOf(JSON.serialize(reqObj));
        RestContext.request = req;
        RestContext.response = res;
        RestCreateCase.createnewcase();
        
        List<Case> caseLst = [SELECT Id from Case];
        System.assertEquals(caseLst.size(), 1);
    }
    
    private static testmethod void createNewCaseTestInvDel(){
        
        Account accRec = [
            SELECT Id 
            FROM Account
            WHERE RecordType.Name = 'Corporate'
        ];
        
        accRec.KAM_Support__c = UserInfo.getUserId();
        UPDATE accRec;
        
        RestCreateCase.RquestWrapper reqObj = new RestCreateCase.RquestWrapper();
        reqObj.SOURCE_APP = CHConstants.INTEGRATION_SOURCE_APP_INV_DEL;
        reqObj.CUST_ID = '1234';
        reqObj.DESCRIPTION = 'This is a description';
        reqObj.INVOICE_NUM = '1234';
        reqObj.INVOICE_VAL = '33';
        reqObj.SALESORDER_NUM = '1234';
        reqObj.BRANCH_CODE = 'AA123';
        reqObj.CASE_TYPE = 'NOPO';
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CreateCase/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.ValueOf(JSON.serialize(reqObj));
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        RestCreateCase.createnewcase();
        Test.stopTest();
        
        List<Case> caseLst = [SELECT Id from Case];
        System.assertEquals(caseLst.size(), 1);
    }
    
    private static testmethod void createCaseUnitTestSafetyCleanNSB(){
        Account accRec = [
            SELECT Id 
            FROM Account
            WHERE WIN_ID__c = '333'
        ];
        
        accRec.KAM_Support__c = NULL;
        accRec.Buying_Decision__c = 'Locally Managed';
        UPDATE accRec;
        
        RestCreateCase.RquestWrapper reqObj = new RestCreateCase.RquestWrapper();
        reqObj.SOURCE_APP = CHConstants.INTEGRATION_SOURCE_APP_NSB;
        reqObj.CUST_ID = '333';
        reqObj.DESCRIPTION = 'This is a description';
        reqObj.INVOICE_NUM = '1234';
        reqObj.INVOICE_VAL = '33';
        reqObj.SALESORDER_NUM = '1234';
        reqObj.BRANCH_CODE = 'AA123';
        reqObj.CASE_TYPE = 'NOPO';
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CreateCase/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.ValueOf(JSON.serialize(reqObj));
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        RestCreateCase.createnewcase();
        Test.stopTest();
        
        List<Case> caseLst = [SELECT Id from Case];
        System.assertEquals(caseLst.size(), 1);
    }
    
    private static testmethod void createCaseUnitTestSafetyCleanCOWB(){
        Account accRec = [
            SELECT Id 
            FROM Account
            WHERE WIN_ID__c = '333'
        ];
        
        accRec.KAM_Support__c = NULL;
        accRec.Buying_Decision__c = 'Locally Managed';
        UPDATE accRec;
        
        RestCreateCase.RquestWrapper reqObj = new RestCreateCase.RquestWrapper();
        reqObj.SOURCE_APP = CHConstants.INTEGRATION_SOURCE_APP_COWB;
        reqObj.CUST_ID = '333';
        reqObj.DESCRIPTION = 'This is a description';
        reqObj.INVOICE_NUM = '1234'; 
        reqObj.INVOICE_VAL = '33';
        reqObj.SALESORDER_NUM = '1234';
        reqObj.BRANCH_CODE = 'AA123';
        reqObj.CASE_TYPE = 'NOPO';
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CreateCase/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.ValueOf(JSON.serialize(reqObj));
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        RestCreateCase.createnewcase();
        Test.stopTest();
        
        List<Case> caseLst = [SELECT Id from Case];
        System.assertEquals(caseLst.size(), 1);
    }
    private static testmethod void createCaseUnitTestSafetyCleanNSB1(){
        Account accRec = [
            SELECT Id 
            FROM Account
            WHERE WIN_ID__c = '333'
        ];
        
        accRec.KAM_Support__c = NULL;
        accRec.Buying_Decision__c = 'Central Buying';
        accRec.Primary_Service_Provider__c = 'Clean Harbors';
        UPDATE accRec;
        
        RestCreateCase.RquestWrapper reqObj = new RestCreateCase.RquestWrapper();
        reqObj.SOURCE_APP = CHConstants.INTEGRATION_SOURCE_APP_NSB;
        reqObj.CUST_ID = '333';
        reqObj.DESCRIPTION = 'This is a description';
        reqObj.INVOICE_NUM = '1234';
        reqObj.INVOICE_VAL = '33';
        reqObj.SALESORDER_NUM = '1234';
        reqObj.BRANCH_CODE = 'AA123';
        reqObj.CASE_TYPE = 'NOPO';
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CreateCase/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.ValueOf(JSON.serialize(reqObj));
        RestContext.request = req;
        RestContext.response = res;
        RestCreateCase.createnewcase();
        
        List<Case> caseLst = [SELECT Id from Case];
        System.assertEquals(caseLst.size(), 1);
    }
	
	
	 private static testmethod void createCaseUnitPO(){
        Account accRec = [
            SELECT Id 
            FROM Account
            WHERE WIN_ID__c = '333'
        ];
        Test.startTest();
        accRec.KAM_Support__c = NULL;
        accRec.Buying_Decision__c = 'Central Buying';
       // accRec.Primary_Service_Provider__c = 'Clean Harbors';
        UPDATE accRec;
        
        RestCreateCase.RquestWrapper reqObj = new RestCreateCase.RquestWrapper();
        reqObj.SOURCE_APP = CHConstants.INTEGRATION_SOURCE_APP_COWB;
        reqObj.CUST_ID = '333';
        reqObj.DESCRIPTION = 'This is a description';
        reqObj.INVOICE_NUM = '1234';
        reqObj.INVOICE_VAL = '33';
        reqObj.SALESORDER_NUM = '1234';
        reqObj.BRANCH_CODE = 'AA123';
        reqObj.PO_TIMING = CHConstants.PO_TIMING;
        reqObj.CASE_TYPE = CHConstants.CASE_TYPE_SERVICE;
        reqObj.SERVICING_BRANCH = 'S123';
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CreateCase/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.ValueOf(JSON.serialize(reqObj));
        RestContext.request = req;
        RestContext.response = res;
        RestCreateCase.createnewcase();
        Test.stopTest();
	    List<Case> caseLst = [SELECT Id from Case];
        System.assertEquals(caseLst.size(), 1);
    }
    
    private static testmethod void createCaseExceptionHandling(){
        Account accRec = [
            SELECT Id 
            FROM Account
            WHERE WIN_ID__c = '333'
        ];
        
        accRec.KAM_Support__c = NULL;
        accRec.Buying_Decision__c = 'Locally Managed';
        UPDATE accRec;
        
        RestCreateCase.RquestWrapper reqObj = new RestCreateCase.RquestWrapper();
        reqObj.SOURCE_APP = CHConstants.INTEGRATION_SOURCE_APP_NSB;
        reqObj.CUST_ID = '333';
        reqObj.DESCRIPTION = 'This is a description';
        reqObj.INVOICE_NUM = '1234';
        reqObj.INVOICE_VAL = '33';
        reqObj.SALESORDER_NUM = '1234';
        reqObj.BRANCH_CODE = 'AA123';
        reqObj.CASE_TYPE = 'NOPO';
        reqObj.GENERATOR_CODE = '551';
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CreateCase/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.ValueOf(JSON.serialize(reqObj));
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        RestCreateCase.createnewcase();
        Test.stopTest();
		List<Exception_Log__c> excepLst = [SELECT Id from Exception_Log__c];
        System.assertEquals(excepLst.size(), 1);
    }
}