force-app/main/default/objects/Account/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
                <default>true</default>
                <label>Base</label>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Locating</fullName>
            </value>
            <value>
                <fullName>Key</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <formula>ShippingCity</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CS_EPA_ID__c.field-meta.xml
<CustomField>
    <fullName>CS_EPA_ID__c</fullName>
    <inlineHelpText>The following fields are required in order to validate the EPA Id in addition to the EPA Id field. 
-Corporate Street 
-Corporate State 
-Corporate Country 
-Generator Status 
-Primary Service Provider</inlineHelpText>
    <label>EPA ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/dunbrdst__c.field-meta.xml
<CustomField>
    <fullName>dunbrdst__c</fullName>
    <description>dunbrdst from Beacon for Key Accounts</description>
    <externalId>true</externalId>
    <label>dunbrdst</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Segment__c.field-meta.xml
<CustomField>
    <fullName>Industry_Segment__c</fullName>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Base &amp; Blended Oils</fullName>
            </value>
            <value>
                <fullName>Brokers</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Ecommerce</fullName>
            </value>
            <value>
                <fullName>Education Services</fullName>
            </value>
            <value>
                <fullName>Engineering &amp; Consulting</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Insurance &amp; Real Estate</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Mining</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Paper &amp; Wood</fullName>
            </value>
            <value>
                <fullName>Pharmaceutical &amp; Biotechnology</fullName>
            </value>
            <value>
                <fullName>Refineries &amp; Oilsands</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Terminals &amp; Pipelines</fullName>
            </value>
            <value>
                <fullName>Transportation Services</fullName>
            </value>
            <value>
                <fullName>Utilities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/KAM_Manager__c.field-meta.xml
<CustomField>
    <fullName>KAM_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Key Account owner&apos;s manager.  Generally a VP.</description>
    <label>CAM Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <type>Picklist</type>
    <valueSet>
	    <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CH A Large &gt;200K</fullName>
            </value>
            <value>
                <fullName>CH C Assigned &gt;30K</fullName>
            </value>
            <value>
                <fullName>D &lt;30,000</fullName>
            </value>
            <value>
                <fullName>CH E Small &lt;30K</fullName>
            </value>
            <value>
                <fullName>CH B Medium &gt;100K</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Reporting_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Vertical__c</fullName>
    <label>Reporting Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Base Oil, Blender, Packager, or Marketer</fullName>
            </value>
            <value>
                <fullName>Brokers</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>Construction - Building Related Trades</fullName>
            </value>
            <value>
                <fullName>Corp RE</fullName>
            </value>
            <value>
                <fullName>Drill Rig Owner</fullName>
            </value>
            <value>
                <fullName>Education Services</fullName>
            </value>
            <value>
                <fullName>Engineering &amp; Consulting - Environmental</fullName>
            </value>
            <value>
                <fullName>Engineering &amp; Consulting - Heavy Construction</fullName>
            </value>
            <value>
                <fullName>Engineering and Consulting – Utilities</fullName>
            </value>
            <value>
                <fullName>Engineering, Consulting - Seismic</fullName>
            </value>
            <value>
                <fullName>General Manufacturing</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Mining, Primary Metals</fullName>
            </value>
            <value>
                <fullName>Oil, Gas Exploration</fullName>
            </value>
            <value>
                <fullName>Oil, Gas Production</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pharmaceutical &amp; Biotechnology</fullName>
            </value>
            <value>
                <fullName>Refineries &amp; Oilsands</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Terminals &amp; Pipelines</fullName>
            </value>
            <value>
                <fullName>Transportation Services</fullName>
            </value>
            <value>
                <fullName>Utilities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ZIP_Master__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZIP Master</label>
    <referenceTo>ZIP_Master__c</referenceTo>
    <relationshipLabel>Accounts (ZIP Master)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Corporate.recordType-meta.xml
<RecordType>
    <fullName>Corporate</fullName>
    <active>true</active>
    <description>All Clean Harbor Corporate Accounts</description>
    <label>Corporate</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>All Clean Harbors Customers</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Contact/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <formula>IF( ISBLANK( Locations__c ) ,   Account.ShippingCity   , Locations__r.Address__City__s)</formula>
    <label>Contact City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>TEXT(Locations__r.Address__CountryCode__s)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>IF( ISBLANK( Locations__c ),  Account.ShippingState  ,TEXT(Locations__r.Address__StateCode__s))</formula>
    <label>Contact State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SIC_VALIDATION_SETTING__c/SIC_VALIDATION_SETTING__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS will consist of a flag which determines if SIC Validation on Account should be implemented or not.</description>
    <label>SIC VALIDATION SETTING</label>
</CustomObject>

force-app/main/default/objects/SIC_VALIDATION_SETTING__c/fields/SIC_VALIDATION_FLAG__c.field-meta.xml
<CustomField>
    <fullName>SIC_VALIDATION_FLAG__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag which determines if SIC Validation should be executed in the custom code or not. Should be Checked if SIC Validation is required.</description>
    <label>SIC_VALIDATION_FLAG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TERRITORY_MANAGEMENT__c/TERRITORY_MANAGEMENT__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS will consist of a flag which determines if Territory Management on Account should be implemented or not. If Yes, the Territory and Owner on Account are set based on the criteria.</description>
    <label>TERRITORY MANAGEMENT</label>
</CustomObject>

force-app/main/default/objects/TERRITORY_MANAGEMENT__c/fields/TM_FLAG__c.field-meta.xml
<CustomField>
    <fullName>TM_FLAG__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag which determines if TM should be executed in the custom code or not thus setting the Territory and the Account Owner field on the Account record. Should be Checked if TM is required.</description>
    <inlineHelpText>Flag which determines if TM should be executed in the custom code or not</inlineHelpText>
    <label>TM_FLAG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/ZIP_Master__c.object-meta.xml
<CustomObject>
    <label>ZIP Master</label>
    <nameField>
        <label>ZIP Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZIP Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZIP_Master__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Zip codes primary city</description>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>US States</description>
    <label>State</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/fields/ZIP__c.field-meta.xml
<CustomField>
    <fullName>ZIP__c</fullName>
    <label>ZIP</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RemoveContactFromCadenceBatchTest.cls
@istest 
public class RemoveContactFromCadenceBatchTest {
    @testSetup
    private static void setup(){
        User userRec = new User(Id=UserInfo.getUserId(), EmployeeNumber='333');
        UPDATE userRec;  
        TERRITORY_MANAGEMENT__c territoryMgmt = new TERRITORY_MANAGEMENT__c();
        territoryMgmt.Name = 'TERRITORY_MGMT_SETTING';
        territoryMgmt.TM_FLAG__c = true;
        insert territoryMgmt;
        COUNTRY_CODES__c countrycodes = new COUNTRY_CODES__c();
        countrycodes.Name = 'CA';
        insert countrycodes;
        
        COUNTRY_CODES__c countrycodes1 = new COUNTRY_CODES__c();
        countrycodes1.Name = 'US';
        insert countrycodes1;
        
        List<ZIP_Master__c> zipMasterList = new List<ZIP_Master__c>();
        for(Integer i = 0; i < 10; i++){
            zipMasterList.add(new ZIP_Master__c(Zip__c = '12345',Country__c = 'US', State__c = 'NY',City__c ='Ashburn'));
			zipMasterList.add(new ZIP_Master__c(Zip__c = '20147',Country__c = 'US', State__c = 'NY',City__c ='Ashburn'));
        }
        insert zipMasterList;
        SIC_VALIDATION_SETTING__c sicValidation = new SIC_VALIDATION_SETTING__c();
        sicValidation.Name = 'SIC_VALIDATION_SETTING';
        sicValidation.SIC_VALIDATION_FLAG__c = false;
        insert sicValidation;
        Id accRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        Id accCorporateRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Corporate').getRecordTypeId();
        Account corAcc = new Account(
            Name = 'Test ',       
            Business_Type__c = 'Base', 
            AccountSource = 'Phone',
            CS_EPA_ID__c = '12345', 
            Sic = '0111',
            ShippingCountry = 'US',
            ShippingState = 'NY',
        	ShippingStreet = 'Test Street',
       	    ShippingCity = 'Ashburn',
            ShippingPostalCode = '12345',
            dunbrdst__c = '12345',
        	KAM_Manager__c = UserInfo.getUserId(), 
            RecordTypeId = accCorporateRecTypeId,                               
            Rank__c = 'CH A Large >200K',
            Reporting_Vertical__c = 'Automotive',
            Industry_Segment__c = 'Automotive',
            Class__c = 'Agricultural Production',
            ownerId = UserInfo.getUserId(), 
            Primary_Service_Provider_New__c='SK ENV',
            KAM_Support__c = UserInfo.getUserId(),
            WIN_ID__c = 'DEL200',
            Buying_Decision__c = 'Central Buying'
        ); 
        insert corAcc; 
        Account acc = new Account(
            Name = 'Test1',       
            Business_Type__c = 'Base', 
            AccountSource = 'Phone',
            CS_EPA_ID__c = '12345', 
            Sic = '0111', 
            RecordTypeId = accRecTypeId,                               
            Rank__c = 'CH A Large >200K',
            Reporting_Vertical__c = 'Automotive',
            Industry_Segment__c = 'Automotive',
            Class__c = 'Agricultural Production',
            ownerId = UserInfo.getUserId(), 
            Primary_Service_Provider__c='Safety Kleen',
            WIN_ID__c = 'DEL201',
            ParentId = corAcc.Id
        ); 
        insert acc;
        
        List<Contact> conList = new List<Contact>();
        for(Integer i = 0; i < 1; i++){
            if(i < 0 ){
                conList.add(new Contact(AccountId = acc.Id, LastName = 'Last ' + i, FirstName = 'First ' + i, Email = 'test'+i+'@test.com', Salutation = 'Mr.'));
            }
            else{
                conList.add(new Contact(AccountId = corAcc.Id, LastName = 'Last ' + i, FirstName = 'First ' + i, Email = 'test'+i+'@test.com', Salutation = 'Mr.'));
            }
        }
        insert conList;
        
        acc.status__c = 'Inactive';
        update acc;
    }
    @isTest static void testcadencewithContactId(){
        List<Contact> conList = [Select id,name from Contact];
        List<id> conIds = new List<id>();
        for(Contact con : conList)
        {
            conIds.add(con.id);
        }
        
        Test.setMock(HttpCalloutMock.class, new RemoveContactFromCadenceMock(200));
        RemoveContactFromCadenceBatch cadenceRemoveObj = new RemoveContactFromCadenceBatch(conIds);
        Test.startTest();
        cadenceRemoveObj.accountHistoryRecsMock = returnAccountHistory();
        cadenceRemoveObj.actionCadenceTrackersMock = returnCadence();
        database.executeBatch(cadenceRemoveObj,200);
        List<Exception_Log__c> errormessage = [select id from Exception_Log__c];
        Assert.isNotNull(errormessage, 'Cadence Remove Failed');
        Test.stopTest();
    }
    @isTest static void testcadenceInactivateAccount(){       
        Test.setMock(HttpCalloutMock.class, new RemoveContactFromCadenceMock(200));
        RemoveContactFromCadenceBatch cadenceRemoveObj = new RemoveContactFromCadenceBatch();
        Test.startTest();
        cadenceRemoveObj.accountHistoryRecsMock = returnAccountHistory();
        cadenceRemoveObj.actionCadenceTrackersMock = returnCadence();
        database.executeBatch(cadenceRemoveObj,200);
        List<Exception_Log__c> errormessage = [select id from Exception_Log__c];
        Assert.isNotNull(errormessage, 'Cadence Remove Failed');
        Test.stopTest();
    }
    @isTest static void testcadencehoursAccount(){       
        Test.setMock(HttpCalloutMock.class, new RemoveContactFromCadenceMock(200));
        RemoveContactFromCadenceBatch cadenceRemoveObj = new RemoveContactFromCadenceBatch(12);
        Test.startTest();
        cadenceRemoveObj.accountHistoryRecsMock = returnAccountHistory();
        cadenceRemoveObj.actionCadenceTrackersMock = returnCadence();
        database.executeBatch(cadenceRemoveObj,200);
        List<Exception_Log__c> errormessage = [select id from Exception_Log__c];
        Assert.isNotNull(errormessage, 'Cadence Remove Failed');
        Test.stopTest();
    }
    @isTest static void testcadencehoursAccountException(){       
        List<Contact> conList = [Select id,name from Contact];
        List<id> conIds = new List<id>();
        for(Contact con : conList)
        {
            conIds.add(con.id);
        }
        Test.setMock(HttpCalloutMock.class, new RemoveContactFromCadenceMock(400));
        RemoveContactFromCadenceBatch cadenceRemoveObj = new RemoveContactFromCadenceBatch(conIds);
        Test.startTest();
        cadenceRemoveObj.accountHistoryRecsMock = returnAccountHistory();
        cadenceRemoveObj.actionCadenceTrackersMock = returnCadence();
        database.executeBatch(cadenceRemoveObj,200);
        List<Exception_Log__c> errormessage = [select id from Exception_Log__c];
        Assert.isNotNull(errormessage, 'Cadence Remove Failed');
        Test.stopTest();
    }
    private static List<ActionCadenceTracker> returnCadence(){
        List<Contact> conList = [Select id,name from Contact];
        List<id> conIds = new List<id>();
        for(Contact con : conList)
        {
            conIds.add(con.id);
        }
        String jsonObject = '[{'+
            '"attributes": {'+
            '"type": "ActionCadenceTracker",'+
            '"url": "/services/data/v56.0/sobjects/ActionCadenceTracker/0qB76000000GzO4EAK"'+
            '},'+
            '"Id": "0qB76000000GzO4EAK",'+
            '"OwnerId": "005760000010oRMAAY",'+
            '"CreatedDate": "2022-10-04T05:42:52.000+0000",'+
            '"CreatedById": "005760000010oRMAAY",'+
            '"ActionCadenceId": "77C760000004CBEEA2",'+
            '"TargetId": "'+conIds[0] +'"'+
            '}]';
        List<ActionCadenceTracker> cadenceList = (List<ActionCadenceTracker>)JSON.deserialize(jsonObject, List<ActionCadenceTracker>.class); 
        return cadenceList;
    } 
    private static List<AccountHistory> returnAccountHistory(){
        List<Contact> conList = [Select id,name,Account.Id from Contact];
        List<id> conIds = new List<id>();
        for(Contact con : conList)
        {
            conIds.add(con.id);
        }
        List<AccountHistory> ah; 
        ah = new List<AccountHistory>{}; 
        ah.add(new AccountHistory(AccountId=conList[0].Accountid, Field='Type'));
        return ah;
    }
    
}