force-app/main/default/objects/Account/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
                <default>true</default>
                <label>Base</label>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Locating</fullName>
            </value>
            <value>
                <fullName>Key</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/dunbrdst__c.field-meta.xml
<CustomField>
    <fullName>dunbrdst__c</fullName>
    <description>dunbrdst from Beacon for Key Accounts</description>
    <externalId>true</externalId>
    <label>dunbrdst</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Segment__c.field-meta.xml
<CustomField>
    <fullName>Industry_Segment__c</fullName>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Base &amp; Blended Oils</fullName>
            </value>
            <value>
                <fullName>Brokers</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Ecommerce</fullName>
            </value>
            <value>
                <fullName>Education Services</fullName>
            </value>
            <value>
                <fullName>Engineering &amp; Consulting</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Insurance &amp; Real Estate</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Mining</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Paper &amp; Wood</fullName>
            </value>
            <value>
                <fullName>Pharmaceutical &amp; Biotechnology</fullName>
            </value>
            <value>
                <fullName>Refineries &amp; Oilsands</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Terminals &amp; Pipelines</fullName>
            </value>
            <value>
                <fullName>Transportation Services</fullName>
            </value>
            <value>
                <fullName>Utilities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/KAM_Manager__c.field-meta.xml
<CustomField>
    <fullName>KAM_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Key Account owner&apos;s manager.  Generally a VP.</description>
    <label>CAM Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/KAM_Support__c.field-meta.xml
<CustomField>
    <fullName>KAM_Support__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person that supports KAM Account</description>
    <label>CAM Support</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <type>Picklist</type>
    <valueSet>
	    <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CH A Large &gt;200K</fullName>
            </value>
            <value>
                <fullName>CH C Assigned &gt;30K</fullName>
            </value>
            <value>
                <fullName>D &lt;30,000</fullName>
            </value>
            <value>
                <fullName>CH E Small &lt;30K</fullName>
            </value>
            <value>
                <fullName>CH B Medium &gt;100K</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Sales_Business_Unit__c</fullName>
    <description>Sales business unit (temporary field - do not use)</description>
    <label>Sales Business Unit</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Same_as_Corp_Address__c.field-meta.xml
<CustomField>
    <fullName>Same_as_Corp_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If True, Corporate Address will be copied to Billing Address</description>
    <label>Remit-to/Billing Address same as Corp</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/WIN_ID__c.field-meta.xml
<CustomField>
    <fullName>WIN_ID__c</fullName>
    <externalId>true</externalId>
    <label>WIN ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ZIP_Master__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZIP Master</label>
    <referenceTo>ZIP_Master__c</referenceTo>
    <relationshipLabel>Accounts (ZIP Master)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Corporate.recordType-meta.xml
<RecordType>
    <fullName>Corporate</fullName>
    <active>true</active>
    <description>All Clean Harbor Corporate Accounts</description>
    <label>Corporate</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>All Clean Harbors Customers</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This field is used to store the Billing Country while converting ShipTo/Gen to Customer account</description>
    <label>Country</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>This field is used to store the Billing State while converting ShipTo/Gen to Customer account</description>
    <label>State</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/WIN_Id__c.field-meta.xml
<CustomField>
    <fullName>WIN_Id__c</fullName>
    <label>WIN Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Zip_Master__c.field-meta.xml
<CustomField>
    <fullName>Zip_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ZIP Master</description>
    <label>Single Postal Code</label>
    <referenceTo>ZIP_Master__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>TEXT(Locations__r.Address__CountryCode__s)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>IF( ISBLANK( Locations__c ),  Account.ShippingState  ,TEXT(Locations__r.Address__StateCode__s))</formula>
    <label>Contact State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WIN_ID__c.field-meta.xml
<CustomField>
    <fullName>WIN_ID__c</fullName>
    <formula>Account.WIN_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>WIN ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SIC_VALIDATION_SETTING__c/SIC_VALIDATION_SETTING__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS will consist of a flag which determines if SIC Validation on Account should be implemented or not.</description>
    <label>SIC VALIDATION SETTING</label>
</CustomObject>

force-app/main/default/objects/SIC_VALIDATION_SETTING__c/fields/SIC_VALIDATION_FLAG__c.field-meta.xml
<CustomField>
    <fullName>SIC_VALIDATION_FLAG__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag which determines if SIC Validation should be executed in the custom code or not. Should be Checked if SIC Validation is required.</description>
    <label>SIC_VALIDATION_FLAG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TERRITORY_MANAGEMENT__c/TERRITORY_MANAGEMENT__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS will consist of a flag which determines if Territory Management on Account should be implemented or not. If Yes, the Territory and Owner on Account are set based on the criteria.</description>
    <label>TERRITORY MANAGEMENT</label>
</CustomObject>

force-app/main/default/objects/TERRITORY_MANAGEMENT__c/fields/TM_FLAG__c.field-meta.xml
<CustomField>
    <fullName>TM_FLAG__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag which determines if TM should be executed in the custom code or not thus setting the Territory and the Account Owner field on the Account record. Should be Checked if TM is required.</description>
    <inlineHelpText>Flag which determines if TM should be executed in the custom code or not</inlineHelpText>
    <label>TM_FLAG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Territory_Master__c/Territory_Master__c.object-meta.xml
<CustomObject>
    <description>Contains all Territory Information viz., SBU, Territory Name, Territory Owner, etc. based on the ZIP Codes.</description>
    <label>Territory Master</label>
    <nameField>
        <label>Territory Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Master</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Master__c/fields/Sales_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Sales_Business_Unit__c</fullName>
    <label>Primary Service Provider</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BPS</fullName>
            </value>
            <value>
                <fullName>CYN</fullName>
            </value>
            <value>
                <fullName>Daylighting Services</fullName>
            </value>
            <value>
                <fullName>DFW</fullName>
            </value>
            <value>
                <fullName>Emerald Services</fullName>
            </value>
            <value>
                <fullName>Field Services</fullName>
            </value>
            <value>
                <fullName>H2O</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Industrial Services</fullName>
            </value>
            <value>
                <fullName>Lodging</fullName>
            </value>
            <value>
                <fullName>Murphys Oil</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Seismic</fullName>
            </value>
            <value>
                <fullName>Safety-Kleen</fullName>
                <label>SK ENV</label>
            </value>
            <value>
                <fullName>SK KPP</fullName>
            </value>
            <value>
                <fullName>Surface Rentals</fullName>
            </value>
            <value>
                <fullName>Synergy</fullName>
            </value>
            <value>
                <fullName>Technical Services</fullName>
            </value>
            <value>
                <fullName>Thermo Fluids</fullName>
            </value>
			<value>
                <fullName>Thompson</fullName>
            </value>
			<value>
                <fullName>Noble Oil</fullName>
            </value>
            <value>
                <fullName>HEPACO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory_Master__c/fields/ZIP_Master__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Master__c</fullName>
    <label>ZIP Master</label>
    <referenceTo>ZIP_Master__c</referenceTo>
    <relationshipLabel>Territory Master</relationshipLabel>
    <relationshipName>Territory_Master</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/ZIP_Master__c.object-meta.xml
<CustomObject>
    <label>ZIP Master</label>
    <nameField>
        <label>ZIP Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZIP Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZIP_Master__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>US States</description>
    <label>State</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/fields/ZIP__c.field-meta.xml
<CustomField>
    <fullName>ZIP__c</fullName>
    <label>ZIP</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseApprovalRelatedListControllerTest.cls
/**
* @description       : 
* @author            : Vikram Simha (Yerabov)
* @group             : 
* @last modified on  : 04-03-2024
* @last modified by  : Vikram Simha
**/
@isTest
public class CaseApprovalRelatedListControllerTest {
    private final static string TEST_Shipping_PostalCode = '45204';
    private final static string TEST_Shipping_Country = 'US';
    private final static string TEST_Shipping_State = 'OR';
    private final static string TEST_Shipping_City = 'Brookings';
    private final static string TEST_Shipping_Street = 'Test Street';
    private final static string TEST_NAME = 'Gillette Company';
    private final static string TEST_PHONE = '799856414';
    private final static string TEST_TYPE =  'Customer';
    private final static string TEST_TYPE1 = 'ShipTo/Gen';
    private final static string TEST_BUSINESS_TYPE = 'Base'; 
    private final static string TEST_RANK = 'CH A Large >200K';
    private final static string TEST_INDUSTRY_SEGMENT = 'Chemical';
    private final static string TEST_INDUSTRY_SEGMENT1 = 'Machinery Manufacturing';
    private final static string TEST_CURRENCYISOCODE = 'USD';
    private final static string TEST_CS_EPA_ID = 'PENDING';
    private final static string TEST_GENERATOR_STATUS = 'Large Quantity Generator'; 
    private final static string TEST_MISSING_CONTACT_TYPE = 'MAIN';
    private final static string TEST_STATUS = 'Active';
    private final static string TEST_ZIP = '45204';
    private final static string TEST_SALES_BUSINESS_UNIT = 'lodging';  
    private final static string TEST_CASE_TYPE = 'New';
    private final static string TEST_CASE_POSTAL_CODES = '02061';
    private final static string TEST_CASE_WIN_ID = 'ECOMT2';
    private final static string TEST_CASE_FIRST_NAME = 'ABC';
    private final static string TEST_CASE_DESCRIPTION = 'Test';
    private final static string TEST_CASE_UNEXPIRE_REASON = 'Account needs to be serviced';
    private final static string TEST_CASE_CALL_CENTER_ACTIVITY_ID = 'ASDE234';
    private final static string TEST_CASE_COMEENT_BODY = 'This is closed because no need of service';
    private final static string TEST_FIRST_NAME = 'Test'; 
    private final static string TEST_LAST_NAME = 'Test';
    private final static string TEST_SALUTATION = 'Mr';    
    private final static string TEST_TITLE = 'title';
    private final static string TEST_EMAIL = 'Test1@testemail.com';
    private final static string TEST_REQUEST_TYPE1 = 'Inactivation Request';
    private final static Id accountUpdateValidationRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Account Update Validations').getRecordTypeId();
    private final static Id fieldChangeRequestRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Field Change Request').getRecordTypeId();
    private final static Id customerRecordTypeId = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get(CHConstants.ACCOUNT_RECORD_TYPE_CUSTOMER).getRecordTypeId();
    @testsetup
    static void setup(){
        SIC_VALIDATION_SETTING__c svsObj = new SIC_VALIDATION_SETTING__c();
        svsObj.name = 'SIC_VALIDATION_SETTING';
        svsObj.SIC_VALIDATION_FLAG__c = true;
        insert svsObj;
        
        TERRITORY_MANAGEMENT__c tmgObj = new TERRITORY_MANAGEMENT__c();
        tmgObj.name = 'TERRITORY_MGMT_SETTING';
        tmgObj.TM_FLAG__c = true;
        insert tmgObj;
        
        COUNTRY_CODES__c countrycodes = new COUNTRY_CODES__c();	
        countrycodes.Name = 'CA';	
        insert countrycodes;	
        
        COUNTRY_CODES__c countrycodes1 = new COUNTRY_CODES__c();	
        countrycodes1.Name = 'US';	
        insert countrycodes1;	
        
        ZIP_Master__c zpObj = new ZIP_Master__c();	
        zpObj.zip__c = TEST_ZIP;	
        zpObj.CurrencyIsoCode = TEST_CURRENCYISOCODE;	
        zpObj.Country__c = TEST_Shipping_Country;	
        zpObj.State__c = TEST_Shipping_State;	
        insert zpObj;	
        
        Territory_Master__c tmObj = new Territory_Master__c();	
        tmObj.name = 'Test TM';	
        tmObj.ZIP_Master__c = zpObj.id;	
        tmObj.CurrencyIsoCode = TEST_CURRENCYISOCODE;	
        tmObj.Sales_business_unit__C = 'lodging';       	
        insert tmObj;
        user activeUser =[select id from user where IsActive = True limit 1];
        Account accObj = new Account();
        accObj.Name =  TEST_NAME;
        accObj.dunbrdst__c = '12345';
        accObj.KAM_Manager__c = activeUser.id;
        accObj.KAM_Support__c = activeUser.id;
        accObj.OwnerId = activeUser.id;
        accObj.Phone = TEST_PHONE;
        accObj.Type = TEST_TYPE;
        accObj.Business_Type__c = TEST_BUSINESS_TYPE;
        accObj.Rank__c = TEST_RANK;
        accObj.Same_as_Corp_Address__c =true;
        accObj.WIN_ID__c = 'GIL210';
        accObj.Industry_Segment__c = TEST_INDUSTRY_SEGMENT;
        accObj.CurrencyIsoCode = TEST_CURRENCYISOCODE;
        accObj.CS_EPA_ID__c =  TEST_CS_EPA_ID;
        accObj.Generator_Status__c = TEST_GENERATOR_STATUS;
        accObj.recordtypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Corporate').getRecordTypeId();
        accObj.ShippingPostalCode = TEST_Shipping_PostalCode;	
        accObj.ShippingCountry = TEST_Shipping_Country;	
        accObj.ShippingState = TEST_Shipping_State;	
        accObj.ShippingCity = TEST_Shipping_City;	
        accObj.ShippingStreet = TEST_Shipping_Street;
        insert accObj;
        
        Account accObjCust = new Account();
        accObjCust.Name = TEST_NAME;
        accObjCust.Phone = TEST_PHONE;
        accObjCust.Type = TEST_TYPE;
        accObjCust.Business_Type__c = TEST_BUSINESS_TYPE; 
        accObjCust.Rank__c = TEST_RANK;
        accObjCust.Same_as_Corp_Address__c =true;
        accObjCust.WIN_ID__c = 'GIL211';
        accObjCust.Industry_Segment__c = TEST_INDUSTRY_SEGMENT;
        accObjCust.CurrencyIsoCode = TEST_CURRENCYISOCODE;
        accObjCust.CS_EPA_ID__c = TEST_CS_EPA_ID;
        accObjCust.Tax_Exemption_Type__c = 'Non Exempt';
        accObjCust.Generator_Status__c = TEST_GENERATOR_STATUS;
        accObjCust.ShippingPostalCode = TEST_Shipping_PostalCode;	
        accObjCust.ShippingCountry = TEST_Shipping_Country;	
        accObjCust.ShippingState = TEST_Shipping_State;	
        accObjCust.ShippingCity = TEST_Shipping_City;	
        accObjCust.ShippingStreet = TEST_Shipping_Street;	
        
        accObjCust.recordtypeId = customerRecordTypeId;
        //accObjCust.ParentId = accObj.Id;
        insert accObjCust;
        
        Contact con = new Contact(AccountId = accObjCust.id);
        con.LastName = 'Contact';
        con.FirstName = 'Main';
        con.Salutation = 'Mr';
        con.Title = 'Default Mgr';
        con.Email = 'Main@default.com';
        con.Phone = '781-792-5000';
        con.Contact_Type__c = 'MAIN';
        insert con;
        Contact con1 = new Contact(AccountId = accObj.id);
        con1.LastName = 'Contact';
        con1.FirstName = 'Main';
        con1.Salutation = 'Mr';
        con1.Title = 'Default Mgr';
        con1.Email = 'Main@default.com';
        con1.Phone = '781-792-5000';
        con1.Contact_Type__c = 'MAIN';
        insert con1;
        Account accObjCust2 = new Account();
        accObjCust2.Name = 'Test2';
        accObjCust2.Phone = TEST_PHONE;
        accObjCust2.Type = TEST_TYPE;
        accObjCust2.Business_Type__c = TEST_BUSINESS_TYPE; 
        accObjCust2.Rank__c = TEST_RANK;
        accObjCust2.Same_as_Corp_Address__c =true;
        accObjCust2.WIN_ID__c = 'GIL212';
        accObjCust2.Industry_Segment__c = TEST_INDUSTRY_SEGMENT;
        accObjCust2.CurrencyIsoCode = TEST_CURRENCYISOCODE;
        accObjCust2.CS_EPA_ID__c = TEST_CS_EPA_ID;
        accObjCust2.Generator_Status__c = TEST_GENERATOR_STATUS;
        accObjCust2.Tax_Exemption_Type__c = 'Non Exempt';
        accObjCust2.ShippingPostalCode = TEST_Shipping_PostalCode;	
        accObjCust2.ShippingCountry = TEST_Shipping_Country;	
        accObjCust2.ShippingState = TEST_Shipping_State;	
        accObjCust2.ShippingCity = TEST_Shipping_City;	
        accObjCust2.ShippingStreet = TEST_Shipping_Street;	
        
        accObjCust2.recordtypeId = customerRecordTypeId;
        //accObjCust2.ParentId = accObj.Id;
        insert accObjCust2;
        
        Contact con2 = new Contact(AccountId = accObjCust2.id);
        con2.LastName = 'Contact';
        con2.FirstName = 'Main';
        con2.Salutation = 'Mr';
        con2.Title = 'Default Mgr';
        con2.Email = 'Main@default.com';
        con2.Phone = '781-792-5000';
        con2.Contact_Type__c = 'MAIN';
        insert con2;
        Test.startTest();
        case casobj = new case();
        casobj.Type = TEST_CASE_TYPE;
        casobj.Effective_Date__c = system.today();
        casobj.Proposed_Owner_Case_Approver__c = UserInfo.getUserId();
        casobj.Current_Owner_Case_Approver__c =UserInfo.getUserId();
        casobj.AccountId = accObjCust2.Id;
        casobj.Status = 'New';
        casObj.recordTypeId = accountUpdateValidationRecordTypeId;
        insert casObj;
        case casobjchild = new case();
        casobjchild.Type = TEST_CASE_TYPE;
        casobjchild.Effective_Date__c = system.today();
        casobjchild.Proposed_Owner_Case_Approver__c = UserInfo.getUserId();
        casobjchild.Current_Owner_Case_Approver__c =UserInfo.getUserId();
        casobjchild.AccountId = accObjCust2.Id;
        casobjchild.Account_Field_Changed__c = 'Name';
        casobjchild.Status ='Awaiting Manager Approval';
        casobjchild.ParentId = casobj.id;
        casobjchild.recordTypeId = fieldChangeRequestRecordTypeId;
        casobjchild.Old_Value__c=TEST_NAME;
        casobjchild.New_Value__c = TEST_NAME+'TEst';
        insert casobjchild;
        Test.stopTest();
    }
    @isTest     
    private static void getChildCaseRecordsTest(){
        
        Test.startTest();
        Account acc =[Select id,Name from Account where name = 'Test2' and recordtypeid=:customerRecordTypeId limit 1];
        List<CAse> casobjchild =[select id,casenumber,Old_value__c, Is_Submitted_for_Approval__c,ParentId,Proposed_Owner_Case_Approver__c from case where accountid=:acc.id and RecordTypeId = : fieldChangeRequestRecordTypeId];
        
        System.debug(casobjchild);
        CaseApprovalRelatedListController.ChildCasesWrapper caseWrapper;
        if(!casobjchild.IsEmpty()){
            caseWrapper = CaseApprovalRelatedListController.getChildCaseRecords(casobjchild[0].parentId);
        } 
        Assert.areNotEqual(caseWrapper.childCasesData,null,'No Case Records Found');
        Test.stopTest();
        
    } 
    @isTest     
    private static void approveRejectCaseRecordsTest(){
        
        Test.startTest();
        Account acc =[Select id,Name from Account where name = 'Test2' and recordtypeid=:customerRecordTypeId limit 1];
        List<CAse> casobjchild =[select id,casenumber,Old_value__c, Is_Submitted_for_Approval__c,ParentId,Proposed_Owner_Case_Approver__c from case where accountid=:acc.id and RecordTypeId = : fieldChangeRequestRecordTypeId];
        System.debug(casobjchild);
        if(!casobjchild.IsEmpty()){
            List<CaseApprovalRelatedListController.DataTableWrapper> wrapperList = CaseApprovalRelatedListController.approveRejectCaseRecords(casobjchild[0].Id, casobjchild[0].parentId,'Approve');
        }
        List<CAse> casobjchild1 =[select id,Status from case where id=:casobjchild[0].Id ];
        Assert.areEqual('Approved', casobjchild1[0].Status,'Case Approval Failed.');
        Test.stopTest();
    } 
}