force-app/main/default/objects/Account/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
                <default>true</default>
                <label>Base</label>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Locating</fullName>
            </value>
            <value>
                <fullName>Key</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry_Segment__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agricultural Production</fullName>
            </value>
            <value>
                <fullName>Agricultural Svcs</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Airports &amp; Aviation Svcs</fullName>
            </value>
            <value>
                <fullName>Asphalt, Terminal</fullName>
            </value>
            <value>
                <fullName>Auto Maintenance</fullName>
            </value>
            <value>
                <fullName>Auto Retail</fullName>
            </value>
            <value>
                <fullName>Biotechnology</fullName>
            </value>
            <value>
                <fullName>Brokers - Waste &amp; Environmental Svcs</fullName>
            </value>
            <value>
                <fullName>Building Materials (excl Lumber Mills)</fullName>
            </value>
            <value>
                <fullName>Business and Personal Services</fullName>
            </value>
            <value>
                <fullName>Chemical - Distributor</fullName>
            </value>
            <value>
                <fullName>Chemical Manufacturing</fullName>
            </value>
            <value>
                <fullName>Colleges &amp; Universities</fullName>
            </value>
            <value>
                <fullName>Construction, Gen Contractors &amp; Builders</fullName>
            </value>
            <value>
                <fullName>Corporate Real Estate</fullName>
            </value>
            <value>
                <fullName>Cruise Lines</fullName>
            </value>
            <value>
                <fullName>Dealerships - Auto</fullName>
            </value>
            <value>
                <fullName>Dealerships - Recreational &amp; Machinery</fullName>
            </value>
            <value>
                <fullName>Drill Rig Owners</fullName>
            </value>
            <value>
                <fullName>Dry Cleaners</fullName>
            </value>
            <value>
                <fullName>Ecommerce</fullName>
            </value>
            <value>
                <fullName>Emergency Response Management</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Civil/Heavy Construction</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Drilling</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Enviro Remediation</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Oilsands</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Seismic &amp; Production</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Utilities</fullName>
            </value>
            <value>
                <fullName>Entertainment and Recreation Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CS_EPA_ID__c.field-meta.xml
<CustomField>
    <fullName>CS_EPA_ID__c</fullName>
    <inlineHelpText>The following fields are required in order to validate the EPA Id in addition to the EPA Id field. 
-Corporate Street 
-Corporate State 
-Corporate Country 
-Generator Status 
-Primary Service Provider</inlineHelpText>
    <label>EPA ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <type>Picklist</type>
    <valueSet>
	    <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CH A Large &gt;200K</fullName>
            </value>
            <value>
                <fullName>CH C Assigned &gt;30K</fullName>
            </value>
            <value>
                <fullName>D &lt;30,000</fullName>
            </value>
            <value>
                <fullName>CH E Small &lt;30K</fullName>
            </value>
            <value>
                <fullName>CH B Medium &gt;100K</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ZIP_Master__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZIP Master</label>
    <referenceTo>ZIP_Master__c</referenceTo>
    <relationshipLabel>Accounts (ZIP Master)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>All Clean Harbors Customers</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/SIC_Codes__c/SIC_Codes__c.object-meta.xml
<CustomObject>
    <description>Maps SIC Codes to class and sets default Primary business for a  SIC code</description>
    <label>SIC Codes</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>SIC Codes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SIC Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SIC_Codes__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>The values in this field maps to the Class field on Account</description>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural Production</fullName>
            </value>
            <value>
                <fullName>Agricultural Svcs</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Airports &amp; Aviation Svcs</fullName>
            </value>
            <value>
                <fullName>Asphalt, Terminal</fullName>
            </value>
            <value>
                <fullName>Auto Maintenance</fullName>
            </value>
            <value>
                <fullName>Auto Retail</fullName>
            </value>
            <value>
                <fullName>Aviation Related Services</fullName>
            </value>
            <value>
                <fullName>Banks, Financial Institutions &amp; Bus Svcs</fullName>
            </value>
            <value>
                <fullName>Base Oil, Blender, Packager, or Marketer</fullName>
            </value>
            <value>
                <fullName>Biotechnology</fullName>
            </value>
            <value>
                <fullName>Brokers - Waste &amp; Environmental Svcs</fullName>
            </value>
            <value>
                <fullName>Building Materials (excl Lumber Mills)</fullName>
            </value>
            <value>
                <fullName>Chemical - Distributor</fullName>
            </value>
            <value>
                <fullName>Chemical Manufacturing</fullName>
            </value>
            <value>
                <fullName>Chemical Mfg - Specialty</fullName>
            </value>
            <value>
                <fullName>Chemical Pipeline</fullName>
            </value>
            <value>
                <fullName>Church, Synagogue, Other Religious Locations</fullName>
            </value>
            <value>
                <fullName>College (2 yr, Junior, Community Colleges)</fullName>
            </value>
            <value>
                <fullName>Colleges &amp; Universities</fullName>
            </value>
            <value>
                <fullName>Construction, Gen Contractors &amp; Builders</fullName>
            </value>
            <value>
                <fullName>Cruise Lines</fullName>
            </value>
            <value>
                <fullName>Dealerships - Auto</fullName>
            </value>
            <value>
                <fullName>Dealerships - Recreational &amp; Machinery</fullName>
            </value>
            <value>
                <fullName>Drill Rig Owners</fullName>
            </value>
            <value>
                <fullName>Dry Cleaners</fullName>
            </value>
            <value>
                <fullName>Emergency Response Management</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Civil/Heavy Construction</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Drilling</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Enviro Remediation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SIC_VALIDATION_SETTING__c/SIC_VALIDATION_SETTING__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS will consist of a flag which determines if SIC Validation on Account should be implemented or not.</description>
    <label>SIC VALIDATION SETTING</label>
</CustomObject>

force-app/main/default/objects/SIC_VALIDATION_SETTING__c/fields/SIC_VALIDATION_FLAG__c.field-meta.xml
<CustomField>
    <fullName>SIC_VALIDATION_FLAG__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag which determines if SIC Validation should be executed in the custom code or not. Should be Checked if SIC Validation is required.</description>
    <label>SIC_VALIDATION_FLAG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TERRITORY_MANAGEMENT__c/TERRITORY_MANAGEMENT__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS will consist of a flag which determines if Territory Management on Account should be implemented or not. If Yes, the Territory and Owner on Account are set based on the criteria.</description>
    <label>TERRITORY MANAGEMENT</label>
</CustomObject>

force-app/main/default/objects/TERRITORY_MANAGEMENT__c/fields/TM_FLAG__c.field-meta.xml
<CustomField>
    <fullName>TM_FLAG__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag which determines if TM should be executed in the custom code or not thus setting the Territory and the Account Owner field on the Account record. Should be Checked if TM is required.</description>
    <inlineHelpText>Flag which determines if TM should be executed in the custom code or not</inlineHelpText>
    <label>TM_FLAG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Territory_Master__c/Territory_Master__c.object-meta.xml
<CustomObject>
    <description>Contains all Territory Information viz., SBU, Territory Name, Territory Owner, etc. based on the ZIP Codes.</description>
    <label>Territory Master</label>
    <nameField>
        <label>Territory Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Master</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Master__c/fields/ZIP_Master__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Master__c</fullName>
    <label>ZIP Master</label>
    <referenceTo>ZIP_Master__c</referenceTo>
    <relationshipLabel>Territory Master</relationshipLabel>
    <relationshipName>Territory_Master</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/ZIP_Master__c.object-meta.xml
<CustomObject>
    <label>ZIP Master</label>
    <nameField>
        <label>ZIP Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZIP Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZIP_Master__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>US States</description>
    <label>State</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/fields/ZIP__c.field-meta.xml
<CustomField>
    <fullName>ZIP__c</fullName>
    <label>ZIP</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestAccountWIN.cls
@isTest
public class TestAccountWIN {
    @testSetup static void setupRecords() {
        Id accRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        Profile p = [SELECT Id FROM Profile WHERE Name='Integration']; 
        
        TERRITORY_MANAGEMENT__c territoryMgmt = new TERRITORY_MANAGEMENT__c();
        territoryMgmt.Name = 'TERRITORY_MGMT_SETTING';
        territoryMgmt.TM_FLAG__c = true;
        insert territoryMgmt;
        
        SIC_VALIDATION_SETTING__c sicValidation = new SIC_VALIDATION_SETTING__c();
        sicValidation.Name = 'SIC_VALIDATION_SETTING';
        sicValidation.SIC_VALIDATION_FLAG__c = true;
        insert sicValidation;
        
        List<User> userList = new List<User>();
        for(Integer i = 0; i < 10; i++){
            userList.add(new User(Alias = 'standt'+ i, Email='standarduser'+i+'@safety-kleen.com', 
            EmailEncodingKey='UTF-8', LastName='Testing '+ i, LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName=datetime.now().millisecond()+'standardusertest'+i+'@safety-kleen.com'));
        }
        insert userList; 
        
        List<ZIP_Master__c> zipMasterList = new List<ZIP_Master__c>();
        for(Integer i = 0; i < 10; i++){
            zipMasterList.add(new ZIP_Master__c(Zip__c = '12345',Country__c = 'US', State__c = 'NY'));
        }
       insert zipMasterList;
        
        Set<Id> sicCodesSet = new Set<Id>();
        List<SIC_Codes__c> sicCodesList = new List<SIC_Codes__c>();
        for(Integer i = 0; i < 10; i++){
            sicCodesList.add(new SIC_Codes__c(SIC_Code__c =  '011' + i, Class__c = 'Agricultural Production'));
        }
        insert sicCodesList;
        
        for(SIC_Codes__c sicCodesLoop : sicCodesList){
            sicCodesSet.add(sicCodesLoop.Id);
        }
        
        sicCodesList.clear();
        
        for(SIC_Codes__c sicCodesLoop : [SELECT Name,SIC_Code__c from SIC_Codes__c WHERE Id IN :sicCodesSet ]){
            sicCodesList.add(sicCodesLoop);
        }

        List<Account> accList = new List<Account>();
        for(Integer i = 0; i < 10; i++){
            accList.add(new Account(Name = 'Test ' + i, Business_Type__c = 'Base', AccountSource = 'Phone', CS_EPA_ID__c = '12345', Sic = '0111', RecordTypeId = accRecTypeId,                               
                                    Rank__c = 'CH A Large >200K', Reporting_Vertical__c = 'Automotive', Industry_Segment__c = 'Automotive', Class__c = 'Agricultural Production',
                                   Primary_Service_Provider_New__c = 'SK BPS')); //
        }
        Territory__c t = new Territory__c();
        t.name = 'TS-AM-Camarillo-CA-01';
        t.Territory_OwnerID__c = UserInfo.getUserId();
        INSERT t;
        Territory_Master__c tm = new Territory_Master__c();
        tm.ZIP_Master__c = zipMasterList[0].Id;
        tm.Sales_Business_Unit__c = 'BPS';
        tm.Name = 'SK BPS IS';
        tm.Territory_ID__c = t.Id;
        INSERT tm;
        test.startTest();
        accList[0].ZIP_Master__c = zipMasterList[0].Id;
        accList[0].WIN_ID__c = 'ECOMT1';
        insert accList;
        test.stopTest();
        COUNTRY_CODES__c countrycodes = new COUNTRY_CODES__c();
        countrycodes.Name = 'CA';
        insert countrycodes;
        
        COUNTRY_CODES__c countrycodes1 = new COUNTRY_CODES__c();
        countrycodes1.Name = 'US';
        insert countrycodes1;
    }
    
    private static testMethod void Method1(){
        test.starttest();
        List<Account> accLst = [SELECT Id FROM Account WHERE WIN_ID__c != NULL];
        String WINID;
        WINID = AccountWIN.returnAccount(accLst[0].Id);
        System.assertEquals(WINID, 'ECOMT1');
        test.stoptest();
    } 
}