force-app/main/default/objects/Account/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry_Segment__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agricultural Production</fullName>
            </value>
            <value>
                <fullName>Agricultural Svcs</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Airports &amp; Aviation Svcs</fullName>
            </value>
            <value>
                <fullName>Asphalt, Terminal</fullName>
            </value>
            <value>
                <fullName>Auto Maintenance</fullName>
            </value>
            <value>
                <fullName>Auto Retail</fullName>
            </value>
            <value>
                <fullName>Biotechnology</fullName>
            </value>
            <value>
                <fullName>Brokers - Waste &amp; Environmental Svcs</fullName>
            </value>
            <value>
                <fullName>Building Materials (excl Lumber Mills)</fullName>
            </value>
            <value>
                <fullName>Business and Personal Services</fullName>
            </value>
            <value>
                <fullName>Chemical - Distributor</fullName>
            </value>
            <value>
                <fullName>Chemical Manufacturing</fullName>
            </value>
            <value>
                <fullName>Colleges &amp; Universities</fullName>
            </value>
            <value>
                <fullName>Construction, Gen Contractors &amp; Builders</fullName>
            </value>
            <value>
                <fullName>Corporate Real Estate</fullName>
            </value>
            <value>
                <fullName>Cruise Lines</fullName>
            </value>
            <value>
                <fullName>Dealerships - Auto</fullName>
            </value>
            <value>
                <fullName>Dealerships - Recreational &amp; Machinery</fullName>
            </value>
            <value>
                <fullName>Drill Rig Owners</fullName>
            </value>
            <value>
                <fullName>Dry Cleaners</fullName>
            </value>
            <value>
                <fullName>Ecommerce</fullName>
            </value>
            <value>
                <fullName>Emergency Response Management</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Civil/Heavy Construction</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Drilling</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Enviro Remediation</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Oilsands</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Seismic &amp; Production</fullName>
            </value>
            <value>
                <fullName>Eng &amp; Consult - Utilities</fullName>
            </value>
            <value>
                <fullName>Entertainment and Recreation Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Status__c.field-meta.xml
<CustomField>
    <fullName>Credit_Status__c</fullName>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <label>Credit Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Archive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Terms__c.field-meta.xml
<CustomField>
    <fullName>Credit_Terms__c</fullName>
    <label>Credit Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>0.5% 10, Net 30 Days</fullName>
            </value>
            <value>
                <fullName>0.5% 20, Net 30 Days</fullName>
            </value>
            <value>
                <fullName>0.5% 25, Net 45 days</fullName>
            </value>
            <value>
                <fullName>1.5% 10, Net 60 days</fullName>
            </value>
            <value>
                <fullName>1.5% 15, Net 30 days</fullName>
            </value>
            <value>
                <fullName>1.5% 15, Net 60 days</fullName>
            </value>
            <value>
                <fullName>1.5% 15, Net 75 days</fullName>
            </value>
            <value>
                <fullName>1% 10, Net 30 days</fullName>
            </value>
            <value>
                <fullName>1% 10, Net 45 days</fullName>
            </value>
            <value>
                <fullName>1% 10, Net 60 days</fullName>
            </value>
            <value>
                <fullName>1% 15, Net 45 days</fullName>
            </value>
            <value>
                <fullName>1% 15, Net 60 days</fullName>
            </value>
            <value>
                <fullName>1% 15, Net 90 days</fullName>
            </value>
            <value>
                <fullName>1% 20, Net 30 days</fullName>
            </value>
            <value>
                <fullName>1% 20, Net 60 days</fullName>
            </value>
            <value>
                <fullName>1% 20, Net 75 days</fullName>
            </value>
            <value>
                <fullName>1% 20, Net 90 days</fullName>
            </value>
            <value>
                <fullName>1% 3, Net 15 days</fullName>
            </value>
            <value>
                <fullName>1% Net 30 Days</fullName>
            </value>
            <value>
                <fullName>2.5% 10, Net 30 days</fullName>
            </value>
            <value>
                <fullName>2.5% 15, Net 45 days</fullName>
            </value>
            <value>
                <fullName>2.5% 15, Net 60 days</fullName>
            </value>
            <value>
                <fullName>2.5% 15, Net 75 days</fullName>
            </value>
            <value>
                <fullName>2% 10, Net 15 days</fullName>
            </value>
            <value>
                <fullName>2% 10, Net 30 Days</fullName>
            </value>
            <value>
                <fullName>2% 10, Net 45 days</fullName>
            </value>
            <value>
                <fullName>2% 10, Net 60 days</fullName>
            </value>
            <value>
                <fullName>2% 10, Net 90 days</fullName>
            </value>
            <value>
                <fullName>2% 15, Net 120 days</fullName>
            </value>
            <value>
                <fullName>2% 15, Net 30 days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Primary_Service_Provider__c</fullName>
    <description>Displays the old Primary Service providers</description>
    <label>Primary Service Provider Old</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Clean Harbors</fullName>
                <default>true</default>
                <label>Clean Harbors</label>
            </value>
            <value>
                <fullName>CYN</fullName>
            </value>
            <value>
                <fullName>Emerald Services</fullName>
            </value>
            <value>
                <fullName>RS Used Oil</fullName>
            </value>
            <value>
                <fullName>Safety Kleen</fullName>
            </value>
            <value>
                <fullName>SK BPS</fullName>
            </value>
            <value>
                <fullName>Thermo Fluids</fullName>
            </value>
			<value>
                <fullName>Thompson</fullName>
            </value> 
            <value>
                <fullName>HPC</fullName>
            </value>
            <value>
                <fullName>Noble Oil</fullName>
            </value>
            <value>
                <fullName>HEPACO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Toggle_Me_to_Bypass_Validation__c.field-meta.xml
<CustomField>
    <fullName>Toggle_Me_to_Bypass_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is using for Test class Bypass</description>
    <label>Toggle Me to Bypass Validation</label>
    <type>Checkbox</type>
</CustomField> 

force-app/main/default/objects/Account/fields/WIN_Validated__c.field-meta.xml
<CustomField>
    <fullName>WIN_Validated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A boolean flag which determines if the record is validated based on WIN Complaint rules. All records with value as TRUE are then extracted by Beacon for downstream processing.</description>
    <label>Pending Beacon Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ConvertRecTypeController.cls
public class ConvertRecTypeController {

    public Account acc {get;set;}
    public Account accObj {get;set;}
    
    public ConvertRecTypeController(ApexPages.StandardController stdController){
        
        acc = (account)stdController.getRecord();
        accObj = new Account();
    }
    
    public PageReference updateRecType(){
        
        List<Account> accToUpdate = new List<Account>();
        
        Map<String, RecordType> recTypeByNameMap = new Map<String, RecordType>();
        for(RecordType rec : [Select Id, DeveloperName, SobjectType from Recordtype where SobjectType = 'Account']){
            recTypeByNameMap.put(rec.DeveloperName, rec);
        } 
        
        accObj = [Select Id, Name, RecordTypeId, RecordType.DeveloperName, Type,Class__c,Credit_Terms__c, Credit_Status__c, ShippingCountry,Primary_Service_Provider__c, Toggle_Me_to_Bypass_Validation__c from Account where Id =: acc.Id LIMIT 1];
        if(accObj.RecordTypeId == recTypeByNameMap.get(CHConstants.ACCOUNT_RECORD_TYPE_PROSPECT_DEVELOPER_NAME).Id){
            
            accObj.RecordTypeId = recTypeByNameMap.get(CHConstants.ACCOUNT_RECORD_TYPE_CUSTOMER).Id;
            accObj.Type = CHConstants.ACCOUNT_TYPE_CUSTOMER;
			accObj.Toggle_Me_to_Bypass_Validation__c = !accObj.Toggle_Me_to_Bypass_Validation__c;
			AccountCRUDHandler.updateAcctFromSTGtoCUST(new list<Account> {accObj});
            accToUpdate.add(accObj);
            
            for(Account childObj : [Select Id, RecordTypeId, Type from Account where ParentId =:accObj.Id]){
                
                childObj.RecordTypeId = recTypeByNameMap.get(CHConstants.ACCOUNT_RECORD_TYPE_CUSTOMER_LOCATION_DEVELOPER_NAME).Id;
                childObj.Type = CHConstants.ACCOUNT_TYPE_SHIPTO_GEN;
                accToUpdate.add(childObj);
            }
        }
        else if(accObj.RecordTypeId == recTypeByNameMap.get(CHConstants.ACCOUNT_RECORD_TYPE_PROSPECT_GEN_DEVELOPER_NAME).Id){
            
            accObj.RecordTypeId = recTypeByNameMap.get(CHConstants.ACCOUNT_RECORD_TYPE_CUSTOMER_LOCATION_DEVELOPER_NAME).Id;
            accObj.Type = CHConstants.ACCOUNT_TYPE_SHIPTO_GEN;
            //accObj.WIN_Validated__c = TRUE;
            accToUpdate.add(accObj);
        }
        
        Database.DMLOptions dml = new Database.DMLOptions(); 
        dml.DuplicateRuleHeader.AllowSave = true;
        Database.update(accToUpdate,dml); 
             
        PageReference acctPage = new PageReference('/' + accObj.Id+'/e?retURL='+ accObj.Id);
        acctPage.setRedirect(true);
        return acctPage;
    }
}