force-app/main/default/objects/Account/fields/CS_EPA_ID__c.field-meta.xml
<CustomField>
    <fullName>CS_EPA_ID__c</fullName>
    <inlineHelpText>The following fields are required in order to validate the EPA Id in addition to the EPA Id field. 
-Corporate Street 
-Corporate State 
-Corporate Country 
-Generator Status 
-Primary Service Provider</inlineHelpText>
    <label>EPA ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cycle__c.field-meta.xml
<CustomField>
    <fullName>Cycle__c</fullName>
    <label>Cycle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Committed</fullName>
            </value>
            <value>
                <fullName>Archive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Generator_Status__c.field-meta.xml
<CustomField>
    <fullName>Generator_Status__c</fullName>
	<inlineHelpText>An account&apos;s generator status can only be upgraded from Salesforce. Downgrades in this area need to be coordinated by our compliance team. For status downgrades, please submit a Service Now ticket using category/subcategory: WIN-Aurora(FocalPoint), CWT-Compliance or WIN-Compliance, EPA ID Number.</inlineHelpText>
    <label>Generator Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Large Quantity Generator</fullName>
            </value>
            <value>
                <fullName>Small Quantity Generator</fullName>
            </value>
            <value>
                <fullName>Conditionally Exempt Sm Qty Generator</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
                <default>true</default>
                <label>Undetermined</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/GENREG__c.field-meta.xml
<CustomField>
    <fullName>GENREG__c</fullName>
    <label>GenReg Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/High_Priority__c.field-meta.xml
<CustomField>
    <fullName>High_Priority__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is for Kafka to pickup records and split into streams</description>
    <label>High Priority</label>
    <type>Checkbox</type> 
</CustomField>

force-app/main/default/objects/Account/fields/New_Customer_validated__c.field-meta.xml
<CustomField>
    <fullName>New_Customer_validated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flagged when new customer is passed through the validation</description>
    <label>New Customer validation check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Business__c.field-meta.xml
<CustomField>
    <fullName>Primary_Business__c</fullName>
    <description>Primary business based off account owner</description>
    <label>Primary Service Provider</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Primary_Service_Provider_New__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Daylighting Services</fullName>
            </value>
            <value>
                <fullName>Emerald Services</fullName>
            </value>
            <value>
                <fullName>Field Services</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Industrial Services</fullName>
            </value>
            <value>
                <fullName>Lodging</fullName>
            </value>
            <value>
                <fullName>Murphys Oil</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Technical Services</fullName>
            </value>
            <value>
                <fullName>Thermo Fluids</fullName>
            </value>
            <value>
                <fullName>H2O</fullName>
            </value>
            <value>
                <fullName>BPS</fullName>
            </value>
            <value>
                <fullName>CYN</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>SK KPP</fullName>
            </value>
            <value>
                <fullName>Surface Rentals</fullName>
            </value>
            <value>
                <fullName>Seismic</fullName>
            </value>
            <value>
                <fullName>Safety-Kleen</fullName>
                <label>SK ENV</label>
            </value>
            <value>
                <fullName>OER</fullName>
            </value>
            <value>
                <fullName>HPC Industrial</fullName>
            </value>
            <value>
                <fullName>PSC</fullName>
            </value>
            <value>
                <fullName>Synergy</fullName>
            </value>
            <value>
                <fullName>DFW</fullName>
            </value>
			<value>
                <fullName>Thompson</fullName>
            </value>
			<value>
                <fullName>Noble Oil</fullName>
            </value>
            <value>
                <fullName>HEPACO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Primary_Service_Provider__c</fullName>
    <description>Displays the old Primary Service providers</description>
    <label>Primary Service Provider Old</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Clean Harbors</fullName>
                <default>true</default>
                <label>Clean Harbors</label>
            </value>
            <value>
                <fullName>CYN</fullName>
            </value>
            <value>
                <fullName>Emerald Services</fullName>
            </value>
            <value>
                <fullName>RS Used Oil</fullName>
            </value>
            <value>
                <fullName>Safety Kleen</fullName>
            </value>
            <value>
                <fullName>SK BPS</fullName>
            </value>
            <value>
                <fullName>Thermo Fluids</fullName>
            </value>
			<value>
                <fullName>Thompson</fullName>
            </value> 
            <value>
                <fullName>HPC</fullName>
            </value>
            <value>
                <fullName>Noble Oil</fullName>
            </value>
            <value>
                <fullName>HEPACO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/State_EPA_ID__c.field-meta.xml
<CustomField>
    <fullName>State_EPA_ID__c</fullName>
    <label>State EPA ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/WIN_Compliance_Errors__c.field-meta.xml
<CustomField>
    <fullName>WIN_Compliance_Errors__c</fullName>
    <description>In course of validation, if there are any errors, those errors are captured on this field and are presented to the user for necessary correction</description>
    <label>Pre-Submission Validation Errors</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/WIN_ID__c.field-meta.xml
<CustomField>
    <fullName>WIN_ID__c</fullName>
    <externalId>true</externalId>
    <label>WIN ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Win_ID_Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Win_ID_Sequence_Number__c</fullName>
    <label>Win ID Sequence Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Win_Validate_New__c.field-meta.xml
<CustomField>
    <fullName>Win_Validate_New__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Win Validate New</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/WIN_Validated__c.field-meta.xml
<CustomField>
    <fullName>WIN_Validated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A boolean flag which determines if the record is validated based on WIN Complaint rules. All records with value as TRUE are then extracted by Beacon for downstream processing.</description>
    <label>Pending Beacon Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Win_Validation_NonRollupAccount__c.field-meta.xml
<CustomField>
    <fullName>Win_Validation_NonRollupAccount__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Win Validation NonRollupAccount</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>All Clean Harbors Customers</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/EPA_SERVICE__c/EPA_SERVICE__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>EPA SERVICE</label>
</CustomObject>

force-app/main/default/objects/EPA_SERVICE__c/fields/ENDPOINT_URL__c.field-meta.xml
<CustomField>
    <fullName>ENDPOINT_URL__c</fullName>
    <label>ENDPOINT_URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Process__c/Integration_Process__c.object-meta.xml
<CustomObject>
    <label>Integration Process</label>
    <nameField>
        <label>Integration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Process__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Integration Processes</relationshipLabel>
    <relationshipName>Integration_Processes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Process__c/fields/Process_Type__c.field-meta.xml
<CustomField>
    <fullName>Process_Type__c</fullName>
    <label>Process Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ownerupdate</fullName>
            </value>
            <value>
                <fullName>BrokerRecordTypeUpdate</fullName>
            </value>
            <value>
                <fullName>WinValidateAndCreate</fullName>
            </value>
            <value>
                <fullName>OCROwnerUpdateBatchProcess</fullName>
            </value>
			<value>
                <fullName>Key Account Update</fullName>
            </value>
			<value>
                <fullName>Contact Error Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Process__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Ignored</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Old_New_Primary_Service_Provider_Mapping__mdt/Old_New_Primary_Service_Provider_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Old New Primary Service Provider Mapping</label>
    <pluralLabel>Old New Primary Service Provider Mapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/Old_New_Primary_Service_Provider_Mapping__mdt/fields/Primary_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Primary_Service_Provider__c</fullName>
    <label>Primary Service Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Old_New_Primary_Service_Provider_Mapping__mdt/fields/Primary_Service_Provider_ABV__c.field-meta.xml
<CustomField>
    <fullName>Primary_Service_Provider_ABV__c</fullName>
    <label>Primary Service Provider ABV</label>
    <length>255</length> 
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountValidatorController.cls
public without sharing class AccountValidatorController {
    private final static Id keyRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(CHConstants.ACCOUNT_RECORD_TYPE_REGIONAL_ACCOUNT_DEVELOPER_NAME).getRecordTypeId();
    private final static Id rfooAccountRecordType = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(CHConstants.ACCOUNT_RECORD_TYPE_RFOO).getRecordTypeId();
    private final static Id competitorAccountRecordType = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(CHConstants.ACCOUNT_RECORD_TYPE_COMPETITOR_DeveloperName).getRecordTypeId();
    private final static Set<String> prfSet = new Set<String>{'Integration', 'Customer Service Light-EOC'};  
    private final static Set<String> prfSetMDM = new Set<String>{'Master Data Management'};   
    private final static string ACCOUNT_STATUS_INACTIVE = 'Inactive'; 
    private final static List<string> AccountTypeNewCustomer= new List<string>{CHConstants.ACCOUNT_TYPE_CUSTOMER, CHConstants.ACCOUNT_RECORD_TYPE_DISTRIBUTOR, CHConstants.ACCOUNT_RECORD_TYPE_CUSTOMER_LOCATION_DEVELOPER_NAME, CHConstants.ACCOUNT_RECORD_TYPE_BROKER, CHConstants.ACCOUNT_RECORD_TYPE_BROKER_LOCATION_DEVELOPER_NAME}; 
    private final static List<string> EligibleEPAIDRecordTypes= new List<string>{CHConstants.ACCOUNT_TYPE_CUSTOMER,CHConstants.ACCOUNT_RECORD_TYPE_BROKER, CHConstants.ACCOUNT_RECORD_TYPE_DISTRIBUTOR, CHConstants.ACCOUNT_RECORD_TYPE_CUSTOMER_LOCATION_DEVELOPER_NAME, CHConstants.ACCOUNT_RECORD_TYPE_BROKER_LOCATION_DEVELOPER_NAME,CHConstants.ACCOUNT_RECORD_TYPE_DISTRIBUTOR_LOCATION_DEVELOPER_NAME,CHConstants.ACCOUNT_RECORD_TYPE_PROSPECT_DEVELOPER_NAME,CHConstants.ACCOUNT_RECORD_TYPE_PROSPECT_GEN_DEVELOPER_NAME};  

    @AuraEnabled  
    public static ValidateResponse validateAccount(string accountId){  
        Boolean iskeyAccount = false;
         
        ValidateResponse validateResObj = new ValidateResponse();
        
        try{
            Account accountRec = AccountDAO.getAccountsByIds(new Set<Id>{accountId})[0];
            
            Map<Id, String> accountIdErrorMessageMapping = Accounts.validateAccount(new Set<Id>{accountRec.Id}, true);
	        Map<Id,Profile> prfMap =  new Map<Id,Profile>([SELECT id from profile where name in ('Salesforce API Only System Integrations','Integration','Customer Service Light-EOC')]);//'System Administrator',
            Map<Id,Profile> prfMapMDM =  new Map<Id,Profile>([SELECT id from profile where name in ('Master Data Management')]);
            
            if(accountIdErrorMessageMapping.containsKey(accountRec.Id)){
                validateResObj.isSuccess = false; 
                validateResObj.message = accountIdErrorMessageMapping.get(accountRec.Id);
                accountRec.WIN_Compliance_Errors__c = accountIdErrorMessageMapping.get(accountRec.Id);
                UPDATE accountRec;
                return validateResObj;
            }
            if(Test.isRunningTest()  || (!prfMap.containsKey(userinfo.getProfileId())  
               && !prfMapMDM.containsKey(userinfo.getProfileId()))) {            // call the EPA REST API from here and based on this set the WIN validation and error details
                   EPAIdResponse epaResponse = validateEPAId(accountRec);
                   if(epaResponse != null && (epaResponse.validEpa != null || !epaResponse.validEpa)) {
                       if(epaResponse.messageCode == 0) {
                           validateResObj.isSuccess = true;
                           validateResObj.message = epaResponse.message; 
                       } else {
                           validateResObj.isSuccess = false;
                           validateResObj.message = epaResponse.exceptionMessage != null ? epaResponse.message + '$$' + epaResponse.exceptionMessage : epaResponse.message;
                           accountRec.WIN_Compliance_Errors__c = epaResponse.message;
                           update accountRec; 
                           return validateResObj;
                       }   
                   } 
               }
             
            Profile currentUserProfile = UserDAO.getProfileDetailsById(new Set<Id>{UserInfo.getProfileId()})[0];
            
            
            if(!accountRec.WIN_Validated__c  && !accountRec.Win_Validate_New__c && !accountRec.New_Customer_validated__c &&
               (accountRec.WIN_ID__c == null && (AccountTypeNewCustomer.contains(accountRec.RecordType.DeveloperName))) && (!prfSetMDM.contains(currentUserProfile.Name) || 
               (prfsetMDM.contains(currentUserProfile.Name) && accountRec.Primary_Business__c == CHConstants.ACCOUNT_PRIMARY_SERVICE_PROVIDER_HPC_INDUSTRIAL)))
            {
                AccountCRUDHandler.isAfterAccount = true;
                accountRec.New_Customer_validated__c = true;
                accountRec.WIN_Compliance_Errors__c='';
                AccountCRUDHandler.lockAccountRecord(accountRec,true);
               
            }
            if(!AccountTypeNewCustomer.contains(accountRec.RecordType.DeveloperName) && !accountRec.New_Customer_validated__c && accountRec.WIN_ID__c == null ) {
                // clear the WIN fields
                if(accountRec.type != 'Key Account')
                {
                    accountRec.WIN_Validated__c = true;
                    accountRec.High_Priority__c=true;
                }
                accountRec.Cycle__c = 'Committed';
                accountRec.WIN_Compliance_Errors__c = '';
			if(accountRec.WIN_Validated__c == true || accountRec.Win_Validate_New__c==true){
                	AccountCRUDHandler.lockAccountRecord(accountRec,true);
				}
				else{
					update accountRec;
				} 
			}
            if(String.isBlank(accountRec.WIN_ID__c)){
                if(accountRec.RecordTypeId == keyRecordTypeId){
                    iskeyAccount = true;
                    createWinIdForKeyAccount(accountRec);
                    update accountRec;								
                }
            } 
            
            if(iskeyAccount){
                updateWinValidateNoRollupChildAccounts(accountRec);
            }
            
            validateResObj.isSuccess = true;
        }catch(Exception exceptionObj){
            validateResObj.isSuccess = false;
            validateResObj.message = exceptionObj.getMessage();
			return validateResObj;
        }
        
        return validateResObj;
    }
    
    public static void updateWinValidateNoRollupChildAccounts(Account accountRec){
        List<Account> childAcct = new List<Account>();
        for(Account acc: [SELECT Id, Win_Validation_NonRollupAccount__c FROM Account 
                          WHERE Parentid =: accountRec.id and Status__c = 'Active'])
        {
            if(!acc.Win_Validation_NonRollupAccount__c){
                acc.Win_Validation_NonRollupAccount__c=true;
                childAcct.add(acc);
            }
        }
        
        if(!childAcct.isEmpty()){ 
            Database.SaveResult[] srResults= Database.update(childAcct, false);
            List<Integration_process__c> integrationProcesses = new List<Integration_process__c>();
            for(Database.SaveResult sr : srResults){
                if(!sr.isSuccess()){
                    Integration_process__c  integProcess= new Integration_process__c();
                    integProcess.Status__c = 'Error';
                    integProcess.Account__c = sr.Id;
                    integProcess.Process_Type__c = CHConstants.KeyAccountUpdate;
                    integProcess.Error_Message__c = sr.getErrors()[0].getMessage();
                    integrationProcesses.Add(integProcess);
                }
            }
            
            if(!integrationProcesses.isEmpty()){
                INSERT integrationProcesses;
            }
        }
    }
    
    private static void createWinIdForKeyAccount(Account accobj){
        Account lastAcc = new Account();
        
        List<Account> lastAccountLst = [Select Id, Win_ID_Sequence_Number__c FROM Account 
            WHERE RecordTypeId =: keyRecordTypeId AND Win_ID_Sequence_Number__c != NULL 
            ORDER BY Win_ID_Sequence_Number__c DESC LIMIT 1];
        
        if(!lastAccountLst.isEmpty()){
            lastAcc = lastAccountLst[0];
        }
            
        Integer currentSeqNumber =0;
        if(lastAcc.Id != NULL){
            currentSeqNumber = Integer.ValueOf(lastAcc.Win_ID_Sequence_Number__c) + 1;
        }
        
        String nameChar = accObj.Name.replace(' ', '').subString(0,2).toUpperCase();
        nameChar = nameChar.replace('.', '');
        accObj.WIN_ID__c = nameChar  + 'KEY' + String.valueOf(currentSeqNumber).leftPad(4, '0');
        accObj.WIN_ID_Sequence_Number__c = currentSeqNumber;
        accObj.Win_Validate_New__c = false;
        accObj.Win_Validation_NonRollupAccount__c = true; 
    }
       
    
    public class ValidateResponse{
        @AuraEnabled public Boolean isSuccess;
        @AuraEnabled public String message;
    }

    /**
* This method takes care of validating the EPA Id entered on the Account.
* Makes a RESTFUL callout to the EPA Service. Uses JSON as request and response.
* 
* @param account   the account record for which the validation is required
* @return true or false baesd on the valid EPA Id
*/ 
    public static EPAIdResponse validateEPAId(Account account) {
        Boolean isEPAIDValid = false;
        String tempGenStatus = '';
        String tempPrimaryProvider = '';
        String tempStateEpaid ='';
        String tempGenreg = '';
        EPAIdResponse response = null;
        
        // Construct the JSON Request
        JSONGenerator gen = JSON.createGenerator(true);
        
        if(EligibleEPAIDRecordTypes.contains(account.RecordType.DeveloperName)){
                //return null;

            // Check if there is null values and make them empty strings
            if(account.Generator_Status__c == null){   
                tempGenStatus = '';
            }
            if(account.Primary_Service_Provider__c == null){
                tempPrimaryProvider = '';
            }
              if(account.State_EPA_ID__c == null){
                tempStateEpaid = '';
            } else {
                tempStateEpaid = account.State_EPA_ID__c;
            }
             if(account.GENREG__c == null){
                tempGenreg ='';
             } else {
                 tempGenreg = account.GENREG__c;
             }
          
            if(account.Generator_Status__c == CHConstants.ACCOUNT_GEN_STATUS_LARGE_QTY_GENERATOR){
                tempGenStatus = CHConstants.ACCOUNT_GEN_STATUS_ABV_LARGE_QTY_GENERATOR;
            }
            else if(account.Generator_Status__c == CHConstants.ACCOUNT_GEN_STATUS_SMALL_QTY_GENERATOR){
                tempGenStatus = CHConstants.ACCOUNT_GEN_STATUS_ABV_SMALL_QTY_GENERATOR;
            }
            else if(account.Generator_Status__c == CHConstants.ACCOUNT_GEN_STATUS_CONDITIONALLY_QTY_GENERATOR){
                tempGenStatus = CHConstants.ACCOUNT_GEN_STATUS_ABV_CONDITIONALLY_QTY_GENERATOR;
            }
             else if(String.isBlank(account.Generator_Status__c) || account.Generator_Status__c == CHConstants.ACCOUNT_GEN_STATUS_NULL || account.Generator_Status__c == CHConstants.ACCOUNT_GEN_STATUS_UNDETERMINED){
                tempGenStatus = CHConstants.ACCOUNT_GEN_STATUS_ABV_NULL;
            }
            List<Old_New_Primary_Service_Provider_Mapping__mdt> primaryServiceProvMtdList = Old_New_Primary_Service_Provider_Mapping__mdt.getAll().values();
                for(Old_New_Primary_Service_Provider_Mapping__mdt primaryServiceProvObj : primaryServiceProvMtdList){
                    if(primaryServiceProvObj.Primary_Service_Provider__c == account.Primary_Service_Provider__c){
                        tempPrimaryProvider = primaryServiceProvObj.Primary_Service_Provider_ABV__c;
                        break;
                    } 
            }
            
            gen.writeStartObject();
            gen.writeStringField(CHConstants.EPA_JSON_REQ_EPA_ID, account.CS_EPA_ID__c);
            gen.writeStringField(CHConstants.EPA_JSON_REQ_ADDRESS_LINE_1, account.ShippingStreet);
            gen.writeStringField(CHConstants.EPA_JSON_REQ_CITY, account.ShippingCity);
            gen.writeStringField(CHConstants.EPA_JSON_REQ_STATE, account.ShippingState);
            gen.writeStringField(CHConstants.EPA_JSON_REQ_COUNTRY_CODE, account.ShippingCountry);
            gen.writeStringField(CHConstants.EPA_JSON_REQ_GENERATOR_STATUS, tempGenStatus);
            gen.writeStringField(CHConstants.EPA_JSON_REQ_PRIMARY_SERVICE_PROVIDER, tempPrimaryProvider);
            gen.writeStringField(CHConstants.EPA_JSON_RES_STATE_EPA_ID, tempStateEpaid);
            gen.writeStringField(CHConstants.EPA_JSON_RES_GENREG_ID, tempGenreg);
            gen.writeEndObject();
            String jsonString = gen.getAsString();
            HttpRequest req = new HttpRequest();
            Http http = new Http();
            req.setEndpoint(EPA_SERVICE__c.getInstance('EPA_SERVICE_ENDPOINT').ENDPOINT_URL__c);
            req.setHeader('Content-Type','application/json');
            req.setHeader('Content-Length',String.valueof(jsonString.length()));
            req.setMethod('POST');
            req.setBody(jsonString);
            
            try{
                HTTPResponse res = new HTTPResponse();
                response = new EPAIdResponse();
                res = http.send(req);
                return response.parse(res.getBody());
            }catch(Exception e){
                account.WIN_Compliance_Errors__c = Label.EPA_VALIDATION_EXCEPTION + e.getMessage();
            } 

        }
     
        return response;
    }  
    
    public class EPAIdResponse{
        @AuraEnabled public Boolean validEpa;
        @AuraEnabled public String message;
        @AuraEnabled public String exceptionMessage;
        @AuraEnabled public Integer messageCode;
        public EPAIdResponse parse(String json){
            return (EPAIdResponse) System.JSON.deserialize(json, EPAIdResponse.class);
 
        }
    }
}