force-app/main/default/objects/Account/fields/Current_Year_Customer_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Current_Year_Customer_Revenue__c</fullName>
    <label>Current Year Customer Revenue</label>
    <summarizedField>Financials__c.Customer_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Financials__c.Account_Revenue_Rollup__c</field>
        <operation>equals</operation>
        <value>Current Year</value>
    </summaryFilterItems>
    <summaryForeignKey>Financials__c.Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Key_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Key_Account_Name__c</fullName>
    <formula>IF(AND(RecordType.Name = &apos;Customer&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), Parent.Name,
IF(AND(RecordType.Name = &apos;Chain&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), Parent.Name,
IF(AND(RecordType.Name = &apos;Distributor&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), Parent.Name,
IF(AND(RecordType.Name = &apos;Broker&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), Parent.Name,
IF(AND(RecordType.Name = &apos;Customer Chain&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), Parent.Name,
IF(AND(RecordType.Name = &apos;Customer Location&apos;, Parent.Parent.RecordType.Name = &apos;Key Account&apos;), Parent.Parent.Name,
IF(AND(RecordType.Name = &apos;Broker Location&apos;, Parent.Parent.RecordType.Name = &apos;Key Account&apos;), Parent.Parent.Name,
IF(AND(RecordType.Name = &apos;Distributor Location&apos;, Parent.Parent.RecordType.Name = &apos;Key Account&apos;), Parent.Parent.Name,
IF(RecordType.Name = &apos;Customer Location&apos;, Parent.Parent.Name, 
IF(RecordType.Name = &apos;Broker Location&apos;, Parent.Parent.Name, 
IF(RecordType.Name = &apos;Distributor Location&apos;, Parent.Parent.Name, 
IF(RecordType.Name = &apos;Chain&apos;, Parent.Name, 
IF(RecordType.Name = &apos;Distributor&apos;, Parent.Name, 
IF(RecordType.Name = &apos;Broker&apos;, Parent.Name, 
IF(RecordType.Name = &apos;Customer&apos;, Parent.Name,
IF(RecordType.Name = &apos;Customer Chain&apos;, Parent.Name, 
IF(RecordType.Name = &apos;Prospect&apos;, Parent.Name,Name )))))))))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Corp/Key Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/WIN_ID__c.field-meta.xml
<CustomField>
    <fullName>WIN_ID__c</fullName>
    <externalId>true</externalId>
    <label>WIN ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/WIN_ID__c.field-meta.xml
<CustomField>
    <fullName>WIN_ID__c</fullName>
    <formula>Account.WIN_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>WIN ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TopAccounts.cls
public class TopAccounts {
   
    //this invocable method takes a single contact id from Flow from a record variable
    //and returns a list of lists of opportunities associated with that contact.
    //the list of lists is stored as a collection variable in the Flow.
    @InvocableMethod (label = 'Get Top Accounts By Location' description = 'returns top accounts by location.')
    
    //this method returns a List of Lists of Opps to the flow and receives a List of Ids
    public static List<List<WrapperForCAM>> getTopAccountsByLocation (List<Account> accounts) {
       Account acc =accounts.get(0);
        //Store in a list the id, closedate and Amounts of opps whose Primary Contact came in the variable "ids"
        //and who have a stage of Clsoed Won and a Close Date of this year
        AggregateResult[] results = [SELECT  ShippingCity, sum(Current_Year_Customer_Revenue__c) TotalAmount FROM Account where Key_Account_Name__c =:acc.Name 
			and status__c='Active' and win_id__c<>null
			group by ShippingCity order by sum(Current_Year_Customer_Revenue__c) desc limit 10]; 
        
        List<WrapperForCAM> wrapperAccounts=new List<WrapperForCAM>();
        for(AggregateResult result:results){
            WrapperForCAM wrapperAccount=new WrapperForCAM();
            wrapperAccount.amount = acc.CurrencyIsoCode+' '+ Decimal.valueOf(String.valueOf(result.get('TotalAmount')));
            wrapperAccount.shippingCity = String.valueOf(result.get('shippingCity'));
                
            wrapperAccounts.Add(wrapperAccount);
        }
        return new List<List<WrapperForCAM>>{wrapperAccounts};
    }  
}