force-app/main/default/objects/Account/fields/Expired__c.field-meta.xml
<CustomField>
    <fullName>Expired__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Flag identifies if this account is archived</inlineHelpText>
    <label>Archived</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Update_Date__c.field-meta.xml
<CustomField>
    <fullName>Update_Date__c</fullName>
    <label>Update Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/WIN_ID__c.field-meta.xml
<CustomField>
    <fullName>WIN_ID__c</fullName>
    <externalId>true</externalId>
    <label>WIN ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <inlineHelpText>Main=Main Contact (required)
PO=PO Requester
AP=Collections 
MANI=Manifest
SALE-Sales
SCHD=Scheduling
ACCT=Invoicing</inlineHelpText>
    <label>Contact Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MAIN</fullName>
            </value>
            <value>
                <fullName>PO</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>MANI</fullName>
            </value>
            <value>
                <fullName>ACCT</fullName>
            </value>
            <value>
                <fullName>SCHD</fullName>
            </value>
            <value>
                <fullName>SALE</fullName>
            </value>
            <value>
                <fullName>CERT</fullName>
            </value>
            <value>
                <fullName>COMP</fullName>
            </value>
            <value>
                <fullName>CORP</fullName>
            </value>
            <value>
                <fullName>CUST</fullName>
            </value>
            <value>
                <fullName>DEA</fullName>
            </value>
            <value>
                <fullName>ENG</fullName>
            </value>
            <value>
                <fullName>ENV</fullName>
            </value>
            <value>
                <fullName>ER</fullName>
            </value>
            <value>
                <fullName>HEAL</fullName>
            </value>
            <value>
                <fullName>HIS</fullName>
            </value>
            <value>
                <fullName>PURC</fullName>
            </value>
            <value>
                <fullName>REM</fullName>
            </value>
            <value>
                <fullName>SHIP</fullName>
            </value>
            <value>
                <fullName>TECH</fullName>
            </value>
            <value>
                <fullName>TRAK</fullName>
            </value>
			<value>
                <fullName>PLNT</fullName>
            </value>
            <value>
                <fullName>MAIT</fullName>
            </value>
            <value>
                <fullName>OPS</fullName>
            </value>
            <value>
                <fullName>TURN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Expired__c.field-meta.xml
<CustomField>
    <fullName>Expired__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to Expire the contact</description>
    <inlineHelpText>Checking expired will expire the entire contact. If you want to remove a type please use the contact type field</inlineHelpText>
    <label>Expired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Update_Date__c.field-meta.xml
<CustomField>
    <fullName>Update_Date__c</fullName>
    <label>Beacon Update Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WIN_ID__c.field-meta.xml
<CustomField>
    <fullName>WIN_ID__c</fullName>
    <formula>Account.WIN_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>WIN ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RestContact.cls
@RestResource(urlMapping = '/ManageContact/*')
global class RestContact {
@HttpGet
    global static List <Contact> getContact()
    { 
        List<Contact> c = [select id, WIN_ID__c,FirstName,LastName,Salutation,Contact_Type__c,Phone,Email from Contact limit 1];
                        //where createddate > startDate and createddate < enddate
                       return c;
    }  
    @HttpPost
    global static void doPost(String FirstName,String LastName,String WINID,String ContactType, String Phone, String Email, String Salutation,String Title,String Receieveemail, String SFcontactId, String UpdatedBy, String UpdatedDt)
    { Contact ct;
       Account a=[Select ID from Account where WIN_ID__C=:WINID];
         If(SFcontactId== '' )
    {
        ct=new Contact();     
    }ELSE{
        ct=[Select ID from Contact where Id=:SFcontactId];     
    }
     try{
            ct.FirstName=FirstName;
            ct.LastName=LastName;
            ct.Salutation=Salutation;
            ct.Phone=Phone;
            ct.Email=Email;
            ct.Title=Title;
            ct.AccountId=a.Id;
             if(ContactType == 'EXP')
             {
                 ct.Expired__c = True; 
             }
         else 
             if(ContactType == 'MAN'){
                 ct.Contact_Type__c = 'MANI'; 
             }
         else 
             if(ContactType == 'ACNT'){
             ct.Contact_Type__c = 'ACCT'; }
         else 
             if(ContactType == 'CSSR'){
             ct.Contact_Type__c = 'CUST'; }
             else
             { 
                 ct.Contact_Type__c=ContactType;
             }
         ct.Update_Date__c=Datetime.Now();
         if(SFcontactId==''){ 
             insert ct;
         }
         else {
             update ct;  
         }
      RestContext.response.responseBody = Blob.valueOf('{"contact_id" :"' +ct.Id +'","Error":""}');
        } catch (Exception e){
            RestContext.response.responseBody = Blob.valueOf('{"contact_id":"","Error": "'+ e.getMessage()+'"}');
            System.debug('Error Message'+ e.getMessage());
        }
}
}