force-app/main/default/objects/Account/fields/IS_Opportunity_Rank__c.field-meta.xml
<CustomField>
    <fullName>IS_Opportunity_Rank__c</fullName>
    <label>IS Opportunity Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/WIN_ID__c.field-meta.xml
<CustomField>
    <fullName>WIN_ID__c</fullName>
    <externalId>true</externalId>
    <label>WIN ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>All Clean Harbors Customers</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Customer_Location.recordType-meta.xml
<RecordType>
    <fullName>Customer_Location</fullName>
    <active>true</active>
    <description>All Clean Harbor Customer Ship-To/Gen Accounts</description>
    <label>Customer Location</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Opportunity_Rank__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Rank__c</fullName>
    <description>Opportunity score for inside sales account scoring purpose</description>
    <formula>IF( 
AND(
TODAY() &gt;=  DATEVALUE( LastModifiedDate ) + 15,

OR( 
Owner.UserRole.DeveloperName = &apos;SK_INS_BPS_AM&apos;,
Owner.UserRole.DeveloperName = &apos;SK_INS_SKE_AM&apos;
),

OwnerId =  Account.OwnerId,

AND(
NOT(ISPICKVAL( StageName , &apos;6 - Pending Services&apos;)),
NOT(ISPICKVAL( StageName , &apos;7 - Closed Won&apos;)),
NOT(ISPICKVAL( StageName , &apos;8 - Closed Lost&apos;))
),

OR(
Account.RecordType.DeveloperName = &apos;Customer&apos;,
Account.RecordType.DeveloperName = &apos;Customer_Location&apos;
),

ISPICKVAL(Account.Status__c, &apos;Active&apos;),
NOT( ISBLANK( Account.WIN_ID__c ) )
), 

9, null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/WIN_ID__c.field-meta.xml
<CustomField>
    <fullName>WIN_ID__c</fullName>
    <description>WIN ID of account picked for opportunity.</description>
    <formula>Account.WIN_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>WIN ID of account picked for opportunity.</inlineHelpText>
    <label>WIN ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityRankBatch.cls
public class OpportunityRankBatch implements Database.Batchable<sObject>{
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        if(!Test.isRunningTest()){
            String query = 'SELECT Id,Opportunity_Rank__c, accountid, account.IS_Opportunity_Rank__c FROM Opportunity where LastModifiedDate <= LAST_N_DAYS:15 AND Opportunity_Rank__c!= null AND account.IS_Opportunity_Rank__c = null AND account.Status__c = \'Active\' AND account.win_id__c != null AND (account.RecordType.DeveloperName = \'Customer\' OR account.RecordType.DeveloperName = \'Customer_Location\')';
            return Database.getQueryLocator(query);
        }else if(Test.isRunningTest()){
            String query = 'SELECT Id,Opportunity_Rank__c, accountid, account.IS_Opportunity_Rank__c FROM Opportunity where LastModifiedDate = Today AND Opportunity_Rank__c = null AND account.IS_Opportunity_Rank__c = null AND account.Status__c = \'Active\' AND account.win_id__c != null AND (account.RecordType.DeveloperName = \'Customer\' OR account.RecordType.DeveloperName = \'Customer_Location\')';
            return Database.getQueryLocator(query);
        }
        return null;
    }
    
    public void execute(Database.BatchableContext BC, List<sObject> scope){
        map<Id, decimal> accoppMap = new map<Id, decimal>();
        List<account> updateAccountList = new List<account>();
        List<Opportunity> oppList = (List<Opportunity>)scope;
        for (Opportunity o:oppList){
            if(accoppMap.isEmpty() || !accoppMap.containsKey(o.accountid)){
                accoppMap.put(o.accountid, o.Opportunity_Rank__c);
            }  
        }
        
        for(id accid: accoppMap.keyset()){
            Account newAcc = new Account();
            newAcc.id = accid;
            newAcc.IS_Opportunity_Rank__c = accoppMap.get(accid);
            updateAccountList.add(newAcc);
        }
        if(updateAccountList.size() > 0){
            List <Database.SaveResult> SaveResultList = Database.update(updateAccountList,false);
            ExceptionLogHelper.logException(true, SaveResultList, 'Account', updateAccountList, 'OpportunityRankBatch', 'execute');
            
        } 
    }
    
    public void finish(Database.BatchableContext BC){
        
    } 
    
    
}