force-app/main/default/objects/Account/fields/Key_Account_Assign_Override__c.field-meta.xml
<CustomField>
    <fullName>Key_Account_Assign_Override__c</fullName>
    <formula>IF(RecordType.Name = &apos;Customer Location&apos;,(Parent.Parent.Account_Assign_Override__c),
IF(RecordType.Name = &apos;Customer&apos;,(Parent.Account_Assign_Override__c), NULL ))</formula>
    <label>Key Account Assign Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Key_Account_Support_Person__c.field-meta.xml
<CustomField>
    <fullName>Key_Account_Support_Person__c</fullName>
    <formula>IF(AND(RecordType.Name = &apos;Customer&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Chain&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Distributor&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Broker&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Customer Chain&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Customer Location&apos;, Parent.Parent.RecordType.Name = &apos;Key Account&apos;), Parent.Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Broker Location&apos;, Parent.Parent.RecordType.Name = &apos;Key Account&apos;), Parent.Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Distributor Location&apos;, Parent.Parent.RecordType.Name = &apos;Key Account&apos;), Parent.Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName ,
IF(RecordType.Name = &apos;Customer Location&apos;,  Parent.Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName , 
IF(RecordType.Name = &apos;Distributor Location&apos;,  Parent.Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName, 
IF(RecordType.Name = &apos;Broker Location&apos;,  Parent.Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName , 
IF(RecordType.Name = &apos;Customer&apos;,  Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(RecordType.Name = &apos;Key Account&apos;,  Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(RecordType.Name = &apos;Customer Chain&apos;,  Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(RecordType.Name = &apos;Distributor&apos;,  Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(RecordType.Name = &apos;Broker&apos;,  Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(RecordType.Name = &apos;Chain&apos;,  Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,&apos;&apos;)))))))))))))))))</formula>
    <label>Corp/Key Account Support Person</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Key_Buying_Decision__c.field-meta.xml
<CustomField>
    <fullName>Key_Buying_Decision__c</fullName>
    <formula>IF(AND(RecordType.Name = &apos;Customer&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), text(Parent.Buying_Decision__c),
IF(AND(RecordType.Name = &apos;Distibutor&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), text(Parent.Buying_Decision__c),
IF(AND(RecordType.Name = &apos;Broker&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), text(Parent.Buying_Decision__c),
IF(AND(RecordType.Name = &apos;Customer Chain&apos;, Parent.RecordType.Name = &apos;Key Account&apos;),  text(Parent.Buying_Decision__c),
IF(AND(RecordType.Name = &apos;Chain&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), text(Parent.Buying_Decision__c),
IF(AND(RecordType.Name = &apos;Customer Location&apos;, Parent.Parent.RecordType.Name = &apos;Key Account&apos;), text(Parent.Parent.Buying_Decision__c),
IF(AND(RecordType.Name = &apos;Distributor Location&apos;, Parent.Parent.RecordType.Name = &apos;Key Account&apos;), text(Parent.Parent.Buying_Decision__c),
IF(AND(RecordType.Name = &apos;Broker Location&apos;, Parent.Parent.RecordType.Name = &apos;Key Account&apos;), text(Parent.Parent.Buying_Decision__c),
IF(RecordType.Name = &apos;Customer Location&apos;, IF(ISBLANK(text(Parent.Parent.Buying_Decision__c)), text(Chain__r.Buying_Decision__c), text(Parent.Parent.Buying_Decision__c)),
IF(RecordType.Name = &apos;Broker Location&apos;, text(Parent.Parent.Buying_Decision__c),
IF(RecordType.Name = &apos;Distributor Location&apos;, text(Parent.Parent.Buying_Decision__c),
IF(RecordType.Name = &apos;Pricing Chain&apos;, text(Parent.Buying_Decision__c),
IF(RecordType.Name = &apos;Distributor&apos;, text(Parent.Buying_Decision__c),
IF(RecordType.Name = &apos;Broker&apos;, text(Parent.Buying_Decision__c),
IF(RecordType.Name = &apos;Customer&apos;, IF(ISBLANK(text(Parent.Buying_Decision__c)), text(Chain__r.Buying_Decision__c), text(Parent.Buying_Decision__c)),
IF(RecordType.Name = &apos;Chain&apos;, text(Buying_Decision__c),
IF(RecordType.Name = &apos;Customer Chain&apos;, text(Parent.Buying_Decision__c), text(Buying_Decision__c) )))))))))))))))))</formula>
    <label>Corp/Key Account Buying Decision</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bypass_Account_Validation__c/Bypass_Account_Validation__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bypass Account Validation</label>
</CustomObject>

force-app/main/default/objects/Bypass_Account_Validation__c/fields/Bypass_Manifest_Address_Requirement__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Manifest_Address_Requirement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Manifest Address Requirement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ChildKAMSupportProcessBatch.cls
public class ChildKAMSupportProcessBatch implements Database.Batchable<sObject>{
	private Set<Id> successKAMSupportAccountIds;    
    private Map<Id, String> failedAccRecordMap = new Map<Id, String>();
    
    public ChildKAMSupportProcessBatch(Set<Id> successKAMSupportAccountIds){
        this.successKAMSupportAccountIds = successKAMSupportAccountIds;
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        Id customerAccountRecordType = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get(CHConstants.ACCOUNT_RECORD_TYPE_CUSTOMER).getRecordTypeId();
    	Id customerLocationAccountRecordType = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get(CHConstants.ACCOUNT_RECORD_TYPE_CUSTOMER_LOCATION).getRecordTypeId();
        Set<Id> successKAMSupportAccountIds = successKAMSupportAccountIds;
        
        Bypass_Account_Validation__c accountValidation = Bypass_Account_Validation__c.getOrgDefaults();
        accountValidation.Bypass_Manifest_Address_Requirement__c = true; 
        UPDATE accountValidation;
        
        String query = 'SELECT Id, Key_Account_Support_Person__c ';
        query += 'FROM Account ';
        query += 'WHERE Key_Account_Assign_Override__c = FALSE AND Status__c != \'Inactive\' ';
        query += 'AND ParentId IN :successKAMSupportAccountIds ';
        query += 'AND Status__c != \'Archive\' AND Key_Account_Support_Person__c != NULL ';
        query += 'AND Key_Buying_Decision__c = \'Central Buying\' ';
        query += 'AND (RecordTypeId = :customerLocationAccountRecordType OR RecordTypeId = :customerAccountRecordType)';
        
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Account> scope){
        Map<String, User> UserbyName = new Map<String, User>();
        Set<String> CASNames = new Set<String>();
        
        for(Account childAccountRec : scope){
            CASNames.add(childAccountRec.Key_Account_Support_Person__c);
        }
        
        for(User Obj : [Select Id, Name from User where isActive = TRUE and Name IN : CASNames]){
            UserbyName.put(Obj.Name, Obj);
        }
        
        List<Account> updateChildAccounts = new List<Account>();
        
        for(Account childAccountRec : scope){
            if(UserByName.ContainsKey(childAccountRec.Key_Account_Support_Person__c)){
                childAccountRec.OwnerId = UserByName.get(childAccountRec.Key_Account_Support_Person__c).Id;
                updateChildAccounts.add(childAccountRec);
            }
        }
        
        if(updateChildAccounts.size() > 0){
            List<Database.SaveResult> saveResultLst = Database.update(updateChildAccounts, false);
            
            for (Database.SaveResult saveResultObj : saveResultLst) {
                if (!saveResultObj.isSuccess()) {
                    //saveResultObj.getId();
                    String errorMsg = '';
                    for(Database.Error err : saveResultObj.getErrors()) {
                        errorMsg += err.getMessage() + '\n';
                    }
                    
                    if(errorMsg.length() > 0)
                        errorMsg = errorMsg.substring(0, errorMsg.length() - 2); 
                    //failedAccRecordMap.put(key, value)
                }
            }
        } 
    }
    
    public void finish(Database.BatchableContext BC){
        Bypass_Account_Validation__c accountValidation = Bypass_Account_Validation__c.getOrgDefaults();
        accountValidation.Bypass_Manifest_Address_Requirement__c = false; 
        UPDATE accountValidation;
    }
}