force-app/main/default/objects/Account/fields/Key_Account_Support_Person__c.field-meta.xml
<CustomField>
    <fullName>Key_Account_Support_Person__c</fullName>
    <formula>IF(AND(RecordType.Name = &apos;Customer&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Chain&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Distributor&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Broker&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Customer Chain&apos;, Parent.RecordType.Name = &apos;Key Account&apos;), Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Customer Location&apos;, Parent.Parent.RecordType.Name = &apos;Key Account&apos;), Parent.Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Broker Location&apos;, Parent.Parent.RecordType.Name = &apos;Key Account&apos;), Parent.Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName ,
IF(AND(RecordType.Name = &apos;Distributor Location&apos;, Parent.Parent.RecordType.Name = &apos;Key Account&apos;), Parent.Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName ,
IF(RecordType.Name = &apos;Customer Location&apos;,  Parent.Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName , 
IF(RecordType.Name = &apos;Distributor Location&apos;,  Parent.Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName, 
IF(RecordType.Name = &apos;Broker Location&apos;,  Parent.Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.Parent.KAM_Support__r.LastName , 
IF(RecordType.Name = &apos;Customer&apos;,  Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(RecordType.Name = &apos;Key Account&apos;,  Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(RecordType.Name = &apos;Customer Chain&apos;,  Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(RecordType.Name = &apos;Distributor&apos;,  Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(RecordType.Name = &apos;Broker&apos;,  Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,
IF(RecordType.Name = &apos;Chain&apos;,  Parent.KAM_Support__r.FirstName  + &quot; &quot; + Parent.KAM_Support__r.LastName ,&apos;&apos;)))))))))))))))))</formula>
    <label>Corp/Key Account Support Person</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Business__c.field-meta.xml
<CustomField>
    <fullName>Primary_Business__c</fullName>
    <description>Primary business based off account owner</description>
    <label>Primary Service Provider</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Primary_Service_Provider_New__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Daylighting Services</fullName>
            </value>
            <value>
                <fullName>Emerald Services</fullName>
            </value>
            <value>
                <fullName>Field Services</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Industrial Services</fullName>
            </value>
            <value>
                <fullName>Lodging</fullName>
            </value>
            <value>
                <fullName>Murphys Oil</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Technical Services</fullName>
            </value>
            <value>
                <fullName>Thermo Fluids</fullName>
            </value>
            <value>
                <fullName>H2O</fullName>
            </value>
            <value>
                <fullName>BPS</fullName>
            </value>
            <value>
                <fullName>CYN</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>SK KPP</fullName>
            </value>
            <value>
                <fullName>Surface Rentals</fullName>
            </value>
            <value>
                <fullName>Seismic</fullName>
            </value>
            <value>
                <fullName>Safety-Kleen</fullName>
                <label>SK ENV</label>
            </value>
            <value>
                <fullName>OER</fullName>
            </value>
            <value>
                <fullName>HPC Industrial</fullName>
            </value>
            <value>
                <fullName>PSC</fullName>
            </value>
            <value>
                <fullName>Synergy</fullName>
            </value>
            <value>
                <fullName>DFW</fullName>
            </value>
			<value>
                <fullName>Thompson</fullName>
            </value>
			<value>
                <fullName>Noble Oil</fullName>
            </value>
            <value>
                <fullName>HEPACO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Service_Provider_New__c.field-meta.xml
<CustomField>
    <fullName>Primary_Service_Provider_New__c</fullName>
    <label>Operating Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SK ENV</fullName>
            </value>
            <value>
                <fullName>SK BPS</fullName>
            </value>
            <value>
                <fullName>SK KPP</fullName>
            </value>
            <value>
                <fullName>Clean Harbors ENV</fullName>
            </value>
            <value>
                <fullName>CHES Oil and Gas</fullName>
            </value>
            <value>
                <fullName>CHES Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ZIP_Master__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZIP Master</label>
    <referenceTo>ZIP_Master__c</referenceTo>
    <relationshipLabel>Accounts (ZIP Master)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bypass_Account_Validation__c/Bypass_Account_Validation__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bypass Account Validation</label>
</CustomObject>

force-app/main/default/objects/Bypass_Account_Validation__c/fields/Bypass_Manifest_Address_Requirement__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Manifest_Address_Requirement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Manifest Address Requirement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/ZIP_Master__c.object-meta.xml
<CustomObject>
    <label>ZIP Master</label>
    <nameField>
        <label>ZIP Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZIP Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/UpdateAccountTerritoryBatch.cls
public class UpdateAccountTerritoryBatch implements Database.Batchable<sObject>, Database.Stateful {
    private Set<Id> corporateAccountIdsSet;
    private Set<Id> corporateAccountIdsNewSet = new Set<Id>();
    private Boolean isParent;
    
    public UpdateAccountTerritoryBatch(Set<Id> corporateAccountIdsSet, Boolean isParent){
        this.corporateAccountIdsSet = corporateAccountIdsSet;
        this.isParent = isParent;
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        Id customerAccountRecordType = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get(CHConstants.ACCOUNT_RECORD_TYPE_CUSTOMER).getRecordTypeId();
    	Id customerLocationAccountRecordType = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get(CHConstants.ACCOUNT_RECORD_TYPE_CUSTOMER_LOCATION).getRecordTypeId();
        
        Set<Id> corporateAccountIdsSet = corporateAccountIdsSet;
        
        Bypass_Account_Validation__c accountValidation = Bypass_Account_Validation__c.getOrgDefaults();
        accountValidation.Bypass_Manifest_Address_Requirement__c = true; 
        UPDATE accountValidation;
        
        String query = 'SELECT Id, Key_Account_Support_Person__c, ZIP_Master__c, Primary_Service_Provider_New__c, Primary_Business__c ';
        query += 'FROM Account ';
        query += 'WHERE ParentId IN :corporateAccountIdsSet ';
        query += 'AND Status__c != \'Inactive\' ';
        query += 'AND Status__c != \'Archive\' ';
        query += 'AND (Primary_Service_Provider_New__c = \'SK ENV\' OR Primary_Service_Provider_New__c = \'SK BPS\') ';
        query += 'AND (RecordTypeId = :customerLocationAccountRecordType OR RecordTypeId = :customerAccountRecordType) ';
        query += 'AND ZIP_Master__c != NULL';
        
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Account> scope){
        this.corporateAccountIdsNewSet.addAll(UpdateAccountTerritoryBatchHandler.updateAccountTerritory(scope, this.isParent));
    }
    
    public void finish(Database.BatchableContext BC){
        if(this.isParent){
            Database.executeBatch(new UpdateAccountTerritoryBatch(this.corporateAccountIdsNewSet, false), 50);
        }
        
        Bypass_Account_Validation__c accountValidation = Bypass_Account_Validation__c.getOrgDefaults();
        accountValidation.Bypass_Manifest_Address_Requirement__c = false; 
        UPDATE accountValidation;
    }
}