force-app/main/default/objects/Account/fields/Number_of_Hires__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Hires__c</fullName>
    <label>Number of Hires</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Category__c.field-meta.xml
<CustomField>
    <fullName>Organization_Category__c</fullName>
    <label>Organization Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>College</fullName>
                <isActive>false</isActive>
                <label>College</label>
            </value>
            <value>
                <fullName>College or University</fullName>
            </value>
            <value>
                <fullName>Diversity Organization</fullName>
            </value>
            <value>
                <fullName>Driver School</fullName>
            </value>
            <value>
                <fullName>Military Agency</fullName>
            </value>
            <value>
                <fullName>Military Base</fullName>
            </value>
            <value>
                <fullName>National Organization</fullName>
                <isActive>false</isActive>
                <label>National Organization</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Skilled Trades Technical/Professional</fullName>
            </value>
            <value>
                <fullName>State Workforce Agency</fullName>
            </value>
            <value>
                <fullName>Technical High School</fullName>
                <isActive>false</isActive>
                <label>Technical High School</label>
            </value>
            <value>
                <fullName>Trade High School</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
                <isActive>false</isActive>
                <label>Website</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_ID__c.field-meta.xml
<CustomField>
    <fullName>Organization_ID__c</fullName>
    <displayFormat>Org-{00000}</displayFormat>
    <label>Organization ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Status__c.field-meta.xml
<CustomField>
    <fullName>Organization_Status__c</fullName>
    <label>Organization Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Qualifying</fullName>
            </value>
            <value>
                <fullName>Qualified Partner</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Strategic Partner</fullName>
            </value>
            <value>
                <fullName>Archive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Size_of_Candidate_Pool__c.field-meta.xml
<CustomField>
    <fullName>Size_of_Candidate_Pool__c</fullName>
    <label>Size of Candidate Pool</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/HR_Talent_Pools.recordType-meta.xml
<RecordType>
    <fullName>HR_Talent_Pools</fullName>
    <active>true</active>
    <description>HR Partnership organizations used to recruit from their talent pools</description>
    <label>HR Recruiting Partners</label>
</RecordType>

force-app/main/default/objects/Location/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Location/fields/Location_ID__c.field-meta.xml
<CustomField>
    <fullName>Location_ID__c</fullName>
    <displayFormat>Loc- {00000}</displayFormat>
    <label>Location ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Location/fields/Location_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Location_Phone_Number__c</fullName>
    <label>Location Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Location/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <formula>TEXT(Address__StateCode__s) &amp; &quot; &quot; &amp; Address__City__s</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location/fields/Number_of_Hires__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Hires__c</fullName>
    <label>Number of Hires</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Location/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>HR Recruiting Partners</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location/fields/Size_of_Candidate_Pool__c.field-meta.xml
<CustomField>
    <fullName>Size_of_Candidate_Pool__c</fullName>
    <label>Size of Candidate Pool</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Location/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LocationServiceTest.cls
/**
 * @description       : 
 * @author            : Irfan Khan
 * @group             : 
 * @last modified on  : 10-13-2022
 * @last modified by  : Suresh Beniwal
 * Modifications Log
 * Ver   Date         Author       Modification
 * 1.0   08-08-2022   Irfan Khan   Initial Version
**/
@isTest 
private class LocationServiceTest {
    private final static string TEST_NAME = 'Nandyala';
    private final static string TEST_STREET = '518501 Farook Nagar';
    private final static string TEST_CITY = 'Nandyala';
    private final static string TEST_StateCode = 'AP';
    private final static string TEST_CountryCode = 'IN';
    private final static string TEST_PostalCode = '518501';
    
@testSetup static void setupmethod() {
        Id RecordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('HR_Talent_Pools').getRecordTypeId();
        Account acc = new Account();
        acc.Name = 'Farheen';
        acc.RecordTypeId = RecordTypeIdAccount;
        acc.Organization_Status__c ='Draft';
        //acc.Organization_ID__c = acc.id;
        acc.Organization_Category__c = 'Driver School';
        acc.ShippingStreet = '123';
        acc.ShippingCity = 'Jaipur';
        acc.ShippingState = 'Rajasthan';
        acc.ShippingCountry = 'US';
        acc.ShippingPostalCode = '302012';
        insert acc;

        Schema.Location loc = new Schema.Location();
        loc.Organization__c = acc.Id;
        loc.Name = TEST_NAME ;
        loc.Address__Street__s = TEST_STREET;
        loc.Address__City__s = TEST_CITY;
        loc.Address__StateCode__s = TEST_StateCode;
        loc.Address__CountryCode__s = TEST_CountryCode;
        loc.Address__PostalCode__s =TEST_PostalCode;
    
      Test.startTest();
            insert loc;
        Test.stopTest();
}
     @IsTest static void TestOrganizationOwner(){
        List<Schema.Location> LocList = [SELECT Id,Name__c, Name,Location_Id__c,Address__c, Address__Street__s, Address__City__s,Address__StateCode__s,Address__CountryCode__s,Address__PostalCode__s,Location_Phone_Number__c,Size_of_Candidate_Pool__c,Number_of_Hires__c,Status__c,Organization__r.Name, Organization__r.Organization_Id__c FROM Location WHERE Name =: TEST_NAME];
         
         Test.startTest();
            List<LocationService.LocationWrapper> listOfLocationWrapper = LocationService.getListOfLocations(LocList);
        Test.stopTest();
         
         System.assertEquals(false, listOfLocationWrapper.isEmpty(), 'Wrapper data should be return !!');
     }
}