force-app/main/default/objects/Account/fields/Number_of_Hires__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Hires__c</fullName>
    <label>Number of Hires</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_ID__c.field-meta.xml
<CustomField>
    <fullName>Organization_ID__c</fullName>
    <displayFormat>Org-{00000}</displayFormat>
    <label>Organization ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/Size_of_Candidate_Pool__c.field-meta.xml
<CustomField>
    <fullName>Size_of_Candidate_Pool__c</fullName>
    <label>Size of Candidate Pool</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Location/fields/Location_ID__c.field-meta.xml
<CustomField>
    <fullName>Location_ID__c</fullName>
    <displayFormat>Loc- {00000}</displayFormat>
    <label>Location ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Location/fields/Location_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Location_Phone_Number__c</fullName>
    <label>Location Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Location/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <formula>TEXT(Address__StateCode__s) &amp; &quot; &quot; &amp; Address__City__s</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location/fields/Number_of_Hires__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Hires__c</fullName>
    <label>Number of Hires</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Location/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>HR Recruiting Partners</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location/fields/Size_of_Candidate_Pool__c.field-meta.xml
<CustomField>
    <fullName>Size_of_Candidate_Pool__c</fullName>
    <label>Size of Candidate Pool</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Location/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LocationService.cls
/**
 * @description       : 
 * @author            : Suresh Beniwal
 * @group             : 
 * @last modified on  : 10-13-2022
 * @last modified by  : Suresh Beniwal
 * Modifications Log
 * Ver   Date         Author           Modification
 * 1.0   06-10-2022   Suresh Beniwal   Initial Version
**/
public without sharing class LocationService { 
    
    /**
    * @description 
    * @author Suresh Beniwal | 06-10-2022 
    * @param List<Schema.Location> listOfLocations 
    * @return List<LocationWrapper> 
    **/
    public static List<LocationWrapper> getListOfLocations(List<Schema.Location> listOfLocations) {
        List<LocationWrapper> listOfLocationWrapper = new List<LocationWrapper>();

        for (Schema.Location locationRecord: listOfLocations) {
            LocationWrapper locationWrapperRecord = new LocationWrapper();
            locationWrapperRecord.locationCode = locationRecord.Location_Id__c;
            locationWrapperRecord.locationName = locationRecord.Name__c;
            locationWrapperRecord.locationPhoneNumber = locationRecord.Location_Phone_Number__c;
            locationWrapperRecord.status = locationRecord.Status__c;
            locationWrapperRecord.sizeOfCandidatePool = locationRecord.Size_of_Candidate_Pool__c;
            locationWrapperRecord.numberOfHires = locationRecord.Number_of_Hires__c;
            locationWrapperRecord.organizationName = locationRecord.Organization__r.Name;
            locationWrapperRecord.organizationCode = locationRecord.Organization__r.Organization_Id__c;
            locationWrapperRecord.address = locationRecord.Address__Street__s != null ? (locationRecord.Address__Street__s + ' , ' + locationRecord.Address__City__s + ' , ' + locationRecord.Address__StateCode__s + ' , ' + locationRecord.Address__CountryCode__s + ' ' + locationRecord.Address__PostalCode__s) : '';
            locationWrapperRecord.street = locationRecord.Address__Street__s;
            locationWrapperRecord.city = locationRecord.Address__City__s;
            locationWrapperRecord.state = locationRecord.Address__StateCode__s;
            System.Address address = locationRecord.Address__c;
            locationWrapperRecord.country = address?.country;
            locationWrapperRecord.zipcode = locationRecord.Address__PostalCode__s;

            listOfLocationWrapper.add(locationWrapperRecord);
        }

        return listOfLocationWrapper;
    }

    public class LocationWrapper {
        @AuraEnabled public String locationCode;
        @AuraEnabled public String organizationCode;
        @AuraEnabled public String locationName;
        @AuraEnabled public String locationPhoneNumber;
        @AuraEnabled public String status;
        @AuraEnabled public Decimal sizeOfCandidatePool;
        @AuraEnabled public Decimal numberOfHires;
        @AuraEnabled public String organizationName;
        @AuraEnabled public String address;
        @AuraEnabled public String street;
        @AuraEnabled public String city;
        @AuraEnabled public String state;
        @AuraEnabled public String country;
        @AuraEnabled public String zipcode;
    }
}