force-app/main/default/objects/Account/fields/Number_of_Hires__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Hires__c</fullName>
    <label>Number of Hires</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_ID__c.field-meta.xml
<CustomField>
    <fullName>Organization_ID__c</fullName>
    <displayFormat>Org-{00000}</displayFormat>
    <label>Organization ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/Size_of_Candidate_Pool__c.field-meta.xml
<CustomField>
    <fullName>Size_of_Candidate_Pool__c</fullName>
    <label>Size of Candidate Pool</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Location/fields/Location_ID__c.field-meta.xml
<CustomField>
    <fullName>Location_ID__c</fullName>
    <displayFormat>Loc- {00000}</displayFormat>
    <label>Location ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Location/fields/Location_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Location_Phone_Number__c</fullName>
    <label>Location Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Location/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <formula>TEXT(Address__StateCode__s) &amp; &quot; &quot; &amp; Address__City__s</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location/fields/Number_of_Hires__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Hires__c</fullName>
    <label>Number of Hires</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Location/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>HR Recruiting Partners</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location/fields/Size_of_Candidate_Pool__c.field-meta.xml
<CustomField>
    <fullName>Size_of_Candidate_Pool__c</fullName>
    <label>Size of Candidate Pool</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Location/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LocationDAO.cls
/**
 * @description       : 
 * @author            : Suresh Beniwal
 * @group             : 
 * @last modified on  : 10-13-2022
 * @last modified by  : Suresh Beniwal
 * Modifications Log
 * Ver   Date         Author           Modification
 * 1.0   06-28-2022   Suresh Beniwal   Initial Version
**/
public with sharing class LocationDAO {
    public static Id hrTalentPoolsContactRecordType = Schema.Sobjecttype.Account.getRecordTypeInfosByDeveloperName().get(CHConstants.ACCOUNT_RECORD_TYPE_HR_TALENT_POOLS).getRecordTypeId();

    /**
    * @description 
    * @author Suresh Beniwal | 06-28-2022 
    * @param Set<Id> setOfId 
    * @return List<Schema.Location> 
    **/
    public static List<Schema.Location> getLocationsBySetOfId(Set<Id> setOfId) {
        return [
            SELECT Id, Name, Location_Id__c, Organization__c, Name__c, Location_Phone_Number__c , Address__c, Status__c, Organization__r.Name, Organization__r.Organization_Id__c,
                Address__Street__s, Address__PostalCode__s, Address__City__s, Address__StateCode__s, Address__CountryCode__s, Size_of_Candidate_Pool__c, Number_of_Hires__c
            FROM Location 
            WHERE Id IN: setOfId AND Organization__c != null 
                AND Organization__r.RecordTypeId =: hrTalentPoolsContactRecordType ORDER BY LastModifiedDate DESC NULLS FIRST];
    }

    /**
    * @description 
    * @author Suresh Beniwal | 07-01-2022 
    * @param Set<Id> setOfId 
    * @return List<Schema.Location> 
    **/
    public static List<Schema.Location> getLocationsByOrganizationIds(Set<Id> setOfId) { 
        return [
            SELECT Id, Name, Location_Id__c, Organization__c, Name__c, Location_Phone_Number__c , Address__c, Status__c, Organization__r.Name, Organization__r.Organization_Id__c,
                Address__Street__s, Address__PostalCode__s, Address__City__s, Address__StateCode__s, Address__CountryCode__s, Size_of_Candidate_Pool__c, Number_of_Hires__c
            FROM Location 
            WHERE Organization__c IN: setOfId AND Organization__c != null 
                AND Organization__r.RecordTypeId =: hrTalentPoolsContactRecordType ORDER BY LastModifiedDate DESC NULLS FIRST];
    }
}