force-app/main/default/objects/Account/fields/Organization_Category__c.field-meta.xml
<CustomField>
    <fullName>Organization_Category__c</fullName>
    <label>Organization Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>College</fullName>
                <isActive>false</isActive>
                <label>College</label>
            </value>
            <value>
                <fullName>College or University</fullName>
            </value>
            <value>
                <fullName>Diversity Organization</fullName>
            </value>
            <value>
                <fullName>Driver School</fullName>
            </value>
            <value>
                <fullName>Military Agency</fullName>
            </value>
            <value>
                <fullName>Military Base</fullName>
            </value>
            <value>
                <fullName>National Organization</fullName>
                <isActive>false</isActive>
                <label>National Organization</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Skilled Trades Technical/Professional</fullName>
            </value>
            <value>
                <fullName>State Workforce Agency</fullName>
            </value>
            <value>
                <fullName>Technical High School</fullName>
                <isActive>false</isActive>
                <label>Technical High School</label>
            </value>
            <value>
                <fullName>Trade High School</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
                <isActive>false</isActive>
                <label>Website</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_ID__c.field-meta.xml
<CustomField>
    <fullName>Organization_ID__c</fullName>
    <displayFormat>Org-{00000}</displayFormat>
    <label>Organization ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Status__c.field-meta.xml
<CustomField>
    <fullName>Organization_Status__c</fullName>
    <label>Organization Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Qualifying</fullName>
            </value>
            <value>
                <fullName>Qualified Partner</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Strategic Partner</fullName>
            </value>
            <value>
                <fullName>Archive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Corporate.recordType-meta.xml
<RecordType>
    <fullName>Corporate</fullName>
    <active>true</active>
    <description>All Clean Harbor Corporate Accounts</description>
    <label>Corporate</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/HR_Talent_Pools.recordType-meta.xml
<RecordType>
    <fullName>HR_Talent_Pools</fullName>
    <active>true</active>
    <description>HR Partnership organizations used to recruit from their talent pools</description>
    <label>HR Recruiting Partners</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Locations__c.field-meta.xml
<CustomField>
    <fullName>Locations__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Locations</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Customer Contacts</relationshipLabel>
    <relationshipName>Customer_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Org_Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Org_Contact_Type__c</fullName>
    <label>Recruiting Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Career Services</fullName>
            </value>
            <value>
                <fullName>Dean</fullName>
            </value>
            <value>
                <fullName>Executive</fullName>
            </value>
            <value>
                <fullName>Program Manager</fullName>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>College Career Counselor</fullName>
                <isActive>false</isActive>
                <label>College Career Counselor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>HR_Talent_Pools</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Contacts (Organization)</relationshipLabel>
    <relationshipName>Customer_Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Organization_Category__c.field-meta.xml
<CustomField>
    <fullName>Organization_Category__c</fullName>
    <formula>TEXT( Account.Organization_Category__c )</formula>
    <label>Organization Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/HR_Talent_Pools.recordType-meta.xml
<RecordType>
    <fullName>HR_Talent_Pools</fullName>
    <active>true</active>
    <description>HR partnership organizations used to recruit from their talent pools</description>
    <label>HR Recruiting Partners</label>
</RecordType>

force-app/main/default/objects/Location/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>HR Recruiting Partners</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organization_Department__c/Organization_Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <displayFormat>Dpt-{00000}</displayFormat>
        <label>Department ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_Department__c/fields/Dept_ID__c.field-meta.xml
<CustomField>
    <fullName>Dept_ID__c</fullName>
    <label>Master Department ID</label>
    <referenceTo>Organization_Department_Mgr__c</referenceTo>
    <relationshipLabel>Departments</relationshipLabel>
    <relationshipName>Departments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Organization_Department__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Departments</relationshipLabel>
    <relationshipName>Departments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organization_Department__c/fields/MGR_LVL_1_DESCR__c.field-meta.xml
<CustomField>
    <fullName>MGR_LVL_1_DESCR__c</fullName>
    <formula>TEXT(Dept_ID__r.MGR_LVL_1_DESCR__c)</formula>
    <label>MGR LVL 1 DESCR</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Department__c/fields/MGR_LVL_3_DESCR__c.field-meta.xml
<CustomField>
    <fullName>MGR_LVL_3_DESCR__c</fullName>
    <formula>TEXT(Dept_ID__r.MGR_LVL_3_DESCR__c )</formula>
    <label>MGR LVL 3 DESCR</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Department__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>HR_Talent_Pools</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Departments</relationshipLabel>
    <relationshipName>Departments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organization_Department_Mgr__c/Organization_Department_Mgr__c.object-meta.xml
<CustomObject>
    <label>Master Department</label>
    <nameField>
        <displayFormat>DMGR-{00000}</displayFormat>
        <label>Master Department ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_Department_Mgr__c/fields/Dept_ID__c.field-meta.xml
<CustomField>
    <fullName>Dept_ID__c</fullName>
    <externalId>true</externalId>
    <label>Dept ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Organization_Department_Mgr__c/fields/MGR_LVL_1_DESCR__c.field-meta.xml
<CustomField>
    <fullName>MGR_LVL_1_DESCR__c</fullName>
    <label>MGR LVL 1 DESCR</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrative</fullName>
            </value>
            <value>
                <fullName>Dene Nation Industrial Service</fullName>
            </value>
            <value>
                <fullName>Environmental Services</fullName>
            </value>
            <value>
                <fullName>SK Sustainability Solutions</fullName>
            </value>
            <value>
                <fullName>#N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Organization_Department_Mgr__c/fields/MGR_LVL_3_DESCR__c.field-meta.xml
<CustomField>
    <fullName>MGR_LVL_3_DESCR__c</fullName>
    <label>MGR LVL 3 DESCR</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asset Mgmt &amp; Supply Chain</fullName>
            </value>
            <value>
                <fullName>Broker Business</fullName>
            </value>
            <value>
                <fullName>Canada Industrial Svcs</fullName>
            </value>
            <value>
                <fullName>CHES Sales and Service</fullName>
            </value>
            <value>
                <fullName>Corp Dev &amp; Real Estate</fullName>
            </value>
            <value>
                <fullName>Corp Pricing &amp; Proposals</fullName>
            </value>
            <value>
                <fullName>Corp Sales &amp; Corp Marketing</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Daylighting Services Canada</fullName>
            </value>
            <value>
                <fullName>Dene Nation Industrial Service</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Distribution Centers</fullName>
            </value>
            <value>
                <fullName>Environmental Svcs Sls and Adm</fullName>
            </value>
            <value>
                <fullName>Facilities Group</fullName>
            </value>
            <value>
                <fullName>IS Sales &amp; Svc Sales &amp; Admin</fullName>
            </value>
            <value>
                <fullName>Lodging Services</fullName>
            </value>
            <value>
                <fullName>National Transportation</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas Field Services</fullName>
            </value>
            <value>
                <fullName>Oil Sands</fullName>
            </value>
            <value>
                <fullName>Project Services</fullName>
            </value>
            <value>
                <fullName>Refined &amp; Blended Product Sale</fullName>
            </value>
            <value>
                <fullName>Safety-Kleen Supply</fullName>
            </value>
            <value>
                <fullName>SK Bulk Products &amp; Services1</fullName>
            </value>
            <value>
                <fullName>SK Facility Operations</fullName>
            </value>
            <value>
                <fullName>SK Pricing &amp; Proposals</fullName>
            </value>
            <value>
                <fullName>SK Sales and Service</fullName>
            </value>
            <value>
                <fullName>SKO Customer Service</fullName>
            </value>
            <value>
                <fullName>SKO Packaging &amp; Blending</fullName>
            </value>
            <value>
                <fullName>SKO Supply Chain</fullName>
            </value>
            <value>
                <fullName>Specialty Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DeparmentManagerDAOTest.cls
/**
 * @description       : 
 * @author            : Suresh Beniwal
 * @group             : 
 * @last modified on  : 08-23-2022
 * @last modified by  : Suresh Beniwal
 * Modifications Log
 * Ver   Date         Author           Modification
 * 1.0   08-10-2022   Suresh Beniwal   Initial Version
**/
@isTest
private class DeparmentManagerDAOTest {
    private final static string TEST_NAME='Mohammed'; 
    private final static string TEST_SALUTATION = 'Mr';
    private final static string TEST_FIRST_NAME='Farheen';
    private final static string TEST_LAST_NAME='Siddique';
    private final static string TEST_RECORDTYPE_ID = Schema.Sobjecttype.Account.getRecordTypeInfosByDeveloperName().get(CHConstants.ACCOUNT_RECORD_TYPE_HR_TALENT_POOLS).getRecordTypeId();
    private final static string TEST_CONTACT_TYPE= 'Dean';
    private final static string TEST_EMAIL = 'irfan@gmail.com';
    private final static string TEST_ORGANISATION_STATUS = 'Draft';
    private final static string TEST_SHIPPING_STREET = 'Tolichowki';
    private final static string TEST_SHIPPING_CITY = 'Hyderabad';
    private final static string TEST_SHIPPING_STATE = 'Telangana';
    private final static string TEST_SHIPPING_COUNTRY = 'India';
    private final static string TEST_SHIPPING_POSTAL_CODE = '500001';
    
    @TestSetup
    static void makeData() {
        Id contactRecordTypeId = Schema.Sobjecttype.Contact.getRecordTypeInfosByDeveloperName().get(CHConstants.ACCOUNT_RECORD_TYPE_HR_TALENT_POOLS).getRecordTypeId();
        Id RecordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('HR_Talent_Pools').getRecordTypeId();
        Account acc = new Account();
        acc.Name = 'Farheen';
        acc.RecordTypeId = RecordTypeIdAccount;
        acc.Organization_Status__c ='Draft';
        //acc.Organization_ID__c = acc.id;
        acc.Organization_Category__c = 'Driver School';
        acc.ShippingStreet = '123';
        acc.ShippingCity = 'Jaipur';
        acc.ShippingState = 'CA';
        acc.ShippingCountry = 'US';
        acc.ShippingPostalCode = '302012';

        insert acc;

        Contact con = new Contact (RecordTypeId = contactRecordTypeId, AccountId = acc.Id, Org_Contact_Type__c =TEST_CONTACT_TYPE,salutation=TEST_SALUTATION, FirstName=TEST_FIRST_NAME, LastName=TEST_LAST_NAME, Email=TEST_EMAIL);
        insert con;

        Schema.Location locationRecord = new Schema.Location();
        locationRecord.Name = 'Test';
        locationRecord.Organization__c = acc.Id;
        locationRecord.Address__Street__s = '124';
        locationRecord.Address__City__s = 'Jaipur';
        locationRecord.Address__StateCode__s = 'CA';
        locationRecord.Address__CountryCode__s = 'US';
        locationRecord.Address__PostalCode__s = '303303';
        insert locationRecord;

        con.Locations__c = locationRecord.Id;
        update con;  

        Organization_Department_Mgr__c departMentManager = new Organization_Department_Mgr__c();
        departMentManager.MGR_LVL_1_DESCR__c = 'Administrative';
        departMentManager.MGR_LVL_3_DESCR__c = 'Corporate';
        insert departMentManager;

        Organization_Department__c organizationDeparments = new Organization_Department__c();
        organizationDeparments.Location__c = locationRecord.Id;
        organizationDeparments.Dept_ID__c = departMentManager.Id;
        insert organizationDeparments;
    }

    @IsTest 
    static void testJobCodeMappingForMgrLevelDescSet(){
        
        Test.startTest();
        List<Organization_Department_Mgr__c> listOfDepartmentManager = DeparmentManagerDAO.getListOfDepartmentManagers();
        Test.stopTest();

        System.assertEquals(false, listOfDepartmentManager.isEmpty(), 'Department managers returned successfully!!'); 
    }
}