force-app/main/default/objects/Account/fields/Organization_ID__c.field-meta.xml
<CustomField>
    <fullName>Organization_ID__c</fullName>
    <displayFormat>Org-{00000}</displayFormat>
    <label>Organization ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Organization_Owners__c/Organization_Owners__c.object-meta.xml
<CustomObject>
    <label>Owner</label>
    <nameField>
        <displayFormat>Own-{00000}</displayFormat>
        <label>Ownership ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Owners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_Owners__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>HR_Talent_Pools</value>
        </filterItems>
        <infoMessage>Only university accounts is displayed</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Owners</relationshipLabel>
    <relationshipName>Organization_Owners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Organization_Owners__c/fields/Owner_Type__c.field-meta.xml
<CustomField>
    <fullName>Owner_Type__c</fullName>
    <label>Owner Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Executive Sponsor</fullName>
            </value>
            <value>
                <fullName>Partnership Owner</fullName>
            </value>
            <value>
                <fullName>Contributor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Organization_Owners__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Recruiter</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Super Recruiter</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Organization_Owners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OwnershipService.cls
/**
 * @description       : 
 * @author            : Suresh Beniwal
 * @group             : 
 * @last modified on  : 07-27-2022
 * @last modified by  : Suresh Beniwal
 * Modifications Log
 * Ver   Date         Author           Modification
 * 1.0   06-10-2022   Suresh Beniwal   Initial Version
**/
public without sharing class OwnershipService {

    /**
    * @description 
    * @author Suresh Beniwal | 06-10-2022 
    * @param List<Organization_Owners__c> listOfOwnerships 
    * @return List<OwnershipWrapper> 
    **/
    public static List<OwnershipWrapper> getListOfOwnerships(List<Organization_Owners__c> listOfOwnerships) {
        List<OwnershipWrapper> listOfOwnershipWrapper = new List<OwnershipWrapper>();
        Map<Id, List<Organization_Owners__c>> mapOfOrganizationOwners = new Map<Id, List<Organization_Owners__c>>();

        for (Organization_Owners__c ownershipRecord: listOfOwnerships) {
            if (!mapOfOrganizationOwners.containsKey(ownershipRecord.Organization__c)) {
                mapOfOrganizationOwners.put(ownershipRecord.Organization__c, new List<Organization_Owners__c>());
            }
            mapOfOrganizationOwners.get(ownershipRecord.Organization__c).add(ownershipRecord);
        }

        for (String key: mapOfOrganizationOwners.keySet()) {
            OwnershipWrapper ownershipWrapperRecord = new OwnershipWrapper();
            for (Organization_Owners__c ownershipRecord : mapOfOrganizationOwners.get(key)) {
                ownershipWrapperRecord.organizationId = ownershipRecord.Organization__r.Organization_Id__c;

                if (ownershipRecord.Owner_Type__c == 'Executive Sponsor') {
                    ownershipWrapperRecord.executiveId = ownershipRecord.Name;
                    ownershipWrapperRecord.executive = ownershipRecord.User__r.Name;
                } else if (ownershipRecord.Owner_Type__c == 'Partnership Owner') {
                    ownershipWrapperRecord.partnershipId = ownershipRecord.Name;
                    ownershipWrapperRecord.partnership = ownershipRecord.User__r.Name;
                } else if (ownershipRecord.Owner_Type__c == 'Contributor') {
                    ownershipWrapperRecord.contributerId = ownershipRecord.Name;
                    ownershipWrapperRecord.contributer = ownershipRecord.User__r.Name;
                }
                ownershipWrapperRecord.organizationName = ownershipRecord.Organization__r.Name;
            }
            listOfOwnershipWrapper.add(ownershipWrapperRecord);
        }

        return listOfOwnershipWrapper;
    }

    public class OwnershipWrapper {
        @AuraEnabled public String organizationId;
        @AuraEnabled public String executiveId;
        @AuraEnabled public String executive;
        @AuraEnabled public String partnershipId;
        @AuraEnabled public String partnership;
        @AuraEnabled public String contributerId;
        @AuraEnabled public String contributer;
        @AuraEnabled public String organizationName;
    }
}