force-app/main/default/objects/Account/fields/Organization_Status__c.field-meta.xml
<CustomField>
    <fullName>Organization_Status__c</fullName>
    <label>Organization Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Qualifying</fullName>
            </value>
            <value>
                <fullName>Qualified Partner</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Strategic Partner</fullName>
            </value>
            <value>
                <fullName>Archive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/HR_Talent_Pools.recordType-meta.xml
<RecordType>
    <fullName>HR_Talent_Pools</fullName>
    <active>true</active>
    <description>HR Partnership organizations used to recruit from their talent pools</description>
    <label>HR Recruiting Partners</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Org_Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Org_Contact_Type__c</fullName>
    <label>Recruiting Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Career Services</fullName>
            </value>
            <value>
                <fullName>Dean</fullName>
            </value>
            <value>
                <fullName>Executive</fullName>
            </value>
            <value>
                <fullName>Program Manager</fullName>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>College Career Counselor</fullName>
                <isActive>false</isActive>
                <label>College Career Counselor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/HR_Talent_Pools.recordType-meta.xml
<RecordType>
    <fullName>HR_Talent_Pools</fullName>
    <active>true</active>
    <description>HR partnership organizations used to recruit from their talent pools</description>
    <label>HR Recruiting Partners</label>
</RecordType>

force-app/main/default/objects/SIC_VALIDATION_SETTING__c/SIC_VALIDATION_SETTING__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS will consist of a flag which determines if SIC Validation on Account should be implemented or not.</description>
    <label>SIC VALIDATION SETTING</label>
</CustomObject>

force-app/main/default/objects/SIC_VALIDATION_SETTING__c/fields/SIC_VALIDATION_FLAG__c.field-meta.xml
<CustomField>
    <fullName>SIC_VALIDATION_FLAG__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag which determines if SIC Validation should be executed in the custom code or not. Should be Checked if SIC Validation is required.</description>
    <label>SIC_VALIDATION_FLAG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TERRITORY_MANAGEMENT__c/TERRITORY_MANAGEMENT__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS will consist of a flag which determines if Territory Management on Account should be implemented or not. If Yes, the Territory and Owner on Account are set based on the criteria.</description>
    <label>TERRITORY MANAGEMENT</label>
</CustomObject>

force-app/main/default/objects/TERRITORY_MANAGEMENT__c/fields/TM_FLAG__c.field-meta.xml
<CustomField>
    <fullName>TM_FLAG__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag which determines if TM should be executed in the custom code or not thus setting the Territory and the Account Owner field on the Account record. Should be Checked if TM is required.</description>
    <inlineHelpText>Flag which determines if TM should be executed in the custom code or not</inlineHelpText>
    <label>TM_FLAG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TaskServiceTest.cls
/**
 * @description       : 
 * @author            : Suresh Beniwal
 * @group             : 
 * @last modified on  : 08-23-2022
 * @last modified by  : Suresh Beniwal 
 * Modifications Log
 * Ver   Date         Author           Modification
 * 1.0   08-23-2022   Suresh Beniwal   Initial Version
**/
@isTest
public class TaskServiceTest {

    private final static string TEST_NAME='Mohammed'; 
    private final static string TEST_SALUTATION = 'Mr';
    private final static string TEST_FIRST_NAME='Farheen';
    private final static string TEST_LAST_NAME='Siddique';
    private final static string TEST_RECORDTYPE_ID = Schema.Sobjecttype.Account.getRecordTypeInfosByDeveloperName().get(CHConstants.ACCOUNT_RECORD_TYPE_HR_TALENT_POOLS).getRecordTypeId();
    private final static string TEST_CONTACT_TYPE= 'Dean';
    private final static string TEST_EMAIL = 'irfan@gmail.com';
    private final static string TEST_ORGANISATION_STATUS = 'Draft';
    private final static string TEST_SHIPPING_STREET = 'Tolichowki';
    private final static string TEST_SHIPPING_CITY = 'Hyderabad';
    private final static string TEST_SHIPPING_STATE = 'Telangana';
    private final static string TEST_SHIPPING_COUNTRY = 'India';
    private final static string TEST_SHIPPING_POSTAL_CODE = '500001';
    private static final string TEST_Job_Category_Group ='Chemists';
    private static final string TEST_Sub_Category ='lab Chemists';
    
    @testSetup
    static void makeData() {
        
        SIC_VALIDATION_SETTING__c setting = new SIC_VALIDATION_SETTING__c();
        setting.SIC_VALIDATION_FLAG__c = true;
        setting.Name = 'SIC_VALIDATION_SETTING';
        insert setting;
        
        TERRITORY_MANAGEMENT__c territory = new TERRITORY_MANAGEMENT__c();
        territory.Name = 'TERRITORY_MGMT_SETTING';
        territory.TM_FLAG__c = true;
        insert territory;
        
        Account acc = new Account();
        acc.Name = 'test account';
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('HR_Talent_Pools').getRecordTypeId();
        acc.Organization_Status__c = 'Draft';
        acc.ShippingStreet = '123';
        acc.ShippingCity = 'Jaipur';
        acc.ShippingState = 'CA';
        acc.ShippingCountry = 'US';
        acc.ShippingPostalCode = '302012';
        insert acc;
        
    }
    
    @isTest
    static void testGetTaskDetails() {
        Id contactRecordTypeId = Schema.Sobjecttype.Contact.getRecordTypeInfosByDeveloperName().get(CHConstants.ACCOUNT_RECORD_TYPE_HR_TALENT_POOLS).getRecordTypeId();
        Account acc = [SELECT Id,RecordType.Name FROM Account LIMIT 1];
        Contact con = new Contact (
            RecordTypeId = contactRecordTypeId, AccountId = acc.Id, 
            Org_Contact_Type__c =TEST_CONTACT_TYPE,salutation=TEST_SALUTATION, 
            FirstName=TEST_FIRST_NAME, LastName=TEST_LAST_NAME, Email=TEST_EMAIL);
        insert con;
        Task taskRecord = new Task();
        taskRecord.WhoId = con.Id;
        taskRecord.WhatId = acc.Id;
        taskRecord.Description = 'test task';
        insert taskRecord;
        
        Task taskRecord1 = new Task();
        taskRecord1.WhoId = null;
        taskRecord1.WhatId = acc.Id;
        taskRecord1.Description = 'test task2';
        insert taskRecord1;
        
        Test.startTest();
        	List<TaskService.TaskWrapper> wrapper = TaskService.getTaskDetails(new Set<Id>{acc.Id});
        	TaskDAO.getAccountActivities(new Set<Id>{acc.Id});
        Test.stopTest();
        System.assertEquals(true, !wrapper.isEmpty(), 'wrapper with taks details is returned');
        
    }
}