force-app/main/default/objects/Account/fields/Organization_ID__c.field-meta.xml
<CustomField>
    <fullName>Organization_ID__c</fullName>
    <displayFormat>Org-{00000}</displayFormat>
    <label>Organization ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
	<description>This field is used to select the locations those are linked to HR related account on which task is creating </description>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.Organization__c</field>
            <operation>equals</operation>
            <valueField>$Source.WhatId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Location</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location/fields/Location_ID__c.field-meta.xml
<CustomField>
    <fullName>Location_ID__c</fullName>
    <displayFormat>Loc- {00000}</displayFormat>
    <label>Location ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Location/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>HR Recruiting Partners</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organization_Job_Code__c/Organization_Job_Code__c.object-meta.xml
<CustomObject>
    <label>Job Categories</label>
    <nameField>
        <displayFormat>Jct-{00000}</displayFormat>
        <label>Job Category Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_Job_Code__c/fields/Job_Category_Group__c.field-meta.xml
<CustomField>
    <fullName>Job_Category_Group__c</fullName>
    <formula>Job_Code_Mapping__r.Job_Category_Group__c</formula>
    <label>Job Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Job_Code__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Job Categories</relationshipLabel>
    <relationshipName>Job_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organization_Job_Code__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>HR_Talent_Pools</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Categories</relationshipLabel>
    <relationshipName>Organization_Job_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organization_Job_Code__c/fields/Sub_Group__c.field-meta.xml
<CustomField>
    <fullName>Sub_Group__c</fullName>
    <formula>Job_Code_Mapping__r.Sub_Group__c</formula>
    <label>Job Sub Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JobCodeService.cls
/**
 * @description       : 
 * @author            : Suresh Beniwal
 * @group             : 
 * @last modified on  : 10-13-2022
 * @last modified by  : Suresh Beniwal
 * Modifications Log
 * Ver   Date         Author           Modification
 * 1.0   06-10-2022   Suresh Beniwal   Initial Version
**/
public without sharing class JobCodeService {
    
    /**
    * @description 
    * @author Suresh Beniwal | 06-10-2022 
    * @param List<Organization_Job_Code__c> listOfJobCodes 
    * @return List<JobCodeWrapper> 
    **/
    public static List<JobCodeWrapper> getListOfJobCodes(List<Organization_Job_Code__c> listOfJobCodes) {
        List<JobCodeWrapper> listOfJobCodeWrapper = new List<JobCodeWrapper>();

        for (Organization_Job_Code__c jobCodeRecord: listOfJobCodes) { 
            JobCodeWrapper jobCodeWrapperRecord = new JobCodeWrapper();
            jobCodeWrapperRecord.jobCategoryCode = jobCodeRecord.Name;
            jobCodeWrapperRecord.locationCode = jobCodeRecord.Location__r.Location_Id__c;
            jobCodeWrapperRecord.organizationCode = jobCodeRecord.Organization__r.Organization_Id__c;
            jobCodeWrapperRecord.jobCategories = jobCodeRecord.Job_Category_Group__c;
            jobCodeWrapperRecord.jobCodeTitles = jobCodeRecord.Sub_Group__c;
            jobCodeWrapperRecord.organizationName = jobCodeRecord.Organization__r.Name;
            jobCodeWrapperRecord.location = jobCodeRecord.Location__r.Name;

            listOfJobCodeWrapper.add(jobCodeWrapperRecord);
        }

        return listOfJobCodeWrapper;
    }

    public class JobCodeWrapper {
        @AuraEnabled public String jobCategoryCode;
        @AuraEnabled public String locationCode;
        @AuraEnabled public String organizationCode;
        @AuraEnabled public String jobCategories;
        @AuraEnabled public String jobCodeTitles;
        @AuraEnabled public String organizationName;
        @AuraEnabled public String location;
    }
}