force-app/main/default/objects/Account/fields/Organization_Status__c.field-meta.xml
<CustomField>
    <fullName>Organization_Status__c</fullName>
    <label>Organization Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Qualifying</fullName>
            </value>
            <value>
                <fullName>Qualified Partner</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Strategic Partner</fullName>
            </value>
            <value>
                <fullName>Archive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Branch.recordType-meta.xml
<RecordType>
    <fullName>Branch</fullName>
    <active>true</active>
    <description>All Clean Harbors Branches</description>
    <label>Branch</label> 
</RecordType>

force-app/main/default/objects/Account/recordTypes/Corporate.recordType-meta.xml
<RecordType>
    <fullName>Corporate</fullName>
    <active>true</active>
    <description>All Clean Harbor Corporate Accounts</description>
    <label>Corporate</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/HR_Talent_Pools.recordType-meta.xml
<RecordType>
    <fullName>HR_Talent_Pools</fullName>
    <active>true</active>
    <description>HR Partnership organizations used to recruit from their talent pools</description>
    <label>HR Recruiting Partners</label>
</RecordType>

force-app/main/default/objects/Data_Upload__c/Data_Upload__c.object-meta.xml
<CustomObject>
    <label>Data Upload</label>
    <nameField>
        <displayFormat>DU-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Uploads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Upload__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Related upload line item status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Upload_Line_Item__c/Data_Upload_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Data Upload Line Item</label>
    <nameField>
        <displayFormat>DUL-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Upload Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Upload_Line_Item__c/fields/Contact_FirstName__c.field-meta.xml
<CustomField>
    <fullName>Contact_FirstName__c</fullName>
    <label>Contact FirstName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Upload_Line_Item__c/fields/Contact_LastName__c.field-meta.xml
<CustomField>
    <fullName>Contact_LastName__c</fullName>
    <label>Contact LastName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Upload_Line_Item__c/fields/Data_Upload__c.field-meta.xml
<CustomField>
    <fullName>Data_Upload__c</fullName>
    <label>Data Upload</label>
    <referenceTo>Data_Upload__c</referenceTo>
    <relationshipLabel>Data Upload Line Items</relationshipLabel>
    <relationshipName>Data_Upload_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Data_Upload_Line_Item__c/fields/Organization_Status__c.field-meta.xml
<CustomField>
    <fullName>Organization_Status__c</fullName>
    <label>Organization Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Qualifying</fullName>
            </value>
            <value>
                <fullName>Qualified Partner</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Strategic Partner</fullName>
            </value>
            <value>
                <fullName>Archive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Upload_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field is created to hold the record status of failure, completed or draft</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SIC_VALIDATION_SETTING__c/SIC_VALIDATION_SETTING__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS will consist of a flag which determines if SIC Validation on Account should be implemented or not.</description>
    <label>SIC VALIDATION SETTING</label>
</CustomObject>

force-app/main/default/objects/SIC_VALIDATION_SETTING__c/fields/SIC_VALIDATION_FLAG__c.field-meta.xml
<CustomField>
    <fullName>SIC_VALIDATION_FLAG__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag which determines if SIC Validation should be executed in the custom code or not. Should be Checked if SIC Validation is required.</description>
    <label>SIC_VALIDATION_FLAG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TERRITORY_MANAGEMENT__c/TERRITORY_MANAGEMENT__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS will consist of a flag which determines if Territory Management on Account should be implemented or not. If Yes, the Territory and Owner on Account are set based on the criteria.</description>
    <label>TERRITORY MANAGEMENT</label>
</CustomObject>

force-app/main/default/objects/TERRITORY_MANAGEMENT__c/fields/TM_FLAG__c.field-meta.xml
<CustomField>
    <fullName>TM_FLAG__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag which determines if TM should be executed in the custom code or not thus setting the Territory and the Account Owner field on the Account record. Should be Checked if TM is required.</description>
    <inlineHelpText>Flag which determines if TM should be executed in the custom code or not</inlineHelpText>
    <label>TM_FLAG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ProcessOrganizationDataBatchTest.cls
@isTest
public class ProcessOrganizationDataBatchTest {

    @testSetup
    static void makeData() {
        
        SIC_VALIDATION_SETTING__c setting = new SIC_VALIDATION_SETTING__c();
        setting.SIC_VALIDATION_FLAG__c = true;
        setting.Name = 'SIC_VALIDATION_SETTING';
        insert setting;
        
        TERRITORY_MANAGEMENT__c territory = new TERRITORY_MANAGEMENT__c();
        territory.Name = 'TERRITORY_MGMT_SETTING';
        territory.TM_FLAG__c = true;
        insert territory;
        
        Account acc = new Account();
        acc.Name = 'test account';
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('HR_Talent_Pools').getRecordTypeId();
        acc.Organization_Status__c = 'Draft';
        acc.ShippingStreet = '123';
        acc.ShippingCity = 'Jaipur';
        acc.ShippingState = 'CA';
        acc.ShippingCountry = 'US';
        acc.ShippingPostalCode = '302012';
        insert acc;
        
    }
    
    @isTest
    static void testExecute() {
        Data_Upload__c upload = new Data_Upload__c();
        upload.Status__c = 'In Progress';
        insert upload;
        
        Data_Upload_Line_Item__c lineItem = new Data_Upload_Line_Item__c();
        lineItem.Data_Upload__c = upload.Id;
        lineItem.Contact_FirstName__c = 'test';
        lineItem.Contact_LastName__c = 'con';
        lineItem.Contact_Email_Address__c = 'test@gmail.com';
        lineItem.Organization__c = 'test org';
        lineItem.Type__c = 'Corporate';
        lineItem.MailAddress__City__s = 'jaipur';
        lineItem.MailAddress__Street__s = 'CA';
        lineItem.MailAddress__StateCode__s = 'NJ';
        lineItem.MailAddress__CountryCode__s = 'US';
        lineItem.MailAddress__PostalCode__s = '302012';
        insert lineItem;
        Test.startTest();
        	Id jobId = Database.executeBatch(new ProcessOrganizationDataBatch(upload.Id));
        Test.stopTest();
        system.assertEquals(true, jobId!=null, 'job is executed');
    }
    
    @isTest
    static void testExecute1() {
        Data_Upload__c upload = new Data_Upload__c();
        upload.Status__c = 'In Progress';
        insert upload;
        
        Data_Upload_Line_Item__c lineItem = new Data_Upload_Line_Item__c();
        lineItem.Data_Upload__c = upload.Id;
        lineItem.Contact_FirstName__c = 'test';
        lineItem.Contact_LastName__c = 'con';
        lineItem.Contact_Email_Address__c = 'test@gmail.com';
        lineItem.Organization__c = 'test account';
        lineItem.Type__c = 'Branch';
        lineItem.MailAddress__City__s = 'jaipur';
        lineItem.MailAddress__Street__s = 'CA';
        lineItem.MailAddress__CountryCode__s = 'US';
        lineItem.MailAddress__StateCode__s = 'NJ';
        lineItem.MailAddress__PostalCode__s = '302012';
        insert lineItem;
        Test.startTest();
        	Id jobId = Database.executeBatch(new ProcessOrganizationDataBatch(upload.Id));
        Test.stopTest();
        system.assertEquals(true, jobId!=null, 'job is executed');
    }
}