force-app/main/default/objects/Account/fields/Primary_Business__c.field-meta.xml
<CustomField>
    <fullName>Primary_Business__c</fullName>
    <description>Primary business based off account owner</description>
    <label>Primary Service Provider</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Primary_Service_Provider_New__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Daylighting Services</fullName>
            </value>
            <value>
                <fullName>Emerald Services</fullName>
            </value>
            <value>
                <fullName>Field Services</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Industrial Services</fullName>
            </value>
            <value>
                <fullName>Lodging</fullName>
            </value>
            <value>
                <fullName>Murphys Oil</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Technical Services</fullName>
            </value>
            <value>
                <fullName>Thermo Fluids</fullName>
            </value>
            <value>
                <fullName>H2O</fullName>
            </value>
            <value>
                <fullName>BPS</fullName>
            </value>
            <value>
                <fullName>CYN</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>SK KPP</fullName>
            </value>
            <value>
                <fullName>Surface Rentals</fullName>
            </value>
            <value>
                <fullName>Seismic</fullName>
            </value>
            <value>
                <fullName>Safety-Kleen</fullName>
                <label>SK ENV</label>
            </value>
            <value>
                <fullName>OER</fullName>
            </value>
            <value>
                <fullName>HPC Industrial</fullName>
            </value>
            <value>
                <fullName>PSC</fullName>
            </value>
            <value>
                <fullName>Synergy</fullName>
            </value>
            <value>
                <fullName>DFW</fullName>
            </value>
			<value>
                <fullName>Thompson</fullName>
            </value>
			<value>
                <fullName>Noble Oil</fullName>
            </value>
            <value>
                <fullName>HEPACO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Territory in which the Account is mapped to</description>
    <label>Territory</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory_ID_SK__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID_SK__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SK&apos;s Territory ID</description>
    <label>Territory ID</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Accounts (TerritoryID_SK)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/WIN_ID__c.field-meta.xml
<CustomField>
    <fullName>WIN_ID__c</fullName>
    <externalId>true</externalId>
    <label>WIN ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <description>Territory Name, owner, branch, primary business, and leadership</description>
    <label>Territory</label>
    <nameField>
        <label>Territory code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Primary_Business__c.field-meta.xml
<CustomField>
    <fullName>Primary_Business__c</fullName>
    <label>Operating Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BPS</fullName>
            </value>
            <value>
                <fullName>CYN Oil</fullName>
                <label>CYN</label>
            </value>
            <value>
                <fullName>CYN Environmental</fullName>
                <isActive>false</isActive>
                <label>CYN Environmental</label>
            </value>
            <value>
                <fullName>Daylighting Services</fullName>
            </value>
            <value>
                <fullName>DFW</fullName>
            </value>
            <value>
                <fullName>Emerald Services</fullName>
            </value>
            <value>
                <fullName>Field Services</fullName>
            </value>
            <value>
                <fullName>H2O</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Industrial Services</fullName>
            </value>
            <value>
                <fullName>Lodging</fullName>
            </value>
            <value>
                <fullName>Murphys Oil</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Performance Plus Products</fullName>
                <isActive>false</isActive>
                <label>Performance Plus Products</label>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>RS Used Oil</fullName>
                <isActive>false</isActive>
                <label>RS Used Oil</label>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
                <isActive>false</isActive>
                <label>Sales Operations</label>
            </value>
            <value>
                <fullName>Seismic</fullName>
            </value>
            <value>
                <fullName>Safety-Kleen</fullName>
                <label>SK ENV</label>
            </value>
            <value>
                <fullName>Synergy</fullName>
            </value>
            <value>
                <fullName>Kleen Performance Products</fullName>
                <label>SK KPP</label>
            </value>
            <value>
                <fullName>Surface Rentals</fullName>
            </value>
            <value>
                <fullName>Technical Services</fullName>
            </value>
            <value>
                <fullName>Thermo Fluids</fullName>
            </value>
			<value>
                <fullName>Thompson</fullName>
            </value>
			<value>
                <fullName>Noble Oil</fullName>
            </value>
            <value>
                <fullName>HEPACO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Territory_OwnerID__c.field-meta.xml
<CustomField>
    <fullName>Territory_OwnerID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TerritoryOwnerUpdateBatch.cls
/**
 * @description       : 
 * @author            : Irfan Khan
 * @group             : 
 * @last modified on  : 01-09-2023
 * @last modified by  : Irfan Khan
**/
global class TerritoryOwnerUpdateBatch implements Database.Batchable<sobject>, Database.Stateful{
    
    global Set<Id> territoryIds;
    global Map<Id, Territory__c> terrMap;
    
    global List<Account> failedAccounts;

    global TerritoryOwnerUpdateBatch(Set<Id> terrIds){
        
        territoryIds = new Set<Id>();
        territoryIds = terrIds;
        failedAccounts = new List<Account>();
        terrMap = new Map<Id, Territory__c>([Select Id, OwnerId, Territory_OwnerID__c, Primary_Business__c from Territory__c where ID IN : territoryIds]);
    }
    
    // Start Batch
    global database.querylocator start(Database.BatchableContext bc){
        
        Set<String> statusSet = new Set<String>();
        statusSet.add('Active');
        Id CORPORATE_ACCOUNT_TYPE = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get(CHConstants.ACCOUNT_RECORD_TYPE_CORPORATE).getRecordTypeId();
        return database.getQuerylocator('Select Id, Name, RecordTypeId, Territory_ID_SK__c, WIN_ID__c, Primary_Business__c from Account where Status__c IN : statusSet AND Territory_ID_SK__c IN : territoryIds AND RecordTypeId != :CORPORATE_ACCOUNT_TYPE');
    }
    
    global void execute(Database.BatchableContext bc, list<Account> accList){
        
        AccountCRUDHandler.IS_SKIP_TRIGGER = TRUE;
        List<Account> updateList = new List<Account>();
        
        for(Account acc : accList){
            if(terrMap.containsKey(acc.Territory_ID_SK__c) && terrMap.get(acc.Territory_ID_SK__c).Primary_Business__c == acc.Primary_Business__c){
                acc.OwnerId = terrMap.get(acc.Territory_ID_SK__c).Territory_OwnerID__c;
                updateList.add(acc);
            }
        }
        
        if(!updateList.isEmpty() && updateList.size() > 0){
            
            Database.SaveResult[] SaveResultList = Database.update(updateList,false);
            
            for(integer i =0; i<updateList.size();i++){
               If(!SaveResultList[i].isSuccess()){
                    Database.Error error = SaveResultList.get(i).getErrors().get(0);
                    String failedDML = error.getMessage();
                    System.debug('-----Error'+failedDML);
					System.debug('-----Acc'+updateList.get(i).Id);					
                    failedAccounts.add(updateList.get(i));
                    
                }
            } 
        }
        AccountCRUDHandler.IS_SKIP_TRIGGER = FALSE;
    }
    
    global void finish(Database.BatchableContext bc){

        if(!failedAccounts.isEmpty() && failedAccounts.size() > 0){

			sendEmail();
            
        }        
    }
    
    public void sendEmail(){
        
        String OrgEmailId;
        
        String orgUrl = URL.getSalesforceBaseUrl().toExternalForm();
        System.debug('-----inside email');
        for(OrgWideEmailAddress owa : [select DisplayName, id, Address from OrgWideEmailAddress]) {
            if(owa.DisplayName.contains('CRMSupport')) {
                OrgEmailId = owa.id;
                break;
            }
        }
        
        String wordBreak = '"white-space: nowrap;"';
        String wordBreakWithStyle = '"white-space: nowrap;background-color:blue; color:white;"';
        
        list<Messaging.SingleEmailMessage> lstSendEmails = new list<Messaging.SingleEmailMessage>();
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(new List<String>{userInfo.getUserEmail(), 'bezawada.balaji@cleanharbors.com'});
        mail.setCcAddresses(new List<String>{'bezawada.balaji@cleanharbors.com'});
        mail.setSubject('Email Notification for Territory Owner Update - Failed Accounts');
        mail.setBccSender(false);
        mail.setUseSignature(false);
        mail.setOrgWideEmailAddressId(OrgEmailId);
        mail.setSaveAsActivity(false);
        
        String emailBody = 'Hi,<br/>Please find below the failed accout records for Territory Owner Update	,<br/><br/>';
        emailBody += '<table border="1" style="border-collapse: collapse;border: 1px solid #000;width:100%;" cellspacing="3" cellpadding="3">';
        emailBody += '<tr><th style='+wordBreakWithStyle+'>Account Name</th><th style='+wordBreakWithStyle+'>WIN ID</th>';
        System.debug('-----inside email size'+failedAccounts.size());
        for(Account acc : failedAccounts){
            
            emailBody += '<tr><td style='+wordBreak+'><a href ="'+orgURL+'/'+acc.Id+'">'+acc.Name+'</a></td><td style='+wordBreak+'>'+acc.WIN_ID__c+'</td>';                
        }
        
        emailBody += '</table><br/><br/>Regards,<br/>Salesforce Team';
        mail.setHtmlBody(emailBody);
        lstSendEmails.add(mail);
	    if(!Test.isRunningTest() && orgUrl.contains('-sandbox')) {
        List<Messaging.SendEmailResult> results = Messaging.sendEmail(lstSendEmails);
        set<Id> setIds = new set<Id>();
        for(Messaging.SendEmailResult rr:results){
            system.debug('----rr'+rr.IsSuccess());
            if(!rr.IsSuccess()){
                setIds.add(rr.getErrors()[0].getTargetObjectId());
				}
			}
        system.debug('****setIds******'+setIds);
		}
	}
}