force-app/main/default/objects/Account/fields/Primary_Service_Provider_New__c.field-meta.xml
<CustomField>
    <fullName>Primary_Service_Provider_New__c</fullName>
    <label>Operating Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SK ENV</fullName>
            </value>
            <value>
                <fullName>SK BPS</fullName>
            </value>
            <value>
                <fullName>SK KPP</fullName>
            </value>
            <value>
                <fullName>Clean Harbors ENV</fullName>
            </value>
            <value>
                <fullName>CHES Oil and Gas</fullName>
            </value>
            <value>
                <fullName>CHES Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Sales_Business_Unit__c</fullName>
    <description>Sales business unit (temporary field - do not use)</description>
    <label>Sales Business Unit</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory_Override__c.field-meta.xml
<CustomField>
    <fullName>Territory_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Territory Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ZIP_Master__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZIP Master</label>
    <referenceTo>ZIP_Master__c</referenceTo>
    <relationshipLabel>Accounts (ZIP Master)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <description>Territory Name, owner, branch, primary business, and leadership</description>
    <label>Territory</label>
    <nameField>
        <label>Territory code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Territory_OwnerID__c.field-meta.xml
<CustomField>
    <fullName>Territory_OwnerID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory_Master__c/Territory_Master__c.object-meta.xml
<CustomObject>
    <description>Contains all Territory Information viz., SBU, Territory Name, Territory Owner, etc. based on the ZIP Codes.</description>
    <label>Territory Master</label>
    <nameField>
        <label>Territory Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Master</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Master__c/fields/Sales_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Sales_Business_Unit__c</fullName>
    <label>Primary Service Provider</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BPS</fullName>
            </value>
            <value>
                <fullName>CYN</fullName>
            </value>
            <value>
                <fullName>Daylighting Services</fullName>
            </value>
            <value>
                <fullName>DFW</fullName>
            </value>
            <value>
                <fullName>Emerald Services</fullName>
            </value>
            <value>
                <fullName>Field Services</fullName>
            </value>
            <value>
                <fullName>H2O</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Industrial Services</fullName>
            </value>
            <value>
                <fullName>Lodging</fullName>
            </value>
            <value>
                <fullName>Murphys Oil</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Seismic</fullName>
            </value>
            <value>
                <fullName>Safety-Kleen</fullName>
                <label>SK ENV</label>
            </value>
            <value>
                <fullName>SK KPP</fullName>
            </value>
            <value>
                <fullName>Surface Rentals</fullName>
            </value>
            <value>
                <fullName>Synergy</fullName>
            </value>
            <value>
                <fullName>Technical Services</fullName>
            </value>
            <value>
                <fullName>Thermo Fluids</fullName>
            </value>
			<value>
                <fullName>Thompson</fullName>
            </value>
			<value>
                <fullName>Noble Oil</fullName>
            </value>
            <value>
                <fullName>HEPACO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory_Master__c/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Territory ID lookup field</description>
    <label>Territory ID</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Territory Master (Territory ID)</relationshipLabel>
    <relationshipName>Territory_Master1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory_Master__c/fields/ZIP_Master__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Master__c</fullName>
    <label>ZIP Master</label>
    <referenceTo>ZIP_Master__c</referenceTo>
    <relationshipLabel>Territory Master</relationshipLabel>
    <relationshipName>Territory_Master</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ZIP_Master__c/ZIP_Master__c.object-meta.xml
<CustomObject>
    <label>ZIP Master</label>
    <nameField>
        <label>ZIP Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZIP Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProspectAccountActivationHandler.cls
public class ProspectAccountActivationHandler {
	@InvocableMethod
    public static void updateProspectAccountActivationOwner(List<Account> accountLst){
        Map<Id, List<Account>> ISAMFilteredAccountMap = new Map<Id, List<Account>>();
        
        for(Account accRec : accountLst){
            if(accRec.ZIP_Master__c != NULL && (accRec.Primary_Service_Provider_New__c == 'SK ENV' || accRec.Primary_Service_Provider_New__c == 'SK BPS')){
                if(ISAMFilteredAccountMap.containsKey(accRec.ZIP_Master__c)){
                	ISAMFilteredAccountMap.get(accRec.ZIP_Master__c).add(accRec);
                }else{
                    ISAMFilteredAccountMap.put(accRec.ZIP_Master__c, new List<Account>{accRec});
                }
            }
        }
        
        List<Territory_Master__c> territoryLst = [
        	SELECT Id, ZIP_Master__c, Territory_ID__r.Territory_OwnerID__c, Sales_Business_Unit__c, Name, Territory_ID__c
            FROM Territory_Master__c
            WHERE (
                ZIP_Master__c IN :ISAMFilteredAccountMap.keySet()
                AND (
                    Sales_Business_Unit__c = 'BPS'
                    OR Sales_Business_Unit__c = 'Safety-Kleen'
                )
            )
            AND Territory_ID__r.Territory_OwnerID__c != NULL
        ];
        
        List<Account> updatedAccountLst = new List<Account>();
        for(Territory_Master__c territoryRec : territoryLst){
            if(ISAMFilteredAccountMap.containsKey(territoryRec.ZIP_Master__c)){
                for(Account accountRec : ISAMFilteredAccountMap.get(territoryRec.ZIP_Master__c)){
                    if(((territoryRec.Sales_Business_Unit__c == 'BPS' && accountRec.Primary_Service_Provider_New__c == 'SK BPS')
                      || (territoryRec.Sales_Business_Unit__c == 'Safety-Kleen' && accountRec.Primary_Service_Provider_New__c == 'SK ENV'))
                      && territoryRec.Name.endsWith('IS')){
                          updatedAccountLst.add(new Account(
                          	Id = accountRec.Id,
                            OwnerId = territoryRec.Territory_ID__r.Territory_OwnerID__c,
                            Territory_Override__c = TRUE
                          ));
                    }
                }
            }
        }
        
        if(!updatedAccountLst.isEmpty()){
        	UPDATE updatedAccountLst;    
        }
    }
}