force-app/main/default/objects/Account/fields/Primary_Business__c.field-meta.xml
<CustomField>
    <fullName>Primary_Business__c</fullName>
    <description>Primary business based off account owner</description>
    <label>Primary Service Provider</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Primary_Service_Provider_New__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Daylighting Services</fullName>
            </value>
            <value>
                <fullName>Emerald Services</fullName>
            </value>
            <value>
                <fullName>Field Services</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Industrial Services</fullName>
            </value>
            <value>
                <fullName>Lodging</fullName>
            </value>
            <value>
                <fullName>Murphys Oil</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Technical Services</fullName>
            </value>
            <value>
                <fullName>Thermo Fluids</fullName>
            </value>
            <value>
                <fullName>H2O</fullName>
            </value>
            <value>
                <fullName>BPS</fullName>
            </value>
            <value>
                <fullName>CYN</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>SK KPP</fullName>
            </value>
            <value>
                <fullName>Surface Rentals</fullName>
            </value>
            <value>
                <fullName>Seismic</fullName>
            </value>
            <value>
                <fullName>Safety-Kleen</fullName>
                <label>SK ENV</label>
            </value>
            <value>
                <fullName>OER</fullName>
            </value>
            <value>
                <fullName>HPC Industrial</fullName>
            </value>
            <value>
                <fullName>PSC</fullName>
            </value>
            <value>
                <fullName>Synergy</fullName>
            </value>
            <value>
                <fullName>DFW</fullName>
            </value>
			<value>
                <fullName>Thompson</fullName>
            </value>
			<value>
                <fullName>Noble Oil</fullName>
            </value>
            <value>
                <fullName>HEPACO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Service_Provider_New__c.field-meta.xml
<CustomField>
    <fullName>Primary_Service_Provider_New__c</fullName>
    <label>Operating Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SK ENV</fullName>
            </value>
            <value>
                <fullName>SK BPS</fullName>
            </value>
            <value>
                <fullName>SK KPP</fullName>
            </value>
            <value>
                <fullName>Clean Harbors ENV</fullName>
            </value>
            <value>
                <fullName>CHES Oil and Gas</fullName>
            </value>
            <value>
                <fullName>CHES Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Sales_Business_Unit__c</fullName>
    <description>Sales business unit (temporary field - do not use)</description>
    <label>Sales Business Unit</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Territory in which the Account is mapped to</description>
    <label>Territory</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/ZIP_Master__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZIP Master</label>
    <referenceTo>ZIP_Master__c</referenceTo>
    <relationshipLabel>Accounts (ZIP Master)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <description>Territory Name, owner, branch, primary business, and leadership</description>
    <label>Territory</label>
    <nameField>
        <label>Territory code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Territory_OwnerID__c.field-meta.xml
<CustomField>
    <fullName>Territory_OwnerID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory_Master__c/Territory_Master__c.object-meta.xml
<CustomObject>
    <description>Contains all Territory Information viz., SBU, Territory Name, Territory Owner, etc. based on the ZIP Codes.</description>
    <label>Territory Master</label>
    <nameField>
        <label>Territory Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Master</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Master__c/fields/Sales_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Sales_Business_Unit__c</fullName>
    <label>Primary Service Provider</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BPS</fullName>
            </value>
            <value>
                <fullName>CYN</fullName>
            </value>
            <value>
                <fullName>Daylighting Services</fullName>
            </value>
            <value>
                <fullName>DFW</fullName>
            </value>
            <value>
                <fullName>Emerald Services</fullName>
            </value>
            <value>
                <fullName>Field Services</fullName>
            </value>
            <value>
                <fullName>H2O</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Industrial Services</fullName>
            </value>
            <value>
                <fullName>Lodging</fullName>
            </value>
            <value>
                <fullName>Murphys Oil</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Seismic</fullName>
            </value>
            <value>
                <fullName>Safety-Kleen</fullName>
                <label>SK ENV</label>
            </value>
            <value>
                <fullName>SK KPP</fullName>
            </value>
            <value>
                <fullName>Surface Rentals</fullName>
            </value>
            <value>
                <fullName>Synergy</fullName>
            </value>
            <value>
                <fullName>Technical Services</fullName>
            </value>
            <value>
                <fullName>Thermo Fluids</fullName>
            </value>
			<value>
                <fullName>Thompson</fullName>
            </value>
			<value>
                <fullName>Noble Oil</fullName>
            </value>
            <value>
                <fullName>HEPACO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory_Master__c/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Territory ID lookup field</description>
    <label>Territory ID</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Territory Master (Territory ID)</relationshipLabel>
    <relationshipName>Territory_Master1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory_Master__c/fields/ZIP_Master__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Master__c</fullName>
    <label>ZIP Master</label>
    <referenceTo>ZIP_Master__c</referenceTo>
    <relationshipLabel>Territory Master</relationshipLabel>
    <relationshipName>Territory_Master</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Person_Type__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person_Type__c</fullName>
    <label>Sales Person Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Development Manager</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Asset Management</fullName>
            </value>
            <value>
                <fullName>Branch Administration</fullName>
            </value>
            <value>
                <fullName>Branch District Manager</fullName>
            </value>
            <value>
                <fullName>Branch Manager</fullName>
            </value>
            <value>
                <fullName>Branch Operations</fullName>
            </value>
            <value>
                <fullName>Branch Project Manager</fullName>
            </value>
            <value>
                <fullName>Call Center Agent</fullName>
            </value>
            <value>
                <fullName>Central Profile</fullName>
            </value>
            <value>
                <fullName>Chemist</fullName>
            </value>
            <value>
                <fullName>Collections</fullName>
            </value>
            <value>
                <fullName>Corporate Billing</fullName>
            </value>
            <value>
                <fullName>Corporate Collections</fullName>
            </value>
            <value>
                <fullName>Corporate Finance</fullName>
            </value>
            <value>
                <fullName>Corporate Pricing</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Dispatcher</fullName>
            </value>
            <value>
                <fullName>Health and Safety</fullName>
            </value>
            <value>
                <fullName>InSite Operations</fullName>
            </value>
            <value>
                <fullName>InSite Program Manager</fullName>
            </value>
            <value>
                <fullName>InSite Project Manager</fullName>
            </value>
            <value>
                <fullName>ISAM</fullName>
            </value>
            <value>
                <fullName>Key Account Manager</fullName>
            </value>
            <value>
                <fullName>Key Account Support</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Master Data Management</fullName>
            </value>
            <value>
                <fullName>Senior Account Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateAccountTerritoryBatchHandler.cls
public class UpdateAccountTerritoryBatchHandler {
    public static Set<Id> updateAccountTerritory(List<Account> corporateAccountLst, Boolean isParent){
        Id currentUserId = UserInfo.getUserId();
        User userRec = [
            SELECT Id, Sales_Person_Type__c, Profile.Name, Territory__c
            FROM User
            WHERE Id =:currentUserId
        ];   
        
        List<Territory__c> territorys;
        if(userRec.Territory__c != NULL){ 
           territorys = [
                SELECT Id, Territory_OwnerID__c
                FROM Territory__c
                WHERE Name = :userRec.Territory__c
                LIMIT 1
            ];
        }
        
        Map<Id, List<Account>> nonSalesPersonFilteredAccountMap = new Map<Id, List<Account>>();
        
        for(Account newAccRecord : corporateAccountLst){
            if(nonSalesPersonFilteredAccountMap.containsKey(newAccRecord.ZIP_Master__c)){
                nonSalesPersonFilteredAccountMap.get(newAccRecord.ZIP_Master__c).add(newAccRecord);
            }else{
                nonSalesPersonFilteredAccountMap.put(newAccRecord.ZIP_Master__c, new List<Account>{newAccRecord});
            }
        }
        
        List<Territory_Master__c> territoryLst = [
            SELECT Id, ZIP_Master__c, Territory_ID__r.Territory_OwnerID__c, Sales_Business_Unit__c, Name, Territory_ID__c
            FROM Territory_Master__c
            WHERE (
                ZIP_Master__c IN :nonSalesPersonFilteredAccountMap.keySet()
            )
        ];
        
        List<Account> updatedAccount = new List<Account>();
        for(Territory_Master__c territoryRec : territoryLst){
            if(nonSalesPersonFilteredAccountMap.containsKey(territoryRec.ZIP_Master__c)){
                for(Account accountRec : nonSalesPersonFilteredAccountMap.get(territoryRec.ZIP_Master__c)){
                    if(((accountRec.Primary_Service_Provider_New__c == 'SK ENV' || accountRec.Primary_Service_Provider_New__c == 'SK BPS')
                        && (territoryRec.Sales_Business_Unit__c == accountRec.Primary_Business__c ))
                       && !territoryRec.Name.endsWith('IS')){
                           
                           if(territoryRec.Territory_ID__c != NULL && territoryRec.Territory_ID__r.Territory_OwnerID__c != NULL
                              && userRec.Sales_Person_Type__c != 'Senior Account Manager' && userRec.Sales_Person_Type__c != 'Account Manager'){
                                  System.debug('territoryRec.Territory_ID__c ' + territoryRec.Territory_ID__c);
                                  accountRec.OwnerId = territoryRec.Territory_ID__r.Territory_OwnerID__c;
                                  accountRec.Territory_Override__c = True;
                                  updatedAccount.add(accountRec);
                              }else if(territorys.size() > 0){
                                  accountRec.OwnerId = UserInfo.getUserId();
                                  accountRec.Territory_Override__c = True;
                                  updatedAccount.add(accountRec);
                              }
                           
                       }
                }
            }
        }
        
        Set<Id> corporateAccountIdsSet = new Set<Id>();
        if(updatedAccount.size() > 0){
       		List<Database.SaveResult> saveResultLst = Database.update(updatedAccount, false);
            
            for (Database.SaveResult sr : saveResultLst) {
                if (sr.isSuccess()) {
                    if(isParent)
                    	corporateAccountIdsSet.add(sr.getId());
                }
                else {
                    // Operation failed, so get all errors                
                    for(Database.Error err : sr.getErrors()) {
                        System.debug('The following error has occurred.');                    
                        System.debug(err.getStatusCode() + ': ' + err.getMessage());
                        System.debug('Account fields that affected this error: ' + err.getFields());
                    }
                }
            }
        }
    
    	return corporateAccountIdsSet;
    }
}