force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Win_Validate_New__c.field-meta.xml
<CustomField>
    <fullName>Win_Validate_New__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Win Validate New</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Broker_Location.recordType-meta.xml
<RecordType>
    <fullName>Broker_Location</fullName>
    <active>true</active>
    <description>All Clean Harbors Broker/Gen Accounts</description>
    <label>Broker Location</label>
</RecordType>

force-app/main/default/objects/Bypass_Account_Validation__c/Bypass_Account_Validation__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bypass Account Validation</label>
</CustomObject>

force-app/main/default/objects/Bypass_Account_Validation__c/fields/Bypass_Manifest_Address_Requirement__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Manifest_Address_Requirement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Manifest Address Requirement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Duplicate_Account_Tracking__c/Duplicate_Account_Tracking__c.object-meta.xml
<CustomObject>
    <label>Duplicate Account Tracking</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Duplicate Account Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Duplicate Account Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Duplicate_Account_Tracking__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Duplicate Account Tracking</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Process__c/Integration_Process__c.object-meta.xml
<CustomObject>
    <label>Integration Process</label>
    <nameField>
        <label>Integration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Process__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Integration Processes</relationshipLabel>
    <relationshipName>Integration_Processes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Process__c/fields/Process_Type__c.field-meta.xml
<CustomField>
    <fullName>Process_Type__c</fullName>
    <label>Process Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ownerupdate</fullName>
            </value>
            <value>
                <fullName>BrokerRecordTypeUpdate</fullName>
            </value>
            <value>
                <fullName>WinValidateAndCreate</fullName>
            </value>
            <value>
                <fullName>OCROwnerUpdateBatchProcess</fullName>
            </value>
			<value>
                <fullName>Key Account Update</fullName>
            </value>
			<value>
                <fullName>Contact Error Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Process__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Ignored</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateRelatedAccountRecordsBatch.cls
public class UpdateRelatedAccountRecordsBatch implements Database.Batchable<sObject>, Database.Stateful {
  private string processType;
  public UpdateRelatedAccountRecordsBatch(string processType) {
    this.processType = processType;
  }
  public Database.QueryLocator start(Database.BatchableContext BC) {
    Bypass_Account_Validation__c accountValidation = Bypass_Account_Validation__c.getOrgDefaults();
    accountValidation.Bypass_Manifest_Address_Requirement__c = true;
	AccountCRUDHandler.isValidationDisable = false;
    update accountValidation;
    AccountCRUDHandler.SKIP_VALIDATION = TRUE;
    string processType = this.processType; 
    String query = 'select Account__c, Status__c,Process_Type__c,account__r.parent.OwnerId from Integration_Process__c where Status__c=\'Pending\' and Process_Type__c=:processType order by Createddate ASC';
    return Database.getQueryLocator(query);
  }
  public void execute(Database.BatchableContext BC, List<Integration_Process__c> scope) {
    Map<Id, Integration_Process__C> accountIntegrationProcessMap = new Map<Id, Integration_Process__C>();
    if (processType == CHConstants.Ownerupdate) {
      List<Account> accountsToUpdate = new List<Account>();

      for (Integration_Process__c integProcess : scope) {
        Account accRec = new Account(Id = integProcess.Account__c, OwnerId = integProcess.Account__r.Parent.OwnerId, Win_Validate_New__c = true);

        if (!accountIntegrationProcessMap.containsKey(integProcess.Account__c)) {
          accountIntegrationProcessMap.put(integProcess.Account__c, integProcess);
        }

        accountsToUpdate.Add(accRec);
      }

      if (!accountsToUpdate.isEmpty()) {
        updateIntegrationProcessRecords(accountIntegrationProcessMap, accountsToUpdate);
      }
    } else if (processType == CHConstants.BrokerRecordTypeUpdate) {
      Id brokerLocationRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Broker_Location').getRecordTypeId();
      List<Account> childAccountsToBeUpdated = new List<Account>();
      for (Integration_Process__c integProcess : scope) {
        Account accRec = new Account();
        accRec.Id = integProcess.Account__c;
        accRec.RecordTypeId = brokerLocationRecordTypeId;
        accRec.Type = 'Brok/Gen';
        accRec.Win_Validate_New__c = true;
        childAccountsToBeUpdated.add(accRec);
        if (!accountIntegrationProcessMap.containsKey(integProcess.Account__c)) {
          accountIntegrationProcessMap.put(integProcess.Account__c, integProcess);
        }
      }

      if (!childAccountsToBeUpdated.isEmpty()) {
        updateIntegrationProcessRecords(accountIntegrationProcessMap, childAccountsToBeUpdated);
      }
    }
  }
  private void updateIntegrationProcessRecords(Map<Id, Integration_Process__C> accountIntegrationProcessMap, List<Account> accountsToUpdate) {
    List<Database.SaveResult> saveResultLst = Database.update(accountsToUpdate, false);
    for (Database.SaveResult saveResultObj : saveResultLst) {
      if (!saveResultObj.isSuccess()) {
        String errorMsg = '';
        for (Database.Error err : saveResultObj.getErrors()) {
          errorMsg += err.getMessage() + '\n';
        }

        if (errorMsg.length() > 0) {
          errorMsg = errorMsg.substring(0, errorMsg.length() - 2);
        }
        accountIntegrationProcessMap.get(saveResultObj.Id).Status__c = 'Error';
        accountIntegrationProcessMap.get(saveResultObj.Id).Error_Message__c = errorMsg;
      } else {
        accountIntegrationProcessMap.get(saveResultObj.Id).Status__c = 'Processed';
      }
    }
    update accountIntegrationProcessMap.values();
  }
  public void finish(Database.BatchableContext BC) {
    Bypass_Account_Validation__c accountValidation = Bypass_Account_Validation__c.getOrgDefaults();
    accountValidation.Bypass_Manifest_Address_Requirement__c = false;
	AccountCRUDHandler.isValidationDisable = true;
    update accountValidation;
  }
}