force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Process__c/Integration_Process__c.object-meta.xml
<CustomObject>
    <label>Integration Process</label>
    <nameField>
        <label>Integration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Process__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Integration Processes</relationshipLabel>
    <relationshipName>Integration_Processes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Process__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Ignored</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ownership_Change_Request__c/Ownership_Change_Request__c.object-meta.xml
<CustomObject>
    <label>Ownership Change Request</label>
    <nameField>
        <displayFormat>OCR-{000000}</displayFormat>
        <label>Ownership Change Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ownership Change Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ownership_Change_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ownership Change Requests</relationshipLabel>
    <relationshipName>Ownership_Change_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>  
</CustomField>

force-app/main/default/objects/Ownership_Change_Request__c/fields/Account_Operating_Segment__c.field-meta.xml
<CustomField>
    <fullName>Account_Operating_Segment__c</fullName>
    <formula>Text(Account__r.Primary_Service_Provider_New__c)</formula>
    <inlineHelpText>Current Operating Segment on the account.</inlineHelpText>
    <label>Account Operating Segment</label>
    <type>Text</type>
</CustomField> 

force-app/main/default/objects/Ownership_Change_Request__c/fields/Account_Operating_Segment_Text__c.field-meta.xml
<CustomField>
    <fullName>Account_Operating_Segment_Text__c</fullName>
    <label>Account Operating Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ownership_Change_Request__c/fields/Account_Owner_del__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner_del__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Ownership_Change_Requests_del</relationshipName>
    <type>Lookup</type>
</CustomField>
 

force-app/main/default/objects/Ownership_Change_Request__c/fields/Account_Primary_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Account_Primary_Service_Provider__c</fullName>
    <formula>Text(Account__r.Primary_Business__c)</formula>
    <inlineHelpText>Current Primary Service Provider on the account.</inlineHelpText>
    <label>Account Primary Service Provider</label>
    <type>Text</type>
</CustomField> 

force-app/main/default/objects/Ownership_Change_Request__c/fields/Account_Primary_Service_Provider_Text__c.field-meta.xml
<CustomField>
    <fullName>Account_Primary_Service_Provider_Text__c</fullName>
    <label>Account Primary Service Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ownership_Change_Request__c/fields/Current_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Current_Account_Owner__c</fullName>
    <description>This field is used for the Items to Approve unmanaged package and is intentionally left off of the layout</description>
    <formula>Account_Owner_del__r.FirstName &amp;&quot; &quot;&amp;  Account_Owner_del__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Account Owner</label>
    <type>Text</type>
</CustomField>
 

force-app/main/default/objects/Ownership_Change_Request__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>    
    <formula>IF(Intra_Quarter_Flip__c,
TODAY(),
IF(EligibileForIntraQuarterFlip__c &amp;&amp; ISPICKVAL(Account_Owner_del__r.Sales_Person_Type__c, &apos;Sales Placeholder&apos;),
NULL,
IF(Month(DATEVALUE(CreatedDate)) =1, DATE(YEAR(DATEVALUE(CreatedDate)) , 04 , 01), 
IF(Month(DATEVALUE(CreatedDate)) =2, DATE(YEAR(DATEVALUE(CreatedDate)) , 04 , 01),
IF(Month(DATEVALUE(CreatedDate)) =3, if((DAY(DATEVALUE(CreatedDate))&gt;= 25),DATE(YEAR(DATEVALUE(CreatedDate)) , 07 , 01),DATE(YEAR(DATEVALUE(CreatedDate)) , 04 , 01)),
IF(Month(DATEVALUE(CreatedDate)) =4, DATE(YEAR(DATEVALUE(CreatedDate)) , 07 , 01), 
IF(Month(DATEVALUE(CreatedDate)) =5, DATE(YEAR(DATEVALUE(CreatedDate)) , 07 , 01), 
IF(Month(DATEVALUE(CreatedDate)) =6, if((DAY(DATEVALUE(CreatedDate))&gt;= 24),DATE(YEAR(DATEVALUE(CreatedDate)) , 10 , 01),DATE(YEAR(DATEVALUE(CreatedDate)) , 07 , 01)),
IF(Month(DATEVALUE(CreatedDate)) =7, DATE(YEAR(DATEVALUE(CreatedDate)) , 10 , 01), 
IF(Month(DATEVALUE(CreatedDate)) =8, DATE(YEAR(DATEVALUE(CreatedDate)) , 10 , 01), 
IF(Month(DATEVALUE(CreatedDate)) =9, if((DAY(DATEVALUE(CreatedDate))&gt;= 24),DATE(YEAR(DATEVALUE(CreatedDate))+1 , 01 , 01),DATE(YEAR(DATEVALUE(CreatedDate)) , 10 , 01)),
IF(Month(DATEVALUE(CreatedDate)) =10, DATE(YEAR(DATEVALUE(CreatedDate))+1 , 01 , 01), 
IF(Month(DATEVALUE(CreatedDate)) =11, DATE(YEAR(DATEVALUE(CreatedDate))+1 , 01 , 01), 
IF(DAY(DATEVALUE(CreatedDate))&gt;= 25,DATE(YEAR(DATEVALUE(CreatedDate))+1 , 04 , 01),DATE(YEAR(DATEVALUE(CreatedDate))+1 , 01 , 01)))))))))))))))</formula>
    <inlineHelpText>This field is auto populated to the first day of the next quarter. Unless submitted in the final week of the current quarter.</inlineHelpText>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ownership_Change_Request__c/fields/Existing_Owner_s_Manager__c.field-meta.xml
<CustomField>
    <fullName>Existing_Owner_s_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Existing Owner’s Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Ownership_Change_Requests5</relationshipName>
    <type>Lookup</type>
</CustomField>
 

force-app/main/default/objects/Ownership_Change_Request__c/fields/Existing_Owner_s_VP__c.field-meta.xml
<CustomField>
    <fullName>Existing_Owner_s_VP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Existing Owner’s VP</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Ownership_Change_Requests6</relationshipName>
    <type>Lookup</type>
</CustomField>
 

force-app/main/default/objects/Ownership_Change_Request__c/fields/Justification__c.field-meta.xml
<CustomField>
    <fullName>Justification__c</fullName>
    <inlineHelpText>Provide any additional information on this particular change request.</inlineHelpText>
    <label>Justification</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>
 

force-app/main/default/objects/Ownership_Change_Request__c/fields/New_Operating_Segment__c.field-meta.xml
<CustomField>
    <fullName>New_Operating_Segment__c</fullName>
    <inlineHelpText>The operating segment that will be populated on the account if approved. This is determined by the requested owner&apos;s primary business.</inlineHelpText>
    <label>Requested Operating Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SK ENV</fullName>
            </value>
            <value>
                <fullName>SK BPS</fullName>
            </value>
            <value>
                <fullName>SK KPP</fullName>
            </value>
            <value>
                <fullName>Clean Harbors ENV</fullName>
            </value>
            <value>
                <fullName>CHES Oil and Gas</fullName>
            </value>
            <value>
                <fullName>CHES Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>
   

force-app/main/default/objects/Ownership_Change_Request__c/fields/New_Owner__c.field-meta.xml
<CustomField>
    <fullName>New_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the owner that is being requested for the account ownership change</description>
    <inlineHelpText>If approved, the user that will become the owner of the account.</inlineHelpText>
    <label>Requested Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Ownership_Change_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>
  

force-app/main/default/objects/Ownership_Change_Request__c/fields/New_Owner_s_Manager__c.field-meta.xml
<CustomField>
    <fullName>New_Owner_s_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Owner’s Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Ownership_Change_Requests3</relationshipName>
    <type>Lookup</type>
</CustomField>  
 

force-app/main/default/objects/Ownership_Change_Request__c/fields/New_Owner_s_VP__c.field-meta.xml
<CustomField>
    <fullName>New_Owner_s_VP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Owner’s VP</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Ownership_Change_Requests4</relationshipName>
    <type>Lookup</type>
</CustomField>
 

force-app/main/default/objects/Ownership_Change_Request__c/fields/Requested_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Requested_Account_Owner__c</fullName>
    <description>This field is used for the Items to Approve unmanaged package and is intentionally left off of the layout</description>
    <formula>New_Owner__r.FirstName &amp;&quot; &quot;&amp; New_Owner__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Requested Account Owner</label>
    <type>Text</type>
</CustomField> 

force-app/main/default/objects/Ownership_Change_Request__c/fields/Requested_Owner_Territory_Id__c.field-meta.xml
<CustomField>
    <fullName>Requested_Owner_Territory_Id__c</fullName>
    <label>Requested Owner Territory Id</label>
    <length>255</length>
    <type>Text</type> 
</CustomField> 

force-app/main/default/objects/Ownership_Change_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet> 
        <restricted>true</restricted>
        <valueSetDefinition>
            <value> 
                <fullName>New</fullName>
            </value>
            <value> 
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved-Pending</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value> 
            <value>
                <fullName>Executed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
			<value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountOwnershipChangeBatch.cls
/**
* @description       : Account Owner Update/WIN Sync Batch Job (587807)
* @author            : Vikram simha
* @group             : 
* @last modified on  : June-26-2022
* @last modified by  : Vikram simha
* Modifications Log
* Ver   Date         Author           Modification
* 1.0   05-30-2022   Suresh Beniwal   Initial Version
**/
public class AccountOwnershipChangeBatch implements Database.Batchable<sObject>{
    String query = '';
    String SKENV='SK ENV';
    String SKBPS='SK BPS';
    public AccountOwnershipChangeBatch(String query)
    {
        this.query = query;
    }
    public Database.QueryLocator start(Database.BatchableContext BC){
        DateTime startDate ;
        DateTime endDate ;
        Integer monthNum = Date.today().month();
        Integer yearNum = Date.today().year();
        if(monthNum < =3 )
        {
            startDate = DateTime.newInstance(yearNum, 01, 01);
            endDate = DateTime.newInstance(yearNum, 03, 31);
            
        }
        else if(monthNum > 3 &&  monthNum <= 6)
        {
            startDate = DateTime.newInstance(yearNum, 04, 01);
            endDate = DateTime.newInstance(yearNum, 06, 30);
        }
        else if(monthNum > 6 && monthNum <= 9)
        {
            startDate = DateTime.newInstance(yearNum, 07, 01);
            endDate = DateTime.newInstance(yearNum, 09, 30);
        }
        else
        {
            startDate = DateTime.newInstance(yearNum, 10, 01);
            endDate = DateTime.newInstance(yearNum, 12, 31);
        }
        startDate = DateTime.valueof(String.escapeSingleQuotes((String.valueofGmt(startDate))));
        endDate = DateTime.valueof(String.escapeSingleQuotes((String.valueofGmt(endDate))));
        if(query=='')
        {
            query = 'SELECT Id, Name, Account__c, Account_Owner_del__c,Account_Operating_Segment_Text__c,Requested_Owner_Territory_Id__c, Account_Operating_Segment__c,Account_Primary_Service_Provider_Text__c, Account_Primary_Service_Provider__c,'+
                'Current_Account_Owner__c, Requested_Account_Owner__c, New_Owner__c, Justification__c, New_Owner_s_Manager__c, New_Owner_s_VP__c, Existing_Owner_s_Manager__c, Existing_Owner_s_VP__c, Effective_Date__c, Status__c, New_Operating_Segment__c, New_Primary_Service_Provider__c, Prior_year_s_revenue__c, Need_Existing_Manager_Approval__c, Account_Owner_Managers_Same__c,'+
                'Account_Owner_Vps_Same__c, Reason_for_Change__c FROM Ownership_Change_Request__c where Status__c = \'Approved-Pending\' and Effective_Date__c >= '+startDate.format('yyyy-MM-dd') +' and Effective_Date__c <= '+endDate.format('yyyy-MM-dd');
        }
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List<sObject> scope){
        List<Account> accounts = new List<Account>();
        Map<id,Ownership_Change_Request__c> ownershipChangeRequestsMap = new Map<Id,Ownership_Change_Request__c>();
        List<Integration_Process__c> integrationRecordsToErrorLog = new List<Integration_Process__c>();
        Set<id> accountIdSet = new Set<id>();
        Set<string> territoryNameSet = new Set<string>();
        Map<string,Territory__c> territoryNameAvailable = new Map<string,Territory__c>();
        for(Ownership_Change_Request__c changeRequestObj : (List<Ownership_Change_Request__c>)scope)
        {
            territoryNameSet.add(changeRequestObj.Requested_Owner_Territory_Id__c);
            if((changeRequestObj.New_Operating_Segment__c == SKENV||changeRequestObj.New_Operating_Segment__c == SKBPS)
               &&(changeRequestObj.New_Operating_Segment__c!=changeRequestObj.Account_Operating_Segment_Text__c || changeRequestObj.New_Primary_Service_Provider__c!=changeRequestObj.Account_Primary_Service_Provider_Text__c))
                
            {
                accountIdSet.add(changeRequestObj.Account__c); 
            }
        }
        Map<Id,Account> accountsMap = new Map<Id,Account>([select id,name,Primary_SK_Branch_Override__c,Primary_SK_Branch__c from account where id in:accountIdSet and Primary_SK_Branch_Override__c=true]);
        List<Territory__c> territoryList= [select id,name from Territory__c where name in :territoryNameSet];
        for(Territory__c  territory : territoryList)
        {
            territoryNameAvailable.put(territory.Name,territory);
        }
        for(Ownership_Change_Request__c changeRequestObj : (List<Ownership_Change_Request__c>)scope)
        {
            if(territoryNameAvailable.ContainsKey(changeRequestObj.Requested_Owner_Territory_Id__c))
            {
                Account acc = new Account();
                acc.id = changeRequestObj.Account__c;
                if(accountsMap.containsKey(changeRequestObj.Account__c))
                {
                    if(accountsMap.get(changeRequestObj.Account__c).Primary_SK_Branch__c!='OAC' && accountsMap.get(changeRequestObj.Account__c).Primary_SK_Branch__c!='RMS')
                    {
                        acc.Primary_SK_Branch_Override__c = false;
                    }
                }
                acc.OwnerId = changeRequestObj.New_Owner__c;
                acc.Primary_Service_Provider_New__c = changeRequestObj.New_Operating_Segment__c;
                acc.Primary_Business__c = changeRequestObj.New_Primary_Service_Provider__c;
                acc.Territory_Override__c = true;
                acc.Territory_ID_SK__c = territoryNameAvailable.get(changeRequestObj.Requested_Owner_Territory_Id__c).Id;
                changeRequestObj.Status__c = 'Executed';
                accounts.add(acc);
            }
            else
            {
                Integration_Process__c integProcess = new Integration_Process__c();
                integProcess.Status__c= 'Error';
                integProcess.Process_Type__c= CHConstants.OCRBatchUpdate;
                integProcess.Account__c= changeRequestObj.Account__c;
                integProcess.Error_Message__c= 'Requested Owner Territory Id Not Found.';
                changeRequestObj.Status__c = 'Failed';
                integrationRecordsToErrorLog.add(integProcess);
            }
            ownershipChangeRequestsMap.put(changeRequestObj.Account__c,changeRequestObj);
        } 
        if(!accounts.Isempty()){
            AccountCRUDHandler.SKIP_ONOwnerChangeBatch = True;
            Database.SaveResult[] ocrList = Database.update(accounts, false);
            for (Database.SaveResult sr : ocrList) {
                Integration_Process__c integProcess = new Integration_Process__c();
                if (sr.isSuccess()) {
                    integProcess.Status__c= 'Processed';
                    integProcess.Process_Type__c= CHConstants.OCRBatchUpdate;
                    integProcess.Account__c= sr.getId();
                } else {
                    for(Database.Error objErr : sr.getErrors()) {
                        integProcess.Status__c= 'Error';
                        integProcess.Process_Type__c= CHConstants.OCRBatchUpdate;
                        integProcess.Account__c= sr.getId();
                        ownershipChangeRequestsMap.get(integProcess.Account__c).Status__c = 'Failed';
                        integProcess.Error_Message__c= objErr.getMessage();
                    }
                }
                integrationRecordsToErrorLog.add(integProcess);
            }
        }
        
        if(!ownershipChangeRequestsMap.IsEmpty())
        {
            Database.SaveResult[] ocrrequestList = Database.update(ownershipChangeRequestsMap.values(), false);
            for (Database.SaveResult sr : ocrrequestList) {
                Integration_Process__c integProcess = new Integration_Process__c();
                if (sr.isSuccess()) {
                    
                } else {
                    for(Database.Error objErr : sr.getErrors()) {
                        integProcess.Status__c= 'Error';
                        integProcess.Process_Type__c= CHConstants.OCRBatchUpdate;
                        integProcess.Error_Message__c= 'Ownership Chage Request Object '+' |'+sr.getId()+'| '+objErr.getMessage();
                        integrationRecordsToErrorLog.add(integProcess);
                    }
                }
            }
        }
        insert integrationRecordsToErrorLog;
    }
    public void finish(Database.BatchableContext BC){
        
    } 
}