force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/WIN_ID__c.field-meta.xml
<CustomField>
    <fullName>WIN_ID__c</fullName>
    <externalId>true</externalId>
    <label>WIN ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>All Clean Harbors Customers</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Customer_Location.recordType-meta.xml
<RecordType>
    <fullName>Customer_Location</fullName>
    <active>true</active>
    <description>All Clean Harbor Customer Ship-To/Gen Accounts</description>
    <label>Customer Location</label>
</RecordType>

force-app/main/default/objects/Case/fields/Case_Rank__c.field-meta.xml
<CustomField>
    <fullName>Case_Rank__c</fullName>
    <description>Case Rank for Inside Sales account ranking purpose</description>
    <label>Case Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Level_1_Escalation__c.field-meta.xml
<CustomField>
    <fullName>Level_1_Escalation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>2nd call / irate customer</description>
    <inlineHelpText>2nd call / irate customer</inlineHelpText>
    <label>Level 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Level_2_Escalation__c.field-meta.xml
<CustomField>
    <fullName>Level_2_Escalation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>3rd call</description>
    <inlineHelpText>3rd call</inlineHelpText>
    <label>Level 2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Level_3_Escalation__c.field-meta.xml
<CustomField>
    <fullName>Level_3_Escalation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>4th call or more</description>
    <inlineHelpText>4th call or more</inlineHelpText>
    <label>Level 3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/WIN_Id__c.field-meta.xml
<CustomField>
    <fullName>WIN_Id__c</fullName>
    <label>WIN Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Collector_PO_Case.recordType-meta.xml
<RecordType>
    <fullName>Collector_PO_Case</fullName>
    <active>true</active>
    <businessProcess>PO Case Process</businessProcess>
    <description>Collector Case</description>
    <label>Collector Case</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Customer_PO_Case.recordType-meta.xml
<RecordType>
    <fullName>Customer_PO_Case</fullName>
    <active>true</active>
    <businessProcess>PO Case Process</businessProcess>
    <label>Customer PO Case</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Customer_Service_Case.recordType-meta.xml
<RecordType>
    <fullName>Customer_Service_Case</fullName>
    <active>true</active>
    <businessProcess>Customer Service</businessProcess>
    <description>Customer Service case</description>
    <label>Customer Service Case</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Customer_Service_Case_New.recordType-meta.xml
<RecordType>
    <fullName>Customer_Service_Case_New</fullName>
    <active>true</active>
    <businessProcess>Customer Service</businessProcess>
    <description>New Customer Service Case Type</description>
    <label>Customer Service Case(New)</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Invoice_Delivery.recordType-meta.xml
<RecordType>
    <fullName>Invoice_Delivery</fullName>
    <active>true</active>
    <businessProcess>Invoice Delivery Case</businessProcess>
    <description>Invoice Delivery Cases from WIN</description>
    <label>Invoice Delivery</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Non_Standard_Billing_Closed_Order.recordType-meta.xml
<RecordType>
    <fullName>Non_Standard_Billing_Closed_Order</fullName>
    <active>true</active>
    <businessProcess>Non Standard Billing</businessProcess>
    <description>Non Standard Billing Closed Order</description>
    <label>Non Standard Billing Closed Order</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Non_Standard_Billing_WIN.recordType-meta.xml
<RecordType>
    <fullName>Non_Standard_Billing_WIN</fullName>
    <active>true</active>
    <businessProcess>Non Standard Billing</businessProcess>
    <description>Non Standard Billing Case from WIN</description>
    <label>Non Standard Billing WIN</label>
</RecordType>

force-app/main/default/classes/CaseRankBatchFix.cls
public class CaseRankBatchFix implements Database.Batchable<sObject>,Database.Stateful{
    public integer total =0;
    public Database.QueryLocator start (database.BatchableContext BC){
        
        string openCaseRecordTypeQuery = '(RecordType.DeveloperName = \'Collector_PO_Case\' OR RecordType.DeveloperName = \'Customer_PO_Case\' OR RecordType.DeveloperName = \'Non_Standard_Billing_Closed_Order\' OR RecordType.DeveloperName = \'Non_Standard_Billing_WIN\' OR RecordType.DeveloperName = \'Invoice_Delivery\' OR RecordType.DeveloperName = \'Customer_Service_Case\' OR RecordType.DeveloperName = \'Customer_Service_Case_New\')';
        string closedCaseRecordTypeQuery = '(RecordType.DeveloperName = \'Customer_Service_Case\' OR RecordType.DeveloperName = \'Customer_Service_Case_New\')';
        string accountRecordQuery = 'account.Status__c = \'Active\' AND account.win_id__c != null AND (account.RecordType.DeveloperName = \'Customer\' OR account.RecordType.DeveloperName = \'Customer_Location\')';
        string openCaseQuery = '(Status = \'New\' OR Status = \'In Progress\') AND (owner.UserRole.DeveloperName = \'SK_INS_BPS_AM\' OR owner.UserRole.DeveloperName = \'SK_INS_SKE_AM\') AND '+openCaseRecordTypeQuery+' AND '+accountRecordQuery;
        string closedCaseQuery = 'Status = \'Resolved\' AND (Level_1_Escalation__c = true OR Level_2_Escalation__c = true OR Level_3_Escalation__c = true) AND ClosedDate = LAST_N_DAYS:10 AND '+closedCaseRecordTypeQuery+' AND '+accountRecordQuery;
        String Query = 'Select Id From Case where (('+openCaseQuery+') OR ('+closedCaseQuery+')) ORDER By AccountId';
        return Database.getQueryLocator(Query);  
    }
    
    public void Execute (Database.BatchableContext BC, List<sObject>Scope){
        total += Scope.size();
        Set<Id> caseId = new Set<Id> ();
        List<Case> updateCaseList = new List<case>();
        for (Case csl:(List<Case>)Scope){
            caseId.add(csl.id);
        }
        
        List<Case> csList = [Select Id, Case_Rank__c,OwnerId,Account.OwnerId,Status From Case where Id in :caseId FOR UPDATE];
        for (Case c:csList){
            if ((c.status == 'New' || c.Status == 'In Progress') && (c.Ownerid == c.Account.Ownerid)){
                Case cs = new case();
                cs.id = c.id; 
                cs.Case_Rank__c = 10;
                updateCaseList.add(cs);
            }else if(c.status == 'Resolved'){
                Case cs = new case();
                cs.id = c.id;
                cs.Case_Rank__c = 7;
                updateCaseList.add(cs);
            }
            
        }
        
        if(updateCaseList.size() >0){
            Database.SaveResult[] SaveResultList = Database.update(updateCaseList,false);
            ExceptionLogHelper.logException(true, SaveResultList, 'Case', updateCaseList, 'CaseRankBatchFix', 'execute');
        }
        
    }
    
    public void Finish (Database.BatchableContext BC){
        
    }
    

}