force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/WIN_ID__c.field-meta.xml
<CustomField>
    <fullName>WIN_ID__c</fullName>
    <externalId>true</externalId>
    <label>WIN ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>All Clean Harbors Customers</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Customer_Location.recordType-meta.xml
<RecordType>
    <fullName>Customer_Location</fullName>
    <active>true</active>
    <description>All Clean Harbor Customer Ship-To/Gen Accounts</description>
    <label>Customer Location</label>
</RecordType>

force-app/main/default/objects/Activity/fields/Event_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Start_Date__c</fullName>
    <formula>ActivityDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Event Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Face to Face</fullName>
            </value>
            <value>
                <fullName>Quoted</fullName>
            </value>
            <value>
                <fullName>Virtual (WebEx)</fullName>
            </value>
            <value>
                <fullName>Working on Quote</fullName>
            </value>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Internal Discussion</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Security Response</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity/fields/Win_Id__c.field-meta.xml
<CustomField>
    <fullName>Win_Id__c</fullName>
    <label>Win Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WIN_ID__c.field-meta.xml
<CustomField>
    <fullName>WIN_ID__c</fullName>
    <formula>Account.WIN_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>WIN ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/WIN_ID__c.field-meta.xml
<CustomField>
    <fullName>WIN_ID__c</fullName>
    <description>WIN ID of account picked for opportunity.</description>
    <formula>Account.WIN_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>WIN ID of account picked for opportunity.</inlineHelpText>
    <label>WIN ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Profile__mdt/Sales_Profile__mdt.object-meta.xml
<CustomObject>
    <description>Sales Profile for Activity Rank Considerations</description>
    <label>Sales Profile</label>
    <pluralLabel>Sales Profiles</pluralLabel>
</CustomObject>

force-app/main/default/objects/Sales_Profile__mdt/fields/Profile_Names__c.field-meta.xml
<CustomField>
    <fullName>Profile_Names__c</fullName>
    <description>Sales Profile for IS Ranking</description>
    <label>Profile Names</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Activity.recordType-meta.xml
<RecordType>
    <fullName>Activity</fullName>
    <active>true</active>
    <description>Follow-ups and reminders</description>
    <label>Activity</label>
</RecordType>

force-app/main/default/classes/ActivityAggregateResultIterator.cls
global class ActivityAggregateResultIterator Implements Iterator<AggregateResult>{
    AggregateResult [] results {get;set;} 
    Integer index {get;set;} 
    
    global ActivityAggregateResultIterator(Boolean isEvent){
        Id taskRecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Activity').getRecordTypeId();
        string salesProfile = [SELECT Profile_Names__c FROM Sales_Profile__mdt where DeveloperName = 'Sales_Profile_for_IS_Ranking'].Profile_Names__c;
        set<string> salesProfileSet = new set<string>();
        salesProfileSet.addAll(salesProfile.split('@'));

        index = 0;
		String query;
        if(isEvent == true){
        	query = 'select accountId, Max(Event_Start_Date__c)maxActivityDate From Event'+
            			' where (Owner.Profile.Name in:salesProfileSet)'+ 
                        ' And (Who.Type=\'Contact\' Or What.Type IN (\'Account\', \'Opportunity\'))'+
                        ' And (account.owner.UserRole.DeveloperName = \'SK_INS_BPS_AM\' OR account.owner.UserRole.DeveloperName = \'SK_INS_SKE_AM\')' +
                        ' And (account.RecordType.DeveloperName = \'Customer\' OR account.RecordType.DeveloperName = \'Customer_Location\')'+
                        ' AND account.Status__c = \'Active\' AND account.win_id__c != null'+
            			' AND Event_Start_Date__c >= LAST_N_DAYS:90'+
            			' AND (Event_Type__c != \'Internal Discussion\' AND Event_Type__c != \'Security Response\')'+
                        ' Group By accountId'; 
        }else if (isEvent == false){
            query = 'select accountId, Max(Event_Start_Date__c)maxActivityDate From Task'+
            			' where RecordTypeId = :taskRecordTypeId'+
                		' AND (Owner.Profile.Name in:salesProfileSet)'+ 
                        ' And (Who.Type=\'Contact\' Or What.Type IN (\'Account\', \'Opportunity\'))'+
                        ' And (account.owner.UserRole.DeveloperName = \'SK_INS_BPS_AM\' OR account.owner.UserRole.DeveloperName = \'SK_INS_SKE_AM\')' +
                        ' And (account.RecordType.DeveloperName = \'Customer\' OR account.RecordType.DeveloperName = \'Customer_Location\')'+
                        ' AND account.Status__c = \'Active\' AND account.win_id__c != null'+
                		' AND Event_Start_Date__c >= LAST_N_DAYS:90'+
                        ' Group By accountId';
        }
        results = Database.query(query);
        system.debug('results size----'+results.size());
    } 
    
    global boolean hasNext(){ 
        return results !=null && !results.isEmpty() && index < results.size(); 
    } 
    
    global AggregateResult next(){ 
        return results[index++]; 
    } 
    
}