force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/WIN_Validated__c.field-meta.xml
<CustomField>
    <fullName>WIN_Validated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A boolean flag which determines if the record is validated based on WIN Complaint rules. All records with value as TRUE are then extracted by Beacon for downstream processing.</description>
    <label>Pending Beacon Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Broker.recordType-meta.xml
<RecordType>
    <fullName>Broker</fullName>
    <active>true</active>
    <description>All Clean Harbors Brokers</description>
    <label>Broker</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Broker_Location.recordType-meta.xml
<RecordType>
    <fullName>Broker_Location</fullName>
    <active>true</active>
    <description>All Clean Harbors Broker/Gen Accounts</description>
    <label>Broker Location</label>
</RecordType>

force-app/main/default/objects/Bypass_Account_Validation__c/Bypass_Account_Validation__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bypass Account Validation</label>
</CustomObject>

force-app/main/default/objects/Bypass_Account_Validation__c/fields/Bypass_Manifest_Address_Requirement__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Manifest_Address_Requirement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Manifest Address Requirement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Location/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChangeRecordTypeForBrokerChildren.cls
public class ChangeRecordTypeForBrokerChildren implements Database.Batchable<sObject>{
    private Id parentAccId;
    
    public ChangeRecordTypeForBrokerChildren(Id parentAccId){
        this.parentAccId = parentAccId;
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC){
         Bypass_Account_Validation__c accountValidation = Bypass_Account_Validation__c.getOrgDefaults();
        accountValidation.Bypass_Manifest_Address_Requirement__c = true; 
        UPDATE accountValidation;
        Id accId = this.parentAccId;
        String query = 'select id from account where parentid =:accId AND RecordType.DeveloperName != \'Broker_Location\' and Status__c=\'Active\'';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Account> scope){
        Id brokerLocationRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Broker Location').getRecordTypeId();
        List<Account> childAccountsToBeUpdated = new List<Account>();
        for(Account accRec: scope){
            accRec.RecordTypeId = brokerLocationRecordTypeId;
            accRec.Type='Brok/Gen';
            accRec.WIN_Validated__c=true;
            childAccountsToBeUpdated.add(accRec);
        }
if(!childAccountsToBeUpdated.isEmpty()){
            List<Database.SaveResult> saveResultLst = Database.update(childAccountsToBeUpdated, false);
            
            for (Database.SaveResult saveResultObj : saveResultLst) {
                if (!saveResultObj.isSuccess()) {
                    String errorMsg = '';
                    for(Database.Error err : saveResultObj.getErrors()) {
                        errorMsg += err.getMessage() + '\n';
                    }
                    
                    if(errorMsg.length() > 0)
                        errorMsg = errorMsg.substring(0, errorMsg.length() - 2); 
                }
            }
        } 
        
    }
    
    public void finish(Database.BatchableContext BC){
        Bypass_Account_Validation__c accountValidation = Bypass_Account_Validation__c.getOrgDefaults();
        accountValidation.Bypass_Manifest_Address_Requirement__c = false; 
        UPDATE accountValidation;
    }
}