force-app/main/default/objects/Account/fields/WIN_ID__c.field-meta.xml
<CustomField>
    <fullName>WIN_ID__c</fullName>
    <externalId>true</externalId>
    <label>WIN ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Comments__c/Comments__c.object-meta.xml
<CustomObject>
    <label>Comment</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Account__c/Competitor_Account__c.object-meta.xml
<CustomObject>
    <description>Competitor Account</description>
    <label>Competitor Account</label>
    <nameField>
        <label>Competitor Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitor Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Competitor Accounts</relationshipLabel>
    <relationshipName>Competitor_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitor_Capture__c/Competitor_Capture__c.object-meta.xml
<CustomObject>
    <label>Competitor Capture</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Competitor Capture Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitor Capture</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor_Capture__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account ID</description>
    <inlineHelpText>Customer account associated with the competitor capture</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Competitor Capture</relationshipLabel>
    <relationshipName>Competitor_Capture</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitor_Capture__c/fields/Annual_UMO_Volume__c.field-meta.xml
<CustomField>
    <fullName>Annual_UMO_Volume__c</fullName>
    <description>Total volume for the year for this customer</description>
    <inlineHelpText>Total volume for the year for this customer</inlineHelpText>
    <label>Annual UMO Volume</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Competitor_Capture__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>Additional comments; If Brand is *Other than Required here; If Competitor is  *OTHER than Required here</description>
    <inlineHelpText>Additional comments; If Brand is *Other than Required here; If Competitor is  *OTHER than Required here</inlineHelpText>
    <label>Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Competitor_Capture__c/fields/Competitor_Account__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Competitor associated with entry. If Competitor not in SF - create new competitor OR use ** OTHER MISC COMPETITOR ** &amp; list competitor &amp; address in comments section</description>
    <inlineHelpText>Competitor associated with entry. If Competitor not in SF - create new competitor OR use ** OTHER MISC COMPETITOR ** &amp; list competitor &amp; address in comments section</inlineHelpText>
    <label>Competitor Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Competitor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Competitor Capture (Competitor Account)</relationshipLabel>
    <relationshipName>Competitor_Capture1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitor_Capture__c/fields/CreatedBy_Username__c.field-meta.xml
<CustomField>
    <fullName>CreatedBy_Username__c</fullName>
    <label>Created by Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Competitor_Capture__c/fields/Invoice_or_Proposal_date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_or_Proposal_date__c</fullName>
    <description>Date on the invoice or proposal. Required if invoice or proposal selected in Attachment Type</description>
    <inlineHelpText>Date on the invoice or proposal. Required if invoice or proposal selected in Attachment Type</inlineHelpText>
    <label>Invoice or Proposal date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Competitor_Capture__c/fields/Oil_Filter_Price__c.field-meta.xml
<CustomField>
    <fullName>Oil_Filter_Price__c</fullName>
    <label>Oil Filter Price Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bin</fullName>
            </value>
            <value>
                <fullName>Drum</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competitor_Capture__c/fields/Oil_Filter_Prices__c.field-meta.xml
<CustomField>
    <fullName>Oil_Filter_Prices__c</fullName>
    <label>Oil Filter Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Competitor_Capture__c/fields/Pay_or_Charge__c.field-meta.xml
<CustomField>
    <fullName>Pay_or_Charge__c</fullName>
    <description>If customer is Pay, Charge or No Charge for UMO</description>
    <inlineHelpText>If customer is Pay, Charge or No Charge for UMO</inlineHelpText>
    <label>Price Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PFO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>No Charge</fullName>
            </value>
            <value>
                <fullName>Charge</fullName>
                <isActive>false</isActive>
                <label>Charge</label>
            </value>
            <value>
                <fullName>Pay</fullName>
                <isActive>false</isActive>
                <label>Pay</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competitor_Capture__c/fields/Price_per_UOM__c.field-meta.xml
<CustomField>
    <fullName>Price_per_UOM__c</fullName>
    <description>Price per the UoM</description>
    <inlineHelpText>Price per the UoM</inlineHelpText>
    <label>Price per Unit of Measure</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Competitor_Capture__c/fields/Product_Packaging__c.field-meta.xml
<CustomField>
    <fullName>Product_Packaging__c</fullName>
    <description>Packaging customer is purchasing</description>
    <inlineHelpText>Packaging customer is purchasing</inlineHelpText>
    <label>Product Packaging</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bulk</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Drum</fullName>
            </value>
            <value>
                <fullName>Pail</fullName>
            </value>
            <value>
                <fullName>Keg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competitor_Capture__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <description>UoM of the price</description>
    <inlineHelpText>UoM of the price</inlineHelpText>
    <label>Unit of Measure</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Packaging__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bulk</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Drum</fullName>
            </value>
            <value>
                <fullName>Gallons</fullName>
            </value>
            <value>
                <fullName>Liters</fullName>
            </value>
            <value>
                <fullName>Quarts</fullName>
            </value>
            <value>
                <fullName>Pail</fullName>
            </value>
            <value>
                <fullName>Keg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competitor_Capture__c/fields/Waste_AF_Price_per_Gallon__c.field-meta.xml
<CustomField>
    <fullName>Waste_AF_Price_per_Gallon__c</fullName>
    <label>Waste AF Price per Gallon</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/RestUMOCapture.cls
/**
 * @description       : 
 * @author            : Irfan Khan
 * @group             : 
 * @last modified on  : 01-09-2023
 * @last modified by  : Irfan Khan
**/
@RestResource(urlMapping = '/CreateUMOCapture/*')

global class RestUMOCapture {
    
    @HttpPost
    
    global static void createnewUMOcapture(){
        
        RestRequest request = RestContext.request;
        
        RequestWrapper reqWrapper = (RequestWrapper)JSON.deserialize(request.requestbody.tostring(), RequestWrapper.class);
                
        try{
            
            Competitor_Capture__c ccObj = new Competitor_Capture__c();
            
            List<Account> accs = new List<Account>();
            accs = [Select Id, Name, OwnerId from Account where WIN_ID__c =:reqWrapper.CUST_ID LIMIT 1];
            if(!accs.isEmpty()){
                ccObj.Account__c = accs[0].Id; 
            }
            
            List<Account> compAccs = new List<Account>();
            compAccs = [Select Id, Name, OwnerId from Account where WIN_ID__c =:reqWrapper.COMPTR_CUST_ID LIMIT 1];
            if(!compAccs.isEmpty()){
                ccObj.Competitor_Account__c = compAccs[0].Id; 
            }
            
            ccObj.Comments__c = reqWrapper.COMMENTS;
            ccObj.CurrencyIsoCode = reqWrapper.CURRENCY_CODE;
            ccObj.Oil_Filter_Prices__c = Decimal.ValueOf(reqWrapper.OIL_FILTER_PRICE);
            ccObj.Oil_Filter_Price__c = reqWrapper.FILTER_PRICE_TYPE;
            ccObj.Invoice_or_Proposal_date__c = (Date.valueOf(reqWrapper.INVOICE_OR_PROP_DT));
            ccObj.Pay_or_Charge__c = reqWrapper.PAYORCHARGE;
            ccObj.Product_Packaging__c = reqWrapper.PROD_PACKG;
            ccObj.RecordTypeId = '012j00000004WMl';
            ccObj.Price_per_UOM__c = Decimal.ValueOf(reqWrapper.UOMPRICE);
            ccObj.Unit_of_Measure__c = reqWrapper.UNITS;
            ccObj.Waste_AF_Price_per_Gallon__c = (Decimal.ValueOf(reqWrapper.WASTE_PRICE));
            ccObj.Annual_UMO_Volume__c = Decimal.ValueOf(reqWrapper.ANNUAL_GALLONS);
            ccObj.CreatedBy_Username__c = reqWrapper.CREATEDBY_USERNAME;
            
            
            insert ccObj;
            
            string Name;
            List<Competitor_Capture__c> cCapt= [select Id,Name from Competitor_Capture__c where Id=: ccObj.Id];
            for(Competitor_Capture__c c: cCapt) {  Name = c.Name;}     RestContext.response.responseBody = Blob.valueOf('{"CompCaptureId" :"' +ccObj.Id+'","Error":"","Comp Capture":"'+Name+'"}');
        }
            	
        
        catch (Exception e){
            system.debug('---'+e.getLineNumber());
            RestContext.response.responseBody = Blob.valueOf('{"CompCap_Id":"","Error":"'+ e.getMessage() +'","CompCaptureId":""}');
        }
    }
        

    global class RequestWrapper{
        
        public String CUST_ID;
        public String COMPTR_CUST_ID;
        public String COMMENTS;
               
        
        public String CREATED_DATE;
        public String CURRENCY_CODE;
        public String OIL_FILTER_PRICE;
        public String FILTER_PRICE_TYPE;
        public String PAYORCHARGE;
        public String UOMPRICE;
        public String PROD_PACKG;
        
        
        //public String REC_TYPEID;
        public String UNITS;
        public String WASTE_PRICE;
        public String INVOICE_OR_PROP_DT;
        public String ANNUAL_GALLONS;
        public String CREATEDBY_USERNAME;
        
    }
}