force-app/main/default/objects/TranseraUser__c/TranseraUser__c.object-meta.xml
<CustomObject>
    <description>Transera User</description>
    <label>TranseraUser</label>
    <nameField>
        <label>TranseraUser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TranseraUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TranseraUser__c/fields/LoginName__c.field-meta.xml
<CustomField>
    <fullName>LoginName__c</fullName>
    <description>Transera Login Name</description>
    <externalId>true</externalId>
    <label>LoginName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TranseraUser__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <description>Transera User Password</description>
    <label>Password</label>
    <length>50</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/TranseraUser__c/fields/SalesforceUsername__c.field-meta.xml
<CustomField>
    <fullName>SalesforceUsername__c</fullName>
    <description>Salesforce Username</description>
    <externalId>true</externalId>
    <label>SalesforceUsername</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TranseraUser__c/fields/Tenant__c.field-meta.xml
<CustomField>
    <fullName>Tenant__c</fullName>
    <description>Tenant Name</description>
    <label>Tenant</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TransUserInfoDetails.cls
global class TransUserInfoDetails
{
    webService static String getUserDetails()
    {    
        SFUser usr = new SFUser();
        usr.userId = UserInfo.getUserId();
        usr.userName = UserInfo.getUserName();
        usr.userOrg = UserInfo.getOrganizationName();
        
        return JSON.serialize(usr);   
    }
    
    webService static String saveOrUpdateUserInfo(String sfUsername, String xeraLogin, String password, String tenant)
    {
        boolean upateRec = true;
        TranseraUser__c xeraUser;
        try {
            xeraUser = [Select SalesforceUsername__c, LoginName__c, Password__c, Tenant__c From TranseraUser__c Where SalesforceUsername__c = :sfUsername limit 1];
        } catch (Exception e) {
            upateRec = false;
        }

        if (xeraUser == null) {
            xeraUser = new TranseraUser__c(SalesforceUsername__c = sfUsername, LoginName__c = xeraLogin, Password__c = EncodingUtil.base64Encode(Blob.valueOf(password)), Tenant__c = tenant);
            upateRec = false;
        }
        
        
        if (upateRec) {
            update xeraUser;
        } else {
            insert xeraUser;
        }

        return 'success';
    }

    webService static String getTranseraUserDetails(String sfUsername)
    {
        System.Debug('getTranseraUserDetails method invoked ' + sfUsername);
        TranseraUser__c usr = [Select SalesforceUsername__c, LoginName__c, Password__c, Tenant__c From TranseraUser__c Where SalesforceUsername__c = :sfUsername limit 1];
        if(usr != null){
            TranseraUserModel userModel = new TranseraUserModel(usr.SalesforceUsername__c, usr.LoginName__c, usr.Password__c, usr.Tenant__c);
            return JSON.serialize(userModel);
        }
        return '{}';
    }
    
    public class SFUser{
        public String userId {get;set;}
        public String userName {get;set;}
        public String userOrg {get;set;}
    }
}