force-app/main/default/objects/TranseraUser__c/TranseraUser__c.object-meta.xml
<CustomObject>
    <description>Transera User</description>
    <label>TranseraUser</label>
    <nameField>
        <label>TranseraUser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TranseraUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TranseraUser__c/fields/LoginName__c.field-meta.xml
<CustomField>
    <fullName>LoginName__c</fullName>
    <description>Transera Login Name</description>
    <externalId>true</externalId>
    <label>LoginName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TranseraUser__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <description>Transera User Password</description>
    <label>Password</label>
    <length>50</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/TranseraUser__c/fields/SalesforceUsername__c.field-meta.xml
<CustomField>
    <fullName>SalesforceUsername__c</fullName>
    <description>Salesforce Username</description>
    <externalId>true</externalId>
    <label>SalesforceUsername</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TranseraUser__c/fields/Tenant__c.field-meta.xml
<CustomField>
    <fullName>Tenant__c</fullName>
    <description>Tenant Name</description>
    <label>Tenant</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestTransUserInfoDetails.cls
@isTest(SeeAllData=true)
private class TestTransUserInfoDetails {
    private static testMethod void testGetUserDetails() {
        String result = TransUserInfoDetails.getUserDetails();
        System.assert(result != null, 'User info can not be empty');
    }

    private static testMethod void testSaveOrUpdateUserInfo() {
        String result = TransUserInfoDetails.saveOrUpdateUserInfo('salesforce@transerainc.com', 'salesforce', 'sunil~1', 'Transera');
        System.assertNotEquals(result, '', 'Could not save the data');
    }

    private static testMethod void testGetTransUserDetails() {
        String salesforceId = 'salesforce';
        TranseraUser__c user = new TranseraUser__c(SalesforceUsername__c = salesforceId , LoginName__c = 'sales', Password__c = EncodingUtil.base64Encode(Blob.valueOf('pass')), Tenant__c = 'transera');
        
        insert user ;
        
        try {
            System.assertNotEquals(TransUserInfoDetails.getTranseraUserDetails(salesforceId),'','The salesforce user does not exist');
        } finally {
            delete user;
        }
    }
}