force-app/main/default/objects/Work_Notes__c/Work_Notes__c.object-meta.xml
<CustomObject>
    <label>Work Note</label>
    <nameField>
        <displayFormat>WN-{0000000}</displayFormat>
        <label>Work Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Notes__c/fields/Win_Validated__c.field-meta.xml
<CustomField>
    <fullName>Win_Validated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Win Validated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/WorkNotesCRUDHandler.cls
/**
 * Helper class invoked from Trigger.
 * 
 * @author	Cloud Sherpas
 * @created	09-Nov-2015
 */ 
public class WorkNotesCRUDHandler {

    /*
     * This method updates the WIN Validated flag to TRUE. Invoked from Trigger.
     * 
     * @param	list of beacon work notes to be updated 
     */ 
    public static void updateWINValidatedFlag(List<Work_Notes__c> workNotesList) {
        for(Work_Notes__c wn : workNotesList) {
            wn.WIN_Validated__c = true;
        }
    }
}