force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <description>Territory Name, owner, branch, primary business, and leadership</description>
    <label>Territory</label>
    <nameField>
        <label>Territory code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Sales_Person_Type__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person_Type__c</fullName>
    <label>Sales Person Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Development Manager</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Asset Management</fullName>
            </value>
            <value>
                <fullName>Branch Administration</fullName>
            </value>
            <value>
                <fullName>Branch District Manager</fullName>
            </value>
            <value>
                <fullName>Branch Manager</fullName>
            </value>
            <value>
                <fullName>Branch Operations</fullName>
            </value>
            <value>
                <fullName>Branch Project Manager</fullName>
            </value>
            <value>
                <fullName>Call Center Agent</fullName>
            </value>
            <value>
                <fullName>Central Profile</fullName>
            </value>
            <value>
                <fullName>Chemist</fullName>
            </value>
            <value>
                <fullName>Collections</fullName>
            </value>
            <value>
                <fullName>Corporate Billing</fullName>
            </value>
            <value>
                <fullName>Corporate Collections</fullName>
            </value>
            <value>
                <fullName>Corporate Finance</fullName>
            </value>
            <value>
                <fullName>Corporate Pricing</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Dispatcher</fullName>
            </value>
            <value>
                <fullName>Health and Safety</fullName>
            </value>
            <value>
                <fullName>InSite Operations</fullName>
            </value>
            <value>
                <fullName>InSite Program Manager</fullName>
            </value>
            <value>
                <fullName>InSite Project Manager</fullName>
            </value>
            <value>
                <fullName>ISAM</fullName>
            </value>
            <value>
                <fullName>Key Account Manager</fullName>
            </value>
            <value>
                <fullName>Key Account Support</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Master Data Management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UserDAO.cls
/**
 * @description       : 
 * @author            : Vikram Simha
 * @group             : 
 * @last modified on  : 03-08-2023
 * @last modified by  : Vikram Simha
 * Modifications Log
 * Ver   Date         Author           Modification
 * 1.0   03-08-2023   Vikram Simha   Initial Version
**/
public without sharing class UserDAO {
    
    /**
    * @description
    * @author Vikram Simha | 04-08-2023 
    * @param Set<String> EmployeeIds 
    * @return List<User> 
    **/
    public static List<User> getUsersforEmpIds(Set<String> employeeIDs) {
        return [
            SELECT Id, Name,EmployeeNumber,ManagerId,isActive FROM user 
            where EmployeeNumber in :employeeIDs
        ];
    }
	
	 /**
    * @description
    * @author Bezawada Balaji| 29-08-2023 
    * @param getProfileDetailsById 
    * @return Set<profileIds> 
    **/
	 public static List<Profile> getProfileDetailsById(Set<Id> profileIds){
        return [
            SELECT Id, Name 
            FROM Profile 
            WHERE Id IN :profileIds
        ];
    }

    public static List<User> getUserDetailsByUserId(Set<Id> userIds){
        return [
            SELECT id,Name,Email,Phone,Profile.Name 
            FROM User
            WHERE Id IN :userIds
        ];
    }

    public static List<User> getUserTerritory(Set<Id> userIds){
        return [
            SELECT Id, Sales_Person_Type__c, Profile.Name, Territory__c
            FROM User
            WHERE Id IN :userIds
        ];
    }

}