force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <description>Territory Name, owner, branch, primary business, and leadership</description>
    <label>Territory</label>
    <nameField>
        <label>Territory code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Territory_OwnerID__c.field-meta.xml
<CustomField>
    <fullName>Territory_OwnerID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TerritoryTriggerHandler.cls
public class TerritoryTriggerHandler {

    public static void updateAccountOwner(List<Territory__c> newList, Map<Id, Territory__c> oldMap){
        
        Set<Id> terrIds = new Set<Id>();
        
        for(Territory__c terr : newList){
            
            if(terr.Territory_OwnerID__c != oldMap.get(terr.Id).Territory_OwnerID__c){
                terrIds.add(terr.Id);
            }
        }
        
        if(!terrIds.isEmpty() && terrIds.size() > 0){
            
            TerritoryOwnerUpdateBatch batchObj = new TerritoryOwnerUpdateBatch(terrIds);
            Database.executeBatch(batchObj, 50);
        }
    }
}