force-app/main/default/objects/Accounts_Receivable__c/Accounts_Receivable__c.object-meta.xml
<CustomObject>
    <description>Open AR</description>
    <label>Accounts Receivable</label>
    <nameField>
        <label>Accounts Receivable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts Receivable</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Accounts_Receivable__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts Receivable</relationshipLabel>
    <relationshipName>Accounts_Receivable1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Accounts_Receivable__c/fields/AR_181_365__c.field-meta.xml
<CustomField>
    <fullName>AR_181_365__c</fullName>
    <label>A/R 181-365 Days</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Accounts_Receivable__c/fields/AR_1_30__c.field-meta.xml
<CustomField>
    <fullName>AR_1_30__c</fullName>
    <label>A/R 1-30 Days</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Accounts_Receivable__c/fields/AR_31_60__c.field-meta.xml
<CustomField>
    <fullName>AR_31_60__c</fullName>
    <label>A/R 31-60 Days</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Accounts_Receivable__c/fields/AR_61_90__c.field-meta.xml
<CustomField>
    <fullName>AR_61_90__c</fullName>
    <description>A/R 61-90 Days</description>
    <label>A/R 61-90 Days</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Accounts_Receivable__c/fields/AR_91_180__c.field-meta.xml
<CustomField>
    <fullName>AR_91_180__c</fullName>
    <label>A/R 91-180 Days</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Accounts_Receivable__c/fields/AR_Current__c.field-meta.xml
<CustomField>
    <fullName>AR_Current__c</fullName>
    <description>A/R Current</description>
    <inlineHelpText>This is total open AR that is not yet past due. All other below values are past due by the number of days indicated by the field label.</inlineHelpText>
    <label>A/R Current</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Accounts_Receivable__c/fields/AR_Over_365__c.field-meta.xml
<CustomField>
    <fullName>AR_Over_365__c</fullName>
    <label>A/R &gt;365 Days</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Accounts_Receivable__c/fields/AR_Total__c.field-meta.xml
<CustomField>
    <fullName>AR_Total__c</fullName>
    <label>A/R Total Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AccountReceivableListController.cls
public class AccountReceivableListController {
    public List<Accounts_Receivable__c> accRecList{get;set;} 
    
    //Constructor
    public AccountReceivableListController(ApexPages.StandardController controller) {
        
        String accId = ApexPages.currentPage().getParameters().get('id');
        accRecList = new List<Accounts_Receivable__c>();
        accRecList = [Select Id, Name,Credit_Limit__c, AR_Current__c, AR_1_30__c, AR_31_60__c, AR_61_90__c, AR_91_180__c, AR_181_365__c, AR_Over_365__c, AR_Total__c from Accounts_Receivable__c where Account__c =: accId];
        
    }
}