force-app/main/default/objects/Organization_Job_Code_Mapping__c/Organization_Job_Code_Mapping__c.object-meta.xml
<CustomObject>
    <label>Master Job Category</label>
    <nameField>
        <displayFormat>MJC-{00000}</displayFormat>
        <label>Master Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Job Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_Job_Code_Mapping__c/fields/Job_Category_Group__c.field-meta.xml
<CustomField>
    <fullName>Job_Category_Group__c</fullName>
    <label>Job Category</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Job_Code_Mapping__c/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
    <label>Sub Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JobCodeMappingDAOTest.cls
@isTest
private class JobCodeMappingDAOTest {
    private static final string TEST_Job_Category_Group ='Chemists';
    private static final string TEST_Sub_Category ='lab Chemists';
    
    @testSetup  private static void setupmethod(){
        Organization_Job_Code_Mapping__c OrgJobCode = new Organization_Job_Code_Mapping__c
        (Job_Category_Group__c = TEST_Job_Category_Group, Sub_Category__c = TEST_Sub_Category);
        insert OrgJobCode;
    }
    @IsTest static void TestJobCodeMappingForJobCategorySet(){
        Organization_Job_Code_Mapping__c jobCodeMapping = [SELECT ID, Job_Category_Group__c FROM Organization_Job_Code_Mapping__c
                                                           WHERE Job_Category_Group__c =: TEST_Job_Category_Group];
        JobCodeMappingDAO.getListOfJobCodeMappings();
        Organization_Job_Code_Mapping__c jobCode = [SELECT ID,Job_Category_Group__c FROM Organization_Job_Code_Mapping__c
                                                    WHERE Job_Category_Group__c =:jobCodeMapping.Job_Category_Group__c ];
        System.AssertEquals(jobCodeMapping.Job_Category_Group__c,jobCode.Job_Category_Group__c,'Organisation JobCode mapping returned successfully');   
    }
    
    @IsTest static void TestJobCodeMappingForJobCategoryNotSet(){                                                           
        JobCodeMappingDAO.getListOfJobCodeMappings();
        Organization_Job_Code_Mapping__c jobCode = [SELECT ID,Job_Category_Group__c FROM Organization_Job_Code_Mapping__c LIMIT 1];
                                                   
        System.AssertNotEquals(jobCode.Job_Category_Group__c,null,'Job Category Group cannot be null');   
    }
}