force-app/main/default/objects/Organization_Job_Code_Mapping__c/Organization_Job_Code_Mapping__c.object-meta.xml
<CustomObject>
    <label>Master Job Category</label>
    <nameField>
        <displayFormat>MJC-{00000}</displayFormat>
        <label>Master Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Job Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_Job_Code_Mapping__c/fields/Job_Category_Group__c.field-meta.xml
<CustomField>
    <fullName>Job_Category_Group__c</fullName>
    <label>Job Category</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Job_Code_Mapping__c/fields/Job_Code__c.field-meta.xml
<CustomField>
    <fullName>Job_Code__c</fullName>
    <externalId>true</externalId>
    <label>Job Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Organization_Job_Code_Mapping__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <label>Job Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JobCodeMappingDAO.cls
/**
 * @description       : 
 * @author            : Suresh Beniwal
 * @group             : 
 * @last modified on  : 06-09-2022
 * @last modified by  : Suresh Beniwal
 * Modifications Log
 * Ver   Date         Author           Modification
 * 1.0   06-09-2022   Suresh Beniwal   Initial Version
**/
public without sharing class JobCodeMappingDAO {
    
    /**
    * @description 
    * @author Suresh Beniwal | 06-09-2022 
    * @return List<Organization_Job_Code_Mapping__c> 
    **/
    public static List<Organization_Job_Code_Mapping__c> getListOfJobCodeMappings() {
        return [ 
            SELECT Id, Name, Job_Category_Group__c, Job_Title__c, Job_Code__c 
            FROM Organization_Job_Code_Mapping__c
            WHERE Job_Category_Group__c != NULL
            
        ];
    }
}