force-app/main/default/objects/User/fields/Primary_Business__c.field-meta.xml
<CustomField>
    <fullName>Primary_Business__c</fullName>
    <description>Primary business to be added to the accounts based off the owners value</description>
    <label>Primary Business</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BPS</fullName>
            </value>
            <value>
                <fullName>CYN Environmental</fullName>
            </value>
            <value>
                <fullName>CYN Oil</fullName>
            </value>
            <value>
                <fullName>Daylighting Services</fullName>
            </value>
            <value>
                <fullName>DFW</fullName>
            </value>
            <value>
                <fullName>Emerald Services</fullName>
            </value>
            <value>
                <fullName>Field Services</fullName>
            </value>
            <value>
                <fullName>H2O</fullName>
            </value>
            <value>
                <fullName>Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Industrial Services</fullName>
            </value>
            <value>
                <fullName>Kleen Performance Products</fullName>
            </value>
            <value>
                <fullName>Lodging</fullName>
            </value>
            <value>
                <fullName>Murphys Oil</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Performance Plus Products</fullName>
            </value>
            <value>
                <fullName>Production Services</fullName>
            </value>
            <value>
                <fullName>RS Used Oil</fullName>
            </value>
            <value>
                <fullName>Safety-Kleen</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>Technical Services</fullName>
            </value>
            <value>
                <fullName>Thermo Fluids</fullName>
            </value>
			<value>
                <fullName>Thompson</fullName>
            </value>
			<value>
                <fullName>Noble Oil</fullName>
            </value>
            <value>
                <fullName>HEPACO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Field_Mapping__mdt/User_Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>User Field Mapping</label>
    <pluralLabel>User Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/User_Field_Mapping__mdt/fields/Operating_Segment__c.field-meta.xml
<CustomField>
    <fullName>Operating_Segment__c</fullName>
    <label>Operating Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Field_Mapping__mdt/fields/Primary_Business__c.field-meta.xml
<CustomField>
    <fullName>Primary_Business__c</fullName>
    <label>Primary Business</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Users.cls
global class Users
{
    @InvocableMethod(callout=true label='Default Operating Segment and PSP as per User Primary Business') 
    public static List<UserWrapperObject> getDefaultOSandPSP(List<Id> userId) {
        User u = [select id,Primary_Business__c from user where Id in :userId limit 1];
        List<UserWrapperObject> wrapObjects = new List<UserWrapperObject>();
        List<User_Field_Mapping__mdt> mcs = User_Field_Mapping__mdt.getall().values();
        for(User_Field_Mapping__mdt mapping : mcs)
        {
          if(mapping.Primary_Business__c == u.Primary_Business__c){
            UserWrapperObject wo = new UserWrapperObject();
            wo.OperatingSegment = mapping.Operating_Segment__c;
            wo.PrimaryServiceProvider = mapping .Primary_Service_Provider__c;
            wrapObjects.add(wo);  
            break;        
          }
        } 
        
        return wrapObjects;
    }  
   global class UserWrapperObject 
   {
     @InvocableVariable(label='OperatingSegment')
    public string OperatingSegment;
        
    @InvocableVariable(label='PrimaryServiceProvider')
    public string PrimaryServiceProvider;
   }
}