force-app/main/default/objects/Financials__c/Financials__c.object-meta.xml
<CustomObject>
    <description>Read only in Salesforce and updated via Beacon.</description>
    <label>Financials</label>
    <nameField>
        <displayFormat>F-{0000000}</displayFormat>
        <label>Financial ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Financials__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financials</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ownership_Change_Request__c/Ownership_Change_Request__c.object-meta.xml
<CustomObject>
    <label>Ownership Change Request</label>
    <nameField>
        <displayFormat>OCR-{000000}</displayFormat>
        <label>Ownership Change Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ownership Change Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ownership_Change_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ownership Change Requests</relationshipLabel>
    <relationshipName>Ownership_Change_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>  
</CustomField>

force-app/main/default/objects/Ownership_Change_Request__c/fields/EligibileForIntraQuarterFlip__c.field-meta.xml
<CustomField>
    <fullName>EligibileForIntraQuarterFlip__c</fullName> 
    <defaultValue>false</defaultValue>
    <label>Eligibile Intra Quarter Flip</label> 
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ownership_Change_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet> 
        <restricted>true</restricted>
        <valueSetDefinition>
            <value> 
                <fullName>New</fullName>
            </value>
            <value> 
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved-Pending</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value> 
            <value>
                <fullName>Executed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
			<value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FinancialHandler.cls
/**
* @description       : 
* @author            : Raghav
* @group             : 
* @last modified on  : 
* @last modified by  :  
* Modifications Log
* Ver   Date         Author           Modification
* 1.0   01-10-2024   Raghav   Initial Version 
**/  
public class FinancialHandler { 
    private static OwnershipChangeRequestHandler ownershiptriggerreq = new OwnershipChangeRequestHandler();
    public void updateOCRQuarterFlipEligibility(Map<Id, SObject> newItems, Map<Id, SObject> oldItems){
        Set<Id> accountIds=new Set<Id>();
        for(Financials__c financial: (List<Financials__c>)newItems.values()){
            accountIds.Add(financial.Account__c);
        }
        List<Ownership_Change_Request__c> ownershipChangeRequests=[Select Id, Account__c, EligibileForIntraQuarterFlip__c from Ownership_Change_Request__c where Account__c in :accountIds and  Status__c in ('Draft','Submitted')];
        if(!ownershipChangeRequests.isEmpty()){
            ownershiptriggerreq.updateOCRQuarterFlipEligibility(ownershipChangeRequests);
            update ownershipChangeRequests;
        }  
    }
}