force-app/main/default/objects/Financials__c/Financials__c.object-meta.xml
<CustomObject>
    <description>Read only in Salesforce and updated via Beacon.</description>
    <label>Financials</label>
    <nameField>
        <displayFormat>F-{0000000}</displayFormat>
        <label>Financial ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Financials__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financials</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Financials__c/fields/Line_of_business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_business__c</fullName>
    <description>product_line_desc</description>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Airborne Imaging</fullName>
            </value>
            <value>
                <fullName>Allied Product Sales</fullName>
            </value>
            <value>
                <fullName>Antifreeze Sales</fullName>
            </value>
            <value>
                <fullName>Base Oil Sales</fullName>
            </value>
            <value>
                <fullName>Blended Oil Sales</fullName>
            </value>
            <value>
                <fullName>Blended Oil Sales – Direct</fullName>
            </value>
            <value>
                <fullName>Bulk Services</fullName>
            </value>
            <value>
                <fullName>Catalyst Services</fullName>
            </value>
            <value>
                <fullName>Catalysts Treatment</fullName>
            </value>
            <value>
                <fullName>Charge for Oil Revenue</fullName>
            </value>
            <value>
                <fullName>Chemical Cleaning</fullName>
            </value>
            <value>
                <fullName>CleanPack</fullName>
            </value>
            <value>
                <fullName>Containerized Waste Services</fullName>
            </value>
            <value>
                <fullName>Contract Blending &amp; Packaging</fullName>
            </value>
            <value>
                <fullName>Daylighting Services</fullName>
            </value>
            <value>
                <fullName>Directional Boring</fullName>
            </value>
            <value>
                <fullName>Direct Ship</fullName>
            </value>
            <value>
                <fullName>Downhole Services</fullName>
            </value>
            <value>
                <fullName>Drill Camps and Catering</fullName>
            </value>
            <value>
                <fullName>Drill Support Services</fullName>
            </value>
            <value>
                <fullName>Drum Services</fullName>
            </value>
            <value>
                <fullName>Emergency Response Services</fullName>
            </value>
            <value>
                <fullName>Field Services</fullName>
            </value>
            <value>
                <fullName>Filtration and Treatment Services</fullName>
            </value>
            <value>
                <fullName>Healthcare - RMW</fullName>
            </value>
            <value>
                <fullName>High Hazardous Services</fullName>
            </value>
            <value>
                <fullName>Household Hazardous Waste</fullName>
            </value>
            <value>
                <fullName>Industrial Cleaning</fullName>
            </value>
            <value>
                <fullName>Inplant Container Moves</fullName>
            </value>
            <value>
                <fullName>Line Locating</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financials__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Financials__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Growth Budget</fullName>
            </value>
            <value>
                <fullName>KAM Budget</fullName>
            </value>
            <value>
                <fullName>Customer Budget</fullName>
            </value>
            <value>
                <fullName>Revenue</fullName>
            </value>
            <value>
                <fullName>KAM Revenue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financials__c/recordTypes/Revenue.recordType-meta.xml
<RecordType>
    <fullName>Revenue</fullName>
    <active>true</active>
    <description>Revenue for all customer &amp; growth budgets</description>
    <label>Revenue</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Financial_Reference_Date__c.field-meta.xml
<CustomField>
    <fullName>Financial_Reference_Date__c</fullName>
    <formula>Job_Start_Date__c-DAY(Job_Start_Date__c)+1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Financial Reference Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Job_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Job_Start_Date__c</fullName>
    <description>This is the date when the job would start.</description>
    <inlineHelpText>This is the date when the job would start.</inlineHelpText>
    <label>Job Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp;  Opportunity.AccountId ,  Opportunity.Account.Name )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/No_Account_Revenue_in_12_Months__c.field-meta.xml
<CustomField>
    <fullName>No_Account_Revenue_in_12_Months__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the account entered on the opportunity had revenue since the first day of the prior year.</description>
    <inlineHelpText>Indicates if the account entered on the opportunity had revenue since the first day of the prior year.</inlineHelpText>
    <label>New Account Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/No_LOB_Revenue_in_12_Months__c.field-meta.xml
<CustomField>
    <fullName>No_LOB_Revenue_in_12_Months__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the LOB entered on the opportunity had revenue since the first day of the prior year.  If it does not have revenue it is flagged as a LOB Cross Sell.</description>
    <inlineHelpText>Indicates if the LOB entered on the opportunity had revenue since the first day of the prior year.  If it does not have revenue it is flagged as a LOB Cross Sell.</inlineHelpText>
    <label>New LOB Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OpportunityLineItemHandler.cls
public class OpportunityLineItemHandler {
    
    Public static void updateLOBCrossSell (List<OpportunityLineItem> newOpportunityLineItemList ){
        List<String> prodIds = new List<String>();
        List<id> oppIds = new List<id>();
        List<Id> accIds = new List<Id>();
        for(OpportunityLineItem oppLiTm : newOpportunityLineItemList){
            prodIds.add(oppLiTm.Product_Name__c);
            oppIds.add(oppLiTm.opportunityId);
        }
        Map<Id,Date> oppCloseDateMap = new Map<id,Date>();
        Map<id,opportunity> oppList = new Map<id,opportunity>([select id,accountId,closedate,Financial_Reference_Date__c,Job_Start_Date__c from opportunity where id in: oppIds]);
        for(Opportunity opp:oppList.values()){
            accIds.add(opp.AccountId);
            
            Integer yy = opp.Financial_Reference_Date__c.year();
            Date dt = Date.newInstance(yy-1, 1, 1);  
            oppCloseDateMap.put(opp.id,dt);
        }
        
        Map<Id,Account> acctFianancialsList = new Map<Id,Account>([
            Select Id,
            (select Account__c,Month__c, Line_of_business__c 
             from Budgets__r 
             where Type__c = 'Revenue') 
            from Account where Id in :accIds
        ]);
        system.debug('acctFianancialsList--->'+acctFianancialsList.size()+'::::'+acctFianancialsList);
        
        for(OpportunityLineItem oppLiTm : newOpportunityLineItemList){
            system.debug('oppLiTm--->'+oppLiTm.id+'::::'+oppLiTm);
            Boolean prodFlag = true;
            Boolean accFlag = true;
            
            for(Financials__c fin: acctFianancialsList.get(oppList.get(oppLiTm.opportunityId).AccountId).Budgets__r){
                system.debug('fin--->'+fin.id+'::::'+fin);
                if(fin.Month__c >= oppCloseDateMap.get(oppLiTm.opportunityId) && fin.month__c < oppList.get(oppLiTm.opportunityId).Financial_Reference_Date__c){
                    if(oppLiTm.Product_Name__c == fin.Line_of_business__c){
                        prodFlag = false;
                        if(accFlag==false)
                            break;
                    }
                    
                    if(oppList.get(oppLiTm.OpportunityId).accountId == fin.Account__c){
                        accFlag = false;
                        if(prodFlag==false)
                            break;
                    }
                }
            }
            
            if(prodFlag){
                oppLiTm.No_LOB_Revenue_in_12_Months__c = true;
            }
            
            else { 
                oppLiTm.No_LOB_Revenue_in_12_Months__c = false;
            } 
            
            if(accFlag){
                oppLiTm.No_Account_Revenue_in_12_Months__c = true;
            }
            
            else {
                oppLiTm.No_Account_Revenue_in_12_Months__c = false;
            }           
        }
    }
	
	public static void PreventOpportunityProductDeletion(List<OpportunityLineItem> newOpportunityLineItems) {
        List<Product2> partsCleanerProductLst = [
            SELECT Id
            FROM Product2
            WHERE Name = 'Parts Cleaners' limit 1
        ]; 
        
        if(!partsCleanerProductLst.isEmpty()){
            for (OpportunityLineItem oli : newOpportunityLineItems) {
                if(oli.Product2Id == partsCleanerProductLst[0].Id ){
                    oli.addError(Label.Prevent_Opportunity_Product_Deletion_Message);
                }
            }
        }
    }
}