force-app/main/default/objects/TAX_SERVICE__c/TAX_SERVICE__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Tax requirement service</description>
    <label>TAX SERVICE</label>
</CustomObject>

force-app/main/default/objects/TAX_SERVICE__c/fields/End_point_url__c.field-meta.xml
<CustomField>
    <fullName>End_point_url__c</fullName>
    <description>End point url</description>
    <label>End point url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Taxcontroller.cls
public class Taxcontroller {

    Public TaxWrapper wrapper{
      get;
      set;
    }

    Public void getdata() {
        String WinId = ApexPages.currentPage().getParameters().get('Companycode');
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(TAX_SERVICE__c.getInstance('TAX SERVICE').End_point_url__c);
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json');
        // Set the body as a JSON object
        HttpResponse response;
        try{
            request.setBody('{"Companycode":"'+WinId+'"}');
            System.debug(request);
            response = http.send(request);
            System.debug(response.getBody());
            // Parse the JSON Response
            wrapper = (TaxWrapper) JSON.deserializeStrict(response.getBody(), TaxWrapper.class);
            If (wrapper.Details.isEmpty())
            {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO, '**NO RECORDS FOUND**'));
            } 
            
        }
        catch(Exception e){
            system.debug(LoggingLevel.ERROR, e.getStackTraceString());
        }
        
    }
}