force-app/main/default/objects/Activity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
	<description>This field is used to select the locations those are linked to HR related account on which task is creating </description>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.Organization__c</field>
            <operation>equals</operation>
            <valueField>$Source.WhatId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Location</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>HR Recruiting Partners</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organization_Job_Code__c/Organization_Job_Code__c.object-meta.xml
<CustomObject>
    <label>Job Categories</label>
    <nameField>
        <displayFormat>Jct-{00000}</displayFormat>
        <label>Job Category Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_Job_Code__c/fields/Job_Category_Group__c.field-meta.xml
<CustomField>
    <fullName>Job_Category_Group__c</fullName>
    <formula>Job_Code_Mapping__r.Job_Category_Group__c</formula>
    <label>Job Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Job_Code__c/fields/Job_Code_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Job_Code_Mapping__c</fullName>
    <label>Job Category</label>
    <referenceTo>Organization_Job_Code_Mapping__c</referenceTo>
    <relationshipLabel>Job Categories</relationshipLabel>
    <relationshipName>Organization_Job_Codes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Organization_Job_Code__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Job Categories</relationshipLabel>
    <relationshipName>Job_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organization_Job_Code__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>HR_Talent_Pools</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Categories</relationshipLabel>
    <relationshipName>Organization_Job_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organization_Job_Code__c/fields/Sub_Group__c.field-meta.xml
<CustomField>
    <fullName>Sub_Group__c</fullName>
    <formula>Job_Code_Mapping__r.Sub_Group__c</formula>
    <label>Job Sub Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Job_Code_Mapping__c/Organization_Job_Code_Mapping__c.object-meta.xml
<CustomObject>
    <label>Master Job Category</label>
    <nameField>
        <displayFormat>MJC-{00000}</displayFormat>
        <label>Master Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Job Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_Job_Code_Mapping__c/fields/Job_Category_Group__c.field-meta.xml
<CustomField>
    <fullName>Job_Category_Group__c</fullName>
    <label>Job Category</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Job_Code_Mapping__c/fields/Sub_Group__c.field-meta.xml
<CustomField>
    <fullName>Sub_Group__c</fullName>
    <label>Job Sub Category</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JobCodeServiceTest.cls
/**
 * @description       : 
 * @author            : Irfan Khan
 * @group             : 
 * @last modified on  : 08-08-2022
 * @last modified by  : Irfan Khan 
 * Modifications Log
 * Ver   Date         Author       Modification
 * 1.0   08-08-2022   Irfan Khan   Initial Version
**/
@isTest 

private class JobCodeServiceTest {
    private final static string TEST_JOB_CATEGORY_GROUP = 'Chemists';
@testSetup static void setupmethod() {
     Organization_Job_Code_Mapping__c OrgMap = new Organization_Job_Code_Mapping__c ();
    OrgMap.Job_Category_Group__c = TEST_JOB_CATEGORY_GROUP;
    
    insert OrgMap;
      
    Organization_Job_Code__c OrgJobCode = new Organization_Job_Code__c ();
    OrgJobCode.Job_Code_Mapping__c = OrgMap.Id ;
    
        
    Test.startTest();
           insert OrgJobCode;
        Test.stopTest();
    }
    @IsTest static void TestJobCategories(){
        List<Organization_Job_Code__c> OrgList = [SELECT ID,Name,Job_Category_Group__c,Sub_Group__c,Organization__r.Name,Location__r.Name FROM Organization_Job_Code__c WHERE Job_Category_Group__c = 'Chemists' ];
       
        Test.startTest();
            List<JobCodeService.JobCodeWrapper> listOfJobCodeWrapper = JobCodeService.getListOfJobCodes(OrgList);
        Test.stopTest();
        
        System.assertEquals(false, listOfJobCodeWrapper.isEmpty(), 'Wrapper data should be return !!');
}
}